### ISSUE TITLE
Does not play back decimal numbers. Similar to Issue #297 

### ISSUE THREAD

**Issue by ipal0** [SeleniumHQ/selenium-ide#1001]
The issue #297 is reappearing again. The decimal numbers does not play back. If the value is 98.25 then it takes 25.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
