### ISSUE TITLE
Incognito Mode

### ISSUE THREAD

**Issue by ujwalashirodkar21** [SeleniumHQ/selenium-ide#1002]
How can i open Chrome browser in Incognito Mode using Selenium IDE?
How do i capture screenshots in Selenium IDE?

**Comment by tourdedave** [comment]
This issue tracker is not the best place for questions like these (see [the project help page](https://www.selenium.dev/selenium-ide/help) for better options). Also, a quick search through the issue tracker will answer your questions of what's possible with regards to these two topics.
