### ISSUE TITLE
Command Line Runner issue: cannot run in Chrome, Firefox and IE drivers

### ISSUE THREAD

**Issue by jesshhu** [SeleniumHQ/selenium-ide#1005]
## 🐛 Bug Report

Command Line Runner issue: cannot run in Chrome, Firefox and IE drivers

## To Reproduce
See below commands I'm using with their respective error:

1. selenium-side-runner -c "browserName=chrome" EMRLoadPageNEW.side
- **SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 77**

2. selenium-side-runner -c "browserName=firefox" EMRLoadPageNEW.side
- **WebDriverError: newSession**

3. selenium-side-runner -c "browserName='internet explorer'" EMRLoadPageNEW.side
- **NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.**

## Expected behavior
I installed Command-Line Runner in my personal laptop with same procedures of installing and linking the path folder to the environment variables, and its working as expected.

Now, I'm trying to used this in my company laptop and the above issue's were experiencing. Sorry for making an issue ticket, I already search for the above errors in google but still cannot find the right answers. I'm bit limited when comes to coding and our team in my company is new in using Selenium IDE. Hope you can help me with regards to my issue.

Thank you!

## Project file reproducing this issue (highly encouraged)

![Chrome Driver](https://user-images.githubusercontent.com/63313429/78707607-69061f00-7943-11ea-8e66-aab18d090548.PNG)
![Firefox1](https://user-images.githubusercontent.com/63313429/78707611-6a374c00-7943-11ea-84ed-207edf44750b.PNG)
![IE](https://user-images.githubusercontent.com/63313429/78707612-6acfe280-7943-11ea-903d-c775cad90f6b.PNG)

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  3.17.0
Please note that selenium-side-runner supports Node.js 8 - 10

Node version: v12.16.1

Browser: Chrome
Browser Version: 80.0.3987.163 (64-bit)

Browser: Firefox
Browser Version: 75.0 (32-bit)

Browser: IE 11
Browser Version: 11.805.17763.0

**Comment by jesshhu** [comment]
Hi here is the copy of my .side
[EMRLoadPageNEW.zip](https://github.com/SeleniumHQ/selenium-ide/files/4446530/EMRLoadPageNEW.zip)

**Comment by tourdedave** [comment]
This sounds like an issue with your browser drivers. Which has nothing to do with the command-line runner specifically.

You can run `chromedriver -v` from the command-line to see version number. If the major version number doesn't match the version of Chrome you're running then it won't work (which would explain the error you're seeing with Chrome). In that case you need to update your version of ChromeDriver.

The same kind of verification goes for the other browsers. You need to make sure that you have the correct browser drivers downloaded and that they're accessible from the system path (which it sounds like they are). Oh, and for IE, there is extra setup you'll need. It's documented [here](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration).

**Comment by jesshhu** [comment]
Hi @tourdedave my chromedriver and iedriver works perfectly, fixed the driver version and follow the instruction in the documentation you've mentioned with regards IE. Thank you!

But still I'm having an error using geckodriver, same error

**WebDriverError: newSession**

I've already checked the version installed in CMD and changed the driver version in PATH.
geckodriver 0.20.0

any queries regards to the issue?

**Comment by jesshhu** [comment]
Hi @tourdedave this ticket has been resolved. How can I closed it? Thanks for your help BTW :)

Hope you're okay! Stay safe, bro!
