### ISSUE TITLE
Stored variables are lost when using Play From Here

### ISSUE THREAD

**Issue by jar452** [SeleniumHQ/selenium-ide#1008]
## 🐛 Bug Report

The variables that I store at the beginning of my script are lost when the script fails and I use the Play From Here function to continue on from the middle of my script.

## To Reproduce

1) create a new script where you store a variable at the very beginning and try to verify text with this variable at the beginning and at the end
2) put a command in your script about halfway down that you know will fail
3) run the script, the variable is stored and verified in the beginning successfully
4) the script will fail on purpose because of step 2 above
5) make use of the Play From Here function on the very next command
6) when it tries to verify the variable at the end, the script will fail because the stored variable has been lost.

## Expected behavior

I expect that when I store a variable, it will be available to use throughout my entire browser session.  It seems that the variables are cleared when utilizing Play From Here.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

File is attached, but it wouldn't let me upload a .side file so I used .txt.  Once you save it locally, simply change the extension back to .side
[Lost_Variables.txt](https://github.com/SeleniumHQ/selenium-ide/files/4457284/Lost_Variables.txt)

In my example, you'll run the current test.
It will fail on step 4.
You'll use Play From Here on step 5 and expect that step 7 will pass just like step 3 did since they're exactly the same, but it will fail because the stored variable is lost.

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  not sure where to see this
Node version: not sure where to see this
Browser: Google Chrome
Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Comment by corevo** [comment]
This is the expected behavior, variables are deleted every time play is hit.

In order to keep variables you can either skip the failing command or use the IDE'S debugging capabilities.

**Comment by jar452** [comment]
Thank you for replying so quickly!

I understand that this is expected behavior, but does it have to be?

Sorry to be a pain, but imagine this scenario if you will:
I use my script to create a new customer in the system and I store the customer number to be verified later in the script.
My script fails halfway through (I have no way of knowing if/when it will fail when I start).
Now, I need to continue on but my customer number variable is gone.
I now have no way to proceed without creating another new customer.
Imagine now that I have 100 inter-dependent scripts leading up to this point that all passed.
Now, I have to re-run all 100 scripts just because my variable was lost in script 101.

Is it possible for it to work the way I originally described (and the way it used to work in the old IDE 2.9.1 for Firefox)?
Why delete the variables upon play when we can instead simply allow them to be overwritten if the script has a command to store it using the same name?

Thank you again for taking the time to review this, I truly appreciate it.

**Comment by corevo** [comment]
Imagine it from our end, you have a program, it crashed, you open it again, it starts from the beginning.

Be it a programming language or script, keeping variables creates difficulties in behavior & tests that are unreliable.

Instead what we could do is allow at some point manual editing of variables, so you could manually add the missing data, that would put the responsibility of script reliability in your hands rather than the IDE's.

**Comment by jar452** [comment]
I like that idea of manually editing the variables.
I'm sure you don't hear this nearly as often as you should, but THANK YOU for keeping the Selenium project going!!  I've been using it for 10+ years now and wouldn't have a job without you.

**Comment by cford-hub** [comment]
I agree, thank you for keeping Selenium alive!  It is such a great tool.  Is there an option to change the behavior of the IDE itself regarding record/play to accommodate this?  The work-around you presented is not really usable, at least I have not much luck with it.  When you add a break in the script, you cannot start recording to update the script while it's in pause mode.  The user must click the STOP key, then click record to correct the failing steps, then resume play (AKA hit the play button), which removes all the stored variables.  Could the record button be active while the script is paused, allowing the user to record?  This would allow the user to then un-pause (not click the play button) yet still resume playing the script with the new adjustments and allowing the variables to stay active?
