### ISSUE TITLE
How to take / capture screen shots in Selenium IDE???

### ISSUE THREAD

**Issue by naveenht** [SeleniumHQ/selenium-ide#1009]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
Duplicate of #182
