### ISSUE TITLE
Missing features, Flow Control and Store Variables

### ISSUE THREAD

**Issue by babuto00** [SeleniumHQ/selenium-ide#101]
Hello, first of all, thank you for your wonderful work! However what I miss are functions I used from Flow Control and Store Variable plugins in former Selenium IDE in FF. Would it be possible to include such functions in the new version? Without any using any plugins, I believe a lot of users would appreciate it. Thank you!

**Comment by corevo** [comment]
Yes, we plan on bringing these features built in the IDE

Cheers,
Tom

**Comment by olds97lss** [comment]
@babuto00 do you have a link for "Flow Control"? I'm not familiar with that one.

**Comment by idefix1** [comment]
I am not babuto00, but I I guess this Firefox addon, which added flow control to the old IDE: https://addons.mozilla.org/en-US/firefox/addon/flow-control/

There is also Kantu IDE, and it already supports flow control in Chrome:  
https://a9t9.com/kantu/docs/webextensions/selenium-ide#flowcontrol

**Comment by olds97lss** [comment]
Thanks!

Kind of surprised I never used that one.

**Comment by babuto00** [comment]
Yeah, it's that firefox addon idefix1 linked. It was pretty useful. Sorry for late response

**Comment by setiseta** [comment]
are there also plans for the commands: for and forxml??

**Comment by corevo** [comment]
`for` will be added, along side `while`,  
`forXml` is a bit problematic, because it can read your filesystem, which is a bit of a security risk.  
We'll have to take a look on how we can do this, while keeping our security policy as permissive as possible.

**Comment by setiseta** [comment]
thanks, sounds good.
yes filesystem is a bit critical.
at the moment i don't use forxml, but for.

**Comment by corevo** [comment]
Just dropping an update on our current thoughts,  
We're going to add the following commands:  
 - `if` `else` `end`
 - `while` `do` `end`

We'll need to give `for` a bit more thought before we implement it (UI terms mostly).

We're looking for a way to migrate the unstructured old flow control. (e.g. `goto` `gotoIf` `label` etc...)

**Comment by Jongkeun** [comment]
Do Store Variable controls include in #140 too?
For example, getEval, storeEval etc..

**Comment by corevo** [comment]
`eval` is a bit of a problem, but `if` also evals the target.  
It's a problem we'll have to address, I don't know how, and I'm not sure whats gonna be the scope of the eval.  
If we want a safer eval, we'll have to eval in an isolated environment, which means that `storeEval` and the likes are useless, since there is no access to the DOM.  
But it might be enough for `if`s.

**Comment by Jongkeun** [comment]
Why do you think `eval`'s scope has a problem?
About security?

**Comment by corevo** [comment]
Yes, say we let you `eval` in the extensions scope, you can get the entire DOM as text.  
And if we let you `eval` in the content side of things, you can add a keylogger to the tab.  
The problem is that the only thing that stops a user from `eval`ing something dangerous, is his responsibility to check what it does.  
There are a lot of blogs that tell you, add this core extension to your IDE and it'll do magic for you, these kind of features are things that vendors (specifically Mozilla), won't stand for.  
We have already been asked to remove all usage of `eval` in the extension.

**Comment by babuto00** [comment]
Hello, just checking in to see if there is any progress relating to the flow control (while command etc.)?
Thank you!

**Comment by corevo** [comment]
Not at the moment, its best to follow the [pr](https://github.com/SeleniumHQ/selenium-ide/pull/140).  
The work is spread across 3 big features we want to ship very soon, control flow, running projects from cli and plugins for the IDE.

**Comment by hohnan** [comment]
I have been trying out the new execute script functionality as well as an if statement but can't get the if statement to work with a variable. 

In the scenario below, "site" is schoolsdev. 

Am I not using the if statement correct as it always goes to the else statement unless I use a schoolsdev in the if statement.

execute script | return window.document.domain | host
execute script | return "${host}".slice(0, 10) | site
if | "${site}"=="schoolsdev"

**Comment by tourdedave** [comment]
@hohnan: I pushed a fix for this in d93332487a3039605214a13c32030f1f3292d7d9. It will go out in a release later today.

**Comment by hohnan** [comment]
@tourdedave: So far so good. Thanks for the quick turn around on that one!!!!

**Comment by tourdedave** [comment]
You're welcome!

**Comment by corevo** [comment]
Can we close this, now that we have control flow and `executeScript`?

**Comment by babuto00** [comment]
yes

**Comment by hvlucas** [comment]
I'm still not able to do if statements on the IDE
`if | ${storedAttribute}=="string"`
Outputs:  
`Failed:
Incomplete block at if`

**Comment by cinnest** [comment]
I had such an error when trying to run the if command alone. As far as I understood, it needs the end statement to close the block. So the command can not be run alone but in the test case with the end statement properly set. I hope it helps ;)

**Comment by hvlucas** [comment]
@cinnest I have an `end` after my assertion statements, between the `if` statement. Can you show me a working example?

**Comment by cinnest** [comment]
@hvlucas, unfortunately I have no access to my computer right now. Tomorrow morning as soon as I get in the office I'll post it for you, ok? Sorry

**Comment by cinnest** [comment]
So @hvlucas here is a code that is working for me. It contains the `if` and `while` statement for looking for a string in a table. If this string is not on the first page of this table it will search on other pages 'til the next button is disabled when it fails or passes the test. 

{
      "id": "d4236f2b-4561-44ac-ade4-226fddd23576",
      "comment": "",
      "command": "if",
      "target": "${myStringExists} == 0",
      "targets": [],
      "value": ""
    }, {
      "id": "54ff14e1-2cab-42e3-848f-18e5c4b1fdab",
      "comment": "",
      "command": "storeXpathCount",
      "target": "xpath=(//table[contains(.,${myString})])",
      "targets": [],
      "value": "myStringExists"
    }, {
      "id": "23c522a2-1515-488c-2fcc-240314564e72",
      "comment": "",
      "command": "storeXpathCount",
      "target": "xpath=(//a[contains(@class, 'ui-paginator-next') and not(contains(@class, 'ui-state-disabled'))])",
      "targets": [],
      "value": "nextExists"
    }, {
      "id": "ff328784-dcfa-4ec2-ae28-3f4dd6eaf2be",
      "comment": "",
      "command": "while",
      "target": "${myStringExists} == 0 && ${nextExists} != 0",
      "targets": [],
      "value": ""
    }, {
      "id": "72157022-13a1-4c55-5167-d8f0a47b75ca",
      "comment": "",
      "command": "click",
      "target": "xpath=(//a[contains(@class, 'ui-paginator-next')])",
      "targets": [],
      "value": ""
    }, {
      "id": "72bb21b6-d45d-4097-b88a-a7024ee6717c",
      "comment": "",
      "command": "storeXpathCount",
      "target": "xpath=(//a[contains(@class, 'ui-paginator-next') and not(contains(@class, 'ui-state-disabled'))])",
      "targets": [],
      "value": "nextExists"
    }, {
      "id": "4467e1d1-2fcc-4e43-48d7-d0e10b3f5331",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "9ea2b38d-4ea6-4fdd-8869-a4389490d025",
      "comment": "",
      "command": "else",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "90ab24b6-959a-4a98-9ef1-652bfd01c64b",
      "comment": "",
      "command": "verifyElementPresent",
      "target": "xpath=(//table[contains(.,${myString})])",
      "targets": [],
      "value": ""
    }, {
      "id": "e69f0692-8f8e-4f0c-a813-281f854611fc",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }

the test output when the `if` statement is false:

> 13.if on ${myStringExists} == 0... OK
> 20.else on ... OK
> 21.verifyElementPresent on xpath=(//table[contains(.,${myString})])... OK
> 22.end on ... OK

... and when it's true:

> 13.if on ${myStringExists} == 0... OK
> 14.storeXpathCount on xpath=(//table[contains(.,${myString})]) with value myStringExists... OK
> 15.storeXpathCount on xpath=(//a[contains(@class, 'ui-paginator-next') and not(contains(@class, 'ui-state-disabled'))]) with value nextExists... OK
> 16.while on ${myStringExists} == 0 && ${nextExists} != 0... OK
> 17.click on xpath=(//a[contains(@class, 'ui-paginator-next')])... OK
> 18.storeXpathCount on xpath=(//a[contains(@class, 'ui-paginator-next') and not(contains(@class, 'ui-state-disabled'))]) with value nextExists... OK
> 19.end on ... OK
> 20.else on ... OK
> 21.verifyElementPresent on xpath=(//table[contains(.,${myString})])... OK
> 22.end on ... OK

Selenium IDE 3.2.5
Google Chrome Version 68.0.3440.106

**Comment by hvlucas** [comment]
@cinnest Ok I figured it out, and now I feel super stupid.
I was trying to run my test FROM the `if` statement, so since it's trying to execute only that line then it failed (I'm guessing it doesn't consider the `end`).  
Running the whole test works normally. I changed my original statement to `"${storedVariable}"=="disabled", because it was considering the value of `storedVariable` as a variable itself.

**Comment by corevo** [comment]
It is a bug that you have to do that, our initial plan was to do `${storedVariable}=="disabled"`.  
We are working on a fix.

**Comment by hvlucas** [comment]
@corevo I see. How about running a test from the `if` statement not working? Is that intentional?

**Comment by corevo** [comment]
The first command is an `if`?

**Comment by hvlucas** [comment]
Running from `if` statement (I've also tried to store the variable before hand, i'm just making a point with the screenshot):
![screenshot from 2018-08-29 10-17-08](https://user-images.githubusercontent.com/26097416/44797497-f59c0900-ab74-11e8-8c99-a2361babe744.png)
Running whole test:
![screenshot from 2018-08-29 10-18-07](https://user-images.githubusercontent.com/26097416/44797503-f765cc80-ab74-11e8-92fe-8c6268e6af38.png)

**Comment by tourdedave** [comment]
Running a control flow command by itself won't work since it will fail syntax validation. Using "Start from here" to set the `if` command as the starting point should work fine.
