### ISSUE TITLE
How will this project go on?

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#1014]
## 💬 Questions and Help

Hi. 
I've also said it in Slack, but **what's going on with this project in the future?**
As you know, many people like and want this project is improved.
As one of the people who have affection, it's curious.

Of course, we knew selenium ide team are doing great work that we don't know.
So this project has not been active now because of that reason.
It doesn't look like doing a review of PR and comment these days.
Both `v3` and `master` branch are.

It's not an obligation, but I hope you let us know.
Is this just a pause for another work? 
Or are you thinking about going in a different direction to this project?

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by AutomatedTester** [comment]
This project will definitely be going on. We feel that it is a good project to help people get started with Selenium. We are always happy to receive more contributions to help take some of the pressure off of core contributors.
