### ISSUE TITLE
can we use jquery in selenium ide?

### ISSUE THREAD

**Issue by vandnanegi** [SeleniumHQ/selenium-ide#1030]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by AutomatedTester** [comment]
You will need to inject jQuery into the page to be able to use it. Please send a more detailed question to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
