### ISSUE TITLE
How to Parameterise in new selenium IDE Plugin(Chrome) 

### ISSUE THREAD

**Issue by wolvriene** [SeleniumHQ/selenium-ide#1043]
How to pass variable such as username, password and input data such as search name in selenium IDE Plugin(Chrome) ?

**Comment by corevo** [comment]
Duplicate of #183

**Comment by wolvriene** [comment]
@corevo 

Could you please help me i am not able to understand, it is possible or not if it is how ?

**Comment by wolvriene** [comment]
I tried by installing file-ulpoader plugin its taking ${username} as input also if i want the same functionality in CLI mode than how can we achieve it.

**Comment by corevo** [comment]
I don't know what that plugin is, you'll have to ask the person who made it.

**Comment by wolvriene** [comment]
@tourdedave 
Can you help me with this ?
