### ISSUE TITLE
Request: Wait commands are missing in new selenium IDE

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#105]
Hi , In my old selenium IDE tests i have used many wait commands which are not available in new IDE.
I need these commands 
WaitForElementPresent , WaitForPageLoad, waitForText, waitForVisible)

Even these needed when i want to write new tests in new IDE. Also i could see only few commands are available in IDE please extend the command list.

**Comment by corevo** [comment]
The new IDE waits automatically for you, if you need extra waits on top of what the IDE automatically does, you can use the `pause` command.

**Comment by olds97lss** [comment]
So, would you use  verifyElementPresent , verifyText, verifyVisible and it will now wait automatically for the element?

**Comment by corevo** [comment]
Not exactly, all commands first wait for the page to finish loading, including any additional network requests.
Then every command that takes a locator has an internal wait mechanism for that locator.
For example even if you have a click command, it would wait for the element to appear.
You shouldn't concern yourself with waiting, unless you reach a situation where it's not satisfactory, then you could add an extra pause, and then add the click, and the click would wait for the element to appear + whatever time you gave that pause beforehand.

Cheers,
Tom

**Comment by corevo** [comment]
We can add `verifyNotVisible`, create an issue for that command, and we'll find the time to add it.
