### ISSUE TITLE
assert commands are missing in new selenium IDE

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#106]
Hi, 
Not all assert command are available .We need below assert commands:
assertElementPresent , assertValue, assertElementNotPresent , assertEditable , asserNotEditable, assertChecked, assertNotChecked, assertSelectedValue, assertEval .Please extend the commands

**Comment by corevo** [comment]
`assertElementPresent` was already reported and will be included in future release.  
I will begin working on more assertions.

**Comment by corevo** [comment]
I intentionally avoided adding `assertEval`, since it is a security risk that does not go well with browser vendors nowadays.

**Comment by manikumary** [comment]
ok
