### ISSUE TITLE
Issue with running selenium-side-runner

### ISSUE THREAD

**Issue by bianyucheng-eb** [SeleniumHQ/selenium-ide#1062]
when I used selenium-side-runner to test, sometimes I get some errors

: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Err
   8 | jest.setTimeout(300000);
   9 | describe("Default Suite", () => {
> 10 |   it("dashboard8", async () => {
     |   ^
  11 |     await tests["dashboard8"](driver, vars);
  12 |     expect(true).toBeTruthy();

this causes my test to stop, I don't know how to solve this issue

**Comment by tourdedave** [comment]
Can you provide a way for us to reproduce the issue? Is there a specific test that it fails with consistently?

**Comment by bianyucheng-eb** [comment]
I can't reproduce this issue. I just re-tested the side file and it didn't report an error. I wonder if this is a network problem?

**Comment by tourdedave** [comment]
Possibly. Seems unrelated to the runner. If you're able to reproduce reliably then please let us know.
