### ISSUE TITLE
NoSuchSessionError

### ISSUE THREAD

**Issue by bianyucheng-eb** [SeleniumHQ/selenium-ide#1063]
When I used selenium-side-runner for testing, sometimes I get this error
![2020-06-02 17-25-09屏幕截图](https://user-images.githubusercontent.com/61490678/83503689-09b52d00-a4f6-11ea-9fd9-1b2ffdc7f21d.png)

I don’t know what caused this error, this error was sent suddenly.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
