### ISSUE TITLE
Play from here opens a new window

### ISSUE THREAD

**Issue by kopitoshka** [SeleniumHQ/selenium-ide#1068]
## 🚀 Feature Proposal

I am not sure if it is a bug or the way it is supposed to work, but the 'Play from here' opens a new window if a new test started. 

Sometimes I need to perform a sequence of steps for the current window (for example, I logged in to a website back-end and I need to fill in a form data on a 'new user' form), but it is not possible because when I click on 'Play from here', Selenium IDE opens a new window where I am not logged in and it just shows 'Preparing to run your test'. 

It would be very helpful if Selenium IDE could play recorded commands in context of the current window.

My software: Chrome Version 83.0.4103.61 (Official Build) (64-bit) for Windows
Selenium IDE: 3.17.0

**Comment by tourdedave** [comment]
`Play from here` works with a window that was opened previously by Selenium IDE -- either from a recording session or from a previous test playback.

It's not possible to attach to a window which you manually opened.

If there isn't a window open, then Selenium IDE will open a new one as you saw.
