### ISSUE TITLE
Is there a way to import Katalon Test suite into new IDE?

### ISSUE THREAD

**Issue by Dukkhey** [SeleniumHQ/selenium-ide#1069]
When trying to import a suite created with Katalon recorder, the following message is is displayed: "Eror migrating project. Unknown file was received."

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
No, we only support the old Selenium IDE format.

Perhaps Katalon has a Selenium IDE export feature?

**Comment by Dukkhey** [comment]
No. Sadly, they don't. I'm just gonna rebuild my suites from scratch. Thanks for the input!

**Comment by corevo** [comment]
Sorry to hear that, maybe someone with Katalon expertise can create a conversion script.
