### ISSUE TITLE
Verify Field Placeholders using Selenium IDE

### ISSUE THREAD

**Issue by hazelbucks** [SeleniumHQ/selenium-ide#1071]
I want to verify the placeholders in all fields on my webpage before I populate them. I am using the
Selenium IDE Chrome extension and the verifyAttribute and assertAttribute are not in the Command Dropdown.

I am also open to using a workaround like storeAttribute and then validating the value stored in this attribute but I am not sure how to do that either.

I am new to automation and selenium so apologises if this is a silly question.

Example:
Validate the Full Address field has a placeholder of "Search Address ..."
![image](https://user-images.githubusercontent.com/66928496/84990831-12aa2d80-b189-11ea-933f-1a6d044f40d3.png)

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
