### ISSUE TITLE
If failing with unexpected token '{' in latest Chrome extension version

### ISSUE THREAD

**Issue by alliedcvil** [SeleniumHQ/selenium-ide#1072]
## 🐛 Bug Report

Using the latest build of the Selenium IDE from Chrome when using an If statement with a stored variable or internal variable the program produces an error stating unexpected token '{'. 

## To Reproduce

Use a simple if statement such as if ${!times} == 30 then do x,y,z.

## Expected behavior

The product to continue to follow through with flow control.

## Test script or set of commands reproducing this issue

https://imgur.com/pBvYwGb

{
  "id": "c57ae5e4-ecd3-46c2-bfc9-d7d20481dd7b",
  "version": "2.0",
  "name": "test",
  "url": "https://www.testurl.com",
  "tests": [{
    "id": "438ecf29-c184-4d96-aff0-12433046f0c8",
    "name": "test",
    "commands": [{
      "id": "5e56e4f5-16ac-4497-bca8-c3c83dfa853f",
      "comment": "",
      "command": "executeScript",
      "target": "return 8",
      "targets": [],
      "value": "pagecounter"
    }, {
      "id": "f829b488-94dd-460d-bfe3-85ac466c203c",
      "comment": "",
      "command": "executeScript",
      "target": "return 1",
      "targets": [],
      "value": "counter"
    }, {
      "id": "a2a8c719-33fd-4c16-be56-96db0f12cbe6",
      "comment": "",
      "command": "times",
      "target": "30",
      "targets": [],
      "value": ""
    }, {
      "id": "e9893848-799f-47be-b885-8534bb54ab93",
      "comment": "",
      "command": "open",
      "target": "https://www.testurl.com",
      "targets": [],
      "value": ""
    }, {
      "id": "563c6a11-55ac-44e1-8065-9bb88a6028b3",
      "comment": "",
      "command": "click",
      "target": "css=.game_row:nth-child(${counter}) .button",
      "targets": [
        ["css=.game_row:nth-child(1) .game_thumb", "css:finder"],
        ["xpath=//div[@id='dlpage']/div[2]/div[2]/div/a/div", "xpath:idRelative"],
        ["xpath=//a/div", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "0651afbf-fda1-435f-8819-fd201c210c55",
      "comment": "",
      "command": "echo",
      "target": "${counter}",
      "targets": [],
      "value": ""
    }, {
      "id": "8850f833-ff69-4812-b948-c52369822d6b",
      "comment": "",
      "command": "executeScript",
      "target": "return ${counter} + 1",
      "targets": [],
      "value": "counter"
    }, {
      "id": "1a1a7a90-e454-403c-9ab2-d698f2547d44",
      "comment": "",
      "command": "if",
      "target": "${!times} === 30",
      "targets": [],
      "value": ""
    }, {
      "id": "f3b1bc40-32b9-4c9f-89af-5195bc3e1192",
      "comment": "",
      "command": "executeScript",
      "target": "return ${pagecounter} + 1",
      "targets": [],
      "value": "counter"
    }, {
      "id": "014205bf-825f-4676-a9e4-6b17c556b207",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "c37346a5-90fb-4177-aa2f-2653f99d79d0",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "aa713af4-105c-490e-8214-bf08bb679138",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["438ecf29-c184-4d96-aff0-12433046f0c8"]
  }],
  "urls": ["https://www.testurl.com/"],
  "plugins": []
}

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome 
Browser version: 83.0.4103.106
Selenium Grid version (if applicable): v3.17.0

**Comment by yuzhva** [comment]
Having same issue at Chrome Version 84.0.4147.125 (Official Build) (64-bit)

```
verify element not present | css=.message-row:last-child
if | ${!statusOK} == true
end
```

> 1.
if on ${ statusOK } == true Failed:
12:01:09
Unexpected token '{'

**Comment by YuriStruszczynski** [comment]
@yuzhva

Did you find a workarround?

**Comment by yuzhva** [comment]
> Did you find a workarround?

@YuriStruszczynski I decided to avoid `if` usage in my QA flow.

So I replaced `if / else` with [Selenium IDE right-click](https://github.com/SeleniumHQ/selenium-ide/issues/754#issuecomment-688308753) and [Selenium IDE shortcut key combinations](https://github.com/SeleniumHQ/selenium-ide/issues/929#issuecomment-688311858)

**Comment by YuriStruszczynski** [comment]
> 
> 
> > Did you find a workarround?
> 
> @YuriStruszczynski I decided to avoid `if` usage in my QA flow.
> 
> So I replaced `if / else` with [Selenium IDE right-click](https://github.com/SeleniumHQ/selenium-ide/issues/754#issuecomment-688308753) and [Selenium IDE shortcut key combinations](https://github.com/SeleniumHQ/selenium-ide/issues/929#issuecomment-688311858)

Too bad, i tried like 2 hours to get a workarround running ... but nothing fixed my problem. I tried to run a click task only if the element is available and found no solution for that, only the statusOK one, which is not working anymore ...

**Comment by Kartoya** [comment]
I don't want to sound too harsh, but ¿why call it a stable version if so many basic features don't work?

**Comment by xbiggyl** [comment]
A year on and this is still not working. Any possibility for a solution or at least a workarounds?

**Comment by PeterThomasAwen** [comment]
This is also happening on Edge Version 92.0.902.49 (Official build) beta (64-bit) (Debian)
Selenium IDE v 3.17.0
![Screenshot from 2021-07-20 15-44-01](https://user-images.githubusercontent.com/69471531/126344674-9a218f9c-4a8c-4359-aab8-a498109ed36c.png)

**Comment by BorderCloud** [comment]
If you need the StatusOK variable, here's a workaround with DOM:
![image](https://user-images.githubusercontent.com/352813/127665187-ea2cddb5-bd41-42c9-b88d-ac65521b27cc.png)

**Comment by Juerg-E** [comment]
> 
> 
> Having the same issue at:
> 
>     * Selenium IDE, Version 3.17.0
> 
>     * Chrome Version 84.0.4147.125 (Official Build) (64-bit)
> 
> 
> Command 	Target
> if 	${!statusOK}
> end 	
> 
> > 1. if on ${!statusOK} Failed:
> >    Unexpected token '{'
> 
> <img alt="Screenshot 2020-08-18 at 12 10 10" width="978" src="https://user-images.githubusercontent.com/5191620/90494108-d163d900-e14b-11ea-9e1b-a9cf59720bbb.png">

Inizialisiere erst die Variable oder teste ob sie existiert.
if | "${!statusOK}" == "$" + "{!statusOK}"
  echo | This var is not set!
end

**Comment by Juerg-E** [comment]
Translation: First initialize the variable or test whether it exists.

**Comment by Delta0001** [comment]
Reporting the same issues described above

> * Selenium IDE, Version 3.17.2
> * Chrome Version 103.0.5060.66 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4537617/177249439-b3eeee83-e019-4497-9a06-d9811ea02c37.png)

**Comment by toddtarsi** [comment]
@alliedcvil - Version 4 is currently in alpha, you can download the nightly version here:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/latest

**Comment by toddtarsi** [comment]
@alliedcvil @Delta0001 - I'm closing this issue, feel free to open a new one if this persists in v4, thanks!
