### ISSUE TITLE
Proxy settings appear to be ignored

### ISSUE THREAD

**Issue by vbisbest** [SeleniumHQ/selenium-ide#1074]
## 🐛 Bug Report

When specifying proxy settings, they appear to be ignored by side-runner.   Example:
`selenium-side-runner -c "browserName=firefox" --proxy-type=manual --proxy-options="http=192.168.1.5:8080" amazon.side`

Tried using Chrome and Firefox with same results.   In the above example the proxy ip address does not exist yet the test still runs successfully.

Using latest version of side-runner and chrome version 83.

**Comment by vbisbest** [comment]
User error, did not specify "https" proxy settings.

**Comment by hudec117** [comment]
@vbisbest could you please share the command including the proxy settings that worked for you?
