### ISSUE TITLE
Bulk copy command rows for re-use elsewhere

### ISSUE THREAD

**Issue by MuntedKiwi** [SeleniumHQ/selenium-ide#1092]
## 🚀 Feature Proposal

Currently only able to copy a solitary command row at a time. It would be extremely useful and efficient to be able to bulk copy blocks of command rows for re-use elsewhere. 

## Motivation

Copying a single command row at a time and porting each time to another part of the script or another script is time consuming.

## Example

Try to hold down shift and other keyboard keys to try to select more than a single command row at a time. No joy. Can only copy one command row at a time.

**Comment by corevo** [comment]
Duplicate
