### ISSUE TITLE
Any common wait command or retry option if commands fail

### ISSUE THREAD

**Issue by vikasqb** [SeleniumHQ/selenium-ide#1096]
## 💬 Questions and Help

Is there somehow I can manage to run my side file using selenium side runner so that I need to make it work with minimal usage of wait commands. Or do we have a retry command if a command is failed due to the unfinished page load, overlay, etc?

**Comment by jeremylorino** [comment]
Most of the time the driver automatically waits for page load and for the existence of an element before interaction.

Do you have more specifics?

**Comment by toddtarsi** [comment]
Closing, in v4 most commands have an implicit timeout / polling condition.
