### ISSUE TITLE
Command plugins access driver

### ISSUE THREAD

**Issue by c24wallis** [SeleniumHQ/selenium-ide#1099]
## 🚀 Feature Proposal

Allow command plugins to access the driver object.

## Motivation

This would allow command plugins like reading or setting querystring values for example, which cannot be done without a handle to the test window.

## Example

Something like:
chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  message.driver.close(); // close the browser
}

**Comment by corevo** [comment]
Selenium IDE does not use webdriver in the browser.

So I'm not sure what you are trying to achieve, maybe instead of suggesting a solution you should suggest a use case that we can accommodate within Selenium IDE.

**Comment by c24wallis** [comment]
Hi - thanks for your reply.

I'm trying to write a plugin as described here: https://www.selenium.dev/selenium-ide/docs/en/plugins/adding-commands

What I need (initially) are commands which will read and write querystring variables, but if I do anything like window.whatever I'm looking at my own plugin window rather than the automated browser window opened by Selenium IDE.

The reason for this is because I have URLs like:
www.example.com/articles?id=5
My test will be something like:
Create New Article
Store ID from Querystring
Open article as different user, using the ID parameter
Assert that the content is correct.

When I referred to the driver above, I mean that inside the IDE code I see things like:
async doOpen(url) {
    await this.driver.get(absolutifyUrl(url, this.baseUrl))
  }

This driver object is basically what I need to get at.

I'm aware this may be impractical, but the rest-like API doesn't seem like a good fit either as it'd be difficult to add everything to it that a driver object might do - i.e. it's querystrings I need today, but it might be that I need my command to navigate somewhere, or to resize the browser etc (imagine something like resize the browser to a predefined size then take a screenshot for user documentation, or to take a snapshot of the DOM as I go for better reporting later, or similar).

All of this could probably be done now using Run Script, but I'd rather limit this to easier to use Selenese commands for the Junior members of the team so they don't have to do any javascript.

Thank you for your consideration of this!

**Comment by capoerafreak** [comment]
why do you want to create a plugin for that
use these commands:

`execute script | return window.location.href; | url `
and then again execute script with a replace ${url}, „http://www.example.com/articles?id=„

**Comment by c24wallis** [comment]
Hi,
The reason I want to do it is because I already did exactly these (and a load more for various cases in our app) in Katalon recorder and I want my team of non-programmers to use Selenium IDE instead.  So a good migration path for me would look like "hey guys, install this and all the commands you already use day to day will still work, plus this one is far better".  Without this, my migration path is "hey, go learn javascript for a few weeks, then install this and rewrite these hundreds of commands"

Also, the specific example is picked as one that is easy to understand, there are other commands that will have similar requirements but do different things that are harder to explain in a ticket.  To give another example, we have coding rules that we automatically check, like "all elements must have this data attribute".  Right now, I have a command that verifies this by looking at a snapshot of the DOM and doing a verify.  However, with Selenium IDE and the execute script command I'd need a VERY big script to do this, or I'd need a smaller script run for every target element on the page.  IF I could access the DOM of the page being tested this would be easy again.

Hope this is a bit clearer?
Thanks

**Comment by corevo** [comment]
You can change the query string right now with plugins, with each command you get in the options the current windowId and tabId.

You can use those to execute Javascript on that page using [tabs.executeScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript).

**Comment by c24wallis** [comment]
Thank you.  When I try that I get permissions errors - seems like the tab ID I get is for the Selenium IDE window rather than the one it's controlling, so Chrome gives me something like chrome.tabs.executeScript: Cannot access a chrome.  Any idea how I'd get round this, please, and if it will work this might be a good example to add to the docs?
Thanks

**Comment by c24wallis** [comment]
Trying again just now, I think this may have solved it by changing my plugin manifest permissions - can I suggest you consider putting the tip about using tabs.executeScript into the documentation?

Thank you very much for your help!
