### ISSUE TITLE
Wildcards on verify not working in new IDE

### ISSUE THREAD

**Issue by setiseta** [SeleniumHQ/selenium-ide#110]
on the old IDE it was possible to use wildcards on any verify command.
(I used obj-*)
this is needede if we are testing an obj creation and after creation i get a titel with obj-[id]
so the id is increasing on every testrun.
so i can't use static values.

**Comment by olds97lss** [comment]
Can you use xpath?

//input[starts-with(@title,'obj-')]

**Comment by corevo** [comment]
In this case I would highly recommend using XPath, since the locator you suggested is not compatible with webdriver.
Same goes with css=contains which should be replaced for future support.

Cheers,
Tom

**Comment by setiseta** [comment]
the problem is, that there is no 'waitForVisible' or something like this, to just check if an element is on the page.

**Comment by corevo** [comment]
verifyElementPresent will be included shortly

Cheers,
Tom

**Comment by setiseta** [comment]
ok thanks, this seems to work, with the new assert element present & xpath
