### ISSUE TITLE
Need help with open Selenium IDE from API then start recording and save it  

### ISSUE THREAD

**Issue by AsafGutman** [SeleniumHQ/selenium-ide#1102]
## 💬 Questions and Help
HI 
i read your post  - Add API methods in Selenium IDE to trigger certain actions #780
and i wonder if you can assist me with sharing the code of starting Selenium IDE from API and start recording 
very appropriate your attention to this post 
BTW 
my framework is based on C# so i want to execute it via Visual studio using  the below example : 
((IJavaScriptExecutor)driver).ExecuteScript("chrome.runtime.sendMessage(\"mooikfkahbdckldjjndioackbalphokd\", {startSideIfClosed: true}, res=>console.log(JSON.stringify(res)));");

the issue is i'm getting the same error all the time  :
OpenQA.Selenium.WebDriverException: 'javascript error: Cannot read property 'sendMessage' of undefined
  (Session info: chrome=84.0.4147.89)'

my full code till now :
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace IDE
{
    class Program
    {
        static void Main(string[] args)
        {
            ChromeOptions options = new ChromeOptions();

            // load IDE extension to chrome
            options.AddExtension(@"C:\Main\temp\extension_3_17_0_0.crx");

            IWebDriver driver = new ChromeDriver(options);

            // Change string inside to JS code that will start recording with the IDE //
            ((IJavaScriptExecutor)driver).ExecuteScript("console.log('started IDE recording');");
           
           ((IJavaScriptExecutor)driver).ExecuteScript("chrome.runtime.sendMessage(\"mooikfkahbdckldjjndioackbalphokd\", {uri: \"/record/session\", verb: \"post\", payload: {url: 'https://www.google.com'}});");// <--- here i'm getting the error 
                        
           // driver.Navigate().GoToUrl("https://www.google.com");
           // driver.Manage().Window.Maximize();

           // // Do some more actions on the url
           // // ……

           // // End recording    
           // ((IJavaScriptExecutor)driver).ExecuteScript("chrome.runtime.sendMessage(\"mooikfkahbdckldjjndioackbalphokd\", {uri: \"/record/session\", verb: \"delete\"});");
           // ((IJavaScriptExecutor)driver).ExecuteScript("console.log('IDE recording stopped');");

            driver.Quit();

            // export the recording to some file
            ((IJavaScriptExecutor)driver).ExecuteScript("<export the recording to code>");
        }
    }
}

the target of the code is to start recording from API than export the test 
10X  

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
You can't access the `chrome` or `browser` object from the ExecuteScript method, because that method runs on the document (for security reasons, please refer to MDN for information about these objects).

In order to access these objects you need to execute your javascript code in an elevated sandbox, such as an extension sandbox, you can't access this sandbox from WebDriver, because it is not part of the WebDriver spec, currently we offer our plugin API via other extensions, so you could develop your own extension to manage Selenium IDE.

**Comment by AsafGutman** [comment]
Hi Tomer
Many thanks for your quick response, can you please guide me where to start
Appreciate your assistance
10x
Asaf

השג את Outlook עבור Android<https://aka.ms/ghei36>

________________________________

**Comment by corevo** [comment]
You can check our documentation [here](https://www.selenium.dev/selenium-ide/docs/en/plugins/plugins-getting-started)
