### ISSUE TITLE
 if on $(myVar) === "a" Failed: $ is not defined

### ISSUE THREAD

**Issue by valgen** [SeleniumHQ/selenium-ide#1129]
## 🐛 Bug Report

The first example in this page:
**https://www.selenium.dev/selenium-ide/docs/en/introduction/control-flow**
when run returns this error:
 **if on $(myVar) === "a" Failed: $ is not defined**

## To Reproduce

Copy the code from the first example in this page:
**https://www.selenium.dev/selenium-ide/docs/en/introduction/control-flow**
run and it returns this error:
 **if on $(myVar) === "a" Failed: $ is not defined**

## Expected behavior

It should not return an error

## Project file reproducing this issue (highly encouraged)
There is no need for a project.

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  N/A
Browser: Google Chrome
Browser Version: 85.0.4183.83 (Official Build) (64-bit)

**Comment by corevo** [comment]
I guess its hard to see in the image, due to size and font used, but the correct syntax is `${myvar}` not `$(myvar)`, use curly braces not parenthesis.
