### ISSUE TITLE
v1.0.3 into an xpi

### ISSUE THREAD

**Issue by olds97lss** [SeleniumHQ/selenium-ide#113]
Can this be put into an xpi for those of us less capable to use?

Thanks.

**Comment by corevo** [comment]
Yes, I'll make sure to publish it

Cheers,
Tom

**Comment by corevo** [comment]
[Published](https://github.com/SeleniumHQ/selenium-ide/releases/download/v1.0.3/selenium-ide.xpi)

**Comment by olds97lss** [comment]
Thanks!
