### ISSUE TITLE
Issue selecting frames

### ISSUE THREAD

**Issue by Tom-Trumper** [SeleniumHQ/selenium-ide#115]
Version: 1.0.3.
Browser: Google Chrome 64.0.3282.186 (64-bit)
OS: macOS 10.13.3

Attempting to execute the `select frame` command with target `index=0` results in _Failed:
Timeout_.

Attached is example test case used to reproduce issue:
[Test Project.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/1763541/Test.Project.side.zip)

**Comment by corevo** [comment]
Fixed, will be included in v1.0.4

**Comment by riskers** [comment]
@corevo when to update version?

**Comment by baseemas** [comment]
Timeout issue is appearing again..
![image](https://user-images.githubusercontent.com/48471350/54183987-2d81f280-44ae-11e9-8492-5e6940b2cd00.png)

**Comment by tourdedave** [comment]
@baseemas What version of the IDE are you running? The GUI looks very different.

**Comment by corevo** [comment]
@baseemas please open SideeX issues with the SideeX project.  
https://github.com/SideeX/sideex

**Comment by baseemas** [comment]
comment added to https://github.com/SideeX/sideex/issues/8

**Comment by corevo** [comment]
Just as an fyi SideeX and Selenium IDE are completely separate projects, and if your tool of choice is SideeX you should ask in their forums for help.  
This issue tracker is for Selenium IDE issues only.
