### ISSUE TITLE
selenium-side-runner won't save cookie info

### ISSUE THREAD

**Issue by thefuckingcode** [SeleniumHQ/selenium-ide#1152]
## 🐛 Bug Report

if need to login by oauth2, selenium-side-runner wont get the right home page.I assume selenium-side-runner doesn't save the cookie info ,which leads to get homepage wrongly.

what should i do ? 

the version of selenium-side-runner is 3.17.0

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

You might have better luck posting your question to [the Google group](https://groups.google.com/forum/#!forum/selenium-users) or [the Selenium Slack channel](https://seleniumhq.herokuapp.com/).
