### ISSUE TITLE
When test fails , selenium-side-runner should output the same message as Selenium IDE does

### ISSUE THREAD

**Issue by thefuckingcode** [SeleniumHQ/selenium-ide#1157]
## 🚀 Feature Proposal

When test fails , selenium-side-runner should output the same message as Selenium IDE does

## Motivation

When test fails , selenium-side-runner should output the same message as Selenium IDE does

## Example
This is what selenium IDE outputs:
![image](https://user-images.githubusercontent.com/23526448/99048884-1a072300-25d1-11eb-8f55-6e348f220dd6.png)
And this is what selenium-side-runner outputs:
![image](https://user-images.githubusercontent.com/23526448/99048919-2ab79900-25d1-11eb-9ac5-1f8cfe38b8b5.png)

I think the message that selenium-side-runner outputs is not precise

**Comment by toddtarsi** [comment]
This should be resolved in v4, which uses a shared runtime.
