### ISSUE TITLE
Unable to import a javascript file into the Selenium IDE for Chrome

### ISSUE THREAD

**Issue by ksl4u** [SeleniumHQ/selenium-ide#1159]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.
I am currently using the selenium IDE Version 3.17.0 and I am trying to import a .js file into the Selenium IDE. But, I am getting the error "Error migrating project Unknown file was received". Could someone please help me with resolving this.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
