### ISSUE TITLE
When saving, it doesn't remember the last folder used.

### ISSUE THREAD

**Issue by olds97lss** [SeleniumHQ/selenium-ide#116]
When opening a script, then saving a script, it seems to always default to the default firefox download folder instead of the folder I go to when I open the script or the folder I just went to when saving the script.

I don't know if this is something that can be remedied, but thought I'd mention it as it can get a bit irritating when you really dig in to a batch of scripts.

**Comment by corevo** [comment]
It is not something that we can currently fix,  
It is a limitation of browser vendors on extensions to keep them from accessing your computer files.  
The save works exactly as downloading a file would.

**Comment by olds97lss** [comment]
Thanks for the info. Guess that's one more thing "new and improved" has removed from Firefox. Guess I'll have to start making shortcuts in my downloads folder to wherever I'm working on scripts at the time.

**Comment by corevo** [comment]
Sorry about that.

Cheers,
Tom
