### ISSUE TITLE
Unable to import a javascript file into the Selenium IDE for Chrome

### ISSUE THREAD

**Issue by ksl4u** [SeleniumHQ/selenium-ide#1160]
I am currently using the selenium IDE Version 3.17.0 and I am trying to import a .js file into the Selenium IDE. But, I am getting the error "Error migrating project Unknown file was received". Could someone please help me with resolving this.

**Comment by tourdedave** [comment]
Selenium IDE can exports to JS files, but it cannot import them. It can only open Selenium IDE scripts (and import legacy Selenium IDE scripts).
