### ISSUE TITLE
Unable to upload files due to cross origin frames in the page

### ISSUE THREAD

**Issue by hayleydack** [SeleniumHQ/selenium-ide#1164]
## 🐛 Bug Report

Error: "Failed: Unable to upload files due to cross origin frames in the page" when uploading document via web app.  This happens when testing and worked in March 2020.  

## To Reproduce

Using a web application which uses multiple frames, navigate to the file upload prompt and then use command 'type', target is the fileupload field and value is the filepath.  Using Chrome browser.

## Expected behavior

The file name appears in the fileupload field and when the save option is selected, the file uploads.

## Project file reproducing this issue (highly encouraged)

Due to the nature of the application, I am unable to share a project file.

## Environment

OS: Windows 10 Enterprise, 1803, 17134.1845
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  Not sure
Node version: Not sure
-->
Browser: Chrome
Browser Version: 86.0.4240.198 (64-bit)

**Comment by toddtarsi** [comment]
I'm going to assume this isn't an issue in v4 and close this, but feel free to re-open if you see it there as well

**Comment by jezahl** [comment]
Hey @toddtarsi 
I'm seeing this issue in 3.17.2 of IDE.
Is there a v4 somewhere??

**Comment by toddtarsi** [comment]
Yep! IDE releases are here:

https://github.com/SeleniumHQ/selenium-ide/releases

**Comment by jezahl** [comment]
Thanks. Does the IDE behave differently to the Chrome Extension I was using?

For example, I have one Test which calls other Tests. In the Chrome Extension these other Tests would be called sequentially. In the full IDE the Tests seem to get called in parallel?

**Comment by toddtarsi** [comment]
Should be sequential
