### ISSUE TITLE
Selenium IDE Large delay when try to run script in Chromium Edge

### ISSUE THREAD

**Issue by melode11** [SeleniumHQ/selenium-ide#1165]
## 🐛 Bug Report

Selenium IDE is not able to run script in Chromium Edge immediately, it is always showing Waiting for Selenium IDE to start plugin(Control mode) for the first couple minutes before start.

![image](https://user-images.githubusercontent.com/3647507/101699853-d917f800-3a30-11eb-8935-feee30eed925.png)

No exception is caught by debugging.

## To Reproduce

Launch Selenium IDE in control mode. 
Record any scripts
Run the scripts.

## Expected behavior

The run should start.

## Environment

OS: 
Selenium IDE Version: 3.17.0
Browser: Chromium Edge.
Browser Version: 87.0.664.57

**Comment by toddtarsi** [comment]
v4 resolves this by only performing ide-playback in electron currently
