### ISSUE TITLE
Remember the path of the opened project

### ISSUE THREAD

**Issue by danielzzz** [SeleniumHQ/selenium-ide#1169]
## 🚀 Feature Proposal

When saving a project it suggests to save it in the same directory it was opened from

## Motivation

right now my project is well deep in the tree, it's a hassle to have to find it every time I try to save the project.
what is surprising that the open feature does remember the latest used location

## Example

just click save to store it

**Comment by corevo** [comment]
As a security mechanism browsers don't give us the path to the file when we load it, just the name of it.

And the dialog itself is completely out of our hand, we can open it, but can't specify in what directory it should be open, I know it is frustrating, but this is part of #363, it suffers from the same limitations.

**Comment by danielzzz** [comment]
but do you get the directory when saving? 
for me it's opening the same directory I have opened the file from. 
maybe you could pick it up from here (sorry if saying stupid things, not sure what you get when saving)

cheers, dan

**Comment by corevo** [comment]
I don't get to pick the directory in which the files are saved, only the file name.

The directory is picked either via the OS, or the browser.
