### ISSUE TITLE
Error : Page wait timed out after 30000ms

### ISSUE THREAD

**Issue by ganesh2183** [SeleniumHQ/selenium-ide#1176]
Using Selenium IDE to record the application flow. When I play the record, I face the error message as "[error] Page wait timed out after 30000ms" while opening the url.

Please help how to fix this error.
![IMG_20210109_100913](https://user-images.githubusercontent.com/41476297/104084048-b5cbad00-5269-11eb-8f45-f5c2e09a214d.jpg)

**Comment by toddtarsi** [comment]
In v4, you can adjust the implicit timeout in the suites pane to set the default implicit waiting limit on all commands. In addition to that, you can set a custom timeout using the -t flag from the side-runner
