### ISSUE TITLE
Selenium and CI

### ISSUE THREAD

**Issue by xbouillet** [SeleniumHQ/selenium-ide#1178]
I would like to use Selenium in my CI process. I plan to use selenium-side-runner by calling it in gitlab. I don't understand why to use a selenium server or a standalone selenium server. The runner is enough, isn't it?

thank you for your explanations

**Comment by AutomatedTester** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

There are awesome people there that can help guide you through the process
