### ISSUE TITLE
Key name different between IDE and CLI runner

### ISSUE THREAD

**Issue by wangchj** [SeleniumHQ/selenium-ide#1190]
## 🐛 Bug Report

We have a set of tests written in Selenium IDE and we're like to run them using selenium-side-runner.

We have 1 test that uses has the following command to clear an input text box:

```json
        {
          "id": "98e7e101-dd74-46b7-96e7-399562abadaf",
          "comment": "Clear OffsetX",
          "command": "sendKeys",
          "target": "css=#motionImageInserterOffsetXInput input",
          "targets": [],
          "value": " ${KEY_BACKSPACE}"
        },
```

We found that `${KEY_BACKSPACE}` works in Selenium IDE but doesn't work in side-runner and `${KEY_BACK_SPACE}` works in side-runner but not in Selenium IDE.

## To Reproduce

1. Run the attached .side file in Selenium IDE. This would succeed
2. Run the same .side file using selenium-side-runner. This would fail

The error message is

```
  TypeError: each key must be a number of string; got undefined

      36 |   });
      37 |   await driver.wait(until.elementLocated(By.css(`#motionImageInserterOffsetXInput input`)), configuration.timeout);
    > 38 |   await driver.findElement(By.css(`#motionImageInserterOffsetXInput input`)).then(element => {
         |   ^
      39 |     return element.sendKeys(` `, Key["BACKSPACE"], Key["BACKSPACE"]);
      40 |   });
      41 |   await driver.wait(until.elementLocated(By.css(`#motionImageInserterOffsetYInput input`)), configuration.timeout);

      at ../node_modules/selenium-webdriver/lib/webdriver.js:2011:15
          at Array.forEach (<anonymous>)
      at WebElement.sendKeys (../node_modules/selenium-webdriver/lib/webdriver.js:2006:31)
      at Object.<anonymous>.tests.Job with Motion Graphic Inserter (commons.js:38:3)
      at Object.<anonymous> (JobwithMotionGraphicInserter.test.js:11:5)
```

## Expected behavior

Key name should be consistent between Selenium IDE and selenium-side-runner.

## Project file reproducing this issue (highly encouraged)

Please see [key_name_bug.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/5907806/key_name_bug.side.txt)

## Environment

OS: OSX
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version: 3.17.0
Node version: 13.10.1
Browser: Chrome
Browser Version: 88.0.4324.96 (Official Build) (x86_64)

**Comment by toddtarsi** [comment]
This is resolved in v4, since all playback; ide and cli uses selenium-webdriver.
