### ISSUE TITLE
Error thown when entering //comment

### ISSUE THREAD

**Issue by Plm01** [SeleniumHQ/selenium-ide#1194]
## 🐛 Bug Report

Hi, 
I'm using Google Chrome is up to date
Version 88.0.4324.150 (Official Build) (64-bit)
For Windows 10

I'm adding comments to each line.  When I run the script, an error is thrown for one comment.  If the comment is removed, the script is successful.

![image](https://user-images.githubusercontent.com/78829935/107446293-8338fc80-6b14-11eb-83c4-ff64dfa9d3e7.png)

**Comment by toddtarsi** [comment]
I believe this is resolved in v4. If it appears to be an issue, please let me know. Thanks!
