### ISSUE TITLE
Installation selenium-side-runner

### ISSUE THREAD

**Issue by xbouillet** [SeleniumHQ/selenium-ide#1196]
Hello,

I try to install selenium-side-runner on a unbuntu server.
I'dont have a GUI interface.

I think I need to install XVBF.

`npm install -g selenium-side-runner`

` npm install -g chromedriverr`

This command failed, in same time i dont have Chrome beacause I dont'have a GUI interface.

So i install xvbf 

` sudo apt install xvfb`

And when i try to lauch selenium, 

`selenium-side-runner test.side`

I have a error: 

```
info:    Running test CI.side
 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    The ChromeDriver could not be found on the current PATH.
```

Could you help me install selenium-side-runner on a server without a GUI interface?

Thank you and wish you a good day  :) :)

**Comment by xbouillet** [comment]
UPDATE:

I have also install chrome

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
sudo apt install chromium-browser
```
And i have configure Xvbf:

```
 Xvfb :10 -ac &
export DISPLAY=:10
```
But I have still error :'( :'(

selenium-side-runner test.side
```
info:    Running test.side
 FAIL  ./DefaultSuite.test.js
 Test suite failed to run
WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

  at Object.throwDecodedError (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
  at parseHttpResponse (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
  at Executor.execute (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)
```

**Comment by toddtarsi** [comment]
A couple notes to help. You want these capabilities to make this work:

```
selenium-side-runner -c \"goog:chromeOptions.args=[headless,no-sandbox] browserName=chrome\" -d -t 15000 ./project.side
```

If you do these, you should be fine.

I'm going to close this for now, as this is very much a "getting started with selenium" problem, and outside of the scope of the ide and a runner.
