### ISSUE TITLE
This item has been disabled in Chrome. Enable this item

### ISSUE THREAD

**Issue by tdorritie** [SeleniumHQ/selenium-ide#1200]
I cannot ENABLE Selenium IDE, it was there yesterday. Around 3pm EST I got a message stating several apps [removed] and extension [disabled] items 'may be dangerous'. My system wants me to remove form chrome but I need for my work. Any information will be helpful

## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by AutomatedTester** [comment]
Hi

Where did the message come from? Was it from your IT dept removing things they felt were not safe?

**Comment by tdorritie** [comment]
Yes they did, back now.
Thanks
