### ISSUE TITLE
Selenium IDE Extension for Chrome Browser

### ISSUE THREAD

**Issue by sarisrael** [SeleniumHQ/selenium-ide#1204]
Our organization network is isolated from the internet
in order to use Selenium IDE Extension for Chrome Browser (https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd)
we need to download it and bleach it 
Is there a way to get the extention file?

**Comment by minhiu** [comment]
https://github.com/SeleniumHQ/selenium-ide/releases
Scroll down and download "selenium-ide.zip"
