### ISSUE TITLE
What you added to PATH seems faulty, I'm not sure on windows but on mac it should end with `node_modules/.bin`

### ISSUE THREAD

**Issue by paswain** [SeleniumHQ/selenium-ide#1205]
i am getting error when running script
Error: Error: Error: The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.

please give me the path for mac

**Comment by toddtarsi** [comment]
Noting here, nothing about the path to chromedriver is in the scope of this project. That's your own challenge, and selenium's website has great tutorials here:

https://chromedriver.chromium.org/getting-started
