### ISSUE TITLE
Jest did not exit one second after the test run has completed

### ISSUE THREAD

**Issue by clicio** [SeleniumHQ/selenium-ide#1206]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
Resolved in v4
