### ISSUE TITLE
Error Jest did not exit one second after the test run has completed

### ISSUE THREAD

**Issue by clicio** [SeleniumHQ/selenium-ide#1207]
## 🐛 Bug Report

About once a week my test randomly case abort at no specific test.
I Run hundreds of test in a row and some condition lets to this error.

## To Reproduce

Running  hundred of scripts with differente selenium-ide calls

## Expected behavior

I expect that all  test cases allways run 

## Project file reproducing this issue (highly encouraged)

N/A

Issues without a reproduction project are likely to stall.

## Environment

OS Windows 10
Selenium IDE Version: 3.15.1
Selenium SIDE Runner Version:  3.17
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 14
Only required if using selenium-side-runner
-->
Browser:
Browser Chrome version 87

**Comment by toddtarsi** [comment]
Resolved in v4
