### ISSUE TITLE
IDE doesn't execute `send keys` command properly in some cases

### ISSUE THREAD

**Issue by Vlad-Galeev** [SeleniumHQ/selenium-ide#1213]
## 🐛 Bug Report

The IDE extension doesn't run the `send keys` command under one Chrome user, but it does under another. When run through FF it runs the command one user tested though. 

## To Reproduce

Website: https://www.labirint.ru/
My code:
```
open|  /  |
click|  id=search-field  |  
type|  id=search-field  |  978-5-907180-08-6
send keys|  id=search-field  |  ${KEY_ENTER}
```
Detailed steps to reproduce the behavior:

## Expected behavior

Even under a brand new chrome user that is created just for testing Selenium scripts the `${KEY_ENTER}` should be sent.  
On my logged in user which I am using constantly, the Enter key is pressed, and the search goes through.   
The same thing should happen on another user.   
The `send keys` shows up in the logs as `OK` but it doesn't do anything on the empty user.  
On the normal user it presses enter in a search bar, thus sending the GET request.AND shows up in the logs as `OK`.

## Test script or set of commands reproducing this issue

I have the script above.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 89.0.4389.90 (Official Build) (64-bit)
Browser Driver version: 89.0.4389.23 !!Note!! this driver is broken when used with Python. crashes PC with a DPC WATCHDOG VIOLATION every time.  
Language Bindings version: Selenium IDE extension for chrome

**Comment by frankhuurman** [comment]
Experiencing the same issue in Brave browser on Ubuntu 20.04.
Tried to record the following test:
- youtube.com base URL
- click the searchbox
- type hola
- click the search button

But the Selenium IDE never gets past the send keys so the search is never executed, tried rerunning and rerecording it several times but no success.

**Comment by toddtarsi** [comment]
v4 uses electron + chromedriver for recording and playback, the design by nature won't have this issue as nothing is emulated anymore
