### ISSUE TITLE
CPU usage has always been high in task manager

### ISSUE THREAD

**Issue by ch219318** [SeleniumHQ/selenium-ide#1214]
## 🐛 Bug Report

When "new tab" is open , the CPU usage is always high. And I didn't use Selenium at the time.
When I turn off senelium, the cpu usage becomes 0

![image](https://user-images.githubusercontent.com/13566639/112086274-e06da680-8bc6-11eb-8871-70126481bed9.png)

## Environment

OS: OSX 10.15.7
Selenium IDE Version:  3.17.0

Browser:
Browser Version: 89.0.4389.90 (x86_64)

**Comment by toddtarsi** [comment]
Well, whole new architecture now. Instead of a high CPU browser extension, it's a high CPU standalone binary 🤷 I'm calling that a fix and closing this
