### ISSUE TITLE
[Firefox] The Components object is deprecated. It will soon be removed.

### ISSUE THREAD

**Issue by rimace** [SeleniumHQ/selenium-ide#1219]
## 🐛 Bug Report

The Firefox (78.9.0 ESR and 88.0 beta) developer console produces an error on every page load stating `The Components object is deprecated. It will soon be removed.`

Please note that there was the bug report #598 , but as @tourdedave wrote, that issue was resolved in 2019, so I guess this one is a new issue.

## To Reproduce

Install the Firefox addon from https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/ ; load any page.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10 / Fedora 34
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version: -
Browser: Firefox
Browser Version: 78.9.0 (ESR) and 88.0 beta

**Comment by wesleywerner** [comment]
This was already reported and closed with Wont Fix. See  #598

**Comment by rimace** [comment]
I saw that.
From my understanding it was closed under the assumption that it will be fixed in the same year. 
So I thought this is a new bug that has nothing to do with #598

**Comment by wesleywerner** [comment]
Indeed, I thought the very same. But I don't think it will get fixed. The good thing is that #598 mentions "when Components get removed, the extension will still work."

Curiously I can't find the native app mentioned there.

**Comment by toddtarsi** [comment]
Not an issue in v4, which runs as an electron binary
