### ISSUE TITLE
Properties minlength and maxlength in input form fields are bypassed

### ISSUE THREAD

**Issue by ualjjcanada** [SeleniumHQ/selenium-ide#1222]
## 🐛 Bug Report

When a input form field has the properties minlength and/or maxlength, type a value in the input field without fitting the minlength or maxlength requirements, the form is submmited without error.

## To Reproduce

Go to a demo page with one input text field validated by minlength and/or maxlength , such as: https://www.wufoo.com/html5/minlength-attribute/
Input a text shorter than 8 characters
Click Submit

## Expected behavior

When click on submit, the browser should show the error message. 
However, Selenium IDE bypasses the error message.
Other validation properties such as "required" or "pattern" are correctly managed by Selenium IDE.

## Project file reproducing this issue (highly encouraged)

A project file `.side` that reproduces this issue is available here: https://github.com/ualjjcanada/selenium-ide-samples

## Environment

OS: Windows 10
Selenium IDE Version:  v3.17.0
Browser:
Browser Version: Firefox 87.0 (64-bits), Chrome  89.0.4389.114 (64-bits)

**Comment by toddtarsi** [comment]
This is likely resolved on v4, seeing as it directly automates a webdriver for local playback now.
