### ISSUE TITLE
selenium side runner is not running / No Output /No error

### ISSUE THREAD

**Issue by jayantmandhare** [SeleniumHQ/selenium-ide#1226]
Hello, 

I am currently running an issue with the selenium side runner when I tried running the side file. The side file don't have much activity in it just browsing in google so that I could test if the selenium side runner. But the selenium driver is not executing my file also not giving any error. The command prompt doesn't show anything. I`ll attach my file below for your reference.
![image](https://user-images.githubusercontent.com/45041732/114924115-3d8a0000-9df3-11eb-9a1c-9d2ef847474e.png)

 I am not sure where the problem is. I have installed chromedriver and also assigned a path in the windows advance settings. But the selenium side runner is not executing my file. May I know what needs to be done in this case?

here is the file : https://drive.google.com/file/d/1AIlRqbG04y6TawO-bcVbcGOruYbrZyG3/view?usp=sharing

**Comment by toddtarsi** [comment]
@jayantmandhare - I believe this should be resolved on v4, closing but feel free to re-open if still an issue there
