### ISSUE TITLE
wrong translation of selectFrame(relative=top)

### ISSUE THREAD

**Issue by larstippmann** [SeleniumHQ/selenium-ide#1228]
Selianize, commands.js
Line 616
if (frameLocation === 'relative=top') {
    return Promise.resolve('await driver.switchTo().frame();')

should be
if (frameLocation === 'relative=top') {
    return Promise.resolve('await driver.switchTo().defaultContent();')

frame() causes an error

**Comment by toddtarsi** [comment]
No longer using selenianize in v4
