### ISSUE TITLE
[selenium-side-runner]Cannot set chromedriver path on command line. 

### ISSUE THREAD

**Issue by vbisbest** [SeleniumHQ/selenium-ide#1235]
It seems like its not possible to set the path to the chromedriver for the side runner.  The chrome options for binary only sets the chrome app location.  e.g. 

`selenium-side-runner -c "browserName=chrome goog:chromeOptions.binary='browser/chrome-mac'"`

Does side runner solely rely on finding the chromedriver based on the PATH variable?   If this is the case, it would be a helpful  add this capability as a feature.

**Comment by AirbornePanda** [comment]
See https://stackoverflow.com/questions/57011098/how-do-i-run-my-selenium-side-runner-to-execute-my-test-against-firefox

Either the webdriver should check for chromeOptions inside the capabailities of the builder or jest-environment-selenium should set the chrome options in the driver. Currently it's none of the above, so setting the path is your only option:

`$PATH=/path/to/chromedriver:$PATH selenium-side-runner -c "browserName=chrome" myTest.side`

**Comment by toddtarsi** [comment]
I'm sorry, but this is a problem for selenium-webdriver core, not the side-runner. Getting drivers onto $PATH, or running the driver manually beforehand is outside the scope of this project.

As a result, I'm going to close this. If you still have issues, please raise an issue in Selenium core.
https://github.com/SeleniumHQ/selenium/issues
Thanks!
