### ISSUE TITLE
Selenium IDE - Run with Side runner fail with variable in object location

### ISSUE THREAD

**Issue by fopaitry** [SeleniumHQ/selenium-ide#1236]
## 🐛 Bug Report

Run with Side runner fail on variable in object location  while it's running fine with Chrome Selenium IDE Extension

## To Reproduce

Run  :
selenium-side-runner --output-directory="H:\99 - Documentation\FPAITRY\Taches spécifiques\Selenium\results" --output-format=junit "H:\99 - Documentation\FPAITRY\Taches spécifiques\Selenium\RHPI-exports.side" --filter TS_FPY

## Current behaviour : 
  
TS_FPY
    × TC_AGRESSO_TI07 (6234ms)

  ● TS_FPY › TC_AGRESSO_TI07

    Unknown locator ${vars.sousmenu}

      112 |       return element.click();
      113 |     });
    **> 114 |     throw new Error("Unknown locator ${vars.sousmenu}");**
          |           ^
      115 |   }
      116 |   await driver.sleep(1000);
      117 | }

      at Object.<anonymous>.tests.menu (commons.js:114:11)
      at Object.<anonymous>.tests.TC_AGRESSO_TI07 (commons.js:482:3)
      at Object.<anonymous> (TS_FPY.test.js:11:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        11.081s, estimated 53s
Ran all test suites.

## Expected behavior

The automation succeed in clicking the "sousmenu"  as well as the Chrome Selenium IDE extension does : 

14:20:53
Running 'login', called by 'TC_AGRESSO_TI07'
14:20:54
1.
open on /webplace/rhpi_ape.jsp?idurl= OK
14:20:54
2.
storeValue on css=input with value buttonName OK
14:20:54
3.
if on ${buttonName}==="Déconnexion" OK
14:20:55
5.
end OK
14:20:55
6.
setWindowSize on 1280x1024 OK
14:20:55
7.
click on id=usr OK
14:20:55
8.
type on id=usr with value UserToChange OK
14:20:55
9.
click on id=pwd OK
14:20:55
10.
type on id=pwd with value PasswordToChange OK
14:20:55
11.
click on css=div:nth-child(6) > input OK
14:20:55
Finished running 'login', returning to 'TC_AGRESSO_TI07'
14:20:56
2.
store on specifiques with value targetmenu OK
14:20:56
3.
**store on id=SPECIFIC_APE_SPE060CL with value sousmenu OK**
14:20:56
Running 'menu', called by 'TC_AGRESSO_TI07'
14:20:56
1.
click on id=menuAfficher OK
14:20:56
2.
pause on 2000 OK
14:20:57
3.
if on ${targetmenu}==="interfaces" OK
14:20:59
7.
elseIf on ${targetmenu}==="requete" OK
14:20:59
10.
elseIf on ${targetmenu}==="specifiques" OK
14:20:59
11.
click on id=b_SPECIFIC OK
14:20:59
12.
**click on ${sousmenu} OK**
14:20:59
13.
end OK
14:20:59
14.
pause on 1000 OK
14:21:00
Finished running 'menu', returning to 'TC_AGRESSO_TI07'
14:21:01
5.
executeScript on var mydate = new Date(); date_year = mydate.getFullYear().toString(); return date_year; with value date_year OK
14:21:01
6.
type on id=prm01 with value 01/01/${date_year} OK
14:21:01
7.
type on id=prm02 with value 31/12/${date_year} OK
14:21:01
8.
click on xpath=//input[@value='Soumettre'] OK
14:21:01
'TC_AGRESSO_TI07' completed successfully

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS:  Windows 10
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  3.17.0
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 
Browser:  Chrome
Browser Version: 90.0.4430.93 (Build officiel) (64 bits)

**Comment by toddtarsi** [comment]
I think this should be resolved in selenium IDE v4
