### ISSUE TITLE
failed to load SourceMap

### ISSUE THREAD

**Issue by createthis** [SeleniumHQ/selenium-ide#1237]
Using Selenium IDE 3.17.0 on chrome 90.0.4430.93 on mac osx Mojave, I'm seeing a lot of `failed to loadSourceMap` warnings on react apps I'm developing:
<img width="1322" alt="Screen Shot 2021-05-10 at 2 00 13 PM" src="https://user-images.githubusercontent.com/1695880/117703780-11666280-b198-11eb-919f-5e6406e6b9ce.png">

Disabling the Selenium IDE chrome extension and reloading the page makes the warnings go away.

**Comment by toddtarsi** [comment]
V4 is a standalone electron binary, so, uh, this is technically resolved
