### ISSUE TITLE
Can not use a variable containing a single quote

### ISSUE THREAD

**Issue by redescaflown** [SeleniumHQ/selenium-ide#1240]
## 🐛 Bug Report

I try to return a variable containing a single quote but I have a bug. Its because selenium-side-runner doesnt escape my single quote : I have this error : javascript error: Unexpected identifier'

If I realise the same test with a text without a single quote, all is Ok.

![escape](https://user-images.githubusercontent.com/17674866/119486898-0810f480-bd59-11eb-9fcb-5c5a2b4033bf.PNG)

Is there any way to force selenium-side-runner escaping this carachter ? 

I would like to precise that I am using selenium-side-runner command, not selenium IDE, it works fine in selenium IDE

**Comment by kogbill** [comment]
I have a basic approach to solve this here:
https://github.com/kogbill/selenium-ide/commit/b5065585fdf72ab4c4f9c2f43f5eab67b5607007

**Comment by toddtarsi** [comment]
This should have been resolved for a while. Tested in v4:
<img width="699" alt="Screen Shot 2022-11-13 at 7 31 59 PM" src="https://user-images.githubusercontent.com/4707505/201557224-9f302861-5631-4db7-ad67-bb502fdf0753.png">
