### ISSUE TITLE
Argument for time.sleep() in generated Python pytest output 1000x too large

### ISSUE THREAD

**Issue by adambhayes** [SeleniumHQ/selenium-ide#1241]
## 🐛 Bug Report

Selenium IDE generates wrong argument for time.sleep when generating Python output.  It uses the time from the IDE, which is in milliseconds, whereas Python time.sleep() uses seconds.  This makes the pause time 1000 times as large as intended.

Project file and python output are in the Project file section of this bug report.  Here are images of the project and the incorrect Python output.

![Screenshot from 2021-05-26 09-53-04](https://user-images.githubusercontent.com/82328878/119675221-d8222980-be0a-11eb-97fd-62f4356bb95b.png)

![Screenshot from 2021-05-26 10-13-17](https://user-images.githubusercontent.com/82328878/119675422-07d13180-be0b-11eb-83a0-ff7b55d7911f.png)

## To Reproduce

1. Rename the sleep-bug.txt file with this issue to sleep-bug.side.
2. Open the sleep-bug.side project file in Selenium-IDE.
3. Generate Python pytest code from it.
4. Check that in the .side file the pause time is 3000 (3 seconds), but in the Python code there is time.sleep(3000), which is 3000 seconds.

## Expected behavior

Expected time.sleep(3) in the generated Python code.

## Project file reproducing this issue 

This is the .SIDE project file (attached as .txt):

[sleep-bug.txt](https://github.com/SeleniumHQ/selenium-ide/files/6547265/sleep-bug.txt)

This is the Python output generated by Selenium-IDE.  Note that sleep(3000) is incorrect:

[test_gnu.txt](https://github.com/SeleniumHQ/selenium-ide/files/6547286/test_gnu.txt)

## Environment

OS: Ubuntu 20.04 LTS
Selenium IDE Version:  3.17.0
Selenium SIDE Runner Version:  
Browser: Firefox 
Browser Version: 88.0.1 (64-bit)

**Comment by toddtarsi** [comment]
@adambhayes - OOPS! Great catch. This was actually fixed around June, and should be deployed in latest. Thanks for reporting, and I'm going to close this.
