### ISSUE TITLE
Black Background

### ISSUE THREAD

**Issue by CharbelBs** [SeleniumHQ/selenium-ide#1248]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation
its very important for a lot of programmer to have a black screen because its help us to concentrate more and our eyes doest get tierd .
And another issur is why you dont have a right click ?

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by toddtarsi** [comment]
Dark mode is going to be part of v4. It isn't quite urgent enough for v3 unfortunately.

**Comment by toddtarsi** [comment]
Also, we do have right click handling for specific situations. However, we are using the extension `contextMenu` functionality on specific elements, and haven't overridden the base right click.

**Comment by CharbelBs** [comment]
Thx for your answers and your hard work !!

**Comment by toddtarsi** [comment]
Closing this as dark mode is supported in v4:

<img width="714" alt="Screen Shot 2022-11-13 at 7 28 33 PM" src="https://user-images.githubusercontent.com/4707505/201556930-6aff1402-40f0-4d56-b640-dc37ada9cc66.png">
