### ISSUE TITLE
How can I use the hot reloading feature work , I get always this window when I use yarn start.

### ISSUE THREAD

**Issue by droidy12527** [SeleniumHQ/selenium-ide#1249]
Can anyone help me out with this issue, I mean I am new to webpack and hot reloading features related it it.
It says that output is served and then I get this output, Can anyone help me and show me how the hot reloading works. Thanks in advance.
![image](https://user-images.githubusercontent.com/53708038/124716245-7bde1980-df21-11eb-82ba-d5c580b8062d.png)

**Comment by toddtarsi** [comment]
@droidy12527 - Are you writing a chrome extension? I think there is a boundary issue with HMR in Chrome extensions. I tend to run webpack in watch mode, and then still have to do the following whenever I want to load my changes:

1. Close Selenium IDE
2. Go to chrome://extensions, and click the refresh button on my extension
3. Re-open Selenium IDE

**Comment by droidy12527** [comment]
@toddtarsi Thank you so much , I will try it and get back.

**Comment by toddtarsi** [comment]
@droidy12527 - Closing this, but feel free to re-open if you still have an issue.
