### ISSUE TITLE
"yarn start" has error on browse, but "yarn build:ext" is fine.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#125]
I pulled the lastest of mast branch.
After this, `yarn start` is not working.
To be exact, yarn start is normal, but if I look at the log of browser, there is something left.
![image](https://user-images.githubusercontent.com/33743343/37379697-2107eda6-2778-11e8-8316-18f1e3266400.png)
And browser is loaded nothing.

But if I build for extension using `yarn build:ext` command, extension has no error and be loaded normally.
This phenomenon started at 8256cf9.
What should I do for using like before?

**Comment by corevo** [comment]
I broke it on purpose, since I'm working less and less on the UI, and more on core functionality, I figured the core functionality should be included directly in the build.  
The problem is that there is no mock for webextensions, perhaps I can dynamically import them wether its production or not.

**Comment by Jongkeun** [comment]
I feel like that is better if possible.

**Comment by corevo** [comment]
I pushed a fix for you fc27224c3e64b9edbede804be353604e6e9d6784

**Comment by Jongkeun** [comment]
Thanks!
