### ISSUE TITLE
Exporting Test Case with Pause command Fails

### ISSUE THREAD

**Issue by jwyza-pi** [SeleniumHQ/selenium-ide#1250]
## 🐛 Bug Report

Exporting a test that contains the `pause` command with no target fails saying it requires a target.  If you provide it a target it fails due to it saying `Cannot read property 'isOptional' of undefined` (probably because pause shouldn't have a target).

## To Reproduce

1. Create A test
2. Add a Pause command with a positive integer value (say 1000)
3. Right Click on Test and Hit Export
4. Hit Export (target language doesn't matter)

## Expected behavior

Export should succeed.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.
(Zipped .side)
[Pause Export Bug.zip](https://github.com/SeleniumHQ/selenium-ide/files/6791780/Pause.Export.Bug.zip)

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Browser: Chrome
Browser Version:  91.0.4472.114

**Comment by toddtarsi** [comment]
@jwyza-pi - Thanks for reporting!

@AutomatedTester @diemol - I actually wrote a fix for this issue a while back:

https://github.com/SeleniumHQ/selenium-ide/pull/1042/files

**Comment by toddtarsi** [comment]
@jwyza-pi - I'm closing this ticket. This issue should be resolved in latest. Thank you for reporting and feel free to re-open if issue re-occurs. Thanks!
