### ISSUE TITLE
Clarify DOC for `select`, `add selection`, `remove selection`

### ISSUE THREAD

**Issue by zhiburt** [SeleniumHQ/selenium-ide#1251]
## 🚀 Feature Proposal

While working on https://github.com/Plato-solutions/siderunner I notice that a command documentation is a bit unclear in regard of  `select`, `add selection`, `remove selection`
https://www.selenium.dev/selenium-ide/docs/en/api/commands#assert-element-present

![image](https://user-images.githubusercontent.com/20165848/125163082-0ded5880-e194-11eb-99a3-146edcdcd6bb.png)
![image](https://user-images.githubusercontent.com/20165848/125163101-2b222700-e194-11eb-8810-3594849ba05a.png)

So does `add/remove select` must support `(e.g., label=, value=, id=, index=)` targets as well as `select` or it just support value match?

## Motivation

Unclear description

## Example

**Comment by toddtarsi** [comment]
@zhiburt - Hm. I suspect the locator is for the select, and the value has to match an option's value.

Thanks for reporting! The commands are documented here:

https://github.com/SeleniumHQ/selenium-ide/blob/v3/packages/side-model/src/command/Commands.js

Any chance I could ask for your help in expanding the language here?

**Comment by zhiburt** [comment]
@toddtarsi thanks for the direction

As I see I was right that `add selection` uses optionLocator instead of value

This example is generated by Selenium IDE

```json
 {
      "id": "ea2c8a40-2058-4148-b2ff-ba167fccb239",
      "comment": "",
      "command": "addSelection",
      "target": "id=multi-select",
      "targets": [
        ["id=multi-select", "id"],
        ["css=#multi-select", "css:finder"]
      ],
      "value": "label=EPAM"
    },
```

**Comment by toddtarsi** [comment]
@zhiburt - I'm going to close this issue, since your rectifying commit is in our history. Thanks again for the help!
