### ISSUE TITLE
Ctrl+Shift+R doesn't working with "Run all tests"

### ISSUE THREAD

**Issue by jockrow** [SeleniumHQ/selenium-ide#1253]
## To Reproduce

When I press key combination "Ctrl+Shift+R" Selenium IDE can't execute command "Run all test", but another shortcuts yes working.

## Expected behavior

I expect to execute "Run all tests" command in Selenium IDE

## Project file reproducing this issue (highly encouraged)

[SampleSearchInGoogle.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/6823468/SampleSearchInGoogle.side.txt)

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Browser: Microsoft Edge
Browser Version: 91.0.864.67 (64-bit)

**Comment by toddtarsi** [comment]
Thanks for reporting. Will take a look later this week.

**Comment by toddtarsi** [comment]
This isn't really a priority in v4. We keep the suites as a separate tab. If this is an issue there, please feel free to re-open. Thanks!
