### ISSUE TITLE
Allow emitCommand to be available in the export-code API

### ISSUE THREAD

**Issue by brandon-piner-aruba** [SeleniumHQ/selenium-ide#1254]
## 🚀 Feature Proposal

It would be useful to have emitCommand available in the export-code API. This function should generate the command with given target / value for a selected language / test framework.

## Motivation

We wish to export commands on a per-command basis.

## Example

```
const command = emitCommand('python-pytest', {
      command: 'click',
      target: "//form[input/@name='email']",
      value: '',
    })
```
which makes `command` = `'self.driver.find_element(By.XPATH, "//form[input/@name=\\\'email\\\']").click()'`

**Comment by toddtarsi** [comment]
Thanks for making a PR and linking it back. Nice work!

**Comment by toddtarsi** [comment]
@brandon-piner-aruba - I'm going to close this issue since you resolved it and we merged it. Let me know if that's not cool, and I'll re-open. Thanks again!
