### ISSUE TITLE
How can I import a library in selenium IDE?

### ISSUE THREAD

**Issue by juanfons** [SeleniumHQ/selenium-ide#1266]
I have an external library called CSV reader, you can find it here:

https://github.com/abhijain2618/csvreader

How can I import this library directly in selenium IDE?

I need this to get data from a file and use it on a web app.
It could be txt or csv or any other type of format.

Thank you!

JM

**Comment by jawira** [comment]
Maybe you should write your own plugin https://www.selenium.dev/selenium-ide/docs/en/plugins/plugins-getting-started

**Comment by toddtarsi** [comment]
@jawira - Thanks for providing great guidance.

@juanfons - I'm going to close this issue. I believe a plugin is exactly what you're looking for. If you'd like more help instrumenting csvreader via a plugin, please reach out via Slack or IRC in the selenium-ide channel! Thanks for writing and sharing a great library!
