### ISSUE TITLE
In the test suite type, it is not possible to drag the positions of the included tests.

### ISSUE THREAD

**Issue by CesarSantosBR** [SeleniumHQ/selenium-ide#127]
In the test suite type, it is not possible to drag the positions of the included tests.

![image.png](https://images.zenhubusercontent.com/58d27b4c51aa2c3057792cd7/5daa325f-7c2c-4968-9c85-4599bd0fc191)

![image.png](https://images.zenhubusercontent.com/58d27b4c51aa2c3057792cd7/9444dad3-b53a-4e4e-94d6-1115f755a89c)

![image.png](https://images.zenhubusercontent.com/58d27b4c51aa2c3057792cd7/57d7e955-b8ac-4f4b-ace7-f77a9c9b2561)

**Comment by Jongkeun** [comment]
I was fixing from yesterday @CesarSantosBR .

**Comment by corevo** [comment]
Is there a specific reason you would like to do that?  
Because my idea was to add to each suite a setup and teardown steps (will look like test cases, but will always be at the beginning and the end respectively).

**Comment by jngale** [comment]
It would be handy to be able to set the order of tests. Having to number them is a bit of a pain.  Call me greedy, I want both 😀
