### ISSUE TITLE
Selenium IDE crashes without any obvious reason.

### ISSUE THREAD

**Issue by YecineM** [SeleniumHQ/selenium-ide#1271]
## 🐛 Bug Report

Selenium IDE crashes every once in a while.
The crash is unpredictable, spontaneous, sometimes I am not even running the extension (no Selenium IDE window is open) and chrome tells me that Selenium IDE extension has crashed (any Selenium IDE will show the sick face picture).

## To Reproduce

I have not run any test case, have not even opened Selenium, yet it crashes, every couple of days.
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS:  Windows 10
Selenium IDE Version:   3.17.0
Selenium SIDE Runner Version:  
Node version: 
Browser: Google Chrome
Browser Version: 93.0.4577.63 (official build) 64 bits.

**Comment by toddtarsi** [comment]
Thank you for reporting. That is very unfortunate. We've been getting a few different issues on the latest Windows. Currently we're investigating this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1249025

Hopefully the investigation of this issue will resolve whatever you're facing.

**Comment by YecineM** [comment]
Thank you for the kind reply.
I have to note that almost (or all?) crashes come with the SBOX_FATAL_MEMORY_EXCEEDED error code of chrome.

**Comment by toddtarsi** [comment]
@YecineM - Did this issue ever resolve for you?

**Comment by toddtarsi** [comment]
Closing this, haven't heard back in a year and we're moving off of the webextension runtime so, shouldn't be an issue anymore.

**Comment by YecineM** [comment]
Thank you @toddtarsi . I apologize for not answering. GitHub's notifications were arriving at my old messed-up email address. I missed your prior messages.
