### ISSUE TITLE
Make target input wider

### ISSUE THREAD

**Issue by mattmundell** [SeleniumHQ/selenium-ide#1275]
## 🚀 Feature Proposal

I am finding it fiddly to edit long command targets.  I think it would help if Target and its sibling fields would use all available space to the right.

## Motivation

Want to make it easier to edit targets.

## Example

![shot-selenium-arrow](https://user-images.githubusercontent.com/32057441/134867623-7aa54def-c95d-4814-9cbf-5eabcee5e733.png)

**Comment by toddtarsi** [comment]
Ah, that makes sense as an ask, and shouldn't be very hard to do. Thanks for requesting this and providing attached snapshot.

**Comment by MarvelCoder** [comment]
@toddtarsi Can I pick this up ?? I was able to find the component for this but just though if there's any documentation available to go through the code base? or should I post my questions on irc regarding my doubts ?

**Comment by toddtarsi** [comment]
@MarvelCoder - Absolutely 🤩! Reach out to me on Slack, I'd love to help. My name there is *surprise* toddtarsi.

https://www.selenium.dev/support/#ChatRoom

**Comment by toddtarsi** [comment]
@mattmundell - I believe this is how it works in v4, so I will close this for now. Feel free to re-open if you see an issue. Thanks!
