### ISSUE TITLE
Chrome Store link not working & no official release?

### ISSUE THREAD

**Issue by Liam-Deacon** [SeleniumHQ/selenium-ide#1283]
Clicking on the Chrome Extension link (to https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd) within the README or the Download Chrome Extension button on the Selenium IDE website at https://www.selenium.dev/selenium-ide/ returns a 404 not found page:

![image](https://user-images.githubusercontent.com/3184694/136778099-ca982a4d-bf5e-4d48-822c-d81c813011ea.png)
 
Note that there is a new extension (released today) within the Chrome store named **Web Recorder IDE** at https://chrome.google.com/webstore/detail/web-recorder-ide/cindigbjamfhkjflcdkbkmkoafojepdh, though this does not look like an official release: 
![image](https://user-images.githubusercontent.com/3184694/136778624-726763ec-ae6a-497e-ab22-db21a211c42a.png)

**Comment by capedavenger** [comment]
Both links now work for me. Possibly they were down in connection with the release of 3.17.1 yesterday.

**Comment by Liam-Deacon** [comment]
Thanks for the update @capedavenger. The links now work for me too - looks like it was a temporary failure. Closing down this issue.
