### ISSUE TITLE
Selenium version showing incorrect when loading IDE

### ISSUE THREAD

**Issue by PKhehra** [SeleniumHQ/selenium-ide#1286]
## 🐛 Bug Report

Selenium IDE version is showing incorrect upon loading IDE in Chrome. Version installed is 3.17.1 but IDE is showing 3.17.0.

## To Reproduce

Have current version of IDE installed (3.17.1) 

Observe version number by clicking extensions  > Selenium IDE > More actions > Manage extensions

Load Selenium IDE addon via Chrome

Observe version number 

## Expected behaviour

Expect version number to be displayed as 3.17.1 as is displayed under manage extensions

## Actual behaviour

Version number shown is 3.17.0

## Environment

OS:  Windows 10 Pro OS 19043.1237 
Selenium IDE Version:   Expected 3.17.1 showing 3.17.0 

Node version:  14.17.6

Browser: Google Chrome
Browser Version:  Version 94.0.4606.81 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/90681697/137132611-c0db2fd0-efd1-4f87-8f06-c5e6885d8939.png)

![image](https://user-images.githubusercontent.com/90681697/137132548-94743ba9-d66d-4ae4-a7dc-02a7cd4391e8.png)

**Comment by toddtarsi** [comment]
@PKhehra - Sorry about that, we actually deployed ahead of merging the PR because the goal was to curtail an outage. The only reason we incremented was to avoid version conflicts with the version that was pulled in the Chrome store. This will be fixed for the next deploy. Thank you for reporting!

**Comment by toddtarsi** [comment]
@PKhehra - This should be resolved on latest. Thanks for the shrewd eye and the great report!
