### ISSUE TITLE
Huge regression in code execution speed

### ISSUE THREAD

**Issue by ch-ris** [SeleniumHQ/selenium-ide#1287]
## 💥 Regression Report

Regression in code execution speed (about 10x slower) right after automatic update of extension to version 3.17.1
Removing the extension and installing unpacked version 3.17.0 from github worked to bring the original speed back.

Every command takes ages, even a simple if/else/end. Especially END commands should be almost instant.
It feels similar to decreasing "test execution speed" manually, but with no option to go fast as usual.

Maybe this is (or isn't) relevant:
Regarding to UI there is notable visible change of added checkboxes for every line executed.
Also when using WHILE cycle, lines already visited were green in past. New version seems to not to keep them green anymore.

## Last working version

Worked up to version: 3.17.0

## To Reproduce

Just run the project with stop watch on previous version and compare to updated version

## Expected behavior

The similar (or better) code execution speed as with previous versions of IDE

## Project file reproducing this issue

So far internal test project with site not available in public containing ~260 lines.
I'll try to reproduce with a simple project as well. 
To be clear I haven't used any setSpeed commands to slow things down.
I also tried adding setSpeed 0 in the beginning of project, but no improvement as well.

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.1
HW: Intel® Core™ i7, 12GB RAM, SSD drive, system is almost idle

Browser:
Browser Version: 94.0.4606.81 (64-bit) (Official latest Build)

**Comment by toddtarsi** [comment]
@ch-ris - Thanks for reporting, and sorry about the delays. I'm very surprised to hear this. We did not change much over the last patch:

https://github.com/SeleniumHQ/selenium-ide/commits/v3/packages/selenium-ide

As you can see, there have been 11 commits, 1 to increment, 1 to drop unused permissions for store compliance, and nine that were pretty much just focused on accessibility changes, tweaking css and adding accessibility props.

I'll take a look later on and try and do what I can to help.

**Comment by toddtarsi** [comment]
@ch-ris - Well dang, it looks like you're right. I ran the seed project on the last version, and it timed at ~2 minutes even. Next, I ran the seed project on this version, and it timed at ~2.5 minutes even. With all the tests we do on waits timing out, this delta is getting kinda rinsed as is, so yeah, 10x on some things may be correct.

Tonight, I'll set up the watcher, and run the tests in a bisect pattern. With only 11 commits, we should have a smoking gun pretty quickly.

**Comment by toddtarsi** [comment]
Notes from testing:

All versions were built using the `yarn build:dev` command.
One pass, stopwatch manually used. Expectation is performance loss will be bad enough to be traceable to one commit and difference in start timing will be negligible.

Benchmarks:

3.17.0 - 1:59.72
41f31a1369e54d7a5323cea207ec2d1970fd3f28 - 2:09.28
ce9d28fcd11e3cc7b63711d8b078de025ca99648 - 1:58.64
latest - 2:04:88

@ch-ris - What I'm finding with my tests more than anything is that execution speed can be highly variable, and nothing I'm seeing from the general test suite we have for this case is really leading me one way or another. Would you be able to supply like a really simple side file to really exacerbate your regression? After further testing today, I'm not quite seeing enough to really troubleshoot a marked regression on my side anymore, and anything you give me, I can add into that test file so we have somewhere to go for future regressions.

**Comment by toddtarsi** [comment]
@ch-ris - Just wanted to check back in here. Would you have an example side file that demonstrates this regression consistently? If so, I can try using it as my basis for investigation. As it is now, the general benchmark is inconclusive.

**Comment by toddtarsi** [comment]
@ch-ris - If you can provide a side file that demonstrates this regression in a consistent way, I will use it to profile the front end and resolve anything here. However, my current belief is that the tests run against a remote site, and that the internet is inherently inconsistent, which leads to things appearing to regress or seeming faster, where really those changes are likely minimal. If I don't hear back from you in two weeks, I'll close this issue. If you want to continue working with me here, you can reply at any time after and we can re-open this.

Thanks for taking the time to report this and explain what you're seeing, but I will need a benchmark to consider this more significant than test-gen regressions, break-fix from new versions, and working towards v4.

**Comment by toddtarsi** [comment]
@ch-ris - I'm closing this issue. Please feel free to re-open if you have a reproduction script. Thanks again.
