### ISSUE TITLE
System.ArgumentException: 'elementDictionary Parameter name: The specified dictionary does not contain an element reference'

### ISSUE THREAD

**Issue by Shafras-Munas-Intrepid** [SeleniumHQ/selenium-ide#1289]
## 💬 Hi I am trying to run Selenium in C# via the console application in VS 2019 Community edition. I am getting an exception as "System.ArgumentException: 'elementDictionary
Parameter name: The specified dictionary does not contain an element reference'"

### Below is the code
class Program
{
        static void Main(string[] args)
        {
            IWebDriver driver = new ChromeDriver();

            driver.Navigate().GoToUrl("http://www.google.com");

            IWebElement element = driver.FindElement(By.Name("q"));
            
            element.SendKeys("Executeautomation");

            driver.Close();
        }
}
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
Hi @ShafrasMunas - This is an issue for the selenium github, not the selenium-ide github. We are simply focused on a front end ide.

If you raise an issue here, I believe you'll find the help you need: https://github.com/SeleniumHQ/selenium/issues

For now, I'm closing this issue.
