### ISSUE TITLE
EACCES error running a test suite

### ISSUE THREAD

**Issue by i5513** [SeleniumHQ/selenium-ide#1290]
Hello,

Sometimes a test suite that contains 5 tests, open only randomly 1 / 2 ... 5 chrome windows

I think the patch found in  https://github.com/SeleniumHQ/selenium/issues/7097 should be applied here

selenium-side-runner.cmd -c "browserName=chrome goog:chromeOptions.args=[ignore-certificate-errors]" -f "Informe" --timeout 300000 --output-directory "C:\Temp\seleniumOut" "C:\Temp\seleniumIDE\Test.side"
info:    Running C:/Temp/seleniumIDE/Test.side
 FAIL  Informes/TestA.test.js
  ? Test suite failed to run

    listen EACCES: permission denied 0.0.0.0:50228

Thanks !

**Comment by toddtarsi** [comment]
@i5513 - So, this issue sounds kinda vague. To recap, you'd like us to update our version of selenium-webdriver to latest in this repo?

**Comment by i5513** [comment]
> @i5513 - So, this issue sounds kinda vague. To recap, you'd like us to update our version of selenium-webdriver to latest in this repo?
@toddtarsi  thank you for replying

Not sure, but it really affects to selenium-side-runner executions, so it should be fixed, it is not important for me how do it. 

Would be nice to have the solution at upstream level

Regards

**Comment by toddtarsi** [comment]
@i5513 - I'll make a small PR to bring it up to latest, and I think that should resolve your issues.

**Comment by toddtarsi** [comment]
@i5513 - I don't say this often, but I should when it is merited. Nice job making an in-depth issue here, so I can follow the thread on what you're encountering.

**Comment by toddtarsi** [comment]
I updated selenium webdriver, but it comes up a major version and the tests are like instantly dumping, so I'll have to look into this. This may be more tricky than I was hoping.

**Comment by toddtarsi** [comment]
Okay, I think I only need to increment the side-runner. I think that was my issue. The PR is linked to this. If it passes, I'll ask for a review early next week. I'd like to get caught up on PRs anyway.

**Comment by toddtarsi** [comment]
@i5513 - So, there is a problem with incrementing selenium-webdriver to latest. Namely, the actions shape changes pretty significantly to be w3c compliant. As a result, this will have to move slow by nature. With a big breaking api change, the side-runner will probably have to come up a major version, and before we do that, I need to bug squash for a while so people stuck on the current version aren't in too much pain.

**Comment by toddtarsi** [comment]
@i5513 - v4 of the side runner is in alpha and available on npm. Please test and let me know if it resolves your issue. For now, I'm going to close this, but feel free to re-open if it persists. Thanks!
