### ISSUE TITLE
Exports with run commands only exports first sub methods

### ISSUE THREAD

**Issue by picunder** [SeleniumHQ/selenium-ide#1291]
## 🐛 Bug Report

When a Test Case has more than one use of the "run" command, the exportation of the code only includes the first sub tests, ommiting the ones from the second and beyond sub tests.

## To Reproduce

Create two Test Cases (TC01.1 and TC01.2) with any command on them ("echo" command for example). Then create another test case (TC01) and call them by using the "run" command. They should be as follow:   
run   |   TC01.1
run   |   TC01.2

Execute the last Test Case (TC01). Observe that in the Selenium IDE they run correctly showing the echo texts in the log window.

No export the last Test Case (TC01) to any languaje (Python for example). Mark the first two options and then save the exported file.

Edit the exported file and look the content.

## Expected behavior

The code should contain the principal module of the main Test Case:   
    *def` test_tC01(self):    
    # Test name: TC01   
    # Step # | name | target | value
    # 1 | run | TC01.1 |    
    self.TC011()   
    # 2 | run | TC01.2 |    
    self.TC012()*   
 

And also the definitions of each sub test Case

 *def tC011(self):
    print("Running Test Case 01. Sub Test 01")*

and 
   *def tC012(self):
    print("Running Test Case 01. Sub Test 02")*

## Observed Behaviour

The second method and any other method beyond the first "run" command are missing. The following lines are NOT included in the exportation 
   *def tC012(self):
    print("Running Test Case 01. Sub Test 02")*

## Project file reproducing this issue (highly encouraged)

Side file with an example of the issue   
[Run Command Bug Report.zip](https://github.com/SeleniumHQ/selenium-ide/files/7489190/Run.Command.Bug.Report.zip)

Python file with the exportation showing the issue
[test_tC01.zip](https://github.com/SeleniumHQ/selenium-ide/files/7489192/test_tC01.zip)

## Environment

OS: Ubuntu 18.04 
Selenium IDE Version:  v3.17.0 
Selenium SIDE Runner Version:  Unknown. Latest? 
Node version: 
Browser: Chrome
Browser Version: 95.0.4638.69 (Official Build) (64-bit)

**Comment by toddtarsi** [comment]
@picunder - Holy cow! Great find, and so sorry about that. I'm going to make sure this becomes a test in our core seed. Thanks for pointing this one out!!

**Comment by toddtarsi** [comment]
@picunder - Also, this affects all code export languages, so wowie zowie!

**Comment by picunder** [comment]
@toddtarsi . Happy to contribute! that is what testers do..hahaha!

 I have mixed feelings... Happy that I found something that helps make Selenium a better product, but sad that it is a real bug and not some bad configuration to quicky go on with my testings..

Greetings from Argentina!

**Comment by toddtarsi** [comment]
@picunder - I laugh so that I so not cry. The fact that this hasn't been addressed before shows how much better a job I need to do highlighting how totally awesome the run command is. The nice thing is that we have test coverage running right up to this (1 run command, but not 2+), so covering the fix will be really easy.

https://github.com/SeleniumHQ/selenium-ide/blob/v3/packages/side-utils/__test__/test-files/test-case-reuse.side

I'm going to try and have it this week. This is definitely my highest priority fix.

**Comment by picunder** [comment]
Nice to know about that priority ! It will be very welcome here!!

**Comment by toddtarsi** [comment]
@picunder - Okay, I made a PR to resolve this this morning. I'll ask the team about merging some of these PRs and maybe doing a release in the next week or two. Thanks again for reporting this!

Also, I made sure to add multiple reused methods to the core test case.

**Comment by NikkTod** [comment]
@picunder, @toddtarsi great work guys, this fix is really needed. 

In some other bugs it was mentioned in the comments and that is way it was missed unfortunately. 

@toddtarsi Do you happen to know when would be the new realease, I need this fix a lot. :)

**Comment by picunder** [comment]
Thanks @toddtarsi !!!

Also I noticed that exportations to python of global variables used in asserts, seem not to be working properly. This looks like the only way to pass arguments to a sub method and allow code reuse, isn´t it? . I will try to make an example of the issue and report it for your evaluation.

Thanks a lot!

**Comment by toddtarsi** [comment]
@NikkTod @picunder - That is a good question. I don't have that access yet, so I'll ask the team. This is probably a good place to release at. The next change set I'm working on is bringing webdriver up to 4.x everywhere, which means I'll probably  be bringing up the selenium-side-runner a major version before the next release. So, probably good to have a clean slice before that.

**Comment by toddtarsi** [comment]
@picunder - Absolutely, if you can get me a small example of what you're seeing in the python code export, I should be able to go after it np.

**Comment by toddtarsi** [comment]
@picunder @NikkTod - I took some time to look around a bit and try some issues. I want to do one more thing this weekend, and then I'm going to push for an increment and release of selenium-ide and side-utils.

**Comment by toddtarsi** [comment]
So, I expect to try and put out a new version before Thanksgiving. I hope this is acceptable for you both.

**Comment by toddtarsi** [comment]
Just for the record, the one more thing is this issue, which @zot has really been helping me understand.

https://github.com/SeleniumHQ/selenium-ide/pull/1297

I feel like fixing nested quotes breaking in the various languages is worth getting into the same batch.

**Comment by NikkTod** [comment]
@toddtarsi before Thanksgiving sounds great, thank you very very much for your support.

And if you can include the nested quotes issue, you will be champion!

**Comment by toddtarsi** [comment]
@NikkTod @picunder - Sorry to report, I'm one week behind on this deployment, but I'm working on the last thing to go out a bit this weekend for some test-generation stuff, so I'll begin rumblings about putting out a release next week.

I just want to keep you two in the loop. Thanks again for thorough bug reporting and being awesome.

**Comment by NikkTod** [comment]
Hi @toddtarsi, really great work, I saw that the pull request for a new release version was approved.

When would the new release 3.17.2 be availble to download from the chrome store :) 

The latest release shown within Github is 3.17.0

**Comment by toddtarsi** [comment]
@NikkTod - Wow, you are looking around! I'm going to check about doing it today. I gained some new access, so I'll see if maybe I can do the github release on my own now.

**Comment by toddtarsi** [comment]
@NikkTod - Cool, I do have Github release access!

**Comment by NikkTod** [comment]
@toddtarsi - you saved us! Very happy that at least someone is taking care of this helpful tool.

Just as an info, I have downloaded the new version and tested this issue, all is good I was able to export (C#) more than one run command.

Keep it going :)

**Comment by toddtarsi** [comment]
@NikkTod - I'm really glad to hear that. Thanks for all of your help with this issue (@picunder too, that test was invaluable). You both have a lovely weekend!

I'm going to try and sync up with someone whose put more blood into this code than I can imagine tomorrow-ish and try to get the new version rolled out by the other mechanisms as well. There are a lot of good devs around this codebase, even if they are taking some personal space. I'm lucky that they're giving me a chance to be part of this 😄
