### ISSUE TITLE
Issue with event source not always setting top property

### ISSUE THREAD

**Issue by atkulp** [SeleniumHQ/selenium-ide#1293]
My team's been confused about errors showing in developer tools in Edge (Chromium):
![image](https://user-images.githubusercontent.com/3195410/141012626-34e95552-71d0-4fd8-a4b8-8427d689a6f0.png)

I finally tracked it down to the Selenium IDE plugin in [prompt-injector.js, line 52](https://github.com/SeleniumHQ/selenium-ide/blob/e6d2041b63de19c19d022ec90d60c000532b8d67/packages/side-recorder/src/content/prompt-injector.js#L52):
```
if (
  event.source.top == window &&
  event.data &&
  event.data.direction == 'from-page-script'
)
```

The issue is that if a message/event is received with `source` equal to `null`, the `event.source.top` reference blows up.  Since it's in an event handler, it doesn't seem to affect anything much, but it would be great to get that message out of the console, plus it's likely missing something sometimes.  I created [a tiny PR](https://github.com/SeleniumHQ/selenium-ide/pull/1292) to address the issue.

**Comment by toddtarsi** [comment]
@atkulp - Thanks for reporting, and even moreso, thanks for adding a guard clause there! I'll try and push it through as fast as I can.

**Comment by toddtarsi** [comment]
@atkulp - Just letting you know, I'd like to try and put out a new version next week with your fixes in. Thanks again!

**Comment by toddtarsi** [comment]
@atkulp - Sorry to report, I'm one week behind on this deployment, but I'm working on the last thing to go out a bit this weekend for some test-generation stuff, so I'll begin rumblings about putting out a release next week.

**Comment by toddtarsi** [comment]
@atkulp - I believe this is all deployed out now! If you feel this isn't the case, feel free to re-open. Thanks again for the great analysis and fix PR! 👍
