### ISSUE TITLE
"Required" test flag

### ISSUE THREAD

**Issue by AlexeyOplachko** [SeleniumHQ/selenium-ide#1294]
## 🚀 Feature Proposal

A flag of some sorts that marks that test is required to succeed in a test suite

## Motivation

Save processing time if a crucial test fails.

## Example

I.E. First step of test suite is to log into the tested app. If it fails, there's no reason to even try rest of the steps because they'll just fail.
So instead of wasting resources running all tests that'll fail anyways, it would just fail "required" test and stop executing rest of the suite.

**Comment by toddtarsi** [comment]
@AlexeyOplachko - How are you running your tests? Do you run your tests directly in the IDE or do you export to a test-runner compatible language? I believe all of the test runners have fail fast settings built in.

**Comment by AlexeyOplachko** [comment]
Currently I'm running them manually directly in the IDE and on CI using selenium-side-runner

**Comment by toddtarsi** [comment]
@AlexeyOplachko - And you are able to use fail-fast flags in the side runner?

**Comment by toddtarsi** [comment]
@AlexeyOplachko - I feel this is not as much of an issue in the IDE, since the IDE is currently best used for iteration / test building. The playback can naturally be funkier because it's using simulated JS, and so shouldn't be the end-all-be-all for the suite running (yet, v4 aims to resolve these issues and align us in a way where we could use selenium-bidi going forward).

**Comment by toddtarsi** [comment]
@AlexeyOplachko - Please reach out here in the next two weeks. If I don't hear back from you, I'll mark this issue as resolved and I won't feel good about it. If we can find a way of ensuring your use-case is met without doing a lot of changes (maybe the side-runner needs better mechanisms for passing through flags to jest, etc), I'd like that even more.

**Comment by toddtarsi** [comment]
@AlexeyOplachko - I'm closing this issue. Please feel free to re-open if your workflow is heavily inhibited. Thanks!
