### ISSUE TITLE
CSS selectors for side test file

### ISSUE THREAD

**Issue by kvippwiz** [SeleniumHQ/selenium-ide#130]
Export javascript code should recognize css selectors like 
:nth-child(x) and [target=_blank]

https://www.w3schools.com/cssref/css_selectors.asp

**Comment by kvippwiz** [comment]
Attach the error log as below.

Running 'SampleRun1'
15.Trying to find css=span.login:nth-child(3)... Failed:
Element css=span.login:nth-child(3) not found
'SampleRun1' completed with 2 error(s)

**Comment by corevo** [comment]
First of all it appears your issue has nothing to do with code export, is it in playback only?  
Secondly, I was not able to reproduce your failure:  
Trying to execute click on css=#c > *:nth-child(3)... Success  
Trying to execute click on css=*[target=_blank]... Success
Are you sure your selector is correct?
