### ISSUE TITLE
Change docs in selenium-side-runner from chromeOptions to goog:chromeOptions

### ISSUE THREAD

**Issue by toddtarsi** [SeleniumHQ/selenium-ide#1301]
As noticed by Turbo.

**Comment by FransUrbo** [comment]
I'm a bit dissapointed that this STILL isn't fixed, considering it's such an easy one!

URL to the discussion: https://app.slack.com/client/T0ABCRTNX/C0ABCS03F

PS, yes, "Turbo" is me..

**Comment by toddtarsi** [comment]
@FransUrbo - I'm sorry, I left it open because I thought it might encourage someone on the fence about contributing to join and do an easy pickup like this 😭

I can do this

**Comment by harsha509** [comment]
Closing as resolved!
