### ISSUE TITLE
Build chrome extension (as for release .zip) locally and test in chrome

### ISSUE THREAD

**Issue by dodger82** [SeleniumHQ/selenium-ide#1303]
## 💬 Questions and Help
Hello,

I want to test an own script export.

Somehow I need to create a release zip with my export package?! Couldn't find any information how to build the chrome extension with a new package.

Thanks in advance!

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
@dodger82 - Can you explain a bit more what you're looking for? I think I could help you more if I understood a bit better.

**Comment by dodger82** [comment]
@toddtarsi sure! Thanks!

I have a special script format i need to export for. The existing export formats like python pytest is not what i need.

What is necessary to build the chrome extension locally?

- I need to test locally -> somehow i need to load the extension with my own export.

Or is there another approach? plugins?

Tried to figure it out with yarn and so, but, to be honest. I'm not used to yarn and I dont understand the seleniumIDE repo structure. In some branches the packages directory is existing in trunk not, but there is v3 and ....

Thanks for your help!

**Comment by toddtarsi** [comment]
@dodger82 - For that, no need to use the extension at all friend 😄

Simply use the npm module `@seleniumhq/side-utils`

It has a module called codeExport.

For your custom format, make sure it has module.exports similar to how all of the other code-export packages do their module.exports.

Then, you can just use a small Node.js script to transpile your side project into test files. This is what mine looks like:

https://gist.github.com/toddtarsi/00307857cbfe38c4c4ab86559f8aca37

**Comment by toddtarsi** [comment]
@dodger82 - This is to help get started, but side-utils lets you export at whatever level of granularity you need. There is project export, suite export, test export, command export.

**Comment by dodger82** [comment]
@toddtarsi 

Great! Thanks for your help! I try to dig into as soon as possible! There's a lot of new stuff included - for me it's new.

I will give feedback, how I solved my "problem". =)

**Comment by toddtarsi** [comment]
@dodger82 - I'm going to close this as an issue for now, but if you have any more questions or anything, feel free to join our slack:

https://www.selenium.dev/support/

There is a specific channel, selenium_ide, that I like to keep a close eye on.
