### ISSUE TITLE
Selenium IDE Firefox extension is not available in addons.mozilla.org

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1309]
## 🐛 Bug Report

Selenium IDE Firefox extension is not available in addons.mozilla.org

## To Reproduce
Open link: [Firefox extension](https://addons.mozilla.org/en-GB/firefox/addon/selenium-ide/)

## Expected behavior
I expected the Selenium IDE Web extension page, but a "Oops! We can’t find that page" error is shown.

## Environment
Browser: Firefox 96

**Comment by toddtarsi** [comment]
Yeah, we've been talking with them about getting back online for the last two days. Despite serving us as an extension for many years, some reviewer decided that we weren't up to snuff and is making things as difficult as possible. Guess they're a fan of cypress or something.

**Comment by jtagcat** [comment]
adding a keyword for anyone searching: AMO

**Comment by allen-munsch** [comment]
~~Is there a way to install the extension from zip, or manually? I'm not sure where the documentation would be to look for that?~~

oh wait, found it.

- https://github.com/SeleniumHQ/selenium-ide/releases/download/v3.17.2/selenium-ide.zip 
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

**Comment by toddtarsi** [comment]
@allen-munsch - Yes, the readme here should walk you through this:

https://github.com/SeleniumHQ/selenium-ide/tree/v3

Sorry this is taking a while, I will take a look at making some more documentation/hand-holding changes to try again with Firefox tonight.

**Comment by toddtarsi** [comment]
Oh awesome, yeah that will be even easier. @allen-munsch - Thanks for taking an informed look around.

**Comment by allen-munsch** [comment]
@toddtarsi I was able to find and get it installed. No worries. Thanks so much. 

![2022-01-13_11-45](https://user-images.githubusercontent.com/33908344/149381955-792e56e0-04f7-416b-b586-199d35990213.png)

**Comment by oldwizard1010** [comment]
manifest.json file for firefox, if you want to install it NOT temporarily from available .zip
not perfect probably, but it works without "is corrupt" message
Don't forget to disable xpinstall.signatures.required flag in about:config

`{
  "description": "Selenium Record and Playback tool for ease of getting acquainted with Selenium WebDriver.",
  "manifest_version": 2,
  "name": "Selenium IDE",
  "version": "3.17.2",
  "homepage_url": "https://github.com/SeleniumHQ/selenium-ide",
  "icons": {
    "16": "icons/icon16.png",
    "32": "icons/icon32.png",
    "64": "icons/icon64.png",
    "128": "icons/icon128.png"
  },
  "browser_action": {
    "default_icon": {
      "16": "icons/icon_menu16.png",
      "32": "icons/icon_menu32.png",
      "64": "icons/icon_menu64.png"
    },
    "default_title": "Selenium IDE"
  },
  "permissions": [
    "tabs",
    "activeTab",
    "contextMenus",
    "downloads",
    "webNavigation",
    "storage",
    "<all_urls>"
  ],
  "web_accessible_resources": [
    "icons/icon128.png",
    "icons/icon_light128.png",
    "assets/prompt.js",
    "assets/indicator.js",
    "assets/highlight.css",
    "bootstrap.html",
    "indicator.html"
  ],
  "content_security_policy": "script-src 'self' 'sha256-W7QWmGne6B9hjKtOqoGmUFOPgpFcUo4Nr/yyMqtgXcU=' 'sha256-g0sGx5oQNWQA7+VAX6oocWOlrBzbLK0jggpU/mFFNHE=' 'unsafe-eval'; object-src 'self'",
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "assets/vendor/global.js",
        "assets/vendor/selenium-browserdetect.js",
        "assets/atoms.js",
        "assets/polyfills.js",
        "assets/escape.js",
        "assets/playback.js",
        "assets/record.js"
      ],
      "match_about_blank": true,
      "all_frames": true
    }
  ],
  "background": {
    "scripts": [
      "assets/background.js"
    ]
  },
  "applications": {
    "gecko": {
      "id": "seleniummod@example.com"
    }
}
}
`

**Comment by MoralCode** [comment]
I was able to work around the missing addon page without compiling from source by grabbing a copy of the .xpi file from archive.org and installing it manually:
 https://web.archive.org/web/20210111093554/https://addons.cdn.mozilla.net/user-media/addons/2079/selenium_ide-3.17.0-fx.xpi?filehash=sha256%3Ab7dd928cdce0a489d7040cc8653633169d28ccc0f27f0fd2ffa783fc6c775889

**Comment by schwabeltier** [comment]
Any News on the missing place in ff?

**Comment by toddtarsi** [comment]
Yeah sure, I'll give an update here.

The first time I submitted, it got rejected because the reviewer was unable to decipher all three steps of our build commands in the getting started docs and missed `peru sync`. So I wrote a build.sh to help them with their difficulties. That was six days ago, and we've been Awaiting Review ever since. My suspicion is that I was less than kind in my handling of this takedown, and so they've decided to shelve the review indefinitely. All and all, it is more fuel to get 4.x out, which will use Electron for its browser system, and then I never have to release anything to the dumpster fire that is the mozilla extension store again.

EDIT: This is a less than professional update, but I'm going to leave it, because not using any four letter words here is about as good as I can do on the topic.

**Comment by toddtarsi** [comment]
Additional update here:

We're 11 days into a submission to the FF web store and still 'Awaiting Review'. I think we've officially reached the 7th circle of developer Hell.

**Comment by timcu** [comment]
Looks like it is available again at addons.mozilla.org :)

**Comment by toddtarsi** [comment]
@timcu - Yeah, we're back as of a few hours ago. I guess I'm closing this issue now. Thanks for your patience everyone.
