### ISSUE TITLE
Can not install on firefox

### ISSUE THREAD

**Issue by dogfootman** [SeleniumHQ/selenium-ide#1321]
I cannot find at firefox add-on at
"https://addons.mozilla.org/en-GB/firefox/addon/selenium-ide/"

i clicked "FIREFOX DOWNLOAD" button on your site
"https://www.selenium.dev/selenium-ide/"

how can i get the add-on on firefox?
(I installed on chrome)

**Comment by toddtarsi** [comment]
https://github.com/SeleniumHQ/selenium-ide/issues/1309

23 days now, welcome to my Hell
