### ISSUE TITLE
There is no more "Execute this command" item in the context menu

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#1326]
## 💥 Regression Report

There is no more "Execute this command" item in the context menu

## To Reproduce

Right-click on a command in a scenario, there used to be an "Execute this comand" item in older Selenium IDE versions, now this item is not present in the context menu.

At the same time the keyboard shortcat "X" works well, it executes the selected command.

## Environment

OS: Windows 10
Selenium IDE Version: 3.17.4
Browser: Firefox
Browser Version: 97

**Comment by toddtarsi** [comment]
@barancev - Thank you for reporting. This isn't a full blocker, so Selenium IDE v4 is still our driving priority. We're trying to hit beta around April, and then triaging and improving the nuances of UX will become a priority again, albeit with the new version as the primary focal point.

**Comment by toddtarsi** [comment]
I'm going to close this, as it is in v4:

<img width="365" alt="Screen Shot 2022-11-10 at 9 23 13 PM" src="https://user-images.githubusercontent.com/4707505/201256158-72de2bd0-40a5-4b8e-82b6-b9bfd6ec1767.png">
