### ISSUE TITLE
Order of mouseup, mousedown and click events

### ISSUE THREAD

**Issue by generalov** [SeleniumHQ/selenium-ide#133]
Thank you so much for the great tool!

It seems that the "clickAt" command emits mouse events in unusual order: 
event: click
event: mousedown
event: mouseup

I tested manually https://codepen.io/egeneralov/pen/XERmRN on MS Edge, FireFox, Chrome, and Safari and the order is:
event: mousedown
event: focus
event: mouseup
event: click

Is the unusual order expected?  

If I'm not mistaken the events order is implemented in https://github.com/SeleniumHQ/selenium-ide/blob/91c9275a2d68b035cf17c5f99efd720852d299aa/packages/selenium-ide/src/content/selenium-api.js#L662-L685

**Comment by corevo** [comment]
I am uncertain as to why the event ordering is different than the browser.  
I tested using [`monitorEvents`](https://developers.google.com/web/tools/chrome-devtools/console/events) and got similar results, I'm afraid this change will introduce unwanted side effects, I'll have to test with it for a bit.

**Comment by generalov** [comment]
We have functionality that adds query parameters to `href` attribute on `mousedown` event. The functionality also handles keyboard and touch events in the similar way. It expects that `click` event (that leads to href navigation) occurs strictly after the `mousedown`, `keydown` and ` touchstart`.

It'll sufficient if mouse events will be emulated correctly.
Ideally `clickAt` command should trigger events regarding to current input device emulation mode: mouse, keyboard, touch and so on. Probably it's a feature request.

**Comment by corevo** [comment]
fixed in 1ae5dd4cb4d97b221bb568d9f13a60a930363d23
