### ISSUE TITLE
Make it quicker to play when recording

### ISSUE THREAD

**Issue by mattmundell** [SeleniumHQ/selenium-ide#1331]
## 🚀 Feature Proposal

Reduce UI overhead of switching from recording to playing:
 - enable the play button in the top bar when recording is active
 - remove the confirmation dialog from the "Play From Here" menu item.

## Motivation

When I'm creating and editing tests I am constantly switching between recording and playing.  These two items get in the way.  For instance I reach for the play button almost every time, and then have to break my flow slightly to remember why it is greyed out.

## Example

1 Click the Record icon
2 Do some things on the page
3 Click Record again to stop it                                              **<= remove this step**
4 Click Play which is now enabled

1 Click the Record icon
2 Do some things on the page
3 Right click on a command in the Selenium window
4 Click Play From Here
5 Click Playback in the Stop Recording dialog                        **<= remove this step**

Play button would be on all the time and would simply stop the recording.
Play From Here menu item would do the same, without asking for confirmation.

**Comment by toddtarsi** [comment]
@mattmundell - This is a great suggestion. We're actually right in the midst of doing the v4 work, but something like this should really not be bad to include as part of that. I'll add this issue to the v4-beta milestone so we keep it in mind 😄

**Comment by Rowdster** [comment]
This seems to be done, at least in my experience, playback via electron in v4 is now the fastest playback I can get, at least on par with side-runner.

**Comment by toddtarsi** [comment]
This is in v4
