### ISSUE TITLE
[feature request] Locator builders

### ISSUE THREAD

**Issue by Enrico9009** [SeleniumHQ/selenium-ide#134]
In the older version of Selenium IDE, we had the possibility to add locators in Options-->Options-->Locator Builders through a .js extension file.

Is this features planned for the new Selenium IDE ?

Thank you.

**Comment by jeremybramwell** [comment]
I think this is a duplicate of #104

**Comment by corevo** [comment]
Indeed, closing at it is a duplicate of #104
