### ISSUE TITLE
Feature Request: Save project with Ctrl + S

### ISSUE THREAD

**Issue by hanumanbandhu** [SeleniumHQ/selenium-ide#135]
When we hit Ctrl+s to save the script its saving as html file instead of .side file .

**Comment by corevo** [comment]
I'll have to clear this issue a bit.  
When hitting Ctrl + S, you're not saving at all, you are downloading the page as html, same thing as if you were to hit Ctrl + S right here.  
I'll rename this to a feature request and work on it.
