### ISSUE TITLE
Chrome Selenium IDE extension does not fire Save button event in Salesforce Lead creation, Firefox works correctly

### ISSUE THREAD

**Issue by blapsley** [SeleniumHQ/selenium-ide#1358]
## 🐛 Bug Report

When using the Chrome Selenium IDE extension to run a test playback, the test passes successfully, but never fires the last step when it should click the Save button and save the Lead.

Firefox's version, however, does Save the lead with the event firing correctly.

## To Reproduce

In a salesforce organization, create a test in the Selenium IDE to create and save a new Lead. Run the test.

## Expected behavior

The save button event is fired and redirects to the saved lead

## Actual Behavior

In Chrome, the save button is clicked, but no save event is fired. In Firefox, the button is clicked and the save event is correctly fired and the lead is saved.

## Project file reproducing this issue (highly encouraged)

See attachments (txt file to allow Github to accept it)

## Environment

OS: macOS Monterey Version 12.2.1 (Intel)
Selenium IDE Version:  3.17.2
Browser: Chrome Version 100.0.4896.60 (Official Build) (x86_64), Firefox 98.0.2 (64-bit)
[corporate_instance.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/8391792/corporate_instance.side.txt)

**Comment by toddtarsi** [comment]
@blapsley - Thank you for reporting this! I suspect you've hit the primary thing we don't like about the selenium-ide v3.

Basically, a lot of the in-IDE playback doesn't use industry standard browser automation via webdriver. Instead, it uses simulated JS events to approximate that playback. Some things that might work here won't work elsewhere, whereas webdriver is much more consistent with not clicking things if they're 0x0 for example, or the element is covered. So, yeah. I am glad for this issue, and I truly believe moving to 4.x will either resolve this issue, or change your interaction pattern with it enough that there is a different-and-closer-to-the-heart-of-the-matter issue we're dealing with.

**Comment by toddtarsi** [comment]
I'm going to close this issue for now, but feel free to re-open if you have any questions or discover anything else later.
