### ISSUE TITLE
Key arrow down selenium ide

### ISSUE THREAD

**Issue by fahdionic2** [SeleniumHQ/selenium-ide#1359]
Hi,
Please how to force click key Arrow down in selenium ide

**Comment by toddtarsi** [comment]
This guy does a good job of explaining it:
https://www.rickyadams.com/wp/index.php/2017/12/01/using-special-keys-in-selenium-ide/

Here's a list of special keys. I think you prefix them with `KEY_` to get em working:
https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/webdriver/key.js
