### ISSUE TITLE
Can't type text with newlines

### ISSUE THREAD

**Issue by mwiencek** [SeleniumHQ/selenium-ide#136]
Using v1.1.0-beta.2 in Firefox 60.0b8

On adding a "type" command, if I press return inside the value input, it inserts a visible "\n", which is fine, but when I run the command, it /also/ types the literal characters "\\" and "n" into the textarea.

<img width="181" alt="untitled" src="https://user-images.githubusercontent.com/1056556/38184754-76d32fac-360f-11e8-8622-07c2c76fb585.png">

The old IDE inserted actual line breaks, as expected.

Next, in the hopes of finding a workaround, I tried replacing the instances of `\n` in the value input with `${KEY_ENTER}`. This had an even more unexpected result:

<img width="181" alt="untitled 2" src="https://user-images.githubusercontent.com/1056556/38184885-73d47bd4-3610-11e8-9c56-831c0841cfcc.png">

(Those are `U+E007`.)

Sources:
```html
<!DOCTYPE html>
<html>
    <body>
        <textarea id="foo"></textarea>
    </body>
</html>
```
```json
{
  "id": "62558e9e-540f-44b9-81b4-a96ceb8d3e92",
  "name": "Untitled Project",
  "url": "",
  "tests": [
    {
      "id": "2583e6d2-1f06-4c14-a3c8-a024bd4264dc",
      "name": "Untitled",
      "commands": [
        {
          "id": "02d7ac67-3c02-43c6-886d-6f286c657a1d",
          "comment": "",
          "command": "type",
          "target": "id=foo",
          "value": "foo\\nbar\\nbaz"
        }
      ]
    }
  ],
  "suites": [
    {
      "id": "ca8a321f-ca8a-44b0-b8e6-1634a0e4df2f",
      "name": "Default Suite",
      "tests": [
        "2583e6d2-1f06-4c14-a3c8-a024bd4264dc"
      ]
    }
  ],
  "urls": []
}
```

**Comment by corevo** [comment]
The `\n` issue was caused by the new way we handle file uploads in the IDE.  
The `${KEY_ENTER}` was an incorrect key code in the key map.

**Comment by Fogest** [comment]
@corevo I still have this same issue. When I use the Selenium IDE in the browser to record input that involves multi line input it will have something like `someText\nNextLineText` generated as a "type" command. This works when played back in the browser, however when played back via the command line runner using the chrome webdriver it does not work and instead puts in the `\n` as text.

**Comment by corevo** [comment]
@Fogest the runner is correct, the fact that we put a new line for the `\n` key combination is a bug, we should type `\n` as a string, cause that's the string.

To send a special key you need to use the `${KEY_ENTER}` syntax, we will fix it in the next major version of the IDE.

**Comment by Fogest** [comment]
@corevo If I do a "type" command in the IDE that is like `blah blah blah ${KEY_ENTER} new line` it will enter the text of key_enter instead of hitting enter during the typing. How am I supposed to enter newlines in the IDE currently and have it work when I save it and try to use it in the runner?

Currently what I am doing is doing a replace on `\\n` with `\n` on the file the IDE generates so that it then works in the runner.

**Comment by corevo** [comment]
We need to fix `${KEY_ENTER}` then, mind opening an issue that `${KEY_ENTER}` doesn't work in the extension + an example?

**Comment by Fogest** [comment]
@corevo I have created the issue regarding the key_enter and it is referenced in this issue
