### ISSUE TITLE
Selenium side runner not launching in headless mode

### ISSUE THREAD

**Issue by CristinWilliams** [SeleniumHQ/selenium-ide#1367]
## 🐛 Bug Report

When running the following command:

`selenium-side-runner -c 'chromeOptions.args=[headless]' ./test2.side`

The following error is returned: "TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()?"

Per 4/12-4/13/2022 discussion the Selenium IDE Slack channel, this causes Chrome to launch again instead of executing the test in headless mode.

## To Reproduce

From within a VM (Ubuntu 20.04), run the command listed in the bug report.

## Expected behavior

Either a pass or fail (when run through the IDE, the test passes).

## Project file reproducing this issue (highly encouraged)

Attached, save as a .side file to run.
[test2.txt](https://github.com/SeleniumHQ/selenium-ide/files/8483322/test2.txt)

## Environment

OS: Windows 10
Selenium IDE Version:  v3.17.2 
Selenium SIDE Runner Version:  3.17.0

Node version: 16.13.0

Browser:
Browser Version:  Chrome 100

**Comment by toddtarsi** [comment]
This works fine now, I use this all the time for work on v4:

```
selenium-side-runner -c \"goog:chromeOptions.args=[headless,no-sandbox] browserName=chrome\" -d -t 15000 ./project.side
