### ISSUE TITLE
Delete key deletes entire command while editing values of the command

### ISSUE THREAD

**Issue by Rowdster** [SeleniumHQ/selenium-ide#1368]
When editing the values within the commands themselves, the delete and backspace keys will remove the entire command with no undo.

Consider removing delete and backspace to remove a command and require instead some visual delete icon.

**Comment by Rowdster** [comment]
typing delete or backspace here removes the full command entry
![image](https://user-images.githubusercontent.com/575732/163651906-d1a53e09-0d6b-4605-b803-32c27e3dfae3.png)

**Comment by toddtarsi** [comment]
@Rowdster - Nice report! Okay, ctrl/cmd+delete deletes commands now. Also, this stuff has been pulled into popup and application level menus. Unfortunately, I don't have standard text based cut / copy / paste working yet now.

**Comment by Rowdster** [comment]
per a conversation, CTRL-DEL would also be a great replacement
