### ISSUE TITLE
"type" command right after "open" doesn't wait for page to load

### ISSUE THREAD

**Issue by mwiencek** [SeleniumHQ/selenium-ide#137]
Using v1.1.0-beta.2 in Firefox 60.0b8

In the old IDE, "open" would apparently wait for the page to load before executing subsequent commands. This doesn't seem to be the case anymore, so the commands that execute while it's still loading have no effect.

The weird thing is, the log shows that the commands which are run before the page loads are _succesful_, even though they clearly aren't: they have zero side effects on the page.

Here is a contrived example which reproduces the issue for me. Sometimes it will succesfully search for dog food, but most of the time (if I keep pressing "play"), it does nothing. In the old IDE, the search is always successful.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="about:blank" />
<title>dog food search</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">dog food search</td></tr>
</thead>
<tbody>
<tr>
	<td>open</td>
	<td>https://duckduckgo.com</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=search_form_input_homepage</td>
	<td>dog food</td>
</tr>
<tr>
	<td>click</td>
	<td>id=search_button_homepage</td>
	<td></td>
</tr>
</tbody>
</table>
</body>
</html>
```

**Comment by 98gmarquee** [comment]
I was just noticing that in 1.0.3.0 as well. It wasn't doing that with 1.0.2.

**Comment by corevo** [comment]
I have made changes to the way `open` works, to make it faster in certain situations, as well as make it work in situations where the current page cannot be automated (redirects you to a loading page).  
I'll take a look at this.

**Comment by corevo** [comment]
I found the root cause of the problem, `type` now that it handles file upload, no longer waits for the page to load.  
Because we handle it differently than other commands (because of file uploading), it can under some circumstances bypass the wait mechanism.  
I'll work on a fix, thanks for reporting this.

**Comment by mwiencek** [comment]
Thanks for the quick fix! :)
