### ISSUE TITLE
script using 'run' causes project window to go blank

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1370]
Trying to load the attached side file is causing a blank screen for me in the project window.  Similarly, playback of other scripts with run are drawing the project window blank as well
[simpleparent.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/8500624/simpleparent.side.txt)

**Comment by coinzdude** [comment]
![image](https://user-images.githubusercontent.com/58857646/163692295-7f276c19-4989-43eb-87a9-23f4e2ba7cfa.png)

**Comment by toddtarsi** [comment]
Fixed these days
