### ISSUE TITLE
Implement the "Find target in page" from v3 

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1382]
We currently have the "Select target in page" feature from v3.  Need to implement the "Find target in page" feature which attempts to highlight based on the current command's selector.  Consider allowing the user to choose particular selectors to be found from the list available within the command.

v3:
![image](https://user-images.githubusercontent.com/58857646/165128841-c21a2225-9b38-49c3-9089-1b33822aaa28.png)

v4:
![image](https://user-images.githubusercontent.com/58857646/165128899-200e5b05-4d66-4b4f-ae56-47a3c86d2487.png)

Relevant code may be found here:
"src/browser/windows/PlaybackWindow/preload/find-select.ts, line 74
This needs to be changed from using postMessage to listening for some window.sideAPI event"

**Comment by toddtarsi** [comment]
This is implemented in latest
