### ISSUE TITLE
Test delete - confirmation dialog

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1385]
It is very easy to accidentally delete a test, and there is no confirmation.  Just need a confirm dialog to display when clicking delete test.

"Confirm? Delete test ____
Yes, No"

![image](https://user-images.githubusercontent.com/58857646/165130949-8d53070a-5d61-4abb-ad0b-9d47aa1e219a.png)

**Comment by toddtarsi** [comment]
oh wowie that is easy

**Comment by toddtarsi** [comment]
Done on latest
