### ISSUE TITLE
When selecting a command and adding a new command, the internal ordering is incorrect

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1386]
When adding a command after selecting some existing command entry, would like the new command to be inserted 'above' the selected command and then be selected/highlighted as well.  Currently, a command entry is added below the selected command and the prior selected command is remaining as selected.

Note: copy/paste of a command inserts and selects a new command nicely

![image](https://user-images.githubusercontent.com/58857646/165129897-969be079-8c7c-450e-bb3e-89e8e447a2cf.png)

**Comment by toddtarsi** [comment]
Preference exists now for toggling
