### ISSUE TITLE
On script edits, keep a flag, and alert the user to save file or continue if the changes would be lost

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1388]
Detect changes in the script, could just be a simple raw compare, or md5 hash, so that when the user would accidentally abandon changes in the file, say when closing the app or loading another script to prompt the user, 

"Save changes to your SIDE file, 'MySide.side'?

Yes, No"

**Comment by toddtarsi** [comment]
Done in v4. Thanks for your help doing this @coinzdude !
