### ISSUE TITLE
New command context menu, "Insert Command"

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1389]
New insert command which inserts a new command entry, same as the +
![image](https://user-images.githubusercontent.com/58857646/165151131-cb748b4b-e368-44ce-83aa-01acefaff782.png)

![image](https://user-images.githubusercontent.com/58857646/165151046-83b60812-7622-4389-8381-973a745ae8d4.png)

**Comment by toddtarsi** [comment]
I agree. This one is clutch.

**Comment by toddtarsi** [comment]
This is in latest, closing
