### ISSUE TITLE
Allow replaceable ad-hoc data for test input

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1391]
Consider a JSON document support for ad-hoc data to use in a test execution.  Allow a test set of data (or more than one?) to be defined within the project config, and allow the test set data to be persisted with the SIDE file save.

Proposed test set data is a simple JSON document with name/value pairs in an object, so values below would replace matched "Store" entries:

store, Username, scriptUser

```json
{
"Username":"someuserID",
"Password":"!@#$",
"SelectListVal":"SelectThisItem"
}
```

**Comment by toddtarsi** [comment]
I'm going to close this. People always make these issues. Some want excel data sources. Some want json. I would rather not do this and require that people write their own parsers and supply whatever data that way.
