### ISSUE TITLE
make use of selenium atoms

### ISSUE THREAD

**Issue by zavelevsky** [SeleniumHQ/selenium-ide#14]
The modules in the selenium main tree (under JS) are google closure modules.
Eventually the IDE will be merged to there and it'll make the landing less bumpy if we use the `atoms` (javascript/atoms) and perhaps some of the other pieces too.
https://github.com/SeleniumHQ/selenium/tree/master/javascript/atoms
The `atoms` provide building blocks for basically every bit of webdriver functionality
Need click? bot.action.click
webdriver.atoms.element will be a useful module

**Comment by corevo** [comment]
I think [this](https://github.com/SeleniumHQ/selenium-ide/blob/master/src/atoms.js) is the compiled version.  
Maybe we can easily replace it?

**Comment by shs96c** [comment]
You can compile from the selenium sources pretty easily. If you're unsure how, I can explain on the irc channel

**Comment by zavelevsky** [comment]
It very much seems to be the case and we are much better off using the code from the Selenium repository

**Comment by corevo** [comment]
[Fixed](https://github.com/SeleniumHQ/selenium-ide/pull/55)
