### ISSUE TITLE
Selenium Side Runner

### ISSUE THREAD

**Issue by jm111015** [SeleniumHQ/selenium-ide#1409]
Setup selenium side runner along with Node.js and npm and it works well. But after uninstalling node.js and installing the latest version as well as the selenium side runner, got this issue after setting-up the path correctly.
![image](https://user-images.githubusercontent.com/24288203/166633732-32da8ace-5443-43c5-83e1-bb1f80a6fe7a.png)

Please help.

Thanks.

**Comment by gabrielgg** [comment]
Confirmed - problem with node 18.2.0 on Mac OS 12.4. Seems like "hostname" ends up undefined in selenium-webdriver for some reason.
Works with node 16.15.0 FWIW

**Comment by toddtarsi** [comment]
@jm111015 - We just put out a new major version on npm here:

https://www.npmjs.com/package/@seleniumhq/side-runner

I need to update the readme on it still haha
