### ISSUE TITLE
selenium-side-runner WebDriverError: Reached error page

### ISSUE THREAD

**Issue by 5hahbaaz** [SeleniumHQ/selenium-ide#1410]
I am trying to run a selenium test with selenium side runner on firefox browser through geckodriver using the command line:

$ selenium-side-runner -c "browserName= firefox moz:firefoxOptions.args=[-headless]" test.side

but i keep running into the below error:

WebDriverError: Reached error page: about:neterror?e=netTimeout&u=https%3A//abcdef.com/&c=UTF-8&d=The%20server%20at%20abcdef.com%20is%20taking%20too%20long%20to%20respond.

I have tried downgrading firefox and geckodriver versions but still no solution. 

Currently using
firefox version -> 99.0.1
geckodriver version-> 0.30.0
selenium-side-runner version-> 3.17.0

**Comment by toddtarsi** [comment]
Hey, we just hit a new major version. I need to test out the side-runner more, its so fresh haha, but would you want to try it and see if it helps?

https://www.npmjs.com/package/@seleniumhq/side-runner
