### ISSUE TITLE
Proxy user and pass

### ISSUE THREAD

**Issue by halotoken** [SeleniumHQ/selenium-ide#1415]
Hi, How can I use proxy with credentials. I didn't see any example.

I tried this;
selenium-side-runner ./test2.side --proxy-type=manual --proxy-options="https=xxxx:7070 user=xxx pass=xxxx"

**Comment by toddtarsi** [comment]
@halotoken - I honestly have no idea. What do you mean proxy with credentials? Is there like an authorization header or something? This sounds very implementation specific.
