### ISSUE TITLE
Remove from recents

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1416]
Could be useful to have a simple "X" to remove an entry from recents like the odd one I managed to get here

![image](https://user-images.githubusercontent.com/58857646/167702038-6e516b81-2b00-490f-89f9-928402f39e0f.png)

**Comment by toddtarsi** [comment]
Meh, most things with recents don't do this, and I don't want to do anything beyond break fix, so I'm just gonna leave it as is
