### ISSUE TITLE
File, Open Recents, or View, Recents to open recents window dialog

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1419]
Would be helpful to see "File, Open Recents" to redisplay the recents dialog.

![image](https://user-images.githubusercontent.com/58857646/167703650-5e927f4c-10d6-4ba5-9520-753996276de4.png)

**Comment by toddtarsi** [comment]
@coinzdude - We should probably go more standard and just do a different menu section with the list of recents

**Comment by toddtarsi** [comment]
Closing this, menu contains recent projects list now
