### ISSUE TITLE
Fails to assert matching text

### ISSUE THREAD

**Issue by com2** [SeleniumHQ/selenium-ide#1423]
## 🐛 Bug Report

I use assert text to make sure a product was added to cart in Wordpress:
**Command** _assert text_
**Target** _css=.woocommerce-message_
**Value** _VER CARRITO “Revelado de película fotográfica” se ha añadido a tu carrito._

**Log** assertText on css=.woocommerce-message with value VER CARRITO “Revelado de película fotográfica” se ha añadido a tu carrito. Failed:
Actual value "VER CARRITO “Revelado de película fotográfica” se ha añadido a tu carrito." did not match "VER CARRITO “Revelado de película fotográfica” se ha añadido a tu carrito."

To be certain I tried:

- copying Actual value from log to the Value field to make sure they match. 
- switching to English in my staging site and translated the title to get the whole string without tildes to make sure that wasn't the issue. 

## To Reproduce

To reproduce unzip [FotoR3.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/8701010/FotoR3.side.zip) then import the .side file to Selenium IDE and run it. 

## Expected behavior

I expect matching strings to be successfully asserted or alternatively that the log file shows me the Actual Value string correctly. 

## Environment

OS: Ubuntu 20.04 LTS
Selenium IDE Version:  3.17.2
Browser: Chromium
Browser Version: Version 101.0.4951.64 (Official Build) snap (64-bit

**Comment by toddtarsi** [comment]
Hey, we just went up a major version! Can you test if your issue still exists here:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.0
