### ISSUE TITLE
incognito

### ISSUE THREAD

**Issue by DanielNemocon** [SeleniumHQ/selenium-ide#1424]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by toddtarsi** [comment]
We're releasing v4 soon, which will run in an Electron process. At that point this feature won't really apply.

**Comment by toddtarsi** [comment]
As a result, I'm closing this now. Thanks for the recommendation!
