### ISSUE TITLE
Open an existing project

### ISSUE THREAD

**Issue by fahdionic2** [SeleniumHQ/selenium-ide#1428]
Hi
Can i put directory of the side inside selenium without open again existing project 
i want just run the side

**Comment by toddtarsi** [comment]
@fahdionic2 - I think this might be nicer in v4. We're getting close to alpha haha. Just some reviewing and paperwork.

**Comment by toddtarsi** [comment]
And idk, maybe the PLC won't like stuff. I hope v4 is good haha. 😄

**Comment by toddtarsi** [comment]
There's still much to do on my part.

**Comment by fahdionic2** [comment]
When this version will be ready ?

**Comment by toddtarsi** [comment]
@fahdionic2 - We're in alpha!!!

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.0

You may get complained at about it being unsafe. We don't have code signing certificates yet, but they're coming. Also the code is built in a CI and hosted on github, so its very transparent in how it reaches you.
