### ISSUE TITLE
Issue with cloning the repo

### ISSUE THREAD

**Issue by tranjith2017** [SeleniumHQ/selenium-ide#1444]
When I clone this project "https://github.com/SeleniumHQ/selenium-ide/tree/v3"
with ----- git clone https://github.com/SeleniumHQ/selenium-ide.git 
I see a typescript project (selenium ide standalone electron application)

But when I download the zip file, I see a javascript react project (selenium ide chrome browser extension)
<img width="572" alt="image" src="https://user-images.githubusercontent.com/28526064/171795288-debe6c92-595c-4658-a43b-6b9f13eb8d7e.png">

Can someone please advise why this happens ?

**Comment by tranjith2017** [comment]
https://github.com/SeleniumHQ/selenium-ide/tree/v3 branch has react extension code &
https://github.com/SeleniumHQ/selenium-ide/tree/trunk branch has electron js code

**Comment by toddtarsi** [comment]
@tranjith2017 - I'm sorry I took so long to respond to this! I missed it entirely. Basically, v3 was a chrome extension, but v4 was planned to be an electron app so that playback no longer had to use emulated JS and better processing around alerts could be achieved.

**Comment by toddtarsi** [comment]
v4 === trunk, also v4 is in alpha! 

https://github.com/SeleniumHQ/selenium-ide/releases/tag/latest <-- Nightly unstable 👍 branch
