### ISSUE TITLE
CommandForm width increase now pushes other important things out of view

### ISSUE THREAD

**Issue by ryanackley** [SeleniumHQ/selenium-ide#1449]
## 💥 Regression Report

The fix for #1275 breaks the UI for me in Chrome on Mac OS X. Specifically, the record and breakpoint buttons are pushed offscreen. It also makes the command table huge and there are no scrollbars

This is the previously working UI available in the chrome web store:
![image](https://user-images.githubusercontent.com/563656/172067986-e7cdafda-5fbf-4ae8-ba7a-f7757c74012d.png)

When I build and run from source, this is the UI I get:
![image](https://user-images.githubusercontent.com/563656/172068086-9cfc9ae3-1a03-462a-b116-09abe08cfd51.png)

## Last working version

Worked up to version: It seems to be caused by b53c405a4448e015895d395c6933824ae5364d58. I haven't tested the version prior but I assume it works.

Stopped working in version: b53c405a4448e015895d395c6933824ae5364d58

## To Reproduce

Checkout and build v3 branch, then run chrome extension

## Expected behavior

The record and breakpoint files should be visible and the entire command table should be visible. 

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: OS X
Selenium IDE Version:  v3 branch 
Browser:
Browser Version: 102.0.5005.61

**Comment by toddtarsi** [comment]
We're getting very close on v4. If possible, I'd love to recommend you try that. We'll be putting non-code-signed releases on github, and once the committee gives us the okay, we'll actually be putting out signed binaries for your OS ❤️

**Comment by toddtarsi** [comment]
We're not putting releases on Github yet, so you'll have to build manually for now, but that's one of my goals this week 😄

**Comment by toddtarsi** [comment]
We're on v4 now and in Alpha!

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.0
