### ISSUE TITLE
Chrome Extension: "record.js:310 Uncaught TypeError: Cannot read property 'relatedTarget' of undefined" when moving iframe separators

### ISSUE THREAD

**Issue by colin0117** [SeleniumHQ/selenium-ide#145]
Hi,

I've noticed this error being reported in Chrome's console when I'm moving iframe separators around:

record.js:310 Uncaught TypeError: Cannot read property 'relatedTarget' of undefined

I'll apologise if my terminology is wrong, I'm new to web development, but here's how to reproduce it:

1. have the Selenium IDE extension enabled in Chrome
2. go to http://live.datatables.net/liluhawe/2/edit
3. press "Run with JS"
4. Ctl+shift+I to open console
5. move the separator between the JavaScript panel and the Output panel
6. when you release the mouse, the error appears

Disabling the chrome extension stops the error being displayed.

Hope that all makes sense :)

Cheers,

Colin

**Comment by corevo** [comment]
It seems to be an issue with the drag and drop classifier, rather than moving an element, the recorder tries to record an element being dropped on a different one, which will fail, since that different element doesn't exist.  
Once I have the time I'll get around to fixing it.

**Comment by toddtarsi** [comment]
I'm going to close this issue, even if it exists, because we're no longer modifying v3, but are attempting to get v4 out of alpha, and I'm just trying to sort of start fresh there somewhat.
