### ISSUE TITLE
Variables don't appear to be processed for target, only value

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1463]
In this test, ${now} processes for 'value', row 7,  but not for 'target', row 15

![image](https://user-images.githubusercontent.com/58857646/172948855-dad398ed-f2a3-4af1-a5c6-323fa676645f.png)

vars should work in either locations

**Comment by toddtarsi** [comment]
@coinzdude - This a v3 specific thing? Can I close it haha

**Comment by toddtarsi** [comment]
@coinzdude - bump

**Comment by coinzdude** [comment]
No, this is a v4 issue. I need variables processed for target. for example, a variable is set with a future item to be clicked needing the variable value. You can't use the variable if the target does not get the replacement.  That line 15 example shown will not target using the value from the variable.  I can look to process these per command, but I think it should be a global feature.

**Comment by coinzdude** [comment]
I found that with a simple test, 'Target' is getting variable values as expected, but not within my particular script. I will look to isolate it.  Thanks!

**Comment by coinzdude** [comment]
I'm closing this until I can isolate or provide a fix

**Comment by coinzdude** [comment]
This was resolved
