### ISSUE TITLE
[BUG] Selenium IDE exteremly slows down FireFox and stops working

### ISSUE THREAD

**Issue by Emad-Eldin-G** [SeleniumHQ/selenium-ide#1468]
## 🐛 Bug Report

Downloaded the Selenium IDE extension on Firefox, and it causes Firefox to crash and stop working when the following happens:
- Starts recording session, and continues fine for about 5 steps. 
- When clicking on a link or submitting a form, it starts loading for a while.
- Then Firefox sends a popup saying "Selenium IDE is slowing down your browser.
- And it stops working.

Note: This occurred on amazon.com

## Expected behavior

Firefox to continue working and submit the query to Amazon's search bar

## Environment

OS: Windows 11
Selenium IDE Version:  3.17.4

Browser: Firefox
Browser Version: 101.0.1 (64-bit)

**Comment by toddtarsi** [comment]
v3 is deprecated, come join us on v4! We're in alpha!!! 

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.0
