### ISSUE TITLE
Request for shortening URL

### ISSUE THREAD

**Issue by Chukkyoj** [SeleniumHQ/selenium-ide#1474]
## (https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 

Hi
So i was thinking if there is a way to shorten the URL to get to certain parts of the website

Example
To get to EXPLORE on this GitHub page using selenium IDE, I will have to 
1. Launch the website https://github.com/
2. Login with a username and password 
3. Click the Explore button before i get to the explore page  
However, I don't want to start from the login page, I just want to start from the point where I am already logged in

Is there a way to do that

**Comment by toddtarsi** [comment]
@Chukkyoj - So you're looking to shortcut the Github login. That's a good question. Probably not an easy one, but its not something we can really solve for you either. Basically, you'd have to know how to get a login from github, and I don't know what the cookie they use is, but you'll need that. If you figure that side out, this is what you'd do. 

1. You create a plugin based on this one: https://github.com/SeleniumHQ/selenium-ide/tree/trunk/packages/side-plugin-example
2. You extend your plugin with a custom command:

```
  commands: {
    loginGithub: {
      name: 'Login to GitHub',
      description: `
        This command should log your browser into GitHub via API,
        get a session cookie, and inject it into the browser
      `,
      execute: async (command, driver) => {
        const ghSessionCookie = await getGHSessionCookie(); 
        // set a cookie on the current domain
        await driver.manage().addCookie({
          name: 'github-session-or-whatever',
          value: ghSessionIdentifier
        });
      },
    },
  },
}
```

The known unknown in this situation is getGHSessionCookie, and assuming you get that working, make sure to set it to the right key as well.

**Comment by toddtarsi** [comment]
Closing this, as its best approached via a bespoke plugin,

**Comment by Chukkyoj** [comment]
Alright Todd that's fine.

If you need me to help you test the project let me know. I have 4+ years
experience as a software test analyst and a certified ISTQB and
Professional member of the British Computer Society.

Looking forward to working with you on this awesome project.

Thanks and Regards

**Comment by toddtarsi** [comment]
@Chukkyoj - Wowie zowie I'm just some clod who got conned into working on this thing unpaid for the last 10 months 😆. Yes please! If you like v3, please try v4 and let me know your experience! Thank you!

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.17

**Comment by Chukkyoj** [comment]
Sure, I will let you know. I can do unpaid in as much as there is room for
growth, that's all I am after for now
