### ISSUE TITLE
Can not find screenshot related commands in Selenium IDE Version 3.17.2 Is there any screenshot command available ?

### ISSUE THREAD

**Issue by dikshaMalvankar** [SeleniumHQ/selenium-ide#1488]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
Nope! Also, v4 doesn't either and is out in alpha:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/latest
