### ISSUE TITLE
Unable to playback the recorded test

### ISSUE THREAD

**Issue by prashanth-sams** [SeleniumHQ/selenium-ide#149]
The IDE interface becomes white when I try to playback the recorded test

![screen shot 2018-04-15 at 11 58 10 am](https://user-images.githubusercontent.com/2948696/38776214-7a4bc168-40a4-11e8-9ada-d2160c7513fd.png)

**Comment by corevo** [comment]
It's being published now to Firefox addons store.  
I'm not publishing to Chrome as its unaffected.
