### ISSUE TITLE
ProjectTab implicitWait setting

### ISSUE THREAD

**Issue by dl8sd11** [SeleniumHQ/selenium-ide#1510]
## 🚀 Feature Proposal

Config to enable the user to set the implicitWait for the WebDriverExecutor.

## Motivation

I faced some situations where the default value of the implicitWait is not enough for many of my commands. I would like to have an option to config this value for every command.

## Example

I tried to add a TextField in the ProjectTab. I would like to know if this setting belongs to another place.

![image](https://user-images.githubusercontent.com/19171021/181425082-f41c77cf-dc79-4f84-87d3-317b163af48c.png)

**Comment by dl8sd11** [comment]
If this feature looks good to the project, I'm also willing to contribute to this feature.

**Comment by toddtarsi** [comment]
@dl8sd11 - Holy cow, I appreciate the offer of help! You rock! However, I think maybe we can help you this time. Go to the suites tab, click the pencil to enter "Edit Suite" mode, and then set the timeout to what you need

**Comment by toddtarsi** [comment]
@dl8sd11 - For a bit more info, timeout is a suite level flag, not a project level flag. That's why its on that tab

**Comment by dl8sd11** [comment]
@toddtarsi Wow, thanks a lot for your help. I am new to the project. The timeout works perfectly for me now!

**Comment by toddtarsi** [comment]
@dl8sd11 - Well if I can help with anything else going forward, please let me know! People offering to PR and who attempt to implement the feature they want go to the front of the line 😄
