### ISSUE TITLE
Does seleniumIDE support recording electron applications?

### ISSUE THREAD

**Issue by GuiStarF** [SeleniumHQ/selenium-ide#1513]
## 💬 Does seleniumIDE support recording electron applications?

I want to use seleniumIDE to record automation scripts for electron applications.
I don't know much about node.js. If so, what should I modify in the source code to replace our electron application path？

#### If anyone also working on the recording of automated test scripts for electron applications, please contact me:yifcheng@foxmail.com

**Comment by toddtarsi** [comment]
Unfortunately, no. We are using an electron app to record web interactions. Don't get me wrong, I'd love it if we could, because then we could make Selenium IDE perform recording and playback on itself for testing. However, thats too much work for not enough gain for us. So, no.
