### ISSUE TITLE
Bug SIDE : Send Keys ${KEY_ENTER} d'ont work on Firefox

### ISSUE THREAD

**Issue by emerisier** [SeleniumHQ/selenium-ide#1514]
## 🐛 Bug Report

Bug IDE SIDE 3.17.4 : Send Keys ${KEY_ENTER} d'ont work on Firefox (v103)

it's work fine on selenium-side-runner and Chrome

**Comment by toddtarsi** [comment]
Not an issue in v4, where we only run in one environment where this works
