### ISSUE TITLE
Bug SIDE : Type on input type="date" d'ont work for angular

### ISSUE THREAD

**Issue by emerisier** [SeleniumHQ/selenium-ide#1515]
## 🐛 Bug Report

Bug IDE SIDE 3.17.4 : Type on input type="date" d'ont work 
specific format date = yyyy-mm-dd

fix for angular : element.dispatchEvent(new Event('input'));

it's work fine on selenium-side-runner

**Comment by toddtarsi** [comment]
We're not making any tweaks to v3 anymore. Please re-open if this is also an issue on v4.
