### ISSUE TITLE
Select target in page not working

### ISSUE THREAD

**Issue by dl8sd11** [SeleniumHQ/selenium-ide#1516]
## 🐛 Bug Report

The find-select can not work after restarting the PlaybackWindow.

![image](https://user-images.githubusercontent.com/19171021/184281340-03356e34-ff83-4262-a960-c35ebaf150af.png)

I found that after restarting playbackWindow there will be some unremoved listener 
 https://github.com/SeleniumHQ/selenium-ide/blob/f716d0686dc7ad806d6bacd9744cd22f8ddb3a14/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/find-select.ts#L29

I have a temporary workaround to bring back this feature. The error can be handle at https://github.com/SeleniumHQ/selenium-ide/blob/f716d0686dc7ad806d6bacd9744cd22f8ddb3a14/packages/selenium-ide/src/main/api/classes/EventListener.ts#L62

I am more than happy if I can contribute to this issue :)

## To Reproduce

I can only reproduce this issue in Windows, Linux does not have this problem.

1. Play a test once
2. Close the PlaybackWindow
3. Play the test again
4. Press this icon for the target of click
![image](https://user-images.githubusercontent.com/19171021/184281621-c8324e3e-9b2d-4eae-bcb6-60cd64827916.png)
5. requestSelectElement fails

## Expected behavior

![image](https://user-images.githubusercontent.com/19171021/184281813-28adb2d4-061c-4307-93ec-3da7c05a046b.png)

## Project file reproducing this issue (highly encouraged)

```
{
  "id": "729c2f12-8fcb-46e5-be2a-c21b2790bcee",
  "version": "3.0",
  "name": "New Project",
  "url": "http://www.google.com",
  "urls": [
    "http://www.google.com"
  ],
  "plugins": [],
  "suites": [
    {
      "id": "c1e845b1-ab35-432f-b526-6e1226e4f05e",
      "name": "New Suite",
      "parallel": false,
      "persistSession": false,
      "tests": [
        "cdea920f-b2fd-4733-a61f-0d1e400f4718"
      ],
      "timeout": 30000
    }
  ],
  "tests": [
    {
      "id": "cdea920f-b2fd-4733-a61f-0d1e400f4718",
      "name": "New Test",
      "commands": [
        {
          "id": "cb27f23f-4abf-41ac-9906-1354a1ae6678",
          "command": "open",
          "target": "/",
          "value": ""
        },
        {
          "command": "click",
          "target": "name=q",
          "value": "",
          "insertBeforeLastCommand": false,
          "frameLocation": "root",
          "id": "e484a51f-8f52-4650-bf23-64b00a2ae50a",
          "targets": [
            [
              "name=q",
              "name"
            ],
            [
              "css=.gLFyf",
              "css:finder"
            ],
            [
              "xpath=(//input[@name='q'])[1]",
              "xpath:attributes"
            ]
          ]
        }
      ]
    }
  ],
  "snapshot": {
    "dependencies": {},
    "tests": [],
    "jest": {
      "extraGlobals": []
    }
  }
}
```
## Environment

OS: Windows 10
Selenium IDE Version:  4.0.0-alpha.0 

Browser: 
Browser Version:

**Comment by toddtarsi** [comment]
@dl8sd11 - Sorry to get around to this so late. There's been a backlog of like 300 issues before I started, and so I almost don't know what to do with this list. I think this should be resolved now. Thank you for advising! I'll close this issue for the moment, but if it is still occurring for you on latest release, feel free to re-open.
