### ISSUE TITLE
Selenium IDE won't play in Windows when using v4.  

### ISSUE THREAD

**Issue by clfordhub** [SeleniumHQ/selenium-ide#1518]
## 🐛 Bug Report

Installing Selenium IDE in v4 doesn't run the test when the play button is clicked.  It will start the playback window if record is clicked, but not when clicking play.  The only way play works in windows is doing cmd Yarn Start

## To Reproduce

Install Selenium IDE v4
Open or create a new test
Click play
Nothing happens in the playback  window

## Expected behavior

I would expect the script to run and show output in the playback window.

## Environment

OS: Windows 10
Selenium IDE Version:  4
Selenium SIDE Runner Version:  ^4.0.0-alpha.6"

-->
Node version: 16
Only required if using selenium-side-runner
-->
Browser:
Browser Version: Chrome latest

**Comment by toddtarsi** [comment]
@clfordhub - Thank you for reporting! I'll work on exposing both back and frontend logs. A buddy of mine used v4 pretty aggressively with the IDE, so there must be a bit more going on here. Regardless, I want the dang answer!

**Comment by toddtarsi** [comment]
@clfordhub - Is this still the case for you, or can I close this? I know a couple people who are using Windows with v4, but I haven't heard unanimous ease either.

**Comment by clfordhub** [comment]
@toddtarsi Yep, this can be closed.

**Comment by toddtarsi** [comment]
Sweet!
