### ISSUE TITLE
Ability to play from here by right clicking on any testcase in a test suite would be beneficial

### ISSUE THREAD

**Issue by brightland** [SeleniumHQ/selenium-ide#1519]
## 👉 [Please follow oneof these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.
Ability to play from here by right clicking on any testcase in a test suite that would continue playing all remaining test cases below including the selected test case would be nice. Old legacy Selenium IDE 2.9.1 used to have that capability.

**Comment by toddtarsi** [comment]
@brightland - Is this regarding v3 or v4 alpha? I have to caution you that I'm only handling takedowns on v3 at this point

**Comment by brightland** [comment]
V3

Best Regards,
Somendra Shrestha

On Aug 29, 2022, at 7:31 PM, toddtarsi ***@***.***> wrote:

﻿

@brightland<https://github.com/brightland> - Is this regarding v3 or v4 alpha? I have to caution you that I'm only handling takedowns on v3 at this point

**Comment by toddtarsi** [comment]
Ah, yeah. We have something like this in v4 although its a bit picky of when you can do it. I need to make it a bit less clever really. Well, sorry about that!
