### ISSUE TITLE
Test Data to retrieve from Excel

### ISSUE THREAD

**Issue by DeepanFernandez** [SeleniumHQ/selenium-ide#1521]
## 🚀 Feature Proposal

Test Data to retrieve from Excel

## Motivation

It can be used by non technical persons. Just changing the data and trigger the execution. as this is just a browser extension, even all the business persons can be used

## Example

Please provide an example for how this feature would be used.

**Comment by toddtarsi** [comment]
Absolutely not. This is something a developer who wants to account for csv or xlsx can do, but not anything in the scope of the core ide. This is why we support plugins tbh.
