### ISSUE TITLE
Selenium IDE browser extension for google chrome requires manifest upgrade to V3. 

### ISSUE THREAD

**Issue by PrithviMedavaram** [SeleniumHQ/selenium-ide#1522]
Selenium IDE browser extension for google chrome requires manifest upgrade to V3. Is there a way to handle this? Or is there a plan to upgrade the manifest version?

**Comment by toddtarsi** [comment]
I'm not planning on it. My plan is basically to make v4 work for my needs and maybe some other people's needs, and que sera sera with v3 imo. If you feel it's very important for it to stay available for your needs, here is the codebase:

https://github.com/SeleniumHQ/selenium-ide/tree/v3

Go nuts

**Comment by toddtarsi** [comment]
I'm closing this issue, as my priority is instead to get v4 functional by January.
