### ISSUE TITLE
Something is wrong with the selenium-side-runner when trying to execute it on a side file : Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by redalucardDev** [SeleniumHQ/selenium-ide#1523]
## 🐛 Bug Report

I am using selenium-side-runner to execute multiple times the same side file. Sometimes it works I have the expected response and sometimes I have an error from selenium-side-runner I don't know why. It seems to be a node error here is the stack trace  : 

`
(/usr/lib/node_modules/selenium-side-runner/node_modules/yargs/yargs.js:38:27)","at Argv (/usr/lib/node_modules/selenium-side-runner/node_modules/yargs/index.js:12:16)","at Object.<anonymous> (/usr/lib/node_modules/selenium-side-runner/node_modules/yargs/index.js:7:1)","at Module._compile (internal/modules/cjs/loader.js:778:30)","at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","at Module.load (internal/modules/cjs/loader.js:653:32)","at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","at Function.Module._load (internal/modules/cjs/loader.js:585:3)","at Module.require (internal/modules/cjs/loader.js:692:17)","at require (internal/modules/cjs/helpers.js:25:18)"],"time":"","message":"Error: ENOENT: no such file or directory,' 
`

I couln't find nothing to explain why I get this error, knowing that it doesn't work all the time.

I suspect that it's occurs because of concurrent access. Could you please help me ? 

## To Reproduce

Call multiple simultanous times this command : 
`
selenium-side-runner --proxy-type=manual --proxy-options="http=XXX.XXX.XXX:XX" XXX.side
`
## Expected behavior

Side file must be read and located but in my case it seems that it happen before trying to locate and execute the file 

## Environment

OS:  Ubuntu 18.04.5
Selenium SIDE Runner Version: 3.17.0

Node version:  v10.24.1

Browser:
Browser Version: Google Chrome 92.0.4515.107

**Comment by toddtarsi** [comment]
Unfortunately, I'm not really supporting v3 anymore. However, if the issue exists in v4, I will triage there.
