### ISSUE TITLE
find element from label

### ISSUE THREAD

**Issue by giuliohome** [SeleniumHQ/selenium-ide#1525]
## 🚀 Find element for humans: by label

When I record a click on a button, I want to find it by looking for the label text. 
This is what a human being actually does.

## Motivation

Modern frameworks like React or Angular are based on components and state function models, thier styles don't provide ids to html elements or otherwise those ids are destryed and created again during effects and transitions.

## Example

This is an example of what I want to do in this enhancemet.
The point of intervention could be e.g. [here where](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/record-handlers.ts#L119) the Playback window subscribes the click event handler to build the “low code” from the event target (seen as a html element) or more in-depth [where a locator](https://github.com/SeleniumHQ/selenium-ide/blob/74fa23e5a7db0ea1b95917e7901cc59367a37e96/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/locator-builders.ts#L64) is obtained from a builder.

For example, imagine a modern material design like this datepicker 

```python
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://mui.com/x/react-date-pickers/getting-started/')
```

the process of finding the element to click (I'd say "find element for humans" https://twitter.com/giuliohome_2019/status/1576301123828187137 ... ) should be:

1.  find the label by looking at the label text
2. **find the id of the html element from the label `for` attribute!**
3. finally click on the element found by id

```python
def find_element_by_label(self, label_txt):
  found_label = self.driver.find_element(by = By.XPath, value = ".//label[text()='{label_txt}'])
  found_key = found_label.get_attribute('for') # my copyright
  return self.driver.find_element(by=By.ID, value = found_key)
```

the opposite during the **recording** process

1. the locator builder gets the id of the element from the event target of the event handler (this is the current as-is situation)
2. now check if there is a label for that element (i.e. a label having a `for` attribute with such an id, see the xpath code below)!
3. define a new builder locator that runs the above said `find_element_by_label`

the point 2 corresponds to something like the following

```python
reverse_for = driver.find_element('xpath',f'//label[@for={mykey}]')
```

A complete snippet of this eaxample's process, back and forward

```python
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://mui.com/x/react-date-pickers/getting-started/')
labelDesktop = driver.find_element("xpath", value = '//label[text()="Date desktop"]')
mykey = labelDesktop.get_attribute('for') # ":Rjaa7albjpd6:"
reverse_for = driver.find_element('xpath',f'//label[@for={mykey}]')
print(reverse_for.text) # "Date desktop"
```

**Comment by toddtarsi** [comment]
@giuliohome - This is a good direction of conversation 😄. So, we basically wrap this repo to do our element attribute recording.

https://www.npmjs.com/package/@medv/finder

This issue talks about what we'd want.

https://github.com/antonmedv/finder/issues/33


We'd want to expose those controls in the IDE so you can prioritize labels over ids over data attributes or whatever. My organization really uses data selectors, so I have some personal skin in this feature too.

**Comment by toddtarsi** [comment]
Oh wait! I see what you're saying. There's already some hooks to do this in IDE. Well, maybe we can float out those preferredOrder controls first and get more granular with the medv stuff later!

**Comment by giuliohome** [comment]
> ... There's already some hooks to do this in IDE. ...

While the IDE is already working fine with things like menu items

![immagine](https://user-images.githubusercontent.com/3272563/193794992-d545cee3-dea5-45ca-bb77-7ddb0fe4af26.png)

where I already have the possibility to select a human (=description based) click

![immagine](https://user-images.githubusercontent.com/3272563/193795167-a06403e0-d214-4637-af67-5b39787602dd.png)

among other possible choices

![immagine](https://user-images.githubusercontent.com/3272563/193795213-abd57898-1a47-4c60-b4e7-461e3a0fd36e.png)

for other components like this date picker 

![immagine](https://user-images.githubusercontent.com/3272563/193795497-9e0dc2a6-484b-40c1-a015-356399686677.png)

it does not propose 

![immagine](https://user-images.githubusercontent.com/3272563/193795820-02ca592c-8d8a-4d09-ba88-2cf6afe429d3.png)

what I would wish... 

hence somehow I  have to manually manage to obtain a key `xpath=.//label[text()='From Ref. Date']@for` which would be super cool if automatic.

![immagine](https://user-images.githubusercontent.com/3272563/193821095-b7df795a-cde8-471e-88b2-b33c19db067e.png)

Ok, I guess I'll have to fork this repository and proceed on my own, maybe...

**Comment by toddtarsi** [comment]
I don't think you should need to fork this repository. I think its more of me having some understanding challenges that I'll need your help to get through. So, let me try to understand. You want a selector builder permutation for 'input' type elements that uses this xpath shape?

```
xpath=.//label[text()='{{Expected Text}}']@for
```

And furthermore, in your case, you wish that this selector also had very high priority right?

When I said 'is supported', I did not mean done-not-touching-is-supported. I meant 'is supported' like there are some starting things that we can use to get what you're maybe-looking-for more easily. I really appreciate your help here, and your analysis of the code is very apt. Working together on this tool will benefit both of us!

**Comment by toddtarsi** [comment]
Also, we put out binaries if you want to ever use it without having to build:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.9

**Comment by giuliohome** [comment]
Great! Thank you for your support! 
I am aftraid this change could be difficult because I think the recorder won't find the "expected text" immediately in the html element in the event target when a user click on the required input through the recorder. 
And also somehow we should produce a "click" or a "type" step with the "id" target read from the previous "for" attribute... 
I don't know if there is an easy way to implement it. I hope we can find a quick solution, perhaps those "starting things that we can use", as you have written.

**Comment by toddtarsi** [comment]
@giuliohome - There might be some trickiness to this for sure, but I'm confident we could get there with a locator builder, probably called something like "xpath:label" perhaps?

https://github.com/SeleniumHQ/selenium-ide/blob/c1e22c5d7283164332212811f108eecaa1528be7/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/locator-builders.ts#L491

**Comment by toddtarsi** [comment]
Also, if you ever need to modify this logic to generate commands in a very vendor-specific or like fork-necessary method, I'd strongly advocate checking out our plugin architecture! With how we sandbox things, your plugin can actually get required in the recording code itself and modify commands as they go through the wire:

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-plugin-example/src/preload/index.ts#L12

This might not look that powerful, but the event argument here is the actual HTML event, so you can do like checks if its a draft-js contenteditable or whatever and change the command during record to be what you want.

**Comment by giuliohome** [comment]
Correct! I agree, I'll try to write it in the next days

**Comment by giuliohome** [comment]
OK. since (I've also have to develop a microservice for my company and) I don't want to leave this too broad and open at the beginning but I would prefer to identify a first step and simplify it, so it can be done (like a first MVP or a first Sprint in Agile), let me say the following, by comparing v3 "as it is" and v4 "to-be" for this enhancement's first step.

At the moment in v3, if I'm recording the click on a button, I can find among other selectors (unfortunately with low priority, but let's ignore the priority atm)

```js
xpath=(//button[@type='button'])[5]
```

maybe the requirement here is to get instead, when a text (e.g. Save) is in the button: 

```js
xpath=(//button[@type='button'  and text() = 'Save' ] ) 
```

(with [1] omitted since it is no longer needed)
That would help a lot because a user perhaps doesn't know the syntax for `and` or `text()` and - last but not least - she/he sees something like 'SAVE' in the UI (for example) and could likely fail to write the correct text 'Save' where upper vs lower case matters.

What do you think about this approach and this definition? Does it sound like a good "User Story" for you?

The goal is that `and text() = 'Save' ` is (IMHO) much more robust and human readable and maintainable than` [5]`

**Comment by toddtarsi** [comment]
I think that sounds great! Please let me know how I can help, and I'll do my best. Also, I agree, text content is a much more sturdy and intuitive selector than an element offset. Of course, if multiple buttons on the page say "Save", we'll need that offset again, but that's pretty edge case.

**Comment by giuliohome** [comment]
> At the moment in v3, if I'm recording the click on a button, I can find among other selectors (unfortunately with low priority, but let's ignore the priority atm)
> 
> ```js
> xpath=(//button[@type='button'])[5]
> ```
> 
> maybe the requirement here is to get instead, when a text (e.g. Save) is in the button:
> 
> ```js
> xpath=(//button[@type='button'  and text() = 'Save' ] ) 
> ```
> 

Here we go, I'm in debug, the locator is `xpath:attributes` and the code is here

https://github.com/SeleniumHQ/selenium-ide/blob/c1e22c5d7283164332212811f108eecaa1528be7/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/locator-builders.ts#L384-L392

At first sight what I am talking about are the **PREFERRED_ATTRIBUTES** 

```ts
  const PREFERRED_ATTRIBUTES = [
    'id',
    'name',
    'value',
    'type',
    'action',
    'onclick',
  ]

```

We're getting only the `type` but we want the `textContent` **too**!

First, I'm going to **add the new attribute** in the code, then `pnpm build `and `start` again my debug...

(I know, I'm slow....   ¯\\\_(ツ)_/¯  )

**Comment by toddtarsi** [comment]
That sounds awesome, and not slow at all! I haven't been able to touch the code in about a week, since my toddler is going through a bit of a phase and such. Way faster than I can go right now!

If that locator is giving you guff, feel free to just add a new locator builder specifically for this thing as well. No pressure either way! I'm sure what you're doing here will only add value 😄

**Comment by giuliohome** [comment]
No worries, I prefer to complete my debug because otherwise I get lost when I start again.
The point is that it is not properly an "attribute" but I'm going to modify the function

https://github.com/SeleniumHQ/selenium-ide/blob/c1e22c5d7283164332212811f108eecaa1528be7/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/locator-builders.ts#L395-L410

to manage it like it was an attribute...

We'll see if my changes are too ugly or acceptable... soon

Thanks for your kind support in the meantime!

**Comment by giuliohome** [comment]
Yeah, I see the alternative I wanted here below, when I debug my code

![image](https://user-images.githubusercontent.com/3272563/194162566-4d60cbb0-298b-4e6e-b327-fbab1afaac9a.png)

I'll prepare a little PR with these few changes

**Comment by toddtarsi** [comment]
Nice! Can you do me a favor and increment the alpha version in packages/selenium-ide/package.json? I think it should be up to like 4.0.0-alpha.10 or so. If you do that, the CI will spit out a new binary with your changes when we merge em 👍

**Comment by giuliohome** [comment]
Of course we can reopen this - or a new one, more specific  - to implement next steps and new locators.
I'm still considering the original idea of adding the new "xpath:label" builder (*): I will return to this asap (on the other hand I'm also thinking about a default, initial control+a for send keys).

(*) I'm afraid this requires a change in https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/third-party/find-element.js and I assume it means opening a corresponding issue in https://github.com/google/wicked-good-xpath or forking it ? Or otherwise (maybe more practical but still quite elaborated) it has to be implemented here by producing two commands ("store attribute" + "send keys") for one click... Or one has to find a (single, well defined) xpath locator with the current third-party find-element... but atm I'm still unable to figure it out because it should be a sort of nested `xpath=.//input[id=(.//label[text()='To Ref. Date'][1]/@for)]` which doesn't work afaik. Registering "two commands for one click" is what I would choose now, if I had to: unfortunately, by definition, _it's not doable as a single-command alternative like all the other locator builders_, hence maybe it's just not feasible (without touching also the UI etc...).

BTW, FYI: A manual way to fill a material design datepicker by label:
- stop the recorder at the relevant step and manually add a new step 
- start with a send keys command and use the automatic "element locator" feature, type a valid value in the datepicker to unhide the label and click the label to find the xpath (something like `@xpath=//label[contains(.,'To Ref. Date')]`)
- the above element is not interactable so...
- change the command into a store attribute and manually insert and complete the above said xpath with a final `@for`
- add another, following send keys command with target `id=${the_above_key}` and a value... 

I guess we can close it this way. On the other hand, the enhancement already done addresses the situation of a button-like element and it's described [here in my previous comment](https://github.com/SeleniumHQ/selenium-ide/issues/1525#issuecomment-1268050709) and it's fully integrated in the automatic recording as one of the usual locator builders.
