### ISSUE TITLE
seleniumide v4 cannot load iframe

### ISSUE THREAD

**Issue by lzt007** [SeleniumHQ/selenium-ide#1533]
## 🐛 Bug Report

I have an old website with some unsafe ifame in it.
The iframe was like（its a website for internal use which I cant make screenshot or provide a url for testing）：

<iframe id="rightMain" src="role?session_id=xxxx-xxxxxxxxxxxxxx&key1=value1&key2=value2"> document </iframe>

The website shows well on my chrome 96.0.4664.110，but when i'm using selenniumide，the page where iframe should be load shows just a white page.The document in iframe was nothing when I check the elements in Chrome DevTools

I,m guessing maybe there has some new security settings in new version of chromium which selemiumide was built with that block the iframe for some reason.

To Reproduce

## Expected behavior
1.open seleniumide
2.open a page with iframe

## Environment
Windows 10
selenium ide 4.0.0 alpha.10

Browser:
the browser built in selenium ide

**Comment by toddtarsi** [comment]
There is an issue in your report, namely that we have a test page for iframes we use coming out of w3c here:

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/tests/examples/frames.side

It's passing just fine in the IDE. To understand your issue, I'm going to need a working side file. Thanks!

**Comment by toddtarsi** [comment]
Feel free to re-open this if you have a reproducing side file.
