### ISSUE TITLE
Bug: Project cannot load without file extension.

### ISSUE THREAD

**Issue by shiningbridge** [SeleniumHQ/selenium-ide#1534]
## 🐛 Bug Report

Window Edge browser, Selenium IDE 3.17
cannot load project saved without file extension.
Error when load.
"
Error migrating project
Unknown file was received
"

## To Reproduce

save project as "saved_project" for example it has no option to choose Selenium format or anything other than "ALLFILE".

load the same file brings error:
“
Error migrating project
Unknown file was received
”

## Expected behavior

load it

## Project file reproducing this issue (highly encouraged)

/

## Environment

OS: Windows 10
Selenium IDE Version:  3.17
Selenium SIDE Runner Version:  /
Node version: /
Browser: Edge
Browser Version: Version 106.0.1370.34 (Official build) (64-bit)

**Comment by shiningbridge** [comment]
Remedy is clear. 
Just rename file with ".side" extension. 

Reference: https://github.com/SeleniumHQ/selenium-ide/issues/861

**Comment by toddtarsi** [comment]
Nice fix
