### ISSUE TITLE
Selenium Side Runner will not run simple .side file

### ISSUE THREAD

**Issue by jezahl** [SeleniumHQ/selenium-ide#1542]
## 🐛 Bug Report

I've created a simple .side file in Chrome (on Windows), and am trying to run this using the side runner on linux. I get this error:-

[root@XTEST selenium-side-runner]# selenium-side-runner  ~sysadmin/simple.side
 FAIL  dist/main.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /usr/local/lib/node_modules/selenium-side-runner/node_modules/@seleniumhq/side-runtime/dist/playback.js:319
                    playTo?.command === this.currentExecutingNode.command.id) {
                           ^

    SyntaxError: Unexpected token .

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@seleniumhq/side-runtime/src/index.ts:18:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.458 s
Ran all test suites within paths "/usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js".

## To Reproduce

selenium-side-runner  ~sysadmin/simple.side

## Expected behavior

The test should run

## Project file reproducing this issue (highly encouraged)

{
  "id": "8aa4dcfa-5d91-434d-8124-5fd22c281414",
  "version": "2.0",
  "name": "simple",
  "url": "",
  "tests": [{
    "id": "afab4ac2-cd5e-4af3-88d1-3e250f8e1417",
    "name": "Test1",
    "commands": [{
      "id": "c0d2201d-370a-4711-a0e9-c99f216397f4",
      "comment": "",
      "command": "echo",
      "target": "Hello There",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "4708e445-1bbb-4731-a583-44d0573a64a8",
    "name": "Test Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["afab4ac2-cd5e-4af3-88d1-3e250f8e1417"]
  }],
  "urls": [],
  "plugins": []
}

## Environment

OS: Windows 11 for IDE, RHEL8 for side-runner
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0
Node version: 10.24
Browser: Chrome
Browser Version: 106.0.5249.119

**Comment by toddtarsi** [comment]
Yes, you'll need to come up Node versions. We don't support 10 on the latest. If you see anywhere where this is indicated, let me know and I'll update the documentation. Right now I think we support 14, 16, and 18 although I haven't tested on 18:

https://github.com/nodejs/Release

**Comment by toddtarsi** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility

**Comment by jezahl** [comment]
Oh! Thanks for the quick response. I'll get a newer version

**Comment by toddtarsi** [comment]
@jezahl - I re-opened this just for transparency. If updating resolves your issues, please close this. Thank you.

**Comment by jezahl** [comment]
Issue resolved with version 16 :)
