### ISSUE TITLE
Side runner doesn't support Echo command?

### ISSUE THREAD

**Issue by jezahl** [SeleniumHQ/selenium-ide#1548]
**Bug Report**

A simple .side file with an echo command doesn't run in side-runner:-

#>selenium-side-runner Simple.side
info: Running test Untitled
info: Building driver for chrome

 RUNS  ../../../../AppData/Roaming/npm/node_modules/selenium-side-runner/dist/main.test.js
info: Driver has been built for chrome
  console.warn
    Unexpected error occured during command: echo-Hello world!- retrying...

      at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:186:15)
      at CommandNode.retryCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:144:12)
      at CommandNode._executeCoreCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:156:12)

  console.error
    Cannot create property 'Symbol(level)' on string 'echo: Hello world!'

      at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:192:17)
      at CommandNode.retryCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:144:12)
      at CommandNode._executeCoreCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:156:12)

 RUNS  ../../../../AppData/Roaming/npm/node_modules/selenium-side-runner/dist/main.test.js
  console.error
    Command failure: echo-Hello world!-

      at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:197:15)
      at CommandNode.retryCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:144:12)

info: Finished test Untitled Failure
warn: Completed with failure

**To Reproduce**
selenium-side-runner simple.side

**Expected behavior**
The test should run

**Project file reproducing this issue (highly encouraged)**
{
  "id": "0b92c09c-f225-4b25-8f4c-c57b15e9a79c",
  "version": "2.0",
  "name": "Simple",
  "url": "",
  "tests": [{
    "id": "b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f",
    "name": "Untitled",
    "commands": [{
      "id": "6067c501-1f4e-4016-9698-9c57685ab0ad",
      "comment": "",
      "command": "echo",
      "target": "Hello world!",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "b252fa97-3a81-43f0-bc31-cecfd20aa525",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f"]
  }],
  "urls": [],
  "plugins": []
}

**Environment**
OS: Windows 11 for IDE and side-runner
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version: 4.0.0
Node version: 16.18.0
Browser: Chrome
Browser Version: 106.0.5249.119

**Comment by toddtarsi** [comment]
Oh, echo was a command. Hm. Okay, I'm sure this is important for debugging. Thank you for making an issue and reproducing side file. I'll take a look at it when I can.

**Comment by toddtarsi** [comment]
@jezahl - This should not be an issue in v4 I believe

**Comment by jezahl** [comment]
Still doesn't work for me

![image](https://user-images.githubusercontent.com/22910260/200277715-5598421a-04d3-4324-b6fc-3631a50ccd53.png)

**Comment by toddtarsi** [comment]
Ah, I see the issue from that error. That's an easy fix

**Comment by toddtarsi** [comment]
@jezahl - Fix is going out now, alpha.24 will be out in like 5 minutes.

**Comment by jezahl** [comment]
Slightly different, but still fails

![image](https://user-images.githubusercontent.com/22910260/200320070-ca1d73cb-992d-4faa-84f6-43578e43e737.png)

**Comment by toddtarsi** [comment]
@jezahl - Are you sure you're on alpha.24 right now?

**Comment by jezahl** [comment]
Yep :-

![image](https://user-images.githubusercontent.com/22910260/200333315-347365fe-0a8d-4925-9460-18bdaf65d3b4.png)

**Comment by jezahl** [comment]
Thanks @toddtarsi Working now
