### ISSUE TITLE
side runner doesn't respect the base-url option

### ISSUE THREAD

**Issue by jezahl** [SeleniumHQ/selenium-ide#1549]
## 🐛 Bug Report

The base-url option doesn't seem to have any effect on script execution

## To Reproduce

selenium-side-runner --base-url https://google.co.uk
or
selenium-side-runner --base-url https://google.com

A browser should open to whichever url I run the script with, but instead it always opens the Playback URL from the .side file (i.e. google.co.uk

## Expected behavior

The correct site should open

## Project file reproducing this issue (highly encouraged)

{
  "id": "0b92c09c-f225-4b25-8f4c-c57b15e9a79c",
  "version": "2.0",
  "name": "Simple",
  "url": "https://google.co.uk",
  "tests": [{
    "id": "b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f",
    "name": "Untitled",
    "commands": [{
      "id": "6067c501-1f4e-4016-9698-9c57685ab0ad",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "b252fa97-3a81-43f0-bc31-cecfd20aa525",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f"]
  }],
  "urls": ["https://google.com/", "https://google.co.uk/"],
  "plugins": []
}

## Environment
OS: Windows 11 for IDE and side-runner
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version: 4.0.0-alpha.16
Node version: 16.18.0
Browser: Chrome
Browser Version: 106.0.5249.119

**Comment by fmrahman** [comment]
Definitely need this old feature.

**Comment by toddtarsi** [comment]
@jezahl @fmrahman - Good call, pushing out a fix for this shortly. Please test and let me know what you see, thanks!

**Comment by jezahl** [comment]
@toddtarsi This still doesn't work for me

Update: My bad - yes this is working now - thanks for the fix @toddtarsi

**Comment by fmrahman** [comment]
@jezahl It's working for me. I verified in 4.0.0-alpha.25 version.
Thanks much @toddtarsi for the fix.

**Comment by jezahl** [comment]
Thanks @toddtarsi
