### ISSUE TITLE
Unable to execute selenium ide tests through terminal

### ISSUE THREAD

**Issue by prashanth-sams** [SeleniumHQ/selenium-ide#155]
Here, `google.side` is the testcase that I exported from the latest Selenium-IDE. 

I tried executing tests from terminal in both ways; but it fail to work. Is there any configuration that I have to make it locally; I just installed selenium-side-runner library using npm and thats it.

`selenium-side-runner -c "browserName=chrome platform=MAC"`
`selenium-side-runner -c "browserName=chrome platform=MAC" google.side`

![screen shot 2018-04-16 at 12 25 48 pm](https://user-images.githubusercontent.com/2948696/38804334-177b34d0-4183-11e8-9dfa-f25a3cbfae50.png)
![screen shot 2018-04-16 at 12 26 13 pm](https://user-images.githubusercontent.com/2948696/38804333-1741cab0-4183-11e8-9d9d-5050399f33e5.png)

**Comment by corevo** [comment]
What version of `selenium-side-runner` are you using? make sure it is `0.3.0`.  
You can check by running `selenium-side-runner --version`.  
In your case you don't need to pass any arguments, running `selenium-side-runner` alone will suffice.

**Comment by prashanth-sams** [comment]
@corevo I pulled the library yesterday and it was `0.2.0`; and the above error is gone after updating the lib with latest `0.3.0`version. However, I face another issue; here it is,

![screen shot 2018-04-16 at 2 50 42 pm](https://user-images.githubusercontent.com/2948696/38805125-c4f61308-4185-11e8-829a-a4d9b95fd74f.png)

**Comment by corevo** [comment]
Yes, it's an issue that I fixed (partially).  
During runtime it creates a folder to place the test case files, just delete that folder and run it again.

**Comment by prashanth-sams** [comment]
@corevo yea, I did it; but it's another issue in looping now..

![screen shot 2018-04-16 at 2 56 55 pm](https://user-images.githubusercontent.com/2948696/38805325-7455d6a8-4186-11e8-8856-075b243c29e8.png)

**Comment by corevo** [comment]
Did you save the project with the new beta?

**Comment by prashanth-sams** [comment]
@corevo The chrome extension still pointing v.3.0.1
https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd

![screen shot 2018-04-16 at 5 37 05 pm](https://user-images.githubusercontent.com/2948696/38812831-685c4c8e-419e-11e8-9b11-fbfefe441e2a.png)

**Comment by corevo** [comment]
You will have to install the beta, get it from [here](https://github.com/SeleniumHQ/selenium-ide/releases/download/v3.1.0-beta.3/selenium-ide.zip) and install it as [developer](https://developer.chrome.com/extensions/getstarted#unpacked)

**Comment by prashanth-sams** [comment]
@corevo yea, it's good now :)

**Comment by corevo** [comment]
np, closing.

**Comment by prashanth-sams** [comment]
@Jongkeun I believe `selenium-side-runner` is more than enough to run tests; browser and platform CLI is an optional one

**Comment by corevo** [comment]
@Jongkeun You'll have to install it globally through `npm` or download from [here](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.1.0-beta.3) for your OS.  
Then just make sure you have a `.side` file in the same folder so it can pick it up.  
As a side note, in **beta 4** you'll have to specify the projects you want to run.

**Comment by Jongkeun** [comment]
Oh Thanks so much @prashanth-sams , @corevo .
I will try to use this.

**Comment by prashanth-sams** [comment]
@corevo @Jongkeun I did some documentation on how to config Selenium IDE for the first time; hope it will be helpful.
https://devopsqa.wordpress.com/2018/04/17/selenium-ide/

**Comment by corevo** [comment]
Awesome ❤️!  
Just as a heads up, I'm planning on changing the runners cli commands a bit, you'll have to pass the projects you want to run, just like you assumed, seems more people tend to think that way.  
It'll work like so
`selenium-side-runner project.side`
or you could also glob
`selenium-side-runner *.side`  
Nothing is final, I'll write the final API, or you could help me do it, [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-side-runner/README.md)

**Comment by prashanth-sams** [comment]
@corevo you did an awesome job; sure, I'll help you update the doc :)
