### ISSUE TITLE
Proxy Options not working in Selenium Side Runner ver 4.0.0-alpha.28

### ISSUE THREAD

**Issue by NikhilHedau** [SeleniumHQ/selenium-ide#1554]
## 🐛 Bug Report

I am getting  operation timeout while executing open command  with proxy to run a side file. The side file is running fine with selenium-side-runner v3.17.0. Also,  as per the debug logs the proxy options list is empty in ver 4.0.0-alpha.28.  PFA logs for your reference.

## To Reproduce

selenium-side-runner defaultSuite.side -c "browserName=chrome" --timeout 30000 --proxy-type=manual --proxy-options="http=proxy1 https=proxy2 bypass=[abc.com]" --debug 

## Expected behavior

Tests should pass

## Project file reproducing this issue (highly encouraged)

{
    "id": "9e77234d-fd07-473d-adbe-d1c5e859536f",
    "version": "2.0",
    "name": "Test",
    "url": "https://www.martinfowler.com",
    "tests": [
        {
             "id": "18b9e884-a887-44f9-b1ec-0e1d0adb2d5a",
            "name": "openAndClickLink2",
            "commands": [
                {
                    "comment": "",
                    "command": "echo",
                    "target": "Command 1",
                    "targets": [],
                    "value": "",
                    "id": "218aaa0e-0823-460f-874d-7df67d0367a7"
                },
                {
                    "id": "828276fc-7351-481e-b6dd-eac0e6e5557d",
                    "comment": "",
                    "command": "open",
                    "target": "/",
                    "targets": [],
                    "value": ""
                },
                {
                    "comment": "",
                    "command": "echo",
                    "target": "Command 2",
                    "targets": [],
                    "value": "",
                    "id": "38505a74-50ff-4597-bea4-527aa5b5ea96"
                },
                {
                    "id": "ebd3d474-83eb-4f13-aef3-c16deeae4325",
                    "comment": "",
                    "command": "click",
                    "target": "linkText=Refactoring",
                    "targets": [
                        [
                            "linkText=Refactoring",
                            "linkText"
                        ],
                        [
                            "css=li:nth-child(1) > a",
                            "css:finder"
                        ],
                        [
                            "xpath=//a[contains(text(),'Refactoring')]",
                            "xpath:link"
                        ],
                        [
                            "xpath=//header[@id='banner']/nav/ul/li/a",
                            "xpath:idRelative"
                        ],
                        [
                            "xpath=//a[contains(@href, 'https://refactoring.com')]",
                            "xpath:href"
                        ],
                        [
                            "xpath=//li/a",
                            "xpath:position"
                        ],
                        [
                            "xpath=//a[contains(.,'Refactoring')]",
                            "xpath:innerText"
                        ]
                    ],
                    "value": ""
                },
                {
                    "comment": "",
                    "command": "pause",
                    "target": "5000",
                    "targets": [],
                    "value": "",
                    "id": "df9394fb-ea92-474a-8315-793809046e84"
                }
            ]
        }
    ],
    "suites": [
        {
            "id": "24c4c2f6-3e31-43ec-82bf-741c66db31f2",
            "name": "Default Suite",
            "persistSession": false,
            "parallel": false,
            "timeout": 300,
            "tests": [
                "18b9e884-a887-44f9-b1ec-0e1d0adb2d5a"
            ]
        }
    ],
    "urls": [
        "https://www.martinfowler.com/"
    ],
    "plugins": []
}

## Environment

OS: Linux
Selenium IDE Version:  NA
Selenium SIDE Runner Version:  4.0.0-alpha.28
Node version: 16.18.0
Browser: Chrome
Browser Version: 96.0.4664.110
Chrome Driver Version : 96.0.4664.45

Logs:
[LogsVer4.0.0-alpha.28.txt](https://github.com/SeleniumHQ/selenium-ide/files/9990635/LogsVer4.0.0-alpha.28.txt)

**Comment by anoopadvaitha** [comment]
+1 facing same issue !

**Comment by toddtarsi** [comment]
@anoopadvaitha @NikhilHedau - Releasing a fix for this now (alpha.30), appears to properly pass through proxy options to the driver. Please re-open if you're still encountering this issue.
