### ISSUE TITLE
side-runner option --output-directory not working in v4

### ISSUE THREAD

**Issue by karasma3** [SeleniumHQ/selenium-ide#1555]
## 🐛 Bug Report

--output-directory option does not work on v4

In v3 it worked and it created .json file with test output.... now my directory is empty

## To Reproduce

`--output-directory=results`

## Expected behavior

.json file with output of the tests and directory `results` is not empty

## Project file reproducing this issue (highly encouraged)

any...
{
  "id": "79701be8-6f1b-4fc6-abdf-0ecdb69e66f1",
  "version": "2.0",
  "name": "untitled",
  "url": "http://localhost:8082/",
  "tests": [{
    "id": "af317391-d1c6-448a-9553-8d2a7bbb1f62",
    "name": "Untitled",
    "commands": [{
      "id": "dfb15256-15cd-4852-8b21-e5205be93bb4",
      "comment": "",
      "command": "open",
      "target": "/app",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "9cdd7442-0870-4d6a-939c-ba2abfb70c61",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["af317391-d1c6-448a-9553-8d2a7bbb1f62"]
  }],
  "urls": ["http://localhost:8080/", "http://localhost:8082/"],
  "plugins": []
}

## Environment

OS: Windows 10 Pro
Selenium SIDE Runner Version: 4.0.0-alpha-15
Node version: 16.14
Browser: Google Chrome
Browser Version: Chrome 105.0.5195.127 (64-bit)

**Comment by anoopadvaitha** [comment]
+1 facing same issue.

**Comment by toddtarsi** [comment]
@karasma3 - Are you using the jest-junit test reporter?

**Comment by karasma3** [comment]
@toddtarsi i was using `--output-format=jest`

**Comment by jamnum1SR** [comment]
Seeing the same here

**Comment by jamnum1SR** [comment]
Same here

**Comment by wilbur-sun** [comment]
"-o results" fails on version 4.0.0-alpha.40, it's not creating the log file before trying to open it.

Error: ENOENT: no such file or directory, open 'C:\Workspace\Selenium\results\results-2023-03-04T01:08:39.664Z.json'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)

**Comment by toddtarsi** [comment]
@wilbur-sun - Issue is resolved, thanks for letting me know.

To everyone else in this channel, sorry about the delays here. There is an escape argument 'jestOptions' or something like that which should provide you the escape hatches to do what you need to.

**Comment by anoopadvaitha** [comment]
Still having same issues in Windows
Using Selenium-side-runner version 4.0.0-alpha.41

node:internal/fs/utils:347

    throw err;
    ^

Error: ENOENT: no such file or directory, open 'result\results-2023-03-06T14:45:10.021Z.json'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at Object.<anonymous> (C:\Users\{username}\AppData\Roaming\npm\node_modules\selenium-side-runner\dist\bin.js:127:22)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'result\\results-2023-03-06T14:45:10.021Z.json'
}

**Comment by toddtarsi** [comment]
@anoopadvaitha - Are you trying this on v41 of the side-runner?

**Comment by anoopadvaitha** [comment]
Yes on Selenium-side-runner version 4.0.0-alpha.41

**Comment by anoopadvaitha** [comment]
The issue is with the file name results-2023-03-06T14:45:10.021Z.json which is not accepted by Windows.
Basically we cannot use characted **:** in the file name on Windows.

**Comment by toddtarsi** [comment]
OHH

**Comment by toddtarsi** [comment]
Okay, well I can resolve that tonight. I gotta do some work for now. Thanks for explaining

**Comment by anoopadvaitha** [comment]
Thank you so much for quick response !

**Comment by toddtarsi** [comment]
@anoopadvaitha - Okay, I am just converting the colons to hyphens. Let me know if that works. Thanks!

**Comment by zielik909** [comment]
Version alpha.42. Issue is in double dot (:) in the name of file. windows doesn't allow that mark.

![image](https://user-images.githubusercontent.com/42648719/223422245-ef7dd0d1-d93d-4309-8fe5-f68986752d8c.png)

**Comment by zcai2023** [comment]
@toddtarsi Just wondering when your fix will be picked up? As of now, this issue is still there (see the screenshot below)
![Capture3](https://user-images.githubusercontent.com/127338702/223793760-076c336b-aa31-4515-92c3-b6844feaba69.PNG)

**Comment by toddtarsi** [comment]
@zcai2023 - oh shoot, I thought it already would be. This commit adjusts that filename and updates the version, so it should have been updated in the ci release

**Comment by zcai2023** [comment]
@toddtarsi Looks like the build failed?
![Capture](https://user-images.githubusercontent.com/127338702/224038132-36fe86c2-90a5-4bc7-9abb-397dd47f094a.PNG)

**Comment by toddtarsi** [comment]
@zcai2023 - I appreciate you looking more closely, but it shouldn't affect it in this case. This failure is coming from the new version of the IDE getting built, which is downstream from releasing all the new versions of the packages on npm.

**Comment by zcai2023** [comment]
@toddtarsi Thank you for looking into this and sharing your findings. Wondering how quickly this downstream build issue can be resolved to try out the --output-directory option.

**Comment by toddtarsi** [comment]
It was just a little intermittency in the network. Nothing to fix. I took a peek and I had missed a little bit of wet code. Dried it up slightly. Fix will be out in 15 or less

**Comment by toddtarsi** [comment]
@zcai2023 - Just noting, this would be on .43

**Comment by zcai2023** [comment]
@toddtarsi Thank you! I updated to .43 and was able to generate a json format result file successfully. Is it the expected format, a super long line in Notepad ++ (see attached screenshot), instead of multiple lines?
![Capture](https://user-images.githubusercontent.com/127338702/224128046-c6aa52f6-8b21-42fe-a1fa-74376fa1dd72.PNG)

**Comment by toddtarsi** [comment]
@zcai2023 - I would assume so. This tries to hew very close to the jest options. So supplying an output directory actually does like `-json -output [some-path-with-timestamped-results]`. So I actually expose a flag called jestOptions or jest-options or something like that. It lets you pass in a string with whatever you want to actually do with Jest. People are always talking about this output format or that, and I don't want that to be a side-runner problem, so I would recommend reading a bit more about jest, finding your options you want for your desired output format, and supplying those cli options directly.

**Comment by zcai2023** [comment]
@toddtarsi I see...thanks for pointing out this direction. Going forward, maybe the official site https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner#specify-a-default-configuration can updated with this info.
