### ISSUE TITLE
Operation timed out! with Proxy Options in selenium side runner version 4.0.0-alpha.31

### ISSUE THREAD

**Issue by NikhilHedau** [SeleniumHQ/selenium-ide#1556]
## 🐛 Bug Report

I am getting Operation timed out! with proxy options  while running a simple side file. As per the debug logs, the execution of the commands is successfull. The test is running successfully without proxy options. 
Link to previous issue with proxy options(#1554)

## To Reproduce

selenium-side-runner -c "browserName=chrome" openAndClickLink2.side --proxy-type=manual --proxy-options="http=proxy1 https=proxy2 bypass=[abc.com]" --debug

## Expected behavior
Tests should pass
## Project file reproducing this issue (highly encouraged)

{
  "id": "9e77234d-fd07-473d-adbe-d1c5e859536f",
  "version": "2.0",
  "name": "Test",
  "url": "https://www.martinfowler.com",
  "tests": [{
    "id": "18b9e884-a887-44f9-b1ec-0e1d0adb2d5a",
    "name": "openAndClickLink2",
    "commands": [{
      "id": "828276fc-7351-481e-b6dd-eac0e6e5557d",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "ebd3d474-83eb-4f13-aef3-c16deeae4325",
      "comment": "",
      "command": "click",
      "target": "linkText=Refactoring",
      "targets": [
        ["linkText=Refactoring", "linkText"],
        ["css=li:nth-child(1) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Refactoring')]", "xpath:link"],
        ["xpath=//header[@id='banner']/nav/ul/li/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, 'https://refactoring.com')]", "xpath:href"],
        ["xpath=//li/a", "xpath:position"],
        ["xpath=//a[contains(.,'Refactoring')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "24c4c2f6-3e31-43ec-82bf-741c66db31f2",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["18b9e884-a887-44f9-b1ec-0e1d0adb2d5a"]
  }],
  "urls": ["https://www.martinfowler.com/"],
  "plugins": []
}

## Environment
OS: macOS Monterey 12.5, Chip : Apple M1 Pro
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version: 4.0.0-alpha.31
Node version: 16.18.0
Browser: Chrome
Browser Version: 106.0.5249.119 (Official Build) (arm64)
Chrome Driver Version : 106.0.5249.61

**Comment by toddtarsi** [comment]
@NikhilHedau - When you run this, can you specify this flag as well `-D`, this is a startup debug flag and it will log all of your configuration. Can you send that configuration to me? I suspect your capabilities may just be somewhat incompatible with selenium-webdriver v4 and I won't really know what to check, but maybe I can just ask the core team.

**Comment by NikhilHedau** [comment]
@toddtarsi , PFB configuration for the above side file , Please let me know in case you need anything else.
Configuration: {
  baseUrl: '',
  capabilities: {
    browserName: 'chrome',
    proxy: {
      proxyType: 'manual',
      httpProxy: 'http://proxy1:port',
      sslProxy: 'http://proxy1:port',
      noProxy: [Array]
    }
  },
  debug: undefined,
  debugStartup: true,
  filter: '.*',
  force: undefined,
  maxWorkers: 8,
  projects: [ '/dir/selenium_files/openAndClickLink2.side' ],
  proxyOptions: {
    http: 'http://proxy1:port',
    https: 'http://proxy1:port',
    bypass: [ 'abc.co' ]
  },
  proxyType: 'manual',
  runId: '37bcb9924e4cccb3840b0b806123651b',
  path: '/usr/local/lib/node_modules/',
  server: '',
  timeout: 15000
}

**Comment by toddtarsi** [comment]
@NikhilHedau - I checked around the IRC channel, and got this confirmation. Those proxy options look correct according to this spec:

https://www.w3.org/TR/webdriver/#proxy

If you're finding some particular capabilities aren't working correctly, I'd recommend taking the `capabilities` field on that configuration object to selenium core and raising any issues you find there with regard to these settings. Also, if you want to store capabilities to make your command easier in the side runner, you may find a '.side.yml' configuration file helpful.

**Comment by toddtarsi** [comment]
I'm closing this because I think that there are confounding proxy issues here and none of the footprint of how that stuff works is what I understand or am trying to take on here. I'll just pass through your options and I wish you the best of luck.
