### ISSUE TITLE
Context menu in the embedded browser is disabled

### ISSUE THREAD

**Issue by vguntupalli-mn** [SeleniumHQ/selenium-ide#1558]
## 🐛 Bug Report

When recording the user actions, the embedded chrome browser is not showing the context menu. This will lead to missing out recording application context menu actions by the user. 

## To Reproduce

1.) Start recording the user actions
2.) Perform a right click action in the embedded chrome browser

## Expected behavior
Expected to see the chrome's (or application specific) right click menu appearing.

## Actual behavior
Context menu didnt appear

**Comment by toddtarsi** [comment]
Yeah, unfortunately, context menus have to be handcrafted in electron, mostly. We're using electron-context-menu to save some of that work. What options are you most interested in w/r/t a right click in the browser window?

**Comment by vguntupalli-mn** [comment]
Thank you for the quick response. 

If technically feasible, I like to have no interference from SIDE in the embedded browser's event handling of context menu. It is possible that the websites have context menus built (some of our apps for example have it). 

Can you please clarify if this is possible?

**Comment by toddtarsi** [comment]
@vguntupalli-mn - Nope! We're using electron. Electron leaves it to the user to implement their own context menus. So, there is no interference becuase the menus don't exist here. However, if you have common right click interactions you use when writing e2e tests, I can look at exposing those. 😄

**Comment by vguntupalli-mn** [comment]
Thanks @toddtarsi  for the response!!!

So electron nullifies the right click action in the webview rendered chrome. Is that what it is?

**Comment by toddtarsi** [comment]
Yeah, Browsers fill in their own vendor specific logic here. Electron does not. The real thing you want, and probably many other users as well is the ability to drive browsers other than electron in local playback. In order to make that work, I have to change the messaging protocols from Electron stuff to Selenium / builtin w3c stuff. We actually wrote it to be configurable earlier and I broke it while prototyping

**Comment by vguntupalli-mn** [comment]
Wow, good to hear that you have implemented it earlier and with that I hope that it may be possible to bring it back. Is it?

This will open up a great deal of things, as some websites will have user actions at right-click on elements (like our sites have). May I request you to please let me know if you can open it up?

**Comment by toddtarsi** [comment]
I will let you know when I get around to it, but it will be on a timeline of months, not days.

**Comment by vguntupalli-mn** [comment]
Thanks @toddtarsi . Yes,  I Understand. 👍

**Comment by toddtarsi** [comment]
Closing to consolidate to this issue:

https://github.com/SeleniumHQ/selenium-ide/issues/1564

**Comment by vguntupalli-mn** [comment]
Hi @toddtarsi , 

Can you please confirm me if this will be implemented/fixed or has this been already been addressed. 

Best regards,
Vijay

**Comment by toddtarsi** [comment]
@vguntupalli-mn - Yep! Not fixed, just consolidating these issues to one feature request

**Comment by vguntupalli-mn** [comment]
Thanks @toddtarsi , for the clarification. 👍
