### ISSUE TITLE
selenium-side-runner: final timeout message although all commands passed

### ISSUE THREAD

**Issue by rtb2000** [SeleniumHQ/selenium-ide#1559]
## 🐛 Bug Report

Test fails with final "Operation timed out!" messages in summary, without giving more details.
Reason are "pause" commands with >=5000ms
An "Operation timed out!" message is given in the final summary for each of these "pause" commands, although
debug output shows "passed" for all commands of the test.
The same test runs fine if executing in the browser plugin.
Removing the pause commands, or setting them to 1000ms, 'solves' the problem.

## To Reproduce

Add a 10 seconds pause to your test.

## Expected behavior

Test pauses 10 seconds and finally succeeds.

## Project file reproducing this issue (highly encouraged)

attached

## Environment

OS: Linux Mint 21 Vanessa x86_64
Selenium IDE Version:  3.17.4
Selenium SIDE Runner Version:  4.0.0-alpha.32
Node version: 18.12.1
Browser: Firefox
Browser Version: 107.0 (64 bit)
Browser: Chromium
Browser Version: 106.0.5249.119 (64-Bit)
[cmdline.side.gz](https://github.com/SeleniumHQ/selenium-ide/files/10103494/cmdline.side.gz)

**Comment by toddtarsi** [comment]
Oh oops! Yes, this command should not have that implicit timeout. The side-runtime caps commands with an implicit timeout! I never thought about if the wait or pause command was longer. Very good call!

**Comment by rtb2000** [comment]
As a workaround I can just use 10x "pause 1000" instead of 1x "pause 10000" :)

**Comment by toddtarsi** [comment]
@rtb2000 - Thank you for the helpful workaround. Latest version is going out now where this should all be resolved. Feel free to re-open if issue persists, thanks!

**Comment by rtb2000** [comment]
Thank you very much. Works fine :)
