### ISSUE TITLE
Menu Bar in Selenium IDE for Chrome and Firefox

### ISSUE THREAD

**Issue by BasaBike** [SeleniumHQ/selenium-ide#156]
Is there or will there be any menu bar in Selenium IDE for Chrome or Firefox ?

**Comment by corevo** [comment]
Is there a specific reason we should have a menu bar?  
At the moment theres not much to put in there, and there is the Chrome and Firefox menu bar, two of them could be confusing.

**Comment by Amine-70** [comment]
A specific reason may be to convert a selenium test file to html or any other stuff

**Comment by Amine-70** [comment]
Yes, of course. No need for a menu bar if it can be done otherwise.
It's just that I can't see how to "save as..." selenium files with the current Firefox add-on UI.

Regards

**Comment by corevo** [comment]
I understand, in the very near future, we'll add the ability to run the project files from command line.  
After that we'll see what more can be done

**Comment by corevo** [comment]
Closing as there is no response from OP, please comment and I'll reopen the issue.

**Comment by mgdtest** [comment]
is there a workaround for the menu bar? I am trying to edit/save as the recorded script. There is no menu bar or a way to save the script as java or python script that I like to edit recorded script.

**Comment by corevo** [comment]
@mgdtest Duplicate of #131
