### ISSUE TITLE
Selenium IDE v4 IDE Suite Improvements

### ISSUE THREAD

**Issue by clfordhub** [SeleniumHQ/selenium-ide#1560]
Currently, in Selenium IDE v4, a user cannot see which test is running within the suite or which ones have passed/failed when the suite completes.  It would be nice to have a submenu beneath the suite name to show the tests and highlight the test that is running.  Or highlight the test in the suite panel to show which has completed (pass/fail status) and highlight the one currently running.  Having the logging display in the IDE window with the test name would also be helpful, as now the logging is displayed separately, but no test case name is visible to show where the IDE is in the suite.

v3 UX is more user friendly for those who use the record and play functionality IDE for test creation and troubleshooting.

**Comment by toddtarsi** [comment]
@clfordhub - This should be resolved in latest, but feel free to re-open if this isn't the case.
