### ISSUE TITLE
selenium-side-runner error: Operation timed out!

### ISSUE THREAD

**Issue by sergeykatelyna** [SeleniumHQ/selenium-ide#1561]
## 🐛 Bug Report

Hi

Could you please help me out with this odd error? It could be a selenium-side-runner bug.

## Issue description

I always get the following error 3-4 times when running my Selenium IDE scripts via Browserstack:

> Operation timed out!
> 	at Timeout.<anonymous> (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:141:13)

![image](https://user-images.githubusercontent.com/34918999/205455108-ad97cc0a-5d93-40bf-8a56-d604b0356889.png)

As you can see in the screenshot, despite this error, the test passes both in selenium-side-runner and Browserstack. Also, there are no issues when running it via the Chrome extension.

So, the problem should be with selenium-side-runner.

I tried to launch it with `--timeout 60000` option - no luck as well.

The SIDE script:
![image](https://user-images.githubusercontent.com/34918999/205455147-7dd9e5cd-77c2-4f18-9c19-af26a3444364.png)

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.32
Node Version: 18.12.1
NPM Version: 9.1.3
Browser: Chrome
Browser Version: 107.0.5304.107

**Comment by jorgelaranjo** [comment]
Same error

```
info: Finished test 004 - My Test - My Feature Success
 FAIL  ../../usr/lib/node_modules/selenium-side-runner/dist/main.test.js (10.696 s)
  Running project My Project
    Running suite My Suite
      ✕ Running test 004 - My Test - My Feature (**10392** ms)

  ● Running project My Project › Running suite My Suite  › Running test 004 -My Test - My Feature OK

    Operation timed out!

      at Timeout.<anonymous> (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:141:13)
```

And another test suite

```
info: Finished test 002 - Login - Success
info: Finished test 004 - My Test - My Feature Success
 FAIL  ../../usr/lib/node_modules/selenium-side-runner/dist/main.test.js (9.571 s)
  Running project TreasuryHub SPA
```

https://github.com/SeleniumHQ/selenium-ide/blob/637e5208e18d337333659d79b8e95d1b19455b0d/packages/side-runtime/src/playback-tree/command-node.ts#L141


Seems related to #1559

**Comment by sergeykatelyna** [comment]
@jorgelaranjo 

I do not think "pause" commands cause these errors.

I replaced all "pause" and "wait" commands with "pause" 1000 (maximum 7 "pause" 1000 one by one).
![image](https://user-images.githubusercontent.com/34918999/205483225-1956f23c-21c4-47ce-b920-3dbc2c7841de.png)

I set timeout=100000 both in the SIDE script and in the CMD command.
![image](https://user-images.githubusercontent.com/34918999/205483235-65d548fe-4be4-43f5-8dc7-2f088cbce390.png)

But I still get 4 "Operation timed out!" errors in selenium-side-runner.
![image](https://user-images.githubusercontent.com/34918999/205483246-67c831a5-68f5-40ef-949a-fa2699c8dadd.png)

As before, the test itself passes. And there are no errors in Browserstack.
![image](https://user-images.githubusercontent.com/34918999/205483255-f087d4cb-a9ac-4f8d-8d04-2def1dcd000b.png)

##

Is there any way to fix this?

Or at least can I disable this error in the code of my local selenium-side-runner? For example, I could remove this piece of code...
![image](https://user-images.githubusercontent.com/34918999/205483275-b87a23cf-a1df-4843-b00d-76f13ef7c059.png)

**Comment by toddtarsi** [comment]
@rtb2000 - Latest version is going out now where this should all be resolved. Feel free to re-open if issue persists, thanks!
