### ISSUE TITLE
Selenium IDE - Build Problem

### ISSUE THREAD

**Issue by onurerdemiroglu** [SeleniumHQ/selenium-ide#1563]
![image](https://user-images.githubusercontent.com/35347777/206447917-9a563c71-9897-405e-a121-188872020e91.png)

I installed the necessary dependencies with (pnpm -r i). When I try to build with (pnpm run build), I get an error as attached. I tried to install the Selenium library with npn and yarn but without success. Is there anyone who can show the way?

**Comment by toddtarsi** [comment]
@onurerdemiroglu - I can help! But you'll have to deal with some annoying questions haha. What version of node, what version of pnpm, what branch are you on?

**Comment by toddtarsi** [comment]
For example, here's the versions I'm on:

```
➜  selenium-ide git:(trunk) node -v
v16.14.2
➜  selenium-ide git:(trunk) pnpm -v
7.13.1
➜  selenium-ide git:(trunk) npm -v
8.14.0
```

Oh, also, where are you calling `pnpm -r i` from? It needs to be the top level directory in the repo

**Comment by onurerdemiroglu** [comment]
Frankly, I'm very inexperienced and I think I'm already pissed off :) The versions I use are as in the screenshot;

![image](https://user-images.githubusercontent.com/35347777/206471196-59e7eb50-58ed-4b88-b9da-6c7c016fdb85.png)


(pnpm -r i) I think I used it in selenium-ide directory :/ I'll check again

**Comment by toddtarsi** [comment]
Welcome to OSS. You stay pissed off long enough, you become the repo owner. Everything there looks good to me. Are you on Windows? I see you're in a directory with a specific version. If you just want to use v4 of the IDE, would you want to download a prebuilt binary? We keep them here:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.26

I am a big fan of building it manually of course.

If you want to see an example of this process, it's part of this github release workflow:

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/.github/workflows/release.yml#L16

**Comment by toddtarsi** [comment]
@onurerdemiroglu - Any luck here? Wnat me to keep this open or can I close it?

**Comment by onurerdemiroglu** [comment]
@toddtarsi I'm done, thank you very much.
