### ISSUE TITLE
BUG:custom command not working

### ISSUE THREAD

**Issue by smildlzj** [SeleniumHQ/selenium-ide#1572]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/1638850/209616814-ffd0c79e-67df-4435-b21b-8c5b5947c0f0.png)
![image](https://user-images.githubusercontent.com/1638850/209616831-55f06826-dfa4-4dba-a0d5-57c2449c3438.png)

## To Reproduce
* any project
* add plugin with example
* replay it

## Expected behavior

working

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Info
it happen by this commit: https://github.com/SeleniumHQ/selenium-ide/commit/6eed9fd53e11b13f81726b2d18ce2b32bbb529a0

https://github.com/SeleniumHQ/selenium-ide/blob/6eed9fd53e11b13f81726b2d18ce2b32bbb529a0/packages/side-runtime/src/playback-tree/command-node.ts#L122

![image](https://user-images.githubusercontent.com/1638850/209617272-84ce234a-a3fc-4958-b244-d175b484fe3e.png)

**Comment by smildlzj** [comment]
@toddtarsi does it broken ?

**Comment by toddtarsi** [comment]
@smildlzj - Ruh roh! I'll take a look real quick

**Comment by toddtarsi** [comment]
@smildlzj - Should be resolved here:

https://github.com/SeleniumHQ/selenium-ide/commit/8fea9bf4e4ffdd2643d91c311210a136754412e8

**Comment by toddtarsi** [comment]
Merged to trunk, releases are building now

**Comment by smildlzj** [comment]
> @smildlzj - Should be resolved here:
> 
> [8fea9bf](https://github.com/SeleniumHQ/selenium-ide/commit/8fea9bf4e4ffdd2643d91c311210a136754412e8)

Yes. it work
