### ISSUE TITLE
Validation error on executing tests through executors

### ISSUE THREAD

**Issue by prashanth-sams** [SeleniumHQ/selenium-ide#158]
Machine used: **MAC**

![screen shot 2018-04-17 at 1 25 49 pm](https://user-images.githubusercontent.com/2948696/38861188-009821e0-4243-11e8-81c4-5d8c5795179e.png)

@corevo Do we need any specific JS libraries to be installed prior to it?

**Comment by prashanth-sams** [comment]
@corevo am I missing something here

**Comment by corevo** [comment]
No, it's an issue that is caused by incorrect forking of the process when it is picked up by the test workers.  
Try the 4th beta I just published.
