### ISSUE TITLE
Siderunner - Timeout reported even if test passes

### ISSUE THREAD

**Issue by ditorelo** [SeleniumHQ/selenium-ide#1584]
## 🐛 Bug Report

This is a duplicate of #1561 but unfortunately I couldn't comment there.

I'm using the latest version of the runner `4.0.0-alpha.36` and still receiving timeout notifications even though the whole test concludes and passes.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/642102/212575894-a13855a8-8826-42f9-a199-dbec1c645b87.png">

## To Reproduce

As per #1561 

## Expected behavior

As per #1561 

## Environment

OS: macOS 12.5 apple chip
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version: 4.0.0-alpha.36
Node version: v18.13.0
Browser: Firefox + Chrome
Browser Version: Firefox 108.0.5359.124 / Chrome 108.0.5359.124

**Comment by toddtarsi** [comment]
@ditorelo - Thanks for reporting, will try and take a look this weekend

**Comment by toddtarsi** [comment]
@ditorelo - Is this still occurring? I tried to resolve this after encountering it in some of my stuff, although I probably didn't get it.

**Comment by toddtarsi** [comment]
@ditorelo - Just posted some more timeout fixes, sorry about any issues here.
