### ISSUE TITLE
Timeout can't be set using configuration file in selenium-side-runner

### ISSUE THREAD

**Issue by anchim94** [SeleniumHQ/selenium-ide#1586]
## 🐛 Bug Report

I want to set the timeout parameter to selenium-side-runner using the configuration file `.side.yml`, but it doesn't work for me.
I can set that value through the command line using `-t` or `--timeout` only.

## To Reproduce

Set configuration file as presented below
```
timeout: 20000
capabilities:
  browserName: "chrome"
debug: true
debugStartup: true
```
After Run command: `selenium-side-runner ./base_url_test.side`
you can see this in the console:
```
Configuration: {
  baseUrl: '',
  capabilities: { browserName: 'chrome' },
  debug: true,
  debugStartup: true,
  filter: '.*',
  force: undefined,
  maxWorkers: 4,
  projects: [
    '/home/.../base_url_test.side'
  ],
  proxyOptions: {},
  proxyType: undefined,
  runId: 'f787f7a40840bc6e9432ccabb93d1f96',
  path: '/usr/lib/node_modules/',
  server: '',
  timeout: 15000,
}
Jest command: ...
```

Also, it can be observed that `selenium-side-runner` wait 15 seconds (not 20 as expected).

## Expected behavior

The timeout can be set to 20 seconds, and it can be observed using the `debugStatup` function.

## Project file reproducing this issue (highly encouraged)
Side file `base_url_test.side`:
```
{
 "id": "024746b1-ebd4-4ef1-96e6-78bdf6e51126",
 "version": "2.0",
 "name": "base_url_test",
 "url": "beta.slashdb.com",
 "tests": [
  {
   "id": "3a59687e-c5f1-4ce6-b41f-50f77f0d8486",
   "name": "Check Base URL",
   "commands": [
    {
     "id": "1ab41e59-08f6-4e88-8166-b45f5147265e",
     "comment": "",
     "command": "open",
     "target": "/",
     "targets": [],
     "value": ""
    },
    {
     "id": "1421c769-9d92-4c52-ac02-5c80c085ba7b",
     "comment": "",
     "command": "assertTitle",
     "target": "SlashDBabc",
     "targets": [],
     "value": ""
    }
   ]
  }
 ],
 "suites": [],
 "urls": [],
 "plugins": []
}
```

## Environment

OS: Ubuntu 20.04.4 LTS
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.37
Node version: v18.11.0
Browser: Chrome
Browser Version: 106.0.5249.119 (64-bit)
chromedriver: 106.0.1

**Comment by toddtarsi** [comment]
@anchim94 - Great call out, thanks for letting me know!

**Comment by toddtarsi** [comment]
@anchim94 - I think I have this resolved. I made some mistakes when adding preprocessor handling for variables and basically was eating the timeout.

**Comment by toddtarsi** [comment]
I'm going to close this, but please let me know if this is still an issue in .40 alpha
