### ISSUE TITLE
how can i build the extension correctly

### ISSUE THREAD

**Issue by geaizhen21** [SeleniumHQ/selenium-ide#159]
I pulled the lastest source. Follow the `README.md`, I build the extention successfully, but it can not work normally.
1. I used the `peru sync`, but it worked too long, so i stopped it and pulled the source from selenium and placed into `selenium-ide\src` manually(according to the `peru.yaml`);
2. I used `yarn` to install the dependencies and used `yarn build:ext` to got a extention successfully;
3. But after I installed it on Chrome, it can not work normally. I started record,but it can not record the steps, and i got this error from the Console when i click the `select/find target in page` button on selenium-ide;

![image](https://user-images.githubusercontent.com/24629821/38871990-cb2bfc2e-4284-11e8-964c-d975ac0d485c.png)

What should i do to build correctly ?

**Comment by corevo** [comment]
Is webpack giving you any errors?

**Comment by stebli** [comment]
how did your yarn build:ext work? i receive the following...

:selenium-ide stebli$ yarn build:ext
yarn run v1.15.2
$ cd packages/selenium-ide && yarn build:dev
error Command "build:dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

looking a the packages.json these scripts dont even exist there.... cannot build this package at all. Pulled today,. clearly im doing something wrong but it looks like this would never work.

**Comment by corevo** [comment]
@stebli please use the `v3` branch to build the extension, for further help try asking in the irc channel.  
Closing as OP did not respond.

**Comment by stebli** [comment]
yarn build:ext:prod
yarn run v1.15.2
$ cd packages/selenium-ide && yarn build
$ rm -rf build && env NODE_ENV=production webpack
env: webpack: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by stebli** [comment]
yarn build:ext
yarn run v1.15.2
$ cd packages/selenium-ide && yarn build:dev
$ webpack
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by stebli** [comment]
after running all commands on V3 

WARNING in ./neo/stores/seed.js
17:496-509 "export 'CommandsArray' was not found in '../models/Command'
 @ ./neo/stores/seed.js
 @ ./neo/containers/Panel/index.jsx
 @ ./neo/containers/Root/index.jsx
 @ multi react-hot-loader/patch ./neo/containers/Root

WARNING in ./neo/stores/seed.js
17:535-548 "export 'CommandsArray' was not found in '../models/Command'
 @ ./neo/stores/seed.js
 @ ./neo/containers/Panel/index.jsx
 @ ./neo/containers/Root/index.jsx
 @ multi react-hot-loader/patch ./neo/containers/Root

ERROR in ./content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot


irc useless, no feedback since initial request hours ago.

**Comment by tourdedave** [comment]
Please make sure to follow the build instructions from [the readme in `v3`](https://github.com/SeleniumHQ/selenium-ide/tree/v3#building).

One of the key steps in it is to run `peru sync`. One of your error messages indicates that is not the case.
