### ISSUE TITLE
Better Export Settings

### ISSUE THREAD

**Issue by elibroftw** [SeleniumHQ/selenium-ide#1591]
## 🚀 Feature Proposal

- ES style export
- Semi-colons on each line
- Use of single quotes over double whenever possible
- Ability to import driver from another file
- Auto import chai expect

## Motivation

Saves me time from having to edit the selenium output

## Example

Please provide an example for how this feature would be used.

https://github.com/elibroftw/modern-desktop-app-template/blob/master/test/toggletheme.spec.js

**Comment by toddtarsi** [comment]
This is not a priority for me. Semi-colons on each line is a specific opinion, and one that is expressly forbidden according to our linter rules (which is es style export, all typescript etc). I would recommend if you want these tweaks, that you write an export format for your needs.

**Comment by toddtarsi** [comment]
@elibroftw - I'm not trying to be snarky either. Please do feel free to tweak an existing export format as needed off of this one:

https://github.com/SeleniumHQ/selenium-ide/tree/trunk/packages/code-export-javascript-mocha

If you get a format you like and the repo is public, let me know and I can add it to a list of some sort on the readme?

**Comment by elibroftw** [comment]
thanks for pointing me in a direction. I'll see if I want to spend time creating an export
