### ISSUE TITLE
If Failed. unexpected token '{'

### ISSUE THREAD

**Issue by zielik909** [SeleniumHQ/selenium-ide#1593]
Hi.
in reference to https://github.com/SeleniumHQ/selenium-ide/issues/1072

bug still present in newest version selenium ide (4,0.0.0 - just downloaded) and  FF,chrome extensions
![Zrzut ekranu 2023-03-07 005240](https://user-images.githubusercontent.com/42648719/223284463-0bb43b48-241c-4e0d-80d3-9df820e766eb.png)

**Comment by toddtarsi** [comment]
Ah, interesting. Thanks for reporting! Just wanted to note, the latest version of the IDE is 4.0.0-alpha.35

I think this is an easy fix, I'll try something in just a moment.

**Comment by toddtarsi** [comment]
Okay, release with this fixed should be going out now. Thanks!
