### ISSUE TITLE
data-test-id not used

### ISSUE THREAD

**Issue by tokyo-watcher** [SeleniumHQ/selenium-ide#1598]
As pointed out in these articles below, there is a bug.
https://github.com/SeleniumHQ/selenium-ide/issues/435#issuecomment-491835113
https://github.com/SeleniumHQ/selenium-ide/issues/990#issuecomment-600182434

That is, in the following source file,
selenium-ide/src/browser/windows/PlaybackWindow/preload/locator-builders.ts

This code
```
    const dataAttributes = ['data-test', 'data-test-id']
    for (let i = 0; i < dataAttributes.length; i++) {
      const attr = dataAttributes[i]
      const value = e.getAttribute(attr)
      if (attr) {
```

must be like this.
```
    const dataAttributes = ['data-test', 'data-test-id']
    for (let i = 0; i < dataAttributes.length; i++) {
      const attr = dataAttributes[i]
      const value = e.getAttribute(attr)
      if (value) { // <-- here
```

Thank you for your reading.

**Comment by toddtarsi** [comment]
@test20161010 - Nice writeup. I would like to implement this really quickly, but it might take me a week since I'm just about to take my toddler on vacation

**Comment by toddtarsi** [comment]
@test20161010 - In the future, feel free to raise this stuff in PRs. I've closed PRs incorrectly before, but I've merged many of them, and with how targeted your explanation and fixes are, I would be happy to merge your commits.

**Comment by toddtarsi** [comment]
Okay, I have lifted your fixes in. In addition, I renamed that to data-test-id and kept it at the top, and wrote another called data-attr which is just above css:finder and tries to use the first data attribute it finds. I find this is pretty good for me when I've got like data-user-id="97" or similar. Should be out in 30, thanks!

**Comment by tokyo-watcher** [comment]
@toddtarsi Thank you very much.
