### ISSUE TITLE
Command Line option to export Selenium IDE to different language test scripts

### ISSUE THREAD

**Issue by anoopadvaitha** [SeleniumHQ/selenium-ide#1599]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
Command Line option to export Selenium IDE to different language test scripts. Currently the Selenium IDE GUI tool both v3 and v4 alpha provides option to export the Selenium .side file to either Python pytest, Java junit etc., I was looking to see if their is an option to generate pytest or junit using command line.
Happy to contribute on this as well.
## Motivation
If we have to develop medium sized test suite using Selenium IDE recording converting each recording to a Pytest using browser extension or an app would take more time and a command line script would give integration with CI/CD pipeline. 

## Example
selenium-code-export --language=python --format=pytest --output-file=test.py ide_file.side

Please provide an example for how this feature would be used.

**Comment by toddtarsi** [comment]
@anoopadvaitha - Yep! Actually, you're pretty close here:

```
npm install -g @seleniumhq/code-export;
npm install -g @seleniumhq/code-export-python-pytest;

side-code-export $(node -e 'console.log(require.resolve("@seleniumhq/code-export-python-pytest"))') ide_file.side ./
# More simply looks like this
# side-code-export path-to-output-format.js path-to-side-file.side ./output-directory
# https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-code-export/src/bin.ts
```

**Comment by anoopadvaitha** [comment]
@toddtarsi  Thank you so much !!

**Comment by anoopadvaitha** [comment]
It isn't working maybe because the npm published package doesn't have bin.ts or bin.js in dist folder

**Comment by toddtarsi** [comment]
@anoopadvaitha - Oh, my bad! Can you try @seleniumhq/side-code-export? Wrong package name sorry

**Comment by anoopadvaitha** [comment]
I tried @seleniumhq/side-code-export even it doesn't have bin.ts or bin.js in the install folder I can only see the below:
![image](https://user-images.githubusercontent.com/5357867/224124997-0e4173ce-f2f5-4447-8548-78569884f482.png)

**Comment by toddtarsi** [comment]
Hmm, very strange. Maybe I need to rename this package to just side-code-export or similar. Sometimes the org prefix or the bin not matching can cause npm to give me grief

**Comment by anoopadvaitha** [comment]
Can you help me on how to call from JS that'll be really helpful
