### ISSUE TITLE
Request for command storeAttribute 

### ISSUE THREAD

**Issue by jngale** [SeleniumHQ/selenium-ide#160]
Would it be possible to add these commands?  Thank you

I would like to add that there seems to be a large number of commands that are not included yet. I do understand priorities, but it is getting challenging. I have just run into a need for storeAttribute and storeXpathCount. Perhaps it is just me always needing what isn't there yet. Thanks so much for all your work and help

I am presently using the latest Chrome version.

**Comment by jngale** [comment]
I would like to add that there seems to be a large number of commands that are not included yet. I do understand priorities, but it is getting challenging. I have just run into a need for storeAttribute and storeXpathCount.  Perhaps it is just me always needing what isn't there yet.  Thanks so much for all your work and help

**Comment by corevo** [comment]
`assertSelectedLabel` and `verifySelectedLabel` were added in [3.1.0](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.1.0)

**Comment by corevo** [comment]
Fixed in #171
