### ISSUE TITLE
Webdriver redirect to google immediately after running VBA code and gives me no chance to control it | Solved !

### ISSUE THREAD

**Issue by Alpin10** [SeleniumHQ/selenium-ide#1601]
**_Hi all. There is a website that I would like to automate via Excel Webdriver but at each execution it redirects to google immediately 
after the execution of the VBA code and leaves me no chance to control it. I saw that there is in its HTML code this code:_**

`<noscript><meta http-equiv="refresh" content="0; url=http://www.google.com/" /></noscript>`

**_I think the problem lies in this part of the code._**

**Comment by toddtarsi** [comment]
@Alpin10 - I'm going to try to help, but I don't honestly know what "excel webdriver" is. Are you using compiled code from selenium ide code export? Are you using Selenium IDE v4? How are you using this project?

**Comment by toddtarsi** [comment]
@Alpin10 - We don't use VBA anywhere in here, nor do we export to VBA, so I'm a bit confused. I think I see what happened here. You're using some .NET type of stuff for webdriver.

I don't think you want to raise an issue here. I'm just selenium-ide, a small R&P tool that uses javascript events to record and selenium to playback browser interactions.

You probably want to raise an issue here:

https://github.com/SeleniumHQ/selenium

^^^ This is Selenium core. This is where all the language bindings are warehoused or something like that maybe. If that is the wrong place, they'll also likely be better at routing

**Comment by toddtarsi** [comment]
@Alpin10 - If that isn't the case, maybe this will help.

If you're in a new project, there should be a third tab labeled "Config". Open it and there should be a website url. Change it from google.com to whatever you want. Start doing record or playback. 🙂

**Comment by toddtarsi** [comment]
I'm going to leave this open. If that resolved your issue, I'll close this. If I don't hear from you for a couple weeks, I'll close this. Thanks buddy!

**Comment by Alpin10** [comment]
> I'm going to leave this open. If that resolved your issue, I'll close this. If I don't hear from you for a couple weeks, I'll close this. Thanks buddy!

I found the solution on this forum : https://bountify.co/need-vba-selenium-expert-website-blocking-selenium

**Comment by toddtarsi** [comment]
Glad you got it :)
