### ISSUE TITLE
Release date of selenium-side-runner v4.

### ISSUE THREAD

**Issue by fmrahman** [SeleniumHQ/selenium-ide#1604]
Hi @toddtarsi 
It's great work that you are doing here, for the v4 upgradation work. Thanks much. Curious to know when will be the release date of the v4 version.

Thanks,
Farooq.

**Comment by toddtarsi** [comment]
@fmrahman - Depends on your definition of released is. I have been publishing v4 of the side-runner on npm for a while, I think it's up to `4.0.0-alpha.43`, so we're 43 versions into the alpha of v4. My plan is to leave alpha/beta over the next six or so months, so hopefully that answers your question.

**Comment by fmrahman** [comment]
I am referring to the final release date of selenium-side-runner v4. We are eager to use v4 in our product but alpha/beta versions are not allowed in the final release of our product. Requesting to publish v4 without any alpha/beta at the earliest.
Thanks once again for your contribution toward this v4 work.

Thanks,
Farooq.

**Comment by toddtarsi** [comment]
Thats a fair request. We're a bit unstable, and we want better test coverage, but I'll make sure to push for code signing certificates asap. That's the big blocker for us tbh. Without being able to be verified as a trusted app on windows / mac, I can't really leave alpha.
