### ISSUE TITLE
The order of recording functions is reversed.

### ISSUE THREAD

**Issue by XiXiangkun** [SeleniumHQ/selenium-ide#1606]
## 🐛 Bug Report

Just new a project and record my operations. The order of functions recorded is reversed.
I need to click the 'open' line before recording to fix it.
<img width="1458" alt="Screenshot 2023-03-30 at 3 45 14 PM" src="https://user-images.githubusercontent.com/46923112/228767690-b9be55ea-5aca-447e-aee8-12b6c23084ff.png">

## To Reproduce

new a project and record my operations.

## Expected behavior

Recorded functions are in order.

## Environment

OS: macOS
Selenium IDE Version:  4.0.0
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
@XiXiangkun - Thanks for the great call out! Sounds like I should jump down past the open step when recording starts.
