### ISSUE TITLE
How can I get test reports in HTML format in Selenium IDE?

### ISSUE THREAD

**Issue by mm0hammadi** [SeleniumHQ/selenium-ide#1620]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.
We want to see the results of the tests that I have saved in the form of an html report. Is it possible to do this?

Is there a tool and plugin for this?

## Example

Please provide an example for how this feature would be used.

**Comment by mm0hammadi** [comment]
Finally, I could find the solution, here is the link which can help you to solve this issue. 
we can use TestNG in intellij-idea 
https://www.lambdatest.com/blog/how-to-generate-testng-reports-in-jenkins/

**Comment by manikantayarramsetti1** [comment]
💬 After running selenium ide test, How to generate html report

**Comment by toddtarsi** [comment]
@manikantayarramsetti - 

https://medium.com/@biswa8998/jest-with-html-report-a884b08d6635
use the jest options from the side-runner to do the underlying jest stuff

**Comment by manikantayarramsetti1** [comment]
i  have issues with running from command line runner , i was running
in selenium ide only. Is jest will generate reports if i run from selenium
ide

**Comment by toddtarsi** [comment]
No, sorry

**Comment by manikantayarramsetti1** [comment]
Is there any other way to generate reports,IF there please tell me

**Comment by manikantayarramsetti1** [comment]
> No, sorry

when i was running test suite contains multiple test from the side runner , if one test case gets failed it is going to next test but i have issue with my application having issue with user login if i logined failed case it will not login to other test, if i logout only will login

**Comment by manikantayarramsetti1** [comment]
> No, sorry

In command line runner if the test gets failed the browser was closing, in there any way not to close the browser, Because in the next test i will run from there.

**Comment by toddtarsi** [comment]
@manikantayarramsetti1 - I'm sorry, but html reports from the IDE just aren't a priority. By and large, this is exactly what the CLI tools are for. If your flow tends to be running a suite and giving someone a html report, practice using the jest options flag on the selenium side runner.

You're the only person I know of asking for this. Thats a sign that you should reconsider your approach.

I'm closing this issue as the original author discovered how to do what they needed.
