### ISSUE TITLE
How to solve？\packages\code-export-csharp-commons\node_modules\.bin\side-code-export. The source file at F:\WebstormProjects\selenium-ide\packages\side-code-export\dist\bin.js does not exist.

### ISSUE THREAD

**Issue by dzjwwm** [SeleniumHQ/selenium-ide#1626]
PS F:\WebstormProjects\selenium-ide> nvm current
v16.13.1
PS F:\WebstormProjects\selenium-ide> pnpm -r i
Scope: all 22 workspace projects
.                                        |  WARN  Ignoring broken lockfile at F:\WebstormProjects\selenium-ide: Lockfile F:\WebstormProjects\selenium-ide\pnpm-lock.yaml not compatible with current pnpm
packages/selenium-ide                    |  WARN  deprecated @types/electron@1.6.10
packages/side-migrate                    |  WARN  deprecated @types/xml-js@1.0.0
packages/side-runner                     |  WARN  deprecated @types/winston@2.4.4
.                                        |  WARN  deprecated @bazel/typescript@5.8.1
.                                        |  WARN  deprecated @bazel/bazel@2.1.0
.                                        |  WARN  deprecated babel-eslint@10.1.0
packages/get-driver                      |  WARN  deprecated @types/minipass@3.3.5
packages/selenium-ide                    |  WARN  deprecated electron-osx-sign@0.6.0
packages/selenium-ide                    |  WARN  deprecated asar@3.2.0
packages/side-runner                     |  WARN  deprecated w3c-hr-time@1.0.2
.                                        |    +1281 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: F:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1297, reused 1292, downloaded 0, added 1281, done
node_modules/.pnpm/electron-chromedriver@18.0.0/node_modules/electron-chromedriver: Running install script, done in 5.5s
node_modules/.pnpm/electron@18.3.15/node_modules/electron: Running postinstall script, done in 6.3s
 WARN  Failed to create bin at F:\WebstormProjects\selenium-ide\packages\code-export-csharp-nunit\node_modules\.bin\side-code-export. The source file at F:\WebstormProjects\selenium-ide\packages\side-code-export\dist\bin.js does not exist.
 WARN  Failed to create bin at F:\WebstormProjects\selenium-ide\packages\code-export-java-junit\node_modules\.bin\side-code-export. The source file at F:\WebstormProjects\selenium-ide\packages\side-code-export\dist\bin.js does not exist.
 WARN  Failed to create bin at F:\WebstormProjects\selenium-ide\packages\code-export-csharp-commons\node_modules\.bin\side-code-export. The source file at F:\WebstormProjects\selenium-ide\packages\side-code-export\dist\bin.js does not exist.
 WARN  Failed to create bin at F:\WebstormProjects\selenium-ide\packages\code-export-csharp-xunit\node_modules\.bin\side-code-export. The source file at F:\WebstormProjects\selenium-ide\packages\side-code-export\dist\bin.js does not exist.
 WARN  5 other warnings
 WARN  Issues with peer dependencies found
packages/selenium-ide
├─┬ ts-node 10.9.1
│ └── ✕ missing peer @types/node@"*"
└─┬ react-dnd 15.1.2
  └── ✕ missing peer @types/node@">= 12"
Peer dependencies that should be installed:
  @types/node@>=12.0.0

Done in 3m 0.4s

**Comment by toddtarsi** [comment]
Oh wow, you're building the client! Nice (excepting the 3m build time, sorry about that its electron stuff i promise haha).

Can you give me the output from `pnpm --version` or equivalent? I think the latest version of pnpm is 8.0 and I haven't migrated to it yet because something breaks the builds. Would you be open to installing pnpm v7 instead? If not, I'd be happy to get v8 working, but it might have to wait a half a week while I find the time at night to do it

**Comment by dzjwwm** [comment]
electron@18.3.15 and electron-chromedriver@18.0.0 cannot be downloaded
![image](https://user-images.githubusercontent.com/44464033/234012334-8e1e4972-d3fe-4aa0-a274-c8d2066b92c9.png)

**Comment by toddtarsi** [comment]
@tl31707chy - Huh. That is one of two things I think:

1. You changed pnpm versions. Maybe you have to clear your modules and try running it again.
2. Maybe npm is just being intermittent. I mean, electron and electron-chromedriver are pretty common packages.

```
npm run clean:lazy; // This script is just a very decorated `rm -rf` command
pnpm i -r
```

**Comment by toddtarsi** [comment]
Also, your lockfile might have been regenerated for v8.  You might need to check that out too.


I'm sorry these issues are happening, and I really appreciate you going through the effort to build locally. I'll work on getting v8 to work. This has bitten a few people and I don't like giving the people actually giving the thing a chance a kick in the ass to start.

**Comment by dzjwwm** [comment]
Still no. I don't know what to do right now, okay
![image](https://user-images.githubusercontent.com/44464033/234170860-e6292a3b-c5c3-4915-bf7b-99ecd66187c6.png)

**Comment by toddtarsi** [comment]
There's nothing you need to do. I need to better understand the unique challenges of windows filesystems I think. Can you let me know if there is a dist/bin.cmd or dist/bin.ps1 or such? I'm not on Windows, so I'm trying to get the binary path stuff right here. Sorry for the trouble

**Comment by dzjwwm** [comment]
I'll give Linux a try
