### ISSUE TITLE
File, New Project is not resetting project to empty project template 

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1630]
Have some project open or edited, then use File, New Project, and something changes about the project state, but the project editor does not show a blank new project.

**Comment by mrgamedev07** [comment]
@toshiya , can i take up this task?

**Comment by toddtarsi** [comment]
@mrgamedev07 - I'd definitely sign off on it!

The state mutation stuff is here in side-api, this is solely concerned with manipulating the root state:

https://github.com/SeleniumHQ/selenium-ide/blob/3725cae8abf61266ff52650f5a7a092d5f72ae13/packages/side-api/src/commands/projects/new.ts

The server controller method is here in selenium-ide, which basically returns the result field of the cache updater:

https://github.com/SeleniumHQ/selenium-ide/blob/5268ff04eaf2e7e0a8b22e862c0bec1fe70f3050/packages/selenium-ide/src/main/session/controllers/Projects/index.ts
