### ISSUE TITLE
Update side-runner to optionally run jest using node explicitly

### ISSUE THREAD

**Issue by GeorgeSchneelochVA** [SeleniumHQ/selenium-ide#1634]
## 🚀 Feature Proposal

It would be nice for side-runner to optionally use a node binary which is specified explicitly in the command line. In [this line](https://github.com/SeleniumHQ/selenium-ide/blob/4.0.0-alpha.39/packages/side-runner/src/bin.ts#L205) side-runner currently executes the `jest.js` file directly:

    spawn(jest, jestArgs, {
    
It would be useful in some situations to run something like this instead:

    spawn('node', [jest, ...jestArgs], {

## Motivation

I'm working on setting up selenium tests to be run with a github action worker on a Windows server. Windows does not read shebang lines so when the `spawn(jest...` line is run it executes whatever is assigned to handle `.js` files, which may not be node. I would like some way to override this behavior so that node can be used instead.

## Example

A windows user could run `./node_modules/.bin/selenium-side-runner.ps1 -c 'browserName=chrome' --use-node ./path-to-side-file.side`, and the `--use-node` argument could cause `spawn('node', [jest, ...jestArgs], {...` to be run instead. I'm not sure this is the best way to do it but it would be helpful for my situation.

**Comment by toddtarsi** [comment]
@GeorgeSchneelochVA - I believe that's implemented [here](https://github.com/SeleniumHQ/selenium-ide/blob/8b0379a17ba7675e6a763d81a676dacc26ecaf34/packages/side-runner/src/bin.ts#L195) and defined [here](https://github.com/SeleniumHQ/selenium-ide/blob/8b0379a17ba7675e6a763d81a676dacc26ecaf34/packages/side-runner/src/bin.ts#L48)

**Comment by GeorgeSchneelochVA** [comment]
@toddtarsi I think the feature you are referring to allows optional jest arguments after `jest.js`, but I'm referring to adding `node` before `jest.js`, as the `command` argument to `spawn`

**Comment by GeorgeSchneelochVA** [comment]
Looks like this was fixed in https://github.com/SeleniumHQ/selenium-ide/pull/1649, going to close this issue

**Comment by toddtarsi** [comment]
Woohoo! @mrgamedev07 - Thank you!!!
