### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by redscolaco** [SeleniumHQ/selenium-ide#1635]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
@redscolaco - This issue is unactionable without any explanation. Closing.
