### ISSUE TITLE
Error: Could not find a config file based on provided values:

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium-ide#1637]
Hello !

I am trying to run Selenium-side-runner in command-line runner in CMD. But I get the following error. It seems like my selenium-side-runner does not even run or start. See attached file.

![Screenshot (26)](https://user-images.githubusercontent.com/128732023/235950241-6192d066-8e3c-4cab-8a89-33eadc56c911.png)

## Environment
OS: Windows 10 Home 64-bit
Selenium IDE Version: 3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.46
Node version: v10.18.0
Browser: Google Chrome - Version 113.0.5672.64 (Official Build) (64-bit)

**Comment by mari0s84** [comment]
I have the same problem

**Comment by toddtarsi** [comment]
Oh no! I've been hearing a lot about windows issues with the side-runner tbh. I'll ask around and see if any of the cloud vendors can loan me like a windows VM or something. I just don't know whats going on here from my mac.

**Comment by toddtarsi** [comment]
Thank you for trying v4 of the side runner!

**Comment by toddtarsi** [comment]
@Rheizi - Looking at it this weekend, can you let me know where the bin file is, and what the bin file contents generally look like on your system? This can be as simple as a picture of the top level folder or whatever. Thanks!

**Comment by toddtarsi** [comment]
Basically, that file is supposed to look one directory up for a config.jest.js file, but it might be all scrambled around for bin reasons so maybe I need to crack that egg another way

**Comment by BeBo1337** [comment]
got the same issue, any fix?
@toddtarsi
the bin file that I think you mean is in:
.../selenium-side-runner/node_modules/jest/bin

Is it a problem native to this version of SSR only?

**Comment by toddtarsi** [comment]
@BeBo1337 @mari0s84 - I'm sorry, this is top on my priority here, but for this week in open source, I am actually working on opentelemetryjs. So, in about a week, I'll be back to look at this, but first I have to learn how they do multi version testing and get that on some of their stuff. I'm sorry, but you know how it can be.

**Comment by bobba84** [comment]
I've got the same problem too, brand new install.

**Comment by toddtarsi** [comment]
Hey all, just wanted to let you know that 3.x doesn't have this issue, but isn't so compatible with v4. I'll have v4 soon, but for now I'm basically messing up Windows stuff and gotta figure out where the jest executable is a bit better. Sorry all!

**Comment by bobba84** [comment]
Should this be closed if the workflow is still awaiting approval? Looks like it's still waiting for an agreement to be signed...

**Comment by toddtarsi** [comment]
@bobba84 - I didn't mean to close anything, did some workflow thing do something? Also holy cow @mrgamedev07 - How long has this been done? I'd be happy to merge. I'm so up a creek with Windows and life in general tbh

**Comment by bobba84** [comment]
All good!! Sorry, I must admit I just honestly didn't know how it worked :) Thanks so much guys!!
