### ISSUE TITLE
Fila de testes

### ISSUE THREAD

**Issue by ThiagoFonseca23** [SeleniumHQ/selenium-ide#1645]
O selenium ide, extensão do google chrome, possuí uma maneira de inserir uma fila de testes?
Sem ter que parar a rotina para selecionar o arquivo que ele tem que fazer o teste toda vez.

**Comment by toddtarsi** [comment]
Google translate: Desculpe pela má tradução

Infelizmente não. Estou lidando apenas com reparos na v3, mas a v4 está em alfa aqui e estou trabalhando mais nessa versão.

**Comment by ThiagoFonseca23** [comment]
Certo, obrigado!
