### ISSUE TITLE
Issue with report generation using jest options with selenium CLI

### ISSUE THREAD

**Issue by srinivas931** [SeleniumHQ/selenium-ide#1651]
## 🐛 Bug Report

Running the selenium side runner CLI with jest options to generate xml report does produce the report. While the same command in .bat does not generate the report

Don't seem to find any jest options that could help with providing a custom output directory for the report [jest docs](https://jestjs.io/docs/configuration#reporters-arraymodulename--modulename-options)

## To Reproduce

1. Open Windows command line and execute below script 
`selenium-side-runner -j "\"--reporters=jest-junit"\" -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome" <Side file path>`
(this generates the 'junit.xml` file under the directory where command is executed)

2. Create a bat file in the same directory with above command and run the bat file. This is not generating the `junit.xml` file

## Expected behavior

`junit.xml` report should be generated

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10 
Selenium IDE Version:  
Selenium SIDE Runner Version:  4.0.0-alpha.47
Node version: v16.18.1
Browser: Chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Comment by toddtarsi** [comment]
Ugh, there is so much with windows and executables I have been going back and forth on buying a vbox license for windows to use or something idk

**Comment by toddtarsi** [comment]
I'm sorry for what you're getting here but like what is windows how many executables does it even have, why do i have to support .sh and .cmd.bat.ps1.exe.sh i mean its a bit yakkity sax

**Comment by srinivas931** [comment]
This morning was able to figure it out. Referring to `jest-junit` library it offers setting environment variables `JEST_JUNIT_OUTPUT_DIR` and `JEST_JUNIT_OUTPUT_NAME` and this did the job. Thank you @toddtarsi for the response

**Comment by toddtarsi** [comment]
@srinivas931 - Oh thank goodness, I'm so happy to hear this. Thank you for the update. I've been banging my head on the wall with Windows lately. Luckily @mrgamedev07 saved the day here last time (thank you again!), but I need to get my node stuff together better on Windows really

**Comment by srinivas931** [comment]
Thank you @toddtarsi , much appreciate your help
