### ISSUE TITLE
How to stop driver.Navigate().GoToUrl() method?

### ISSUE THREAD

**Issue by wangshuai-007** [SeleniumHQ/selenium-ide#1664]
## 💬 Questions and Help

I know,I can use `driver.Navigate().GoToUrl("https://google.com")` to visit google.com.

I try to visite https://www.apkmirror.com/apk/google-inc/google-calculator/google-calculator-8-4-503542421-release/google-calculator-8-4-503542421-2-android-apk-download/

But it is too slow,usally this command will cause time out error.
And I can stop the document loading by click stop button.

And I try to use the follow code to do that action.
```c#
driver.ExecuteScript("setTimeout(function(){window.stop()},5000)");

driver.Navigate().GoToUrl("https://www.apkmirror.com/apk/google-inc/google-calculator/google-calculator-8-4-503542421-release/google-calculator-8-4-503542421-2-android-apk-download/");

```

But it does not work.

It is in line with expectations,Because when `window.location` changed all script will clear.

Is there an asynchronous `Navigate().GoToUrl()` method ,so that I can stop the document loading action?

Or, Is there a  method like `driver.Navigate().Stop()`?

**Comment by toddtarsi** [comment]
@wangshuai-007 - Would you raise this issue here instead?

https://github.com/SeleniumHQ/selenium

I don't know about this stuff, sorry and good luck!

**Comment by wangshuai-007** [comment]
As the replace,I found a solution in [Page load strategy for Chrome driver (Updated till Selenium v3.12.0)](https://stackoverflow.com/a/43737358/7960551)

First,Set `chromeOptions.PageLoadStrategy = PageLoadStrategy.Eager;`
Then,Use `WebDriverWait`
```c#
WebDriverWait waitDownloadLink = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
waitDownloadLink.Until(f => f.FindElement(By.LinkText("here")));
```

wait element visiable
