### ISSUE TITLE
window closing

### ISSUE THREAD

**Issue by manikantayarramsetti1** [SeleniumHQ/selenium-ide#1669]

**Comment by toddtarsi** [comment]
No. The IDE won't do this for you. I'm not interested in implementing this feature. Commenting on six different issues is also moving the needle in the wrong direction. If you need to do this, I'd recommend making your login logic part of a test and using the run command to call it as part of the test start.

**Comment by manikantayarramsetti1** [comment]
yes i was doing like this only, login logic part of a test and using the run
command, but previously my session was not logged out  in test1.so in next test case test2
i cannot login because of user
 session opens

**Comment by toddtarsi** [comment]
So is your problem that you need to drop sessions between tests? This should occur automatically in the side-runner. What version of side-runner are you using?

**Comment by manikantayarramsetti1** [comment]
> So is your problem that you need to drop sessions between tests? This should occur automatically in the side-runner. What version of side-runner are you using?

selenium-side-runner@4.0.0-alpha.48 this is the version i m using . i m struck with droping session

**Comment by manikantayarramsetti1** [comment]
> So is your problem that you need to drop sessions between tests? This should occur automatically in the side-runner. What version of side-runner are you using?

is there any way you know, please let me know

**Comment by manikantayarramsetti1** [comment]
> So is your problem that you need to drop sessions between tests? This should occur automatically in the side-runner. What version of side-runner are you using?

my issue was closed without knowing me, how can i apprach this user 
session problem
