### ISSUE TITLE
User Session already opened Issue Because Of this i cannot run tests

### ISSUE THREAD

**Issue by manikantayarramsetti1** [SeleniumHQ/selenium-ide#1670]
## 💬 I have multiple test Suite contains multiple tests inside it. Please see the structure of my testsuite below.

- PracticeTestSuiteOne

1. Test1
2. Test2  \\exception occurs in some where (here user loggined)
3. Test3  (here we cannot login to application because of user loggined at test2)
4. Test4
5. Test5
6. Test6

### Actually Happening:
If i run PracticeTestSuiteOne in selenium side runner.It started with Test1 contains my application logging in and doing some tests and logging out and then going to Test2.In this case it is fine for me.

If i run PracticeTestSuiteOne in selenium side runner.It started with Test1 contains my application logging in and doing some tests and logging out and then going to Test2 then in test2 somewhere my test failed and then going to test3 but in test3 i cannot logging in to my application, because in test2 my user session is opened. so i cannot open in test3.

### Expected behavior:

In selenium side runner i want to run all the tests in the PracticeTestSuiteOne.Because of test2 fails i cannot run remaining tests in the PracticeTestSuiteOne.I want to run all the tests and generate reports.

Note: In selenium ide user session issue is not their but we cannot generate reports using selenium ide. so i m running tests in side runner in selenium side runner user session issue came because of this i cannot generate reports.

### Environment
OS: Macos
Selenium IDE Version: 3.17.2
Browser: ChromeVersion 114.0.5735.198 (Official Build) (arm64)

**Comment by matewilk** [comment]
I'd encourage you to follow one of the issues templates where you were given instructions to provide more context around the challenges you're coming across. I'd create the issue from scratch and follow the instructions.

Are you able to give more context?
Is this issue related to Selenium?
What have you tried so far, what is the error and what is throwing the error, if it makes sense?

I'd also try searching for a similar issue in the Issues tab and on other websites like [StackOverflow](https://stackoverflow.com/) where you might find people encountering similar behaviour from their workflows.

**Comment by manikantayarramsetti1** [comment]
@matewilk @toddtarsi given more context about my issue
