### ISSUE TITLE
Create Selenium IDE EDGE

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium-ide#1671]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
Not going to happen, I'm sorry. Selenium IDE v3 would need a miracle to clear the webextension manifest changes. Basically, the extension is on borrowed time. All effort is on v4 these days, which runs on Windows. Once we allow you to configure drivers in the IDE, this will be complete. For now, just closing this issue as its not going to happen.
