### ISSUE TITLE
Selenium-Side-Runner: Unknown command storeXpathCount

### ISSUE THREAD

**Issue by Pun-slinger** [SeleniumHQ/selenium-ide#1679]
![image](https://github.com/SeleniumHQ/selenium-ide/assets/59809715/01c80dab-f567-47b9-b667-145d4fd0091e)

Hi, I'm getting this error when I ran selenium-side-runner on my tests. The command exist on Selenium IDE but not here it seems like. Does selenium-side-runner not support the storeXpathCount command ?

**Comment by toddtarsi** [comment]
Oh wowie, yeah looks like that command didn't make it to v4 yet. Good catch! If you use the latest of v3 of the side-runner, it should be there. I'll look at adding it to v4. Thanks for letting me know!

**Comment by Pun-slinger** [comment]
Thank you so much! I looked everywhere and I couldn't find anyone with the issue so I thought I bring it here

**Comment by Pun-slinger** [comment]
Hi! Sorry for asking but I want to ask if you'll be adding the command soon and when will it be added ?

**Comment by toddtarsi** [comment]
@Pun-slinger - I'm looking tonight 👍

**Comment by Pun-slinger** [comment]
woohoooo ! Thank you so much !

**Comment by toddtarsi** [comment]
@Pun-slinger - In v4, there is a command, store element count, which is selector independent. There is a package, side-migrate, which I should modify to perform this conversion for you on a side file. I'll take a look. Would a package you can use with npx to directly modify a side file in place work alright?

**Comment by toddtarsi** [comment]
There's some nasty commands in v3, the local playback specific stuff especially, which should be dumped in v4

**Comment by toddtarsi** [comment]
@Pun-slinger - Okay, I added a bin to side-migrate. I think something like this should work, although my test coverage here sucks:

```
npx @seleniumhq/side-migrate your-side-file.side new-side-file-for-comparison.side
```

You can make the paths the same too if you'd like to migrate in-place, although I'd make sure to have a way of reverting, like source control or w/e

**Comment by toddtarsi** [comment]
This will update your side files for v4. If you're using the v3 IDE and the v4 side-runner in the CI, you can probably do an update in-place in the step prior to running your suites.

**Comment by Pun-slinger** [comment]
the side migrate works and I had switched to using IDE v4. It's a bit wonky since I'm so used to using v3 until now but, thank you so much!

**Comment by toddtarsi** [comment]
@Pun-slinger - Closing this as there is a migration path for this now (will work on documentation).

Thanks mate!
