### ISSUE TITLE
Script with the Times command fails when run with selenium-side-runner v4

### ISSUE THREAD

**Issue by Pun-slinger** [SeleniumHQ/selenium-ide#1680]
## 🐛 Bug Report

The times command fails when run with the selenium-side-runner. 
Happen in both cases when command value is a hard coded number and when it comes from a variable

This error does not happen when the script is run directly from the IDE, only with selenium-side-runner

## To Reproduce

1. Create a script that use a time command to loop run echo command for any amount of times. Amount can either be hard coded or come from a variable with store command
2. Run the script in the IDE and it runs successfully to completion
3. Run the script in the selenium-side-runner

## Expected behavior

When run via the selenium-side-runner, the script successfully to completion with no error

## Project file reproducing this issue (highly encouraged)

The script fails immediately after being started.

Here are some screenshots
1. Times command with value come from a variable with store command (FAILED)
![image](https://github.com/SeleniumHQ/selenium-ide/assets/59809715/41d4fe0a-d151-4089-b76e-890cc7b8b456)

2. Times command with value hard coded (FAILED)
![image](https://github.com/SeleniumHQ/selenium-ide/assets/59809715/a4934953-a3f9-43aa-80ca-1b5fbf758e20)

3. While command (SUCCESS)
![image](https://github.com/SeleniumHQ/selenium-ide/assets/59809715/22dac506-8643-41d4-ab69-1542c1cca5c3)

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
@Pun-slinger - Resolved in latest and has a test 👍
