### ISSUE TITLE
Assert target with stored variable does not work (v4)

### ISSUE THREAD

**Issue by Pun-slinger** [SeleniumHQ/selenium-ide#1689]
## 🐛 Bug Report

Assert target with stored variable failed for both Selenium IDE v4 and selenium-side-runner v4

All assert commands failed if target contains stored variable (Assert Value, Assert Element Present, Assert Text, etc...)

## To Reproduce

![image](https://github.com/SeleniumHQ/selenium-ide/assets/59809715/e2b5190a-0ce4-4cbd-bf54-0fd3172a2f73)

## Expected behavior

No error should occure, test should run successfully to completion

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS:  Windows 10
Selenium IDE Version:   4.0.0-alpha.46
Selenium SIDE Runner Version:   4.0.0-alpha.55
Node version:  v18.14.2.
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
Oh! The locator on assert element present. Aha!

**Comment by toddtarsi** [comment]
@Pun-slinger - Okay, added preprocessors for the following assertions:

element present
element not present
title
value

**Comment by toddtarsi** [comment]
@Pun-slinger - Closing this! Feel free to open for more
