### ISSUE TITLE
Failed to create bin at /Users/zhoujun/Desktop/selenium-ide-trunk/packages/code-export-csharp-xunit/node_modules/.bin/side-code-export. The source file at /Users/zhoujun/Desktop/selenium-ide-trunk/packages/side-code-export/dist/bin.js does not exist

### ISSUE THREAD

**Issue by zhoujun19930703** [SeleniumHQ/selenium-ide#1696]
<img width="2161" alt="image" src="https://github.com/SeleniumHQ/selenium-ide/assets/33832353/e55d2599-e4e5-4cec-b1f7-791eec5fa66d">

**Comment by zhoujun19930703** [comment]
No matter what I do, it always appears.

**Comment by toddtarsi** [comment]
@zhoujun19930703 - I see you closed this. Yep! It's because the first time the code builds, the bin files aren't built yet, so they don't symlink during the first install phase.
