### ISSUE TITLE
Selenium IDE not recording keystrokes in input fields

### ISSUE THREAD

**Issue by karthikuj** [SeleniumHQ/selenium-ide#1699]
## 🐛 Bug Report

Selenium IDE does not record keystrokes in input fields unless you click somewhere else after filling out the field. So, if you press enter after typing something in a search bar the the keystrokes won't be recorded.

## To Reproduce

1. Start IDE and open https://google.com/.
2. Start recording.
3. Enter something in search field and press enter.
4. The keystrokes won't be recorded.

## Expected behavior

1. User will expect it to record the keystrokes even when they don't explicitly out focus the element.

## Project file reproducing this issue (highly encouraged)

NA

Issues without a reproduction project are likely to stall.

## Environment

OS: Linux Ubuntu 22.04
Selenium IDE Version:  [4.0.0-alpha.46](https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.46)
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by toddtarsi** [comment]
@karthikuj - Just wanted to note, this is because the recorder appears to use the change event on inputs more than key down, so this command tends to wait until blur for fields.

**Comment by islamuddin** [comment]
@toddtarsi so keeping in view your above comment when we are clicking outside on end of typing input, recorder is recording that click command too along with type command. That is sometimes fails the testcase due to its random nature. How to avoid this happening?

**Comment by toddtarsi** [comment]
@karthikuj @islamuddin - I finally found this, sorry for the delay here. It came down to a record handler not operating in the capture phase. Sorry about that, x.58 is going out tonight and should resolve this. Happy holidays

**Comment by karthikuj** [comment]
Awesome :smile: 
Thank you!

**Comment by toddtarsi** [comment]
Closing this issue, as I believe this bug is resolved
