### ISSUE TITLE
blank window with firefox 59.0.2 and fedora 27

### ISSUE THREAD

**Issue by fpusersuggest** [SeleniumHQ/selenium-ide#170]
Hi, I have problem to run selenium-ide extension on fedora 27 with firefox 59.0.2.
Simply I run the extension by the button and it has opened a blank window. I have cleaned the firefox temp with  bleachbit, but nothing was changed.

**Comment by corevo** [comment]
I have a problem reproducing this?  
Can you explain step by step?

**Comment by fpusersuggest** [comment]
A guy on irc have explained me that this is the new selenium-ide... and my bug concern the old firefox extension. Then I close the isssue and I try the new code.

**Comment by corevo** [comment]
Closing for now, cc me if still relevant

**Comment by fpusersuggest** [comment]
well I reopen in becuase I think is relevant.
Those are the steps:
1) I go to https://addons.mozilla.org/en-GB/firefox/addon/selenium-ide/
2) I click add to firefox
3) I install the extension
4) I click on the button "Selenium IDE"

This is the window I've got.
![shot1](https://user-images.githubusercontent.com/6614719/39410492-750ec1ea-4bf9-11e8-9738-80431772355d.jpg)
