### ISSUE TITLE
Is it normal to only generate a manifest file in the record directory after executing yarn build? The version is 3.17.2.

### ISSUE THREAD

**Issue by ws121200** [SeleniumHQ/selenium-ide#1720]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
@ws121200 - This is normal and common for monorepos. Typically, the yarn.lock, pnpm.lock, or package-lock.json only exists in the root directory.
