### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Samyak109** [SeleniumHQ/selenium-ide#1729]
## 🐛 Bug Report

When we install exe for selenium IDE,  repeatedly this error occurs. When we click on retry it installs 
![image](https://github.com/SeleniumHQ/selenium-ide/assets/43925548/84adf0d5-c6a7-4256-bb8b-8369f6851445)

## To Reproduce

1. Download latest exe from Releases
2. Run it and you will get the error

Tried it with deleting all files previous stored in filesystem but no luck
## Expected behavior

Installation should finish without any error

## Environment

OS: Windows 10
Selenium IDE Version: Selenium.IDE.Setup.4.0.0-alpha.53
Browser:
Browser Version: Chrome Version 118.0.5993.89 (Official Build) (64-bit)

**Comment by toddtarsi** [comment]
Hm, okay, I'm going to try getting a windows VM from somewhere to try. Thanks for the heads up!

**Comment by toddtarsi** [comment]
@Samyak109 - Someone else reported this as well recently. Sorry to check in so much later, but did this clear up for you at all?

**Comment by toddtarsi** [comment]
x.58 is going out tonight, and it does a lot for making things better I think

**Comment by Samyak109** [comment]
@toddtarsi Sure I will try the latest build once you publish and then update you

**Comment by toddtarsi** [comment]
@Samyak109 - Looking pretty good to me here:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.58

**Comment by Samyak109** [comment]
@toddtarsi Getting the same error on .58

**Comment by toddtarsi** [comment]
@Samyak109 -  Damn, I'll look into incrementing the build tooling next time I hit this. Seeing as its part of the install command, it has to be something with electron-builder I think

**Comment by toddtarsi** [comment]
@Samyak109 - We are now building for each platform on the native platform, so no more building windows on mac.

https://github.com/SeleniumHQ/selenium-ide/releases

Please test and let me know how things look 🤞

**Comment by toddtarsi** [comment]
@Samyak109 - I'm closing this. I imagine its much better now seeing as it builds natively.
