### ISSUE TITLE
New project and load project button throwing error and  not launching the project in windows

### ISSUE THREAD

**Issue by mrgamedev07** [SeleniumHQ/selenium-ide#1730]
## 🐛 Bug Report
In the latest version 4.0.0-alpha.55, getting error 
 TypeError: e.setWindowButtonVisibility is not a function
![image](https://github.com/SeleniumHQ/selenium-ide/assets/73687196/5b1afc1f-882d-4a27-8525-fb99631c5ac7)

## To Reproduce

1. open the selenium ide 
2. click on new project 

## Expected behavior

project should be opened 

## Environment

OS:  Windows 10
Selenium IDE Version:  4.0.0-alpha.55
Selenium SIDE Runner Version:  4.0.0-alpha.55

**Comment by mrgamedev07** [comment]
@toddtarsi i think the function "window.setWindowButtonVisibility()" is only supported for mac os 

Here is ref: https://github.com/electron/electron/issues/19052

**Comment by toddtarsi** [comment]
@mrgamedev07 - Ah! My mistake, commit going out now to only call this on Mac. Sorry about that, I am working on making the various windows cache better across platforms, but over-optimized for mac here.

**Comment by toddtarsi** [comment]
@mrgamedev07 - Should be live in like 15 minutes on x.56

**Comment by toddtarsi** [comment]
@mrgamedev07 - Just wanted to check out how things are going. x.58 is going live tonight and just does a lot for stability and performance. Reordering is improved, recording is improved, etc. If you get the chance, please give it a whirl and if things look alright, I'll close this issue. Feel free to make any new issues for new problems.

**Comment by toddtarsi** [comment]
@mrgamedev07 - We are now building for each platform on the native platform, so no more building windows on mac.

https://github.com/SeleniumHQ/selenium-ide/releases

Please test and let me know how things look 🤞

**Comment by toddtarsi** [comment]
Closing this. I believe it's quite resolved in latest.
