### ISSUE TITLE
Side Runner does not take the variables from the previous test case in the same test suite

### ISSUE THREAD

**Issue by ianhe1** [SeleniumHQ/selenium-ide#1735]
## 🐛 Bug Report

I have a test suite that contains a number of test cases. 
test suite 1
  test case 1  -  set environment variables (one of the variables is user ID)
  test case 2 - login  (using the used ID that was set in the test case 1)
  test case 3 - carry out web page operations
  test case 4 - ....

The test runs fine in Selenium IDE
But it failed when I run from side runner
I can see that the user ID is not passed to the login test case. 

## Environment

OS: Windows 11 
Selenium IDE Version:   3.1.7
Selenium SIDE Runner Version:  4.0.0-alpha.60
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 18.16.0
Only required if using selenium-side-runner
-->
Browser:
Browser Version: Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by ianhe1** [comment]
I remember the similar test was running fine before. Could it be due to that node version? I have latest node js installed on my machine. I noticed that the side runner supports node.js 8-10

**Comment by ianhe1** [comment]
[IanheTestProject.zip](https://github.com/SeleniumHQ/selenium-ide/files/13468815/IanheTestProject.zip)
Here is the sample side file for reproduce the issue.

**Comment by toddtarsi** [comment]
@ianhe1 - Thank you for sharing repro and steps. I'll try taking a look later tonight. I probably need to adjust my handling of the variables w/r/t the persist session boolean

**Comment by ianhe1** [comment]
@toddtarsi Thank you very much Todd.

**Comment by toddtarsi** [comment]
@ianhe1 - Sorry that took a couple extra days, batched up a bunch of little improvements and fixes.

.58 is going out tonight and should be an overall improvement here. I used your side file to test, thanks for that! Please let me know your experience.

**Comment by ianhe1** [comment]
Thank you @toddtarsi for your help. I will test it out and let you know. How can I get your fix? Just reinstall the latest side runner?

**Comment by toddtarsi** [comment]
Yep! I keep publishing new versions here:

https://github.com/SeleniumHQ/selenium-ide/releases

**Comment by toddtarsi** [comment]
Oh oops, that's the IDE! Yes, there should be a new version of the side runner on npm

**Comment by toddtarsi** [comment]
`npm i selenium-side-runner@latest`

**Comment by ianhe1** [comment]
@toddtarsi Got it. I reinstalled the runner and tested your fix. It works now! Thank you very much Todd for your help in resolving this issue so quickly. Very much appreciated!
