### ISSUE TITLE
When performing batch pasting in the Selenium IDE Window client application, the content is not pasted into the selected position.

### ISSUE THREAD

**Issue by egen0805** [SeleniumHQ/selenium-ide#1736]
## 🐛 Bug Report

When pasting content in bulk in the Selenium IDE Windows client application, the content is not pasted at the selected position.

## To Reproduce

Open the Selenium IDE Windows client application.
Copy a command from another source.
Select a position within Selenium IDE for pasting.
Attempt to paste the copied content using Ctrl+Shift+V.

The pasted content is not placed in the selected position, but appears in another location, which affects the accuracy and efficiency of the pasting operation.

## Expected behavior

The pasted content should be accurately placed at the selected position.

## Environment

[Selenium.IDE.Setup.4.0.0-alpha.56.exe](https://github.com/SeleniumHQ/selenium-ide/releases/download/4.0.0-alpha.56/Selenium.IDE.Setup.4.0.0-alpha.56.exe)

**Comment by toddtarsi** [comment]
@egen0805 - Great call! I have it fixed locally and will try to push it up early tomorrow

**Comment by toddtarsi** [comment]
@egen0805 - Sorry that took an extra day, had to fix some regressions in the recorder too. I think .58 should be out in 15. I think its just an overall improvement. Please let me know your experience, thanks!

**Comment by egen0805** [comment]
@toddtarsi  Thank you for resolving this issue! I will test the improvements in version .58 and provide feedback. Thank you!

**Comment by egen0805** [comment]
@toddtarsi I have experienced the .58 version and it is working fine now. The experience is very good. Thank you for your efforts!
