### ISSUE TITLE
 SessionNotCreatedError: session not created: Chrome failed to start: exited normally.

### ISSUE THREAD

**Issue by mehrdad2000** [SeleniumHQ/selenium-ide#1741]
Hi 
on RHEL 8 minimal i try to run below command but got this error:
selenium-side-runner   mytest.side

    SessionNotCreatedError: session not created: Chrome failed to start: exited normally.
      (session not created: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)

FYI:
ChromeDriver 120.0.6099.71 
Google Chrome 120.0.6099.71
selenium-side-runner 4.0.0-alpha.60

Any idea?
Thanks

**Comment by toddtarsi** [comment]
@mehrdad2000 - This really sounds like a chromedriver issue, or something a bit below the api that selenium-side-runner wraps. 

https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t?page=1&tab=scoredesc#tab-top

I would try doing some sanity tests in your environment to make sure your chrome / chromedriver are installed and configured in a way that works on your system. To get more logging out of the side runner, you can add '-dD' which adds startup debug logging and test debug logging, but I feel this is something that you might even want to look at having a ten line test in selenium-webdriver you test this based off of.

**Comment by toddtarsi** [comment]
@mehrdad2000 - You ever figure this out? I might close this in a couple days if I don't hear back
