### ISSUE TITLE
WaitForElementPresent command is not working in selenium-side-runner 4.0.0-alpha.61

### ISSUE THREAD

**Issue by NikhilHedau** [SeleniumHQ/selenium-ide#1744]
## 🐛 Bug Report

waitForElementPresent command is passing even for a non present element locator.

## To Reproduce

selenium-side-runner waitForElementPresent.side  -c "browserName=chrome" --debug

## Expected behavior

Test should fail.

## Project file reproducing this issue (highly encouraged)

{
  "id": "aa7c65aa-fe3e-45ea-adab-267439a50f9f",
  "version": "2.0",
  "name": "Test",
  "url": "https://www.martinfowler.com",
  "tests": [{
    "id": "e9e9562d-49e9-4381-8fac-cf0f02cd5465",
    "name": "Untitled",
    "commands": [{
      "id": "4f36e10b-84b6-4a3b-b3a5-78bca1265caa",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "8e6f7909-08d2-4ddf-8c0a-42b93075705c",
      "comment": "",
      "command": "waitForElementPresent",
      "target": "linkText=Recent Chgges",
      "targets": [],
      "value": "60000"
    }, {
      "id": "1ec01d42-e30f-44e9-a970-66cc81b675de",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "2dacc401-3e89-423a-8a94-cef0305c4bdf",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["e9e9562d-49e9-4381-8fac-cf0f02cd5465"]
  }],
  "urls": ["https://www.martinfowler.com/"],
  "plugins": []
}

## Environment

OS:  MacOS(13.5.1), Chip: Apple M1 Pro
Selenium IDE Version:  Selenium IDE v4
Selenium SIDE Runner Version:  4.0.0-alpha.61
Node version: 16.18.0
Browser: Chrome
Browser Version: 120.0.6099.109 (Official Build) (arm64)
Chrome Driver Version : 120.0.6099.71

**Comment by toddtarsi** [comment]
@NikhilHedau - Thank you for including a side file, I'm off today and one kids in daycare and one is napping. Let me take a look rill quick!

**Comment by toddtarsi** [comment]
@NikhilHedau - I am doing some final testing on this branch:

https://github.com/SeleniumHQ/selenium-ide/pull/1717

I will have it merged this weekend. It fixes these issues and adds over 500 (🥵) different tests to the CI to help protect this stuff going forward.

**Comment by toddtarsi** [comment]
@NikhilHedau - It's live, resolved in latest, and heavily tested by the CI going forward. You should be good from here on 😄

**Comment by NikhilHedau** [comment]
@toddtarsi , Thanks for the update and resolving this.
