### ISSUE TITLE
Importing testsuite - Wrong order 

### ISSUE THREAD

**Issue by daniele-pecora** [SeleniumHQ/selenium-ide#175]
When importing a lagacy testsuite it requires to individually import the corresponding tests.
The tests will then be imported in the wrong order.
It has no effect if the tests are imported as a single files or over selecting multiple files.
There is also no way to re-order the tests after the import.

Would be nice to see this coming.

Importing requested test files
<img width="427" alt="individual-import" src="https://user-images.githubusercontent.com/2026072/39563204-7cea8ea4-4eaf-11e8-8e83-c194763bcc67.png">

No option to reordering the test, neither they get imported as defined in test-suite
<img width="853" alt="missing-test-ordering" src="https://user-images.githubusercontent.com/2026072/39563206-7fa7d926-4eaf-11e8-81fc-5dfb863c3883.png">

Check it out with this test-suite
[test-suite.zip](https://github.com/SeleniumHQ/selenium-ide/files/1969847/test-suite.zip)

**Comment by corevo** [comment]
Its not because of import order, or legacy test suites.  
Tests are ordered alphabetically by nature.  
The reasoning is that when you run them from CI, the order is not reliable, since they may run in parallel.

**Comment by daniele-pecora** [comment]
Wow! But that would make it impossible to have re-usable test cases.

**Comment by corevo** [comment]
Each one of them is a different `it`, and they are unique in that sense.

**Comment by daniele-pecora** [comment]
That may be true, but how do you combine more complex integration tests when you don't re-use single test?
How do you manage to name that meaningful?

By the way, that worked with the XUL Selenium IDE plugin (what we are still using).

Even running the suite from the Selenium Server Standalone keeps the order defined in the Test-Suite.

**Comment by corevo** [comment]
We have a few plans for it, firstly we want to add a setup and teardown stages in suites.  
This way the suite can focus on only testing the logic, if that won't cut it we'll do something else.

**Comment by daniele-pecora** [comment]
So you'll keep this issue closed?

**Comment by corevo** [comment]
Do you mind reposting this issue as reusing test-cases in suites?  
Because this issues title and body don't represent the underlying cause.
