### ISSUE TITLE
Record after playback resets URL

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1753]
Alpha 78 build

Record a script, starting with some home page  
![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/02aba565-7141-4b08-b062-bea357b7d43a)

Then record and navigate to another location in the script
![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/1f02f517-873f-4767-808f-51ebe981b93a)

Then play back the script, ending at the expected last URL/location

Then click record. URL is reset to initial URL

![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/692751b1-b613-40b8-844d-ceeeeda22cde)

Expected behavior is that the current URL would remain and not change to initial URL (which is the prior behavior)

**Comment by coinzdude** [comment]
log

11:15:03 AM [info] [ 'Instantiating driver builder for ', 'electron' ]
11:15:03 AM [info] [ 'Building driver for electron' ]
11:15:04 AM [info] [ 'Built driver for electron' ]
11:15:05 AM [debug] [ 'Playing state changed prep for test New Test', '' ]
11:15:05 AM [debug] [ 'Playing state changed playing for test New Test', '' ]
11:15:05 AM [debug] [ 'executing open|/' ]
11:15:06 AM [debug] [ 'passed open|/' ]
11:15:06 AM [debug] [ 'executing click|linkText=About' ]
11:15:07 AM [debug] [ 'passed click|linkText=About' ]
11:15:07 AM [debug] [ 'Playing state changed finished for test New Test', '' ]
11:15:11 AM [info] [ 'Instantiating driver builder for ', 'electron' ]
11:15:11 AM [info] [ 'Building driver for electron' ]
11:15:11 AM [info] [ 'Built driver for electron' ]

**Comment by toddtarsi** [comment]
@coinzdude - v .79 will be live shortly, and should have this resolved:

1. After playing through, the test remains on the final command instead of resetting back to the first.
2. The command pane will do a best effort scrolling to keep the active command in the viewport. This is just because it seems unpleasant to have the recorder commands scroll out of view mid recording.

**Comment by coinzdude** [comment]
@toddtarsi  Just did try https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.1-alpha.79-windows but it has the same issue

**Comment by toddtarsi** [comment]
@coinzdude - I will try reproducing your exact test. I used a suite in side-testkit as my test, and didn't cover this. Thanks for testing!

**Comment by toddtarsi** [comment]
@coinzdude - Will be resolved in next version, should be out later tonight

**Comment by toddtarsi** [comment]
@coinzdude - Resolved in x.80

**Comment by coinzdude** [comment]
Working, thanks!
