### ISSUE TITLE
Selenium 4: Select test automatically when loading project

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1755]
## 🚀 Feature Proposal

First time Selenium IDE 4.0.1-alpha loads a project, the "Selected Test" combo is empty. It would be nice if there was a way of indicate a default test that showed automatically. It would be nice too that if the project contains just one test, this test shows in the "Selected test" combo automatically.

## Motivation

Improve ease of use of Selenium IDE

**Comment by toddtarsi** [comment]
@BartolomeSintes - This was on my backlog, will do!

**Comment by BartolomeSintes** [comment]
👍

**Comment by toddtarsi** [comment]
@BartolomeSintes - This will definitely be in next version

**Comment by toddtarsi** [comment]
This is live in x.80

**Comment by BartolomeSintes** [comment]
I have tried it and it works. Thank you very much! 🥳

**Comment by toddtarsi** [comment]
Thank you for reporting!
