### ISSUE TITLE
Suggestion: Improve order of media control icons

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1761]
I think that the order of the media control icons could be improved. The current order is the following one
Before starting the test
![imagen](https://github.com/SeleniumHQ/selenium-ide/assets/1515413/5d0a39b3-c90c-47ec-9d17-c5fcfc76c36b)
During test playing
![imagen](https://github.com/SeleniumHQ/selenium-ide/assets/1515413/8df5223d-b475-4b3f-8732-32875f85e40b)
After pausing
![imagen](https://github.com/SeleniumHQ/selenium-ide/assets/1515413/3a3f79ca-6f5a-4a68-b2c2-cab4b7077f80)
I would say that the order after pausing should be Stop + Play + Record instead of Play + Record + Stop
With the current order, if you pause the test you have to move the mouse in order to continue the playing of the test. With the proposed order, you could pause and replay without needing to move the mouse.

OS: Windows 10
Selenium IDE Version: x.80 alpha

**Comment by toddtarsi** [comment]
@BartolomeSintes - Will do, I appreciate your perspective on this!

**Comment by toddtarsi** [comment]
Oh! @BartolomeSintes - This should be live in latest btw

**Comment by toddtarsi** [comment]
@BartolomeSintes - Live in 98, please close if it looks okay

**Comment by BartolomeSintes** [comment]
Solved. 👌
