### ISSUE TITLE
Why doesn't the browser plugin look the same when you run your open source project locally?   The first screenshot shows how it looks when you add the selenium-IDE plugin to your browser。The second graph is the effect of running your source code in local IDEA. Why are these two effects different?

### ISSUE THREAD

**Issue by fenglangjuxu-gansu** [SeleniumHQ/selenium-ide#1765]
![image](https://github.com/SeleniumHQ/selenium-ide/assets/37046006/9184bd20-1a9d-4029-910e-3c32bd79d47e)

**Comment by fenglangjuxu-gansu** [comment]
![image](https://github.com/SeleniumHQ/selenium-ide/assets/37046006/26acc6bc-e726-48d7-9a0a-4546f4db31c0)

**Comment by beerwin** [comment]
@fenglangjuxu-gansu : The browser plugin is version 3.x of the IDE. The source code is for the new version 4.x of the IDE, which is no longer a browser plugin but a standalone application. You should use the latter as it looks stable enough to build tests with it.

**Comment by fenglangjuxu-gansu** [comment]
> @fenglangjuxu-gansu : The browser plugin is version 3.x of the IDE. The source code is for the new version 4.x of the IDE, which is no longer a browser plugin but a standalone application. You should use the latter as it looks stable enough to build tests with it.
Thank you very much for your answer.
You mean I should use this source code to run the tests locally, right? However, I saw that most of the time the source code was committing new code to the trunk branch. Every time I pulled the new code, the local screen and functionality were always different when I launched it through the IDEA tool. So how do I use it?

**Comment by beerwin** [comment]
@fenglangjuxu-gansu 
The source code is for Selenium IDE developers/contributors. The best way to use Selenium IDE is to install it via npm. You need at least NodeJS 16.x to install it.

**Comment by fenglangjuxu-gansu** [comment]
> @fenglangjuxu-gansu The source code is for Selenium IDE developers/contributors. The best way to use Selenium IDE is to install it via npm. You need at least NodeJS 16.x to install it.
Thank you again for your answer.
I am a software developer. I want to use Selenium IDE to implement the recording and playback functions of the browser test process. I do not implement it through npm installation. Instead, I pull the source code to local startup to realize these two functions. In this way, you can Does it feel feasible? Is this method better than installing a browser plug-in? 
My job task is to develop a browser test process recording and playback function, rather than using software that has been developed by others.

**Comment by toddtarsi** [comment]
Yes, I am going to keep refining v4. V3 (webex) is unfortunately on borrowed time. There is a change set to the permission model of web extensions called manifest v3 that will be going out this year. This will disable web extensions from executing arbitrary code. A core aspect of tools like these are allowing for user supplied code snippets to be executed to make comparisons and store variables and obtain non-standard attributes and stuff, and there's basically no way to do that as a web extension anymore.

Regardless, v4 does a ton for improving user experience regardless. Local v remote playback is a ton more consistent, and the plugin interaction is vastly simplified. Although there is still some polishing that needs done. Please let me know any issues you encounter @fenglangjuxu-gansu.

@beerwin - Thank you for your help here!

**Comment by toddtarsi** [comment]
For now, I am going to close this. Thank you for opening it @fenglangjuxu-gansu and please let me know if I can help with anything.
