### ISSUE TITLE
MaxListenersExceededWarning error message in debug window

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1766]
## 🐛 Bug Report
Often, I can see several messages like this one in the debug window 
18:14:40 [error] [
  '(node:22904) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.onMutate.response listeners added to [IpcMainImpl]. Use emitter.setMaxListeners() to increase limit'
]
The error does not stop my tests, so it does not bother me, but perhaps you are interested in preventing this kind of bug. I can provide the .side file of the test or whatever information you would need.

## Environment
OS: Windows 10
Selenium IDE Version: 4 alpha 80

**Comment by edvinjunda** [comment]
I get same error message during this issue: https://github.com/SeleniumHQ/selenium-ide/issues/1763

**Comment by toddtarsi** [comment]
Thanks for calling this out guys! I'm actually going to close this because its a bit redundant with this issue, but its a top priority for me!

https://github.com/SeleniumHQ/selenium-ide/issues/1763
