### ISSUE TITLE
Failed to run npm run build selenium-ide@4.0.1-alpha.91 build:webpack: 'webpack

### ISSUE THREAD

**Issue by wzjgzcc** [SeleniumHQ/selenium-ide#1768]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by wzjgzcc** [comment]
selenium-ide-trunk\packages\selenium-ide:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  selenium-ide@4.0.1-alpha.91 build:webpack: `webpack`

**Comment by toddtarsi** [comment]
@wzjgzcc - Is this using the npm install? I must have broken things 😮‍💨 I've added a lot of tests, but I've been committing straight to trunk lately because I was debugging an auto-updater system.

Is there any more text here btw, can you paste anymore text?

**Comment by wzjgzcc** [comment]
![企业微信截图_17066738205260](https://github.com/SeleniumHQ/selenium-ide/assets/32294886/8112a49f-6589-409e-bfe2-dc647e0acd35)
npm pnpm cnpm I have tried all three types of install as shown below: Run the build command

**Comment by toddtarsi** [comment]
@wzjgzcc - Ah, okay! You are using a git clone or similar.

Try going up two directory levels (to selenium-ide-trunk) and doing `pnpm i -r; npm run build; npm run start;`. That should get you rolling in a local process version of the electron app.

**Comment by wzjgzcc** [comment]
I just executed these three commands in the directory you said and the second one reported an error as shown in the picture above @toddtarsi

**Comment by toddtarsi** [comment]
@wzjgzcc - Hm! The problem with this error is that its a downstream error, and there must be something earlier that started the issue. So let's take this one step at a time, and let me know if any step fails. From the project root, run the following commands:

1. Reset everything: `npm run clean;`
2. Install deps: `pnpm i -r;`
3. Build typescript dependencies: `npm run build:ts`
4. Build webpack bundles: `npm run build:webpack`

Screenshot the error message again.
Let me know what you get for `pnpm -v` and `node -v`.

Are you looking to develop on the IDE or simply use it?

If you're looking to develop, there's some monorepo / symlinking issue and we'll have to get your build toolchain figured out

If you're just looking to use it, there are easier ways:

You can download it via npm: `npm i -g selenium-ide; selenium-ide`
You can also download the binaries via the releases page too: https://github.com/SeleniumHQ/selenium-ide/releases/tag/v4.0.1-alpha.90

**Comment by wzjgzcc** [comment]
Develop in IDE @toddtarsi

**Comment by wzjgzcc** [comment]
@toddtarsi run to npm run build:ts as shown below
![1](https://github.com/SeleniumHQ/selenium-ide/assets/32294886/384a343a-a489-4710-baf4-2e1a6f04a37a)
![2](https://github.com/SeleniumHQ/selenium-ide/assets/32294886/ff9706c2-8f54-4a32-b148-c6285971db33)
