### ISSUE TITLE
Comments are missing from command list items

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1778]
Comments are missing in build 95 for commands
![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/9065b21e-68c1-4427-bb6d-28a090a0682b)

**Comment by toddtarsi** [comment]
Ah, dang! I'll take a look later tonight. Thanks for reporting!

**Comment by toddtarsi** [comment]
added in latest, although it needs to be a bit better tbh

**Comment by coinzdude** [comment]
Thanks!
