### ISSUE TITLE
Need line numbers in commands list

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1779]
The line numbers are missing now (build 95). Maybe this can be a configuration?

![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/75898d54-0071-412b-969e-2a1235bd25a1)

**Comment by toddtarsi** [comment]
@coinzdude - Thanks for the great issues! Yeah, it looks like my width calculation system broke in latest. I just added the resizable drawer section, so that definitely broke some stuff. I'll take a look later tonight. This should be easy

**Comment by edvinjunda** [comment]
Were there even numbers before near commands :O?

**Comment by toddtarsi** [comment]
@edvinjunda @coinzdude - This is fixed in latest. The test steps need to be above a certain width to switch it to table UX. I think I'll add a system setting to this soon to control the threshold width later, but no rush right now.

**Comment by coinzdude** [comment]
> Were there even numbers before near commands :O?

Yeah, check the screenshot above

**Comment by coinzdude** [comment]
> @coinzdude - Thanks for the great issues! Yeah, it looks like my width calculation system broke in latest. I just added the resizable drawer section, so that definitely broke some stuff. I'll take a look later tonight. This should be easy

Thanks!
