### ISSUE TITLE
Project editor window needs indicator of file name

### ISSUE THREAD

**Issue by coinzdude** [SeleniumHQ/selenium-ide#1780]
Ideally the project editor window will indicate the current open file name, or blank if not saved

e.g. Project Editor - My Side File

![image](https://github.com/SeleniumHQ/selenium-ide/assets/58857646/9718fe12-b3a1-4385-96f1-b71fd43d9f6d)

**Comment by toddtarsi** [comment]
@coinzdude - Great issue, will have it this week or next! I got a bit of quality of life improving to do around content editables and session persistence, as well as other stabilizations, but once things calm down, I'd be happy to add this on.

**Comment by toddtarsi** [comment]
added in latest

**Comment by coinzdude** [comment]
Thanks!
