### ISSUE TITLE
Window title does not change when a new project is loaded

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1786]
## 🐛 Bug Report

The Selenium IDE window title shows the path of the first loaded project (.side file). But if a second (or a third, etc.) project is loaded, the window title is not updated. It always show the path of the first loaded project.

## To Reproduce

1. Open Selenium
2. Select a project. The path of the .side file is shown in the top window title.
3. Select a different project. The path of the .side file is not updated.

## Expected behavior

The window title should always contain the path of the last opened .side file.

## Environment

OS: Windows 10
Selenium IDE Version:  4.0.1 alpha 97

**Comment by toddtarsi** [comment]
@BartolomeSintes - Fixed in v97

**Comment by toddtarsi** [comment]
*98 I mean

**Comment by BartolomeSintes** [comment]
The issue seems to be solved in alpha 98. Good work! 👍 I will close the issue.
