### ISSUE TITLE
Selenium IDE v3 support

### ISSUE THREAD

**Issue by nagik** [SeleniumHQ/selenium-ide#1789]
## 💬 Questions and Help
Hi,
I do realize Selenium IDE v4.0.x is out there, but an alpha release.  My org always prefers we use a stable release. Until a stable release is made available, will Selenium IDE 3.17.x be supported.  Most importantly, if any security vulnerability is reported on Selenium IDE v3.17.x, will that be fixed? 

Any reply or pointer will be of great help. 

-
nagendra

**Comment by toddtarsi** [comment]
@nagik - It'd have to be something pretty serious for me to care. The browser vendors have been basically pushing back the end date for manifest v3 for like 2 years now. To call the extension "living on borrowed time" is extremely accurate. Because no amount of fixing will get v3 over that.

**Comment by nagik** [comment]
Thank you for the quick response @toddtarsi. Yes, I understand that manifest v2 extensions will get scrubbed from web store.  Is it correct to assume that will be the end of support for Selenium IDE v3.17.x?

**Comment by toddtarsi** [comment]
Unfortunately yeah

**Comment by nagik** [comment]
Thank you for the confirmation.
