### ISSUE TITLE
For longer test suites, can not drag the script import window

### ISSUE THREAD

**Issue by QA1MTG** [SeleniumHQ/selenium-ide#179]
Attempting to import a large test suite (90 tests).  In chrome, the window gets cut off so that you can not see all the scripts you have to click and drag, and the OK button is not available.  
![screen shot 2018-05-03 at 9 18 06 am](https://user-images.githubusercontent.com/12834912/39578728-eb6ae3ee-4eb2-11e8-87d8-069d113577d9.png)

**Comment by corevo** [comment]
Oh boy, I didn't expect that.  
I'll add a scroller.

**Comment by QA1MTG** [comment]
Thanks.  Do I need to reinstall selenium IDE. or download the next beta version?

**Comment by corevo** [comment]
Not yet, it has been committed to the code, but is not bundled as release as of yet.  
The next release is coming very shortly.  
Releasing rapidly puts a lot of strain since we have a review process every time.
