### ISSUE TITLE
alpha 98 Bug/regression: 'open' command fails if stored variable is used in 'target'

### ISSUE THREAD

**Issue by BartolomeSintes** [SeleniumHQ/selenium-ide#1790]
## 🐛 Bug Report

Test suites that worked OK in alpha 97 do not work in alpha 98.

If an open command uses a stored value, the command fails.
For instance, the following command that worked in alpha 97 do not work in alpha 98. Selenium can not find the page.
````
                {
                    "id": "definiciones-generales-1",
                    "command": "store",
                    "target": "/consultar/php/ejercicios/bases-datos/bases-de-datos-1/bases-de-datos-1-1",
                    "value": "urlBase"
                },
                {
                    "id": "inicio-1",
                    "command": "open",
                    "target": "${urlBase}/index.php",
                    "value": ""
                },
                {
                    "id": "inicio-2",
                    "command": "waitForElementPresent",
                    "target": "xpath=//h1[.=\"Bases de datos (1) 1 - Inicio\"]",
                    "value": "20000"
                }
````
Selenium IDE screenshot
![imagen](https://github.com/SeleniumHQ/selenium-ide/assets/1515413/8af6d942-3f40-4973-bfc6-d4daff63a523)

But if no stored value is used, the test works fine.
````
                {
                    "id": "inicio-1",
                    "command": "open",
                    "target": "/consultar/php/ejercicios/bases-datos/bases-de-datos-1/bases-de-datos-1-1/index.php",
                    "value": ""
                },
                {
                    "id": "inicio-2",
                    "command": "waitForElementPresent",
                    "target": "xpath=//h1[.=\"Bases de datos (1) 1 - Inicio\"]",
                    "value": "20000"
                }
````

## To Reproduce

Download and execute the attached two .side files. The one with stored value does not work properly in alpha 98, but works fine in alpha 97.

## Expected behavior

I expected no error

## Project file reproducing this issue (highly encouraged)
(remove the .txt part added in order to attach the files)
[test-1-issue.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/14301896/test-1-issue.side.txt)
[test-2-issue.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/14301451/test-2-issue.side.txt)

## Environment

OS: Windows 10
Selenium IDE Version: 4.0.1 alpha 98

**Comment by toddtarsi** [comment]
@BartolomeSintes - This is a great issue. I know exactly how to fix, thanks for reporting it!

**Comment by toddtarsi** [comment]
@BartolomeSintes - This is resolved in x.99

**Comment by BartolomeSintes** [comment]
Problem seems to be solved in x.99. Thank you very much. 👍
