### ISSUE TITLE
Can't open Selenum Ide on Mac

### ISSUE THREAD

**Issue by fgcui1204** [SeleniumHQ/selenium-ide#1791]
## 💬 Questions and Help
Can't open Selenum Ide on Mac M1;

Selenum ide version: [4.0.1-alpha.98](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v4.0.1-alpha.98)

Error Snapshot:
<img width="295" alt="image" src="https://github.com/SeleniumHQ/selenium-ide/assets/8295896/4a4e2dfe-ee75-4c8b-8fbe-0a9383ad42f3">

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
@fgcui1204 - Ah shit, it looks like it started a chromedriver process but didn't kill it.

Did it exit ugly in any way on the last run? 

To get unstuck, do this in terminal:

```
pkill -9 chromedriver;
```
That will clear out any instances of electron-chromedriver that are still running.
It will work on the next run. I'll work on a UX to address possible zombie chromedrivers.

Thanks for reporting!

**Comment by edvinjunda** [comment]
Ending task with task bar manager also helps. Zombie chromdrivers usually appear after selenium crashes

**Comment by fgcui1204** [comment]
Thanks @toddtarsi , It's working now
