### ISSUE TITLE
Selenium-IDE 4 on MacOS: Unable to startup due to chromedriver error:  

### ISSUE THREAD

**Issue by vonlaughing** [SeleniumHQ/selenium-ide#1814]
I'm running on a MacOS and downloaded 4.0.1-beta.5 (Selenium-IDE-4.0.1-beta.5.dmg specifically) but is unable to open it.
<img width="264" alt="image" src="https://github.com/SeleniumHQ/selenium-ide/assets/38173379/b59e803f-089f-453d-989d-0dc0dfcb2a3d">
It is giving me this error. 

Previously I installed the webextension from here https://chromewebstore.google.com/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd
I deleted the extension but the problem still persists.

I was wondering if anyone have any idea what the problem is? Much appreciated!

**Comment by toddtarsi** [comment]
Yes, sorry, there is an issue in beta.5 🤦, beta.4 is functional.

**Comment by vonlaughing** [comment]
> Yes, sorry, there is an issue in beta.5 🤦, beta.4 is functional.

Thank you for helping me! I downloaded beta.4 but unfortunately the problem still exists :( .
<img width="256" alt="image" src="https://github.com/SeleniumHQ/selenium-ide/assets/38173379/b065bb10-b85b-4299-a9f4-6998b05f50bb">

**Comment by toddtarsi** [comment]
@vonlaughing - Thank you for reporting. A fix is going out for this in five or so minutes, and then a new version will be live in 30. I'm sorry, this was a goofy mistake on my part. Basically, the logging api called the logging api, which kinda repeated until it all crashed. That won't happen anymore. Thank you for your patience.

**Comment by toddtarsi** [comment]
Eh, taking a bit to clear CI, but I promise clean version coming up

**Comment by vonlaughing** [comment]
Thank you!!

**Comment by toddtarsi** [comment]
@vonlaughing - It's in review here: https://github.com/SeleniumHQ/selenium-ide/pull/1816

Basically, we're looking at adding Chinese localization alongside the fixes. Thanks again for reporting!

**Comment by vonlaughing** [comment]
@toddtarsi I installed the new 4.0.1-beta.8 version but it is still giving me the same error :(
<img width="263" alt="image" src="https://github.com/SeleniumHQ/selenium-ide/assets/38173379/3c2e11a7-5265-4ea8-9d2e-4be5dd32a892">

**Comment by toddtarsi** [comment]
@vonlaughing - Sorry to take a long time to respond, took a weekend away. Can you try restarting your computer and seeing if it works? If so, I will start working on a feature so that the app recovers more gracefully. Basically, if a chromedriver server is already running, we currently crash. It can lead to bad crashes causing more bad crashes because a rogue chromedriver process is blocking a port. Restarting your computer could kill those bad processes. If that fixes it, I will work on a fix to ask about killing any servers on startup if a collision is encountered.

**Comment by vonlaughing** [comment]
> @vonlaughing - Sorry to take a long time to respond, took a weekend away. Can you try restarting your computer and seeing if it works? If so, I will start working on a feature so that the app recovers more gracefully. Basically, if a chromedriver server is already running, we currently crash. It can lead to bad crashes causing more bad crashes because a rogue chromedriver process is blocking a port. Restarting your computer could kill those bad processes. If that fixes it, I will work on a fix to ask about killing any servers on startup if a collision is encountered.

Thank you!!!!! Restarting the computer did it!

However after running chrome the same error occurred, even if I kill the chrome process. Currently I can only run the app right after restarting my computer. Thank you for your help!!

**Comment by toddtarsi** [comment]
@vonlaughing - Okay, not ideal but perfect that we know the cause. I'll start working on a system to kill running chromedriver processes on startup so that won't be necessary in the future.
