### ISSUE TITLE
Error logging in Selenium IDE (version 3.17.2) 

### ISSUE THREAD

**Issue by TJSWANS300** [SeleniumHQ/selenium-ide#1838]
Hi.

For Selenium IDE (version 3.17.2), is there a way in which we can just filter out errors in the log?

Example:
- Have a Test Suite that runs for around 8 hours and would just like to see any errors that are returned in the log

**Comment by TJSWANS300** [comment]
Any update on this?

**Comment by toddtarsi** [comment]
@TJSWANS300 - I don't think so. v3 is pretty much at EOL, and this capability isn't in my plan for v4. It wouldn't be too bad to add, but it doesn't interest me.

**Comment by toddtarsi** [comment]
@TJSWANS300 - Closing this since we are discussing it further in the next issue
