### ISSUE TITLE
Selenium IDE Failed To Capture Select2 dropdown Elements

### ISSUE THREAD

**Issue by Manikandan-1712** [SeleniumHQ/selenium-ide#1842]
We have noticed that the Selenium IDE extension fails to capture the dropdown action and the selected value from the Select2 dropdown. We kindly request you to look into this issue and provide a permanent fix in a future update.

1. Issue happening for select2 dropdown
2. Multi select dropodwn
3. Filter dropdown which uses select2

## To Reproduce

1. Start Record 
4. Click dropdown which uses select2 as element
5. observe no entries for clicked and option selected 

## Expected behavior - 

should have click command for dropdown click and options click 

.side File not having entry for the select2 clicked events and selected dropdown options

## Environment

OS: Linux  '6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Selenium IDE Version:  3.17.2

Browser: Chrome
Browser Version: 124.0.6367.78 (Official Build) (64-bit)

**Comment by toddtarsi** [comment]
This sounds like something a plugin should address. I'm not interested in fixing components on a case by case basis.

**Comment by toddtarsi** [comment]
Actually I remember writing this exact plugin back on v2 😆 

They use non-standard html, there's no way that sorta thing should be in core
