### ISSUE TITLE
Error on installation and run

### ISSUE THREAD

**Issue by ilhamibrahimvaultdragon** [SeleniumHQ/selenium-ide#1843]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

I have this error : 
PS D:\DdDet\newDdDet\selenium-ide> pnpm -r i
Scope: all 22 workspace projects
Lockfile is up to date, resolution step is skipped
 WARN  Failed to create bin at D:\DdDet\newDdDet\selenium-ide\packages\code-export-csharp-nunit\node_modules\.bin\side-code-export. ENOENT: no such file or directory, stat 'D:\DdDet\newDdDet\selenium-ide\packages\side-code-export\dist\bin.js.EXE'
 WARN  Failed to create bin at D:\DdDet\newDdDet\selenium-ide\packages\code-export-csharp-commons\node_modules\.bin\side-code-export. ENOENT: no such file or directory, stat 'D:\DdDet\newDdDet\selenium-ide\packages\side-code-export\dist\bin.js.EXE'
 WARN  Failed to create bin at D:\DdDet\newDdDet\selenium-ide\packages\code-export-java-junit\node_modules\.bin\side-code-export. ENOENT: no such file or directory, stat 'D:\DdDet\newDdDet\selenium-ide\packages\side-code-export\dist\bin.js.EXE'
 WARN  Failed to create bin at D:\DdDet\newDdDet\selenium-ide\packages\code-export-ruby-rspec\node_modules\.bin\side-code-export. ENOENT: no such file or directory, stat 'D:\DdDet\newDdDet\selenium-ide\packages\side-code-export\dist\bin.js.EXE'
 WARN  Failed to create bin at D:\DdDet\newDdDet\selenium-ide\packages\code-export-csharp-xunit\node_modules\.bin\side-code-export. ENOENT: no such file or directory, stat 'D:\DdDet\newDdDet\selenium-ide\packages\side-code-export\dist\bin.js.EXE'
 WARN  15 other warnings
Done in 1.4s

Thus giving me this error :
PS D:\DdDet\newDdDet\selenium-ide> pnpm run start

> selenium-ide-monorepo@ start D:\DdDet\newDdDet\selenium-ide
> cd packages/selenium-ide && npm start

> selenium-ide@4.0.1-beta.12 start
> electron build/main-bundle.js

npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: selenium-ide@4.0.1-beta.12
npm ERR!   at location: D:\DdDet\newVD\selenium-ide\packages\selenium-ide
 ELIFECYCLE  Command failed with exit code 1.

Anything I miss? Can you please help?

**Comment by toddtarsi** [comment]
Hm, I'm not sure. Did you do all the build steps here?

https://github.com/SeleniumHQ/selenium-ide?tab=readme-ov-file#building

**Comment by ilhamibrahimvaultdragon** [comment]
yes, I did

**Comment by toddtarsi** [comment]
What is the output from the build command?

**Comment by toddtarsi** [comment]
@ilhamibrahimvaultdragon -

That error message is fine on the install. You're not using those bin files, and if you were, you wouldn't be using em in the node modules folder. You could just run them at the compiled locations. 

If you need those bin files to be in the node_modules folder instead of just at like packages/[package-name]/dist/bin.js or something like that, just rerun pnpm -r i after you build, and the linking will work that time. It's an extra step I should write down, but it's fine without really. It's just a warning message.

What I'm interested in is if the build finished without error.
What happens if you run `npm run build`

What are the file contents of packages/selenium-ide/build?

**Comment by toddtarsi** [comment]
Closing this in a few days

**Comment by toddtarsi** [comment]
Without underlying build output, nothing can be done here. Closing next week.
