### ISSUE TITLE
Can’t export code because of store title syntax not working.

### ISSUE THREAD

**Issue by AdrienVerstrepen** [SeleniumHQ/selenium-ide#1844]
## 🐛 Bug Report 

When I have any tests that get the title using the store title command I can’t export it to Javascript Mocha for no reasons. 

## To Reproduce 

Create a new test containing « store title » 

## Expected behavior 

When I choose to export my test it should be exported not saying that the store title problem is waiting for something in the target slot. 

## Project file reproducing this issue (highly encouraged) Issues without a reproduction project are likely to stall. 

[Bug report.side.json](https://github.com/user-attachments/files/15901753/Bug.report.side.json)

(just remove the .json for the file to work correctly in the web extension)

## Environment 
OS: Ubuntu 22.04.4 LTS with Gnome 42.9
Selenium IDE Version: 3.17.2 (web extension)
Browser: Chrome
Browser Version:  126.0.6478.55 (official build) (64 bits)

**Comment by toddtarsi** [comment]
Alright, I'm going to propose a slightly silly workflow. I don't really maintain v3 anymore, but if you want to try v4, I think I'd be able to help there. 

If you have nodejs, you can do this to get everything you need:

`npm install -g side-code-export side-migrate @seleniumhq/code-export-javascript-mocha`

Then, you can do something like the following (probably can be better done, but you get the idea):

1. `side-migrate ./project-v3.side ./project-v4.side` (this will migrate v3 commands to v4 as needed)
2. `side-code-export @seleniumhq/code-export-javascript-mocha ./project-v4.side ./tests` (export your tests)
3. `mocha ./tests` (run your tests)

**Comment by AdrienVerstrepen** [comment]
Ok thank you for your answers.

The commands you gave didn't work but I find a workaround that I'm sharing here if anyone need it :
```bash
npm install -g side-code-export @seleniumhq/code-export-javascript-mocha
```
```bash
npm install -g @seleniumhq/side-migrate
```
And then what you gave should work in theory.

**Comment by toddtarsi** [comment]
Awesome, nice job sleuthing! Sorry I borked that package name.
