### ISSUE TITLE
Opening old test cases

### ISSUE THREAD

**Issue by lcsqlpete** [SeleniumHQ/selenium-ide#185]
I used Selenium a while back and created several test cases and test suites.  Is it possible to open them in this version?
Thanks,
Pete

**Comment by Jongkeun** [comment]
Could you upload your test files?

**Comment by corevo** [comment]
Yes you can migrate old suites and test cases to the new version.

**Comment by lcsqlpete** [comment]
OK, figured it out.  None of the old files had file extensions so they were greyed out in the file open dialog. They were created a while back in Firefox.  I added a .html file extension to them and now they open fine.
