### ISSUE TITLE
Select target in page doesn't work in Chrome

### ISSUE THREAD

**Issue by lcsqlpete** [SeleniumHQ/selenium-ide#186]
I cannot get the Select target in page to recognize any elements on a web page.  I click the button, then switch to the web page with the element I want to select, but clicking anything just executes the normal action for a link, button or whatever, and nothing turns up in the Selenium Target field for the command.  

The command I'm trying to complete is assert element present.

I've tried this while the recorder is running and when it is not.

Is this a known bug or am I doing something wrong?

Thanks,
Pete

**Comment by corevo** [comment]
Definitely not, the only reason I can think of is that you opened the page prior to opening the IDE.  
Try refreshing and selecting again.  
If not please send a video or step by step guide to recreate this, as its working on my end.

**Comment by corevo** [comment]
I've added a specific warning in these cases [here](https://github.com/SeleniumHQ/selenium-ide/commit/c685159b5709a6ba83e31dea8ab751c23833eea6)

**Comment by kriegaex** [comment]
Sorry for asking about a closed ticket, but what about HTTPS domains? Nowadays most web sites do not use unencrypted HTTP anymore. For me this functionality fails on URLs starting with `https://`.

**Comment by heather-cunningham** [comment]
I can't get it to work in Firefox Developer Edition either.
