### ISSUE TITLE
More of a question than an issue, clickAt vs click

### ISSUE THREAD

**Issue by 98gmarquee** [SeleniumHQ/selenium-ide#187]
I notice that when recording that the new IDE tends to use clickAt with x,y coordinates vs just click. I never used clickAt much. What are the x,y coordinates referencing? The location of the element on the screen or where it clicks in relation to the actual x,y of the element on the screen?

Is there a reason why it uses clickat vs click?

Thanks.

**Comment by corevo** [comment]
Where it clicks in relation to the element.  
Unless your element checks the click position at the event, theres not much of a difference.  
You may freely change it to click and remove the coordinates.
