### ISSUE TITLE
Hi from the Kantu for Chrome / Selenium IDE "Light" team

### ISSUE THREAD

**Issue by A9T9** [SeleniumHQ/selenium-ide#19]
I see that you are working on a new Selenium IDE -great.

We at [a9t9](https://a9t9.com/) have started work on a browser automation extension a few months ago. This extension implements the Selenium IDE concept and the most common commands are supported already, with more to follow soon (for example variable support, assertions will be available with the next update).  

- [Install link](https://chrome.google.com/webstore/detail/kantu-browser-automation/gcbalfbdmfieckjlnblleoemohcganoc)

- [Homepage](https://a9t9.com/kantu/web-automation/chrome) with some background info and project status

- Code (open-source): [Github](https://github.com/A9T9/Kantu-for-Chrome)

Our extension borrows key concepts and commands from the original Firefox IDE and if we can return a few things now, even better.

If there are no direct follow up questions, you are welcome to close the ticket after reading. Just wanted to make sure you are aware of our work and the option to (re)use it :-)

Best,
Mathias

**Comment by zavelevsky** [comment]
Thanks. As we don't plan to merge entire project setup, are there any specific parts you think I should consider using?

**Comment by barancev** [comment]
I should note that Kantu has "sticky" GPL license, so we hardly can take and reuse any part of it

**Comment by zavelevsky** [comment]
good catch. I guess we'll close it then.
We welcome any contribution via PR of course.

**Comment by A9T9** [comment]
>...are there any specific parts you think I should consider using?

Hi... at this stage, I do not have a specific part in mind. Look around and if you need anything take it (see my comments about the license below). Likewise, if I come across a part that I think you _should_ take I will ping you again ;-)

>I should note that Kantu has "sticky" GPL license, so we hardly can take and reuse any part of it

At least at this stage, we (a9t9) own 100% of the copyright, so we can donate any part of the Kantu code to your project under any license you need (e. g. Apache). So the GPL license will be no problem - just ping me if you want to reuse certain parts now or later.
