### ISSUE TITLE
Running IDE 3.0.2 script headless using command line

### ISSUE THREAD

**Issue by rakeshqq** [SeleniumHQ/selenium-ide#194]
Hi,
I am new to Selenium. I recorded a script using IDE 3.0.2 and able to replay/run it successfully. Is there any way to run this script by scheduling it. I also dont find way to run it using command line so that I can put into batch or cronjab.
I can see lot of such features in older IDE 2.9.1-fx but dont find in IDE 3.0.2. 
Seeking help and guidance to run my test with scheduled and Command line option

**Comment by rakeshqq** [comment]
Thanks very much for update. It might sound stupid question but
1.  is there any wiki or instruction for upgrading my existing IDE to this new Beta Release.
2. What will be command syntax?

Thanks
RR

**Comment by corevo** [comment]
1. In the [README](https://github.com/SeleniumHQ/selenium-ide/blob/master/README.md) you can see the instructions of installing [as developer](https://developer.chrome.com/extensions/getstarted#manifest).  
2. The up to date runner README is [here](https://github.com/SeleniumHQ/selenium-ide/blob/extensibility/packages/selenium-side-runner/README.md)

**Comment by Lube** [comment]
I manage to get all working, except for headless mode for the side runner? Does this involve a capability?

**Comment by corevo** [comment]
What error are you getting?

**Comment by Lube** [comment]
I ended up hardcoding the capability in src/index.js

``` 
const configuration = {
  capabilities: {
    browserName: "chrome",
    chromeOptions: {
      args: ['headless']
    }
  },
  path: path.join(__dirname, "../../")
};
```
Trying to create a clean docker enviroment, Im finding this issue:
 FAIL  ./LoginFlow.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'quit' of undefined

      at WebdriverEnvironment.teardown (../node_modules/jest-environment-selenium/dist/index.js:32:30)
          at Generator.throw (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        60.215s
Ran all test suites.


This is my dockerfile

FROM ubuntu:16.04

RUN apt update
RUN apt install xvfb curl wget unzip libxi6 libgconf-2-4 libnss3 -y

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt update
RUN apt install nodejs -y

RUN wget -N http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -P ~/
RUN unzip ~/chromedriver_linux64.zip -d ~/
RUN rm ~/chromedriver_linux64.zip
RUN mv -f ~/chromedriver /usr/local/bin/chromedriver

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt update 
RUN apt install google-chrome-stable -y

WORKDIR /home/ubuntu
RUN mkdir selenium-side-runner
COPY ./selenium-side-runner /home/ubuntu/selenium-side-runner

WORKDIR /home/ubuntu/selenium-side-runner

**Comment by Lube** [comment]
After commenting the teardown line, Im getting this error

```
WebDriverError: unknown error: Chrome failed to start: exited abnormally
      (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-39-generic x86_64)

      at Object.checkLegacyResponse (../node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../node_modules/jest-environment-selenium/dist/index.js:46:17)
      at WebdriverEnvironment.setup (../node_modules/jest-environment-selenium/dist/index.js:25:32)
```

**Comment by Lube** [comment]
After setting --no-sandbox, and --headless, now Im battling yet another error:

```
/home/ubuntu/selenium-side-runner/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

WebDriverError: no such session
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.13.0-39-generic x86_64)
```

**Comment by Lube** [comment]
Finally got it working with  --no-sandbox and xvfb

```

const configuration = {
  capabilities: {
    browserName: "chrome",
    chromeOptions: {
      args: ['no-sandbox']
    }
  },
  path: path.join(__dirname, "../../")
};
```

xvfb-run node dist/index.js test.side

**Comment by corevo** [comment]
@Lube is that what you were looking for?  
xvfb does run Chrome with head, it's just virtual so you don't see it on the display.

**Comment by corevo** [comment]
Closing since OP's issue was answered.

**Comment by cemol** [comment]
@Lube, Where did you find the capability in src/index.js? I am getting the same error as you. But where is the src/index.js located?
