### ISSUE TITLE
[Feature request] Command reference tab

### ISSUE THREAD

**Issue by bdy-combine** [SeleniumHQ/selenium-ide#199]
It would be nice like in Selenium IDE 2.x to have the Reference tab to be able to see the parameters for the commands.

So when you are traveling through the commands you are able to see the details in the reference tab for that selected/active command.

**Comment by corevo** [comment]
Yes! I know it's missing and it's definitely on my mind to fix.

Cheers,
Tom

**Comment by bdy-combine** [comment]
Really nice,  thx!

Cheers.
