### ISSUE TITLE
Would you consider combining efforts and building one extension?

### ISSUE THREAD

**Issue by FDIM** [SeleniumHQ/selenium-ide#2]
I've done quite some work on e2e test builder: https://github.com/cuubas/e2e-test-builder and I think it could be used as a base for selenium ide and built further. 

I've posted about this in selenium developer google group, but it seems like my post is not getting approved - at least this will be visible :)

**Comment by zavelevsky** [comment]
Can you please do so by means of a PR to this repository? If possible, please do it in separate increments so that we can examine the different areas separately (e.g. we might think the record library is amazing but have opinions against the ui)

**Comment by FDIM** [comment]
I'd like to keep this open until you (or someone else) decides what to do. The work I've done is a bit too far to submit as PRs as it is in a working condition just needs to be built further

**Comment by zavelevsky** [comment]
Agreed. As we discussed, you will look again for a solution to FS access that doesn't require a local client and we will continue in a couple of days.
Question: what are you reading/writing from the file system?

**Comment by FDIM** [comment]
as it is now, extension reads/writes test case files. It supports selenium ide html format (basically a html table) and proprietary protractor/jasmine spec file (dumps json + runnable code). It is also able to read both of them.

**Comment by bcmoney** [comment]
Just wanted to put this Chrome extension on the radar as well: http://sideex.org/

Seems they are actively working to replace missing SeleniumIDE functionality in FF by releasing a new WebExtension-based plugin soon. Why not have all these splintered groups come together under the original SeleniumIDE name? Also going to ping their Devs...

**Comment by zavelevsky** [comment]
@bcmoney coincidentally, I stumbled upon sideex today.
I already emailed the author asking for his approval to use it as start point.
It is distributed under Apache license - so it's more of a courtesy.
We are now reviewing their code - it requires work (cleaning, properly bundling, and more).
We will soon merge it to this repository.
BTW, the extension can be loaded on Firefox - but with Mozilla there's the case of their addon approval process.

**Comment by FDIM** [comment]
Alright, you can close this issue as it seems you've chose another extension as a base. At least consider adding 'special attribute' locator as one of the strategies when you reach that point.

**Comment by zavelevsky** [comment]
@FDIM I completely agree.
Regarding the special attribute - can you please open a separate issue?
Regarding clean slate - we are modernizing everything. We use rollup for proper build and packaging process, we will probably go with React for the view layer. We will use modern JS but not TypeScript, at least at the beginning. I don't want to force it on anyone. I personally like TS BTW.

**Comment by FDIM** [comment]
Sounds like you have a solid plan. Anything against angular-cli/angular? I find it quite convenient, I am not sure if you looked at the codebase but I was able to use it even for background / content scripts :) Didn't have to do anything special except few gulp tasks.
