### ISSUE TITLE
Firefox, Windows: When saving project location of file, it needs to be found each time

### ISSUE THREAD

**Issue by bdy-combine** [SeleniumHQ/selenium-ide#201]
On Firefox (59.0.3) on Windows 10 when I save the Selenium IDE project, I need to find the location each time to save it. It would be nice if plugin kept track on location for storing the file, så each time something needs to be stored on harddrive, it would try opening default this filelocation.

Maybe saving should have 2 options. "Save as" or just "Save" - but that might be a Feature Request.

**Comment by corevo** [comment]
I know it's annoying, but the current extension format doesn't let me know where was the project loaded from.  
Thus I can't save to that location again, which in turn forces you to navigate to that directory every time.  
The best solution I have atm is to create shortcuts in the default directory to convenient places.

**Comment by charlestonsoftware** [comment]
@corevo - would it be possible to provide an option on the UI where the user can type in the directory?  Similar to the base URL option? 

It would be an extra step for the user, but at least it is only an extra step the first time the project is setup.
