### ISSUE TITLE
some UI scripts(like Twitter widget) may be broken by Selenium IDE

### ISSUE THREAD

**Issue by hiroshitoda** [SeleniumHQ/selenium-ide#205]
I found this issue when using Google Chrome and accessing to https://dev.twitter.com/web/embedded-timelines with Selenium-IDE installed environment.
In this page, Twitter widget cannot be displayed properly with below error:

```
Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null
    at n (widgets.js:9)
    at i.<anonymous> (widgets.js:9)
    at i.<anonymous> (widgets.js:8)
    at i.run (widgets.js:8)
    at i.flush (widgets.js:8)
    at i.runBatch (widgets.js:8)
    at widgets.js:8
    at t (widgets.js:8)
    at widgets.js:8
```

I'm afraid that it would be caused by injected element like `<div id="selenium-highlight"></div>` and it would be found in executing other UI scripts.

**Comment by corevo** [comment]
Do you have an example that doesn't use an uglified version of `widgets.js`?

**Comment by corevo** [comment]
I have an idea, instead of adding the `div` on the beginning I'll add and remove it per request for highlight.  
That should substantially reduce the friction.

**Comment by hiroshitoda** [comment]
> Do you have an example that doesn't use an uglified version of widgets.js?

No, I don't. Sorry.

> I have an idea, instead of adding the `div` on the beginning I'll add and remove it per request for highlight.
> That should substantially reduce the friction.

I agree to your idea. I think it's just one way to solve this issue.

**Comment by hiroshitoda** [comment]
@corevo Thank you for your great work!
