### ISSUE TITLE
how to convert selenium ide command to python in latest version?

### ISSUE THREAD

**Issue by makarun007** [SeleniumHQ/selenium-ide#211]
in older version i click file->Export test case menu to convert my selenium ide command to java/python. 
But in newer version i doesn't know how to get?. can any one pls help me?

**Comment by corevo** [comment]
Duplicate of #131

**Comment by taufanbagusdpa** [comment]
> in older version i click file->Export test case menu to convert my selenium ide command to java/python.
> But in newer version i doesn't know how to get?. can any one pls help me?

i cannot see export to python in my selenium IDE

**Comment by tourdedave** [comment]
Code export for Java is currently all that's available. Python is coming next. You can track the progress of code export in #592.
