### ISSUE TITLE
selenium-side-runner : "error:   The project Untitled Project is of older format"

### ISSUE THREAD

**Issue by vijayg78** [SeleniumHQ/selenium-ide#212]
Hi,
I installed the latest version of IDE and selenium-side-runner. But I get the error that

**""error:   The project Untitled Project is of older format, open and save it again using the IDE.""** 

when trying to run the command

**selenium-side-runner -c "browserName=chrome platform=MAC" test4.side**

I tried installing the beta version of IDE, but still getting the same error. Any hint on how to resolve this error?

Regards, Vijay

**Comment by corevo** [comment]
What versions are you using?

**Comment by vijayg78** [comment]
The IDE version is - 3.1.0
selenium-side-runner version is 0.6.0

both of them got installed today.

**Comment by corevo** [comment]
Try using 0.5.0, I took down the 6th beta from here, but I can't unpublish it from npm

**Comment by vijayg78** [comment]
Will check that and let you know. Thanks for the hint.

**Comment by Name-less** [comment]
Hello, i have the same issue using the version 0.7.0 and IDE version 3.1.1 (both newly installed), do you have any news on this ?

**Comment by corevo** [comment]
I stripped the feature from 3.1 because it wasn't ready yet, I'll bring it back for 3.2.  
I'll post another beta soon.

**Comment by venkat-rafay** [comment]
@corevo Where can I find release dates for future versions or get notified of future releases?

**Comment by corevo** [comment]
We are an open source project based on volunteer work, we don't offer release dates other than as soon as it is complete.  
Release changelog is available on [GitHub](https://github.com/SeleniumHQ/selenium-ide/releases), if you watch the project you'll be notified whenever a release is pushed.

**Comment by BlinkBolt** [comment]
I downloaded an installed the beta IDE for Chrome for Windows and installed the beta SIDE Runner on Red Hat Enterprise Linux 7.5, and now I'm getting this error:

$ selenium-side-runner eRA\ Websites.side
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'quit' of undefined

      at WebdriverEnvironment.teardown (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:30)
          at Generator.throw (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.218s
Ran all test suites.

$ 

NOTE: I did recreate the .side file from scratch with the beta IDE.

BTW, this is the output from installing SIDE Runner on Red Hat Enterprise Linux 7.5:

# npm install -g selenium-side-runner@beta
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
/usr/bin/selenium-side-runner -> /usr/lib/node_modules/selenium-side-runner/dist/index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/selenium-side-runner/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ selenium-side-runner@3.2.0-beta.1
updated 3 packages in 19.786s
#

**Comment by BlinkBolt** [comment]
I installed chromedriver and selenium-webdriver, and I'm now getting the following errors on Red Hat Enterprise Linux 7.5:

$ selenium-side-runner eRA\ Websites.side
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    WebDriverError: unknown error: DevToolsActivePort file doesn't exist
      (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-862.3.2.el7.x86_64 x86_64)

      at Object.checkLegacyResponse (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        60.473s
Ran all test suites.

$

**Comment by BlinkBolt** [comment]
I tried running selenium-server-standalone-3.13.0.jar with the following command line:

$ xvfb-run java -Dwebdriver.chrome.driver=/bin/chromedriver -jar /usr/local/bin/selenium-server-standalone-3.13.0.jar

That part seems to work fine.

Then running SIDE Runner with this command line (in another window):
$ selenium-side-runner --debug --server http://localhost:4444/wd/hub eRA\ Websites.side

I got this error:

 FAIL  ./Default Suite.test.js (14.368s)
  Default Suite
    ✕ jira (11854ms)

  ● Default Suite › jira

    TypeError: Assignment to constant variable.

      13 | });
      14 | beforeEach(() => {
    > 15 |   vars = {};
         |   ^
      16 | });
      17 | afterEach(async () => (cleanup()));

      at Object.<anonymous>.beforeEach (Default Suite.test.js:15:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        14.74s, estimated 15s
Ran all test suites.

Does this work at all?

**Comment by corevo** [comment]
Looks like you are using 3.2 beta 2 of the runner with IDE 3.2 beta 1
Export the test case again.

Cheers,
Tomer

**Comment by BlinkBolt** [comment]
I upgraded the Selenium IDE for Chrome for Windows to 3.2.0-beta.2 and re-saved the .side file and now it works!!!

**Comment by BlinkBolt** [comment]
One thing: When I test with an intentionally bad URL ("https://**jirax**.era.nih.gov" instead of "https://**jira**.era.nih.gov") it takes a very long time to timeout.  Is there a way to shorten the timeout?

**Comment by tourdedave** [comment]
I ran into a similar issue with an error on teardown. In my case it was a `ReferenceError`. I've logged the issue in #301.

**Comment by BlinkBolt** [comment]
Everything was working fine with 3.2 beta 2 side-runner with IDE 3.2 beta 2, but I just upgrade them both to 3.2.2 and upgrade selenium-server-standalone.jar from 3.13 to 3.14.  I created a new brand ".side" file with the IDE in Chrome for Windows ran in under Red Hat Enterprise Linux 7.5. and got this:

$ xvfb-run java -Dwebdriver.chrome.driver=/bin/chromedriver -jar /usr/local/bin/selenium-server-standalone-3.14.0.jar >/dev/null 2>&1 &
$ selenium-side-runner eRA\ Websites.side
● Validation Warning:

  Unknown option "testEnvironmentOptions.capabilities" with value {"browserName": "chrome", "platform": "LINUX"} was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "testEnvironmentOptions.params" with value {} was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "testEnvironmentOptions.runId" with value "fd5538b47942b8886f8eaf217ab6198e" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "testEnvironmentOptions.path" with value "/usr/lib/node_modules/" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "testEnvironmentOptions.server" with value "http://localhost:4444/wd/hub" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "testEnvironmentOptions.timeout" with value 15000 was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    SessionNotCreatedError: Unable to create new service: ChromeDriverService
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: 'eraopsccmon201p.era.nih.gov', ip: '165.112.230.76', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.6.3.el7.x86_64', java.version: '1.8.0_181'
    Driver info: driver.version: unknown

      at Object.checkLegacyResponse (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:626:16)
      at buildDriver (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.738s
Ran all test suites.
