### ISSUE TITLE
"type" command is not recorded at certain cases.

### ISSUE THREAD

**Issue by izawatk** [SeleniumHQ/selenium-ide#214]
I recorded following action.

1. Open google.(https://www.google.com/)
2. Input search keyword at search box.
3. Press Enter key.
   And search result is displayed.

When running the test case, search keyword is not input and 
search result is not displayed.
Only "open" and "click at" command is recorded at IDE.

And then, we tried to click "Google Search" insted of pressing Enter key.
As a result, "type" command is recognized and search result is displayed.

We tested Other site(ex.yahoo), and the result is OK.
Is this behavior expected?
Is this issue related to #168 and #208?

Chrome version: 66.0.3359.181
Selenium IDE version: 3.0.3

**Comment by corevo** [comment]
Not really, there is a caveat with the type command that sometime it doesn't get picked up.  
It depends on the way the web application handles the change in the input.  
To get around this, quoting from the [docs](https://www.seleniumhq.org/docs/02_selenium_ide.jsp#recording):
> 
The type command may require clicking on some other area of the web page for it to record.
>
