### ISSUE TITLE
Import Suite: Can't click and drag multiple test cases into IDE at same time

### ISSUE THREAD

**Issue by QA1MTG** [SeleniumHQ/selenium-ide#217]
Attempting to import a suite that has about 15 tests.  I attempted to highlight all tests in my file folder and drag them into the import screen, and it is not successful.  I have to pull one file at a time. I feel like this was working at one time, either it was my imagination or something changed.

**Comment by corevo** [comment]
It is the intended behavior, and it may be a regression, I'll take a look.

**Comment by Dukuu-Wild** [comment]
Also i noticed the following, **STR:**
import suite, see dialog to import testcases
press browse, choose some testcases, including some, that are not related to this suite.
**ER:** not related cases are skipped when dialog is confirmed
**AR:** on confirmation, no cases are analised/imported when there are "other" test cases than those expected by testsuite.

This may be also the reason that drag and drop doesn't work for you? @QA1MTG

**Comment by corevo** [comment]
@QA1MTG I can't reproduce the behavior

**Comment by corevo** [comment]
@Dukuu-Wild fixed the behavior you have explained in 3e0b6069.

**Comment by QA1MTG** [comment]
Thanks guys

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
