### ISSUE TITLE
IDE: Doesn't appear to be a way to import additional files to an imported suite

### ISSUE THREAD

**Issue by QA1MTG** [SeleniumHQ/selenium-ide#218]
After importing a suite to the IDE, if I want to add additional older Selenium IDE test case files and convert them to work with the existing suite, there doesn't appear to be a way to do this.  If I click the + button, it will ask me to name a new test case, but I can't import an additional case to the suite

If I attempt to open an additional file, the suite will be replaced by the single file
If I attempt to add a new test case, it will allow me to name a new case but it will be empty

**Comment by corevo** [comment]
I think that if you open an old test case, it may be worthwhile to add it to the tests, rather than to create a new project for it.

**Comment by QA1MTG** [comment]
Thanks.  Is there an ETA for the next release?

**Comment by corevo** [comment]
I really wanna land two more features in this release,  
If I can't do that in a timely manner, I'll publish a release without them.
