### ISSUE TITLE
Open url with variable in it.

### ISSUE THREAD

**Issue by 98gmarquee** [SeleniumHQ/selenium-ide#226]
Probably outside the norm, but I build url's with variables from data to open various pages. It seems I can't open such a url.

I store the value in a variable, then use the normal Open|${variableName}| command and it says 
`"Failed:
 is not a valid URL."`

I don't think it's seeing the url. If I use echo|${variableName}| I see the url.

Would be similar to doing something like the following
store|https://www.google.com|tempUrl
open|${tempUrl}|

**Comment by corevo** [comment]
I'm aware of this issue, it requires fundamental changes to the way `store` commands work.  
It's definitely something we plan on fixing.

**Comment by 98gmarquee** [comment]
Thanks for the update. I will keep an eye out for that as I use it in most of my scripts to open a custom internal jsp that I pass a web server name, database name and record ID into via multiple variables to pull/verify data from a database directly.

**Comment by dkhaye** [comment]
I'm also very interested in seeing this functionality available.
I'm in the process of trying to upgrade my QA Suite to use the new Selenium IDE and having this functionality would save me a lot of time where I wouldn't have to refactor tests to navigate to the right URL from the home page.
