### ISSUE TITLE
Convert old tests in the new format

### ISSUE THREAD

**Issue by BorderCloud** [SeleniumHQ/selenium-ide#23]
Hello

I have a lot of tests with the old selenium ide (firefox 54). 
How convert my old tests in the new format ?

Thanks
Karima

**Comment by zavelevsky** [comment]
1. Did you try to open them and fail?
2. We plan to support the old IDE format. Haven't gotten there yet.
Leaving this issue open as a TODO.

**Comment by BorderCloud** [comment]
There is not error (I didn't see) but it doesn't work.
I looked the format HTML with a new test is not exactly the same.

**Comment by zavelevsky** [comment]
OK, thanks for the info - we will try to get there ASAP.
Please consider attaching the tests you are trying to use so we will make sure the fix works once it's ready.

**Comment by BorderCloud** [comment]
example of files : https://gist.github.com/BorderCloud/908dccf53663b453c5fa7cde5e981d8b
- simple test
- test suite

**Comment by corevo** [comment]
Can I use this in our automated tests?  
It will require putting the file in the repository (also means the license has to comply with the repo's license)

**Comment by BorderCloud** [comment]
No problemo
Say me when I can test your new version.
