### ISSUE TITLE
Base URL problem

### ISSUE THREAD

**Issue by alFrame** [SeleniumHQ/selenium-ide#231]
First I'd like to express my deeps gratitude for making a Selenium IDE version that works in the new FireFox. I really appreciate this!

Bare with me, I am a pure user with some hacking ability. I use Selenium to login to the WordPress websites I maintain and switch to a specific page in the dashboard to then run a backup. I manged to import the old projects into the new Selenium IDE, but I am facing one issues.

Description: It seems impossible to add the base URL to the open command. The base URL has to be chosen from the pull down menu on top of the right part of the UI. I get that. This makes working with it a bit cumbersome because I have to select the base URL, then select the job (which in my case contains switching to the WordPress login page, enter the login/password and then switches to the BackupBuddy page) and then run that test. Very cumbersome is to switch to the next website, because once a base URL is entered, the pull-down only shows that one base URL.

**Question: Is it somehow possible to enter the base URL with the open command?**

Plus one very annoying issue with the UI. On the left is the list of tests. That window gets wider if the mouse floats above it. Then it gets narrower if the mouse leaves that area. This makes the right part of the UI shift left, thereby moving the play button. This happens with a delay, so aiming for the play button has to be done twice. I wish I had a screen capture possibility. Hoping you get what I mean.

**Comment by 98gmarquee** [comment]
Could use alt+prntscrn before and after then attach them. I use this a lot as a very light screen grab app that lets you put annotations/boxes around things after selecting:
http://www.ducklink.com/

**Comment by alFrame** [comment]
Thanks for the link. Unfortunately the download has a "Error establishing a database connection". On Windows I could use the sniping tool, but then again a video would be needed to explain the issue correctly.

**Comment by corevo** [comment]
Well, if you wanna enter a base url in the open command just use an absolute url.  
The idea we are taking the base url with is one url per one application.  
So each Selenium IDE project should correspond to a single application, there are caveats with this design and we are throwing ideas at how to achieve more flexibility with the design, while keeping the simplicity.  
That being said, if you have a dozen tests working on the same base url, that's more than fine, the one that isn't can just use an absolute url instead.  
On the other hand, if each of your test has a different url, I'd either break them into different Selenium IDE projects, or define them all with absolute urls, as long as its **maintainable!**

**Comment by alFrame** [comment]
Corevo, thank you for getting back on this! So you're saying I should enter nothing into the base URL and enter the full URL into the open command, right?

I did try that using http://, www only, noth together, with a slah at the end etc. but Selenium kept coming back saying "Trying to execute open on http://blah.com/wp-admin... Failed: Is not a valid URL."

I also changed the test name, since the name of the test, presumably coming form the title data in the imported html, contained the URL as well.

To no avail.

The only way the test works if there's a correct URL in the base URL and the open contains everything after the base URL e.g. bas URL: http://blah.com and the open command /wp-admin/.

Seems that Selenium IDE doesn't want full URL's in the open command. Or I am missing something.

**Comment by corevo** [comment]
![image](https://user-images.githubusercontent.com/888886/41415240-c80522c0-6ff0-11e8-8606-50a05ea65c22.png)
This will open wikipedia instead of google.  
I'll make sure that if the base url is empty but the open target is valid, it'll pass,  
For the time being the work around is to have a dummy base url, and set the absolute one in the target.

**Comment by alFrame** [comment]
Corevo, Thanks again. That works! Very cool!
