### ISSUE TITLE
Slashes in URLs and Xpath

### ISSUE THREAD

**Issue by schunt1** [SeleniumHQ/selenium-ide#233]
Hi, I am just starting to try this new selenium-ide for some of my legacy scripts.  I am struggling with the / in Xpath and URLs being replace by &#x2F;  when I open the scrip in the IDE.  Is there a trick or tip to get around this?
Thanks Si

**Comment by corevo** [comment]
I don't understand the issue, a `/` is replaced with a `/`?

**Comment by schunt1** [comment]
Hi
I have attached two images to explain the issue.  You'll see in the old version it shows "xpath=//span[contains(text(),'Log Out')]" in the target, in the new version it replaces the / with the hex character code &#x2F; i.e. "xpath=&#x2F;&#x2F;span[contains(text(),&#x27;Log Out&#x27;)]"

I hope that explains it better.  Thanks for you help.

![selenium_ide_new](https://user-images.githubusercontent.com/2545233/41435893-2a1055d2-6fee-11e8-8c66-89dac76976a2.jpeg)
![selenium_ide_old](https://user-images.githubusercontent.com/2545233/41435899-2e5cf3f2-6fee-11e8-9df3-80826d77e10a.jpeg)

**Comment by schunt1** [comment]
I should also mention I'm opening a legacy HTML file.  I notice that your new file format is JSON, so if I convert these files that should work.

**Comment by corevo** [comment]
That's exactly what it's doing, there must be an issue with encoding, I'll make sure to take a look.

**Comment by corevo** [comment]
I'm unable to reproduce the issue, can you reproduce the issue and upload a test case?
![image](https://user-images.githubusercontent.com/888886/41898408-a444feaa-7932-11e8-963e-78a1d9a537b2.png)

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
