### ISSUE TITLE
StoreEval missing

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#234]
Hi,

The StoreEval command is missing in the Selenium IDE Firefox Version 3.0.3.0.

Thank you by advance for this add.
AyaSF

**Comment by corevo** [comment]
Duplicate of https://github.com/SeleniumHQ/selenium-ide/issues/138#issuecomment-378153014

**Comment by AyaSF** [comment]
ok, replace it with this command :

<tr>
	<td>store</td>
	<td>javascript{ command of old storeEval }</td>
	<td>dateToday</td>
</tr>
