### ISSUE TITLE
Type does'nt work anymore with input readonly

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#235]
Hi,

In the Selenium IDE Firefox version 3.0.3.0, it is not anymore possible to use the type command with a readonly input.

Could you fix that?

Thank you very much by advance,
AyaSF

**Comment by corevo** [comment]
If the input is readonly, you shouldn't be able to `type` in it, that is the intended behavior.

**Comment by AyaSF** [comment]
It was possible in the previous selenium.
And that serves me a lot for test cases.

For example, a readonly input with a calendar.
And in my case, i always want the same date 12/06/2018.
Every month the calendar change, so i can't make a test to choose a date in a calendar that can be reusable. Except if i can type in the input.

Could you reopen this issue please? 

Thank you by advance.
AyaSF

**Comment by corevo** [comment]
According to the [W3C WebDriver spec](https://www.w3.org/TR/webdriver/#elements), element that is readonly will not be typed to.  
I'm sorry but this is the current intended Selenium behavior.  
More over I have tested it myself with Selenium 3.6.0 and reached the same conclusion.

**Comment by AyaSF** [comment]
I use selenium ide every day, so i assure you it was possible in the previous ide version on firefox 54.

I understand you want to follow rules. But it's for me a necessary functionality.
So thank you for your great job on this version, but unfortunetly I have to reuse the old one.

Good continuation !

**Comment by corevo** [comment]
Perhaps you could try using `runScript` to make the input editable, and then make it readonly after setting to value, to not interfere with the application.

**Comment by AyaSF** [comment]
Thanks a lot for the tip. I'll try it tomorrow. ;)

**Comment by AyaSF** [comment]
resolve with runScript before.
