### ISSUE TITLE
Unable to import with <!---- comment

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#237]
Hi,

It is not possible to import an old test if it contains this string  : 
With Selenium IDE Firefox version 3.0.3.0

Could you fix this?

Thank you by advance.
AyaSF

**Comment by corevo** [comment]
I've asked the community to give me an example test case containing a comment here https://github.com/SeleniumHQ/selenium-ide/issues/107#issuecomment-371515963.  
If you can reduct any information you can't share, and post a test case just like that, I'll get working on it right away.

**Comment by Dukuu-Wild** [comment]
Hello, @corevo .
Here is a sample file with comment with several dashes:
[!Log in as test user.htm.zip](https://github.com/SeleniumHQ/selenium-ide/files/2111194/Log.in.as.test.user.htm.zip)
And a screenshot with an error: http://i.prntscr.com/C4GZyUUjQYSA0JviPwkQEg.png
Thanks for your work!

**Comment by corevo** [comment]
Thanks!
