### ISSUE TITLE
Add assert value to recording context menu

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#238]
Hi,

Is it possible to add the assert value command on the right click?
With Selenium IDE Firefox version 3.0.3.0

Thank you by advance,
AyaSF

**Comment by corevo** [comment]
Yes you definitely can, when you're recording a test case, you'll see that a new Selenium IDE menu will show on right click, from which you can easily add assertions.
![image](https://user-images.githubusercontent.com/888886/41429605-3c5ebef4-7016-11e8-9e50-279f1b9de7f3.png)

**Comment by AyaSF** [comment]
Yes i see this menu.

But there is no "assert value" command in this list.
Could you reopen this issue please.

Thanks a lot by advance,
AyaSF

**Comment by corevo** [comment]
Of course!

**Comment by toddtarsi** [comment]
Closing, as 3.x won't be around much longer
