### ISSUE TITLE
Not stop anymore on assert command

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#239]
Hi,

Is it possible to stop the test when an assert command returns false?
With Selenium IDE Firefox version 3.0.3.0

Thank you by advance.
AyaSF

**Comment by hohnan** [comment]
Was just running a test today and noticed the same thing. Assert element present is performing the same as verify element present. It should end the test case on the spot.

**Comment by corevo** [comment]
Duplicate of #89.  
This is a long await fix, it's already in master, and will go live in 3.1.0, sorry for the long wait.

**Comment by AyaSF** [comment]
Sorry for the duplicate issue and thank by advance for your fix.
