### ISSUE TITLE
Firefox 57+ Support

### ISSUE THREAD

**Issue by rhessinger** [SeleniumHQ/selenium-ide#24]
Since Firefox has changed their extension model, can you guys update this to work in the the newer versions of Firefox Developer Edition 57+?

**Comment by corevo** [comment]
Yes, we plan on supporting the webextension standard, specifically firefox and google chrome

**Comment by contorax** [comment]
Please advise how to install and add Selenium IDE to Firefox Developer Edition 57.0b8   or Firefox  Quantum 57.ob.11

**Comment by zavelevsky** [comment]
One way to do it now is to run through the extension build process (clone the repo, ran yarn and yarn build), then open Firefox, go to addons, click the settings button and choose debug add-ons, then click to load from a file and navigate to /build/manifest.json

it's a WIP :)

**Comment by UsernameIsAlreadyTakenByMe** [comment]
Hi, please share the build if it's working :)

**Comment by corevo** [comment]
Currently you will have to build it yourself from one of the [releases](https://github.com/SeleniumHQ/selenium-ide/releases).  
We are working on bundling into crx

**Comment by nischt** [comment]
When can we expect the selenium build which supports firefox version 57 and above.

**Comment by corevo** [comment]
We are planning on a major release in the very near future.

**Comment by nischt** [comment]
Any rough ETA for that.I was ooking for Python selenium builds

**Comment by corevo** [comment]
I'll update an ETA when I have one, I can say its nearing very fast.  
Exporting the IDE project to Selenium python code is not part of this release.

**Comment by nischt** [comment]
Thanks for the update.
I was actually looking for next package after selenium-3.8.0.tar.gz which has support for Firefox 57 and above.
Hope that will be available.

**Comment by barancev** [comment]
@nischt Selenium 3.8.0 for python is available:
https://pypi.python.org/pypi/selenium/3.8.0

But why do you ask about this package in IDE subproject?

**Comment by nischt** [comment]
This verison is avaliable but currently it does not have enhancements to support firefox 57.
Thats why I was asking the ETA of this selenium build.

**Comment by barancev** [comment]
@nischt What enhancements do you mean exactly?

**Comment by seelamk** [comment]
Me too eagerly waiting for latest IDE for Firefox 57.0x...
Can you suggest with a link to download older Firefox which supports IDE.

**Comment by 98gmarquee** [comment]
I use 54.0.1 64 bit: https://filehippo.com/download_firefox_64/76360/

Really hoping that when this new version gets built, we can still use the old IDE scripts as I have hundreds that I use for day to day front end testing. In my spare time, I try to learn what I can with selenium core, but the IDE does so much for me and I have so little time to learn/rewrite all my scripts that I will keep a portable version of 54.0.1 as long as I can.

**Comment by corevo** [comment]
You can get the latest Firefox beta [here](https://github.com/SeleniumHQ/selenium-ide/releases).  
We are working on more features from the old IDE, and working on publishing it to Mozilla's Addons Store, in the mean time use that link to install it manually.

**Comment by 98gmarquee** [comment]
@corevo Thanks! I didn't realize there was an actual build yet.

The naming convention is odd. But I was able to open a simple html sel script and run some of it. Awesome to see progress!

Wonder what the odds of Samit Badle redoing his additional IDE add-ons. I've come to rely on those as well with the IDE. His highlight is nice so you can see page activity as well as the pause a suite on error vs what the IDE did by default which was fail out of the current script and just starting the next one.

Not sure who made the ide sidebar, but I like that as well vs having it in it's own popup.

Funny how you don't realize how much you rely on something until it's gone.

Great work guys!

**Comment by samitbadle** [comment]
Thanks! It is always nice to hear when people are using my addons. Last time I checked, my addons were downloaded more than 1.5 million times. Given their popularity, I will definitely try to create them for the new IDE. I am still researching what features are possible with the restrictions that the browsers now impose on the addons.
- Samit Badle

**Comment by olds97lss** [comment]
@samitbadle If you start a thread for it, please let me know. I'd like to follow it to see the progress.

Thanks!
