### ISSUE TITLE
Test Execution Order

### ISSUE THREAD

**Issue by MStahl15** [SeleniumHQ/selenium-ide#240]
## Meta -
OS:  Windows 10
Selenium Version:  Selenium IDE 3.0.3.0
Browser:   Firefox (should apply to all)

## Feature Request -
Ability to drag and drop tests within a test suite into a specific order before running the entire suite.  

This would be a great feature since a lot of objects have to be created in a specific order in projects.

**Comment by corevo** [comment]
Duplicate of #127
