### ISSUE TITLE
Not able to import the same test script more than once in a test suite.

### ISSUE THREAD

**Issue by RiniTapasya** [SeleniumHQ/selenium-ide#244]
## Meta -
OS:  
Win 7 64bit.
Selenium IDE Version:  
 V3.0.3
Browser:  Mozilla Firefox 

Browser Version:  
 60.0.2

## Expected Behavior - New Selenium IDE V3.0.3 should behave the same like V2.9.1. In old version I was able to create test suite which contains the same test script imported many times. Eg : "User login" Test script, wherever the user can login. 
In a test suite I've used this script at many places. 

## Steps to reproduce -
1. Import test suite "File" of Selenium IDE V2.9.1 in V3.0.3. The dialog occurs. 
The dialog shows the test script present in old selenium. It contains "User login" Test script repeated many times.
2. Import Userlogin test script. A tick mark occur corresponding to first "Userlogin" test script.
Try to import again Userlogin test script. No tick mark occurs for Userlogin which is present second time in the test suite. 

Note : In this test suite we've used the same test script "Userlogin" at 5places. The tick mark occurs only for 1 User login and remaining 4 remains unticked. 
So new test suite doesn't get created automatically by closing the dialog.

**Comment by Dukuu-Wild** [comment]
It is also Related to #224. But here it is much more detailed =)

**Comment by RiniTapasya** [comment]
Issues I am facing is, not able to import same test case like login or logout again and again in the same test suite which was possible earlier.
Test cases are present in alphabetical order and I am not able to change the order of execution. 

WHEN IT IS FIXED PLEASE LET US KNOW. DO IT IN HIGHER PRIORITY BASIS.

**Comment by RiniTapasya** [comment]
No error is occurring. :( It is like the test scripts are accepted by getting ticked. Once it get ticked it automatically try to open the test scripts in selenium IDE dialog. But it is still in progress of displaying the test scripts and not opening in selenium IDE.

**Comment by corevo** [comment]
I need more to go on, can you recreate the issue with a dummy suite and post it here?
