### ISSUE TITLE
SyntaxError: Unexpected identifier (async setup() { in selenium-side-runner\node_modules\jest-environment-selenium\dist\index.js:23)

### ISSUE THREAD

**Issue by saefren** [SeleniumHQ/selenium-ide#251]
## Meta -
OS:  Windows 10
Selenium IDE Version:  3.1.0 beta7
Browser:  Chrome
Browser Version:  Version 67.0.3396.87 (Official Build) (64-bit)

## Expected Behavior -
Expected the test to succeed.

## Actual Behavior -
Getting a syntax-error, see full output:
PS D:\Projects\SomeProject\testing\regression> selenium-side-runner --server http://server:4444/wd/hub SomeProject.side
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    C:\Users\foobar\AppData\Roaming\npm\node_modules\selenium-side-runner\node_modules\jest-environment-selenium\dist\index.js:23
      async setup() {
            ^^^^^

    SyntaxError: Unexpected identifier

      at C:/Users/foobar/AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-runner/build/run_test.js:39:29

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.04s
Ran all test suites.

## Steps to reproduce -
Nothing special, first attempt to a basic test. I created a side file using Selenium IDE with one test with a few simple steps (I simply recorded clicking some links). I added this test to the Default suite and saved it to SomeProject.side.

**Comment by corevo** [comment]
What's your node version?

Cheers,
Tom

**Comment by saefren** [comment]
6.1.0

I just upgraded node before doing all of this, here's the output (still have cmd open)

PS C:\Program Files\nodejs> npm-windows-upgrade
npm-windows-upgrade v4.1.0
? Which version do you want to install? 6.1.0
Checked system for npm installation:
According to PowerShell: C:\Program Files\nodejs
According to npm:        C:\Users\foobar\AppData\Roaming\npm
Decided that npm is installed in C:\Program Files\nodejs
Upgrading npm... -

Upgrade finished. Your new npm version is 6.1.0. Have a nice day!

**Comment by saefren** [comment]
Makes sense. I thought I had the latest but apparently not! Let me retry with version 10.x (current release).

**Comment by corevo** [comment]
Cheers!
