### ISSUE TITLE
TinyMCE/CKEditor gets div (.selenium-highlight) inserted when Selenium IDE is simply enabled

### ISSUE THREAD

**Issue by khoallaby** [SeleniumHQ/selenium-ide#255]
## Meta -
OS:  
Win 10
Selenium IDE Version:  
3.0.3

Browser:  
firefox/chrome

Browser Version:  
latest -- ffx 59 / chrome 67

## Expected Behavior -
Don't generate/append this code please

## Actual Behavior -
Simply having Selenium IDE ENABLED... (it doesn't even need to be actively running/used) will insert/generate extraneous code in rich texting editors like TinyMCE and CKEditor

## Steps to reproduce -
Open up any page that contains an instance of TinyMCE or CKEditor. Check the "source" version of the editor to see that the following code is inserted:

```
&nbsp;
<div id="selenium-highlight"></div>
```

If the "source code" version of the editor is initially selected, this bug won't work. BUT if you switch to Visual/non-source, and then back to source code, the div above gets inserted still

**Comment by khoallaby** [comment]
Huge issue for people that use CMSes or these text editors in general, and because it's caused by simply having Selenium enabled (not even running). This random div and nbsp can cause extra spacing/formatting issues.

**Comment by Dukuu-Wild** [comment]
Confirm this issue, encountered on drupal-7 CMS in CKE editor fields.
We encountered it several month ago, and had to disable Selenium plugin in work broswer.
Thanks to khoallaby for reporting!

**Comment by corevo** [comment]
This is the same error as described by #205.  
It is fixed but unreleased, I'm planning on a release in the very near future.

**Comment by Dukuu-Wild** [comment]
> I'm planning on a release in the very near future.
that's great news!
As this problem just today caused another issue for me and loss of time on investigation.
 Just disabling plugin helped.

**Comment by khoallaby** [comment]
Woohoo thanks!!
