### ISSUE TITLE
Giving a warning message when pressing F5 in selenium IDE

### ISSUE THREAD

**Issue by DannyvdMee** [SeleniumHQ/selenium-ide#256]
## Meta -
OS:  
Windows 10
Selenium IDE Version:  
3.0.3.0

Browser:  
Firefox
Browser Version:  
60.0.1 (64-bits)

## Expected Behavior -
Give a little warning when you are accidentally pressing F5 when your current project haven't been saved
## Actual Behavior -
When pressing F5 no warning is displayed and everything that isn't saved will be lost
## Steps to reproduce -
1. Open Selenium IDE for FireFox
2. Do something
3. Press F5 and no warning message is displayed if you want to save your work

Note: If this is a duplicate I'm sorry I didn't saw this issue inside the issues list

**Comment by DannyvdMee** [comment]
First I boot up Selenium IDE.
Then I'm opening an **existing** .side project
I edit something and press F5
No warning message is shown

When having a blank selenium file a warning message is indeed shown to warn about losing data.

But when opening an exsisting file, and edit it it will not be shown

**Comment by corevo** [comment]
I was able to reproduce this, and will work on a fix.

**Comment by DannyvdMee** [comment]
Alright, Thankyou for your time and effort
