### ISSUE TITLE
Recording new steps in a test case, they do not insert where selected, rather appear at the bottom. 

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#260]
## Meta -
OS:  

Selenium IDE Version:  

Selenium SIDE Runner Version:  

Node version:  

Browser:  
Chrome
Browser Version:  

## Expected Behavior -
Newly recorded steps should be inserted where select step is, not at the bottom
## Actual Behavior -
Steps are appended to bottom of test case when new recording, then they have to be copied to the desired location. For very long cases this is difficult.  Also before they used to insert where selected, so it seems like the recording is not working.  I have a long monitor and was able to see them at the bottom.
## Steps to reproduce -
Record several steps, leaving out one, such as a verify.  Then select the spot where you want to verify things, then record the verify or new click.  Nothing appears where you select, rather they are inserted at the end of the test case.

**Comment by saradhit** [comment]
@corevo is the code fix available in Selenium IDE 3.1.0? if not when this will be available to use, i recorded few steps today in 3.1.0 and it is still adding at the bottom

**Comment by corevo** [comment]
Fixed in 3.1.1 the update is already pushing to everyone

Cheers,
Tomer

**Comment by saradhit** [comment]
@corevo Great... Thanks.
