### ISSUE TITLE
Chrome IDE lacks parity with Firefox IDE

### ISSUE THREAD

**Issue by luquitia** [SeleniumHQ/selenium-ide#262]
## Meta -
OS:  Windows 10
Selenium IDE Version:  3.1.0 (latest)
Browser:  Chrome vs. Firefox (both current versions)
Browser Version:  Chrome 67.0.3396.87 vs. Firefox 59.0.2 (64-bit

## Expected Behavior -
Chrome version of this Sel-IDE plugin should work same as Firefox Sel-IDE plugin (at least in terms of playing scripts).

## Actual Behavior -
Chrome Sel-IDE has significant lag behind Firefox Sel-IDE capabilities:
1. Chrome is missing some implicit wait coding for pages to load and a script that runs fine in Firefox at normal (top) speed fails consistently in Chrome at the same normal (top) speed. If I reduce the speed to about 80% in Chrome, I am able to run that script.
2. Chrome lacks 3.1.0 support for "execute script" command, which is working fine in Firefox. Chrome gives error like, "executeScript on z = new Date(); var x = z.getYear(); var y = x + 1900; return y with value year... Undetermined  Aborting..."

## Steps to reproduce -

1.  Slowness upon signing in and trying to click next element fails for Chrome (at top speed), but works fine in Firefox (at top speed); I'm accessing an internal QA URL, applying to job, signing in and the next element (that fails in Chrome due to speed) is:
{
      "id": "2134e85c-7b8a-404a-aa16-d014e85ed1e6",
      "comment": "",
      "command": "click",
      "target": "id=startapply",
      "value": ""
    }

2. Example of execute script command passing in Firefox, but failing in Chrome:
{
      "id": "4c1de468-582c-40a5-95eb-baeecfb86c51",
      "comment": "",
      "command": "executeScript",
      "target": "z = new Date(); var x = z.getYear(); var y = x + 1900; return y",
      "value": "year"
    }

**Comment by corevo** [comment]
Next time please split the issues.  
1. A reason for a behavior like this is most likely app specific, because unlike 2, it is not an error that reproduces itself on every page. Without an example to go over it'll be hard for me to reproduce this case.  
2. The issue is known to me, and I'm already working on a fix.

**Comment by luquitia** [comment]
1 is sort of app-specific (in the way our app handles "pages" & some rendering slowness), but is also clearly a code difference between Chrome and Firefox IDE. It fails frequently and on various pages in Chrome at normal (top) speed, but consistently passes in Firefox (same script) at same speed.  If I have time, I'll log a separate ticket with more details on that.

2. good to know, thanks!
