### ISSUE TITLE
where is "store eval"? "run script" not working. How to eval javascripts in Selenium IDE?

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#264]
## Meta -
OS:  

Selenium IDE Version:  

Selenium SIDE Runner Version:  

Node version:  

Browser:  

Browser Version:

**Comment by corevo** [comment]
`store eval` is deprecated because of security issues. please move to `execute script` or `execute async script`, they can put the result on a variable.  
Next time please fill in the Meta, as well as the other sections, or the issue will be closed.

**Comment by cemol** [comment]
Ok, but why does not this work: 
store    javascript{"joe+" + Math.floor(Math.random()*11111) + "@gmail.com";}    var
echo    ${var} 

And, where is Meta?

**Comment by cemol** [comment]
or this:
**execute script**    javascript{"joe+" + Math.floor(Math.random()*11111) + "@gmail.com";}   var
**echo**                  ${var}

**Comment by corevo** [comment]
Look at the issue, the Meta is empty.  
As I said `store` that evals javascript has security issues.  
When you use execute script you have to return at the end, don't use the `javascript{}` preprocessor.

**Comment by cemol** [comment]
Thank you!
