### ISSUE TITLE
[Question] A plan for making the commands

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#266]
You know if you saw the old selenium code, he had combined several command keywords to create a command at the old selenium.
So he could create many commands easily.
For example, `store` + `Alert`, `store`+`Attribute`, `store`+`Checked`...

There was tons of the commands which made like this.
We could make each of these commands, but I thought they were a waste of time.

What do you think about this?

**Comment by corevo** [comment]
Making a lot of commands is a waste of time, considering we have other features to do.  
Instead I'm adding commands as I see fit (usually if more commands are needed to support a feature, or if someone asked for it).  
If you wanna add more commands be my guest, but in the future I plan on moving to #230 which will make the `Selenium` prototype useless.

**Comment by Jongkeun** [comment]
I asked because I don't wanna make a lot of commands too.
If will be your plan, it is so nice.
I hope to be made soon.
