### ISSUE TITLE
Function verifyText

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#270]
## Meta -
OS:  OSX
Selenium IDE Version:  3.1.1
Browser:  
Browser Version:  
Firefox 60

## Actual Behavior -

In the old version of SELENIUM (2.9) we can use the function verifytext with a sort of containt. For this i use text to look for with * after

Now it's impossible

![moz-extension__2](https://user-images.githubusercontent.com/40666727/42039151-04d6a4ce-7aed-11e8-9094-c3dcd5f36f68.jpg)

**Comment by tourdedave** [comment]
We're aware of this issue and tracking its progress in #141.
