### ISSUE TITLE
Pb with action with message after

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#271]
## Meta -
OS:  OSX
Selenium IDE Version:  3.1.1
Browser:  
Browser Version:  Firefox 60

## Actual Behavior - 

On the old version (2.9) I had a suite of code to simulate a clic on a button and then manage the different messages to follow

Now when i use the same code, when this arrive on the line simulating the click on the button, the test hangs and does not go further (but i have the message whis yes / no) 

![moz-extension___db9f514d-27b1-6e4b-bb8a-7147e3c91782_-_selenium_ide_-_imported_project_](https://user-images.githubusercontent.com/40666727/42039339-6e0c6d02-7aed-11e8-81a1-88063285413f.jpg)

**Comment by corevo** [comment]
> on the old version I had a suite of code to simulate a clic on a button and then manage the different messages to follow

Is the expected behavior (you even said on the old version), please reformat your issue.  
I don't understand what do you mean by blocks on the line?  
Does the IDE not click it? does the button appear on the page? how do I reproduce this?  
Please make sure the issue is filled to the fullest

**Comment by corevo** [comment]
The yellow line means the IDE is executing the command? Did you wait for the IDE to complete the execution?

Cheers,
Tomer

**Comment by rob1gr** [comment]
yes i wait but the test is blocking in this step. Actualy i use the same test with 2.9 and it's OK and there is no modification in the application i'm testing

**Comment by corevo** [comment]
Wait until the IDE reports back the error

Cheers,
Tomer

**Comment by rob1gr** [comment]
I wait but there isn't no reports. this stay on the line and in the log the step : click on id=deleteButton ...

you can see on the new screenshot the application with the message after click on deleteButton on the selenium ide window
![moz-extension___db9f514d-27b1-6e4b-bb8a-7147e3c91782_-_selenium_ide_-_imported_project__et_addenachat](https://user-images.githubusercontent.com/40666727/42043147-006499ec-7af6-11e8-8659-cec03a2f1002.jpg)

**Comment by corevo** [comment]
There is a limitation with the current architecture of Selenium IDE.  
alerts, confirmations and prompts halt the IDE's execution, for that reason we added two new commands:  
- `choose cancel on next confirmation`
- `choose ok on next confirmation`  
You need to place the correct one before the `click` that initiates the alert.

**Comment by rob1gr** [comment]
it's not good for me. the message is not reconize

**Comment by corevo** [comment]
I don't understand your comment, you need to place either of the commands I've mentioned out before the click.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
