### ISSUE TITLE
Select Command is not working in Firefox-IDE 3.1.0

### ISSUE THREAD

**Issue by saradhit** [SeleniumHQ/selenium-ide#272]
Hello,
Select command is not selecting a drop down item. Below are the required details. Let me know if you need more information. Thanks in advance.

## Actual Behavior - Not selecting the drop down item even after providing the index of the list item.
When this step is executed, Log shows Select on css=css=span.k-input...OK and successful 

## Steps to reproduce  -
Record a script using Selenium IDE on Firefox Browser and try to select a drop down item from any drop down box.

Command: Select
Target: css=span.k-input
Value: listitem5

**Comment by corevo** [comment]
The `select` tests run daily.  
![image](https://user-images.githubusercontent.com/888886/42100286-76073ace-7bc8-11e8-86d4-b3a5a6371f6d.png)
As far as I see it, the problem is with the specific `select` that you are testing, please provide better steps to reproduce the problem.

**Comment by saradhit** [comment]
@corevo Click command with List item fixed my issue. Thank You.
