### ISSUE TITLE
Invalid CSS selector for class

### ISSUE THREAD

**Issue by SpyMachine** [SeleniumHQ/selenium-ide#273]
## Meta -
OS:  10.13.5
Selenium IDE Version:   3.1.0
Browser:  Chrome
Browser Version:  67.0.3396.99

## Expected Behavior -
Expect selector to have valid CSS

## Actual Behavior -
Selector has invalid CSS

## Steps to reproduce -
I was able to reproduce this issue with the following HTML snippet:
```
<html>
  <body>
    <span class="text">TEXT</span>
    <div>
      <a href="http://google.com">
        <span class="content "> 
          <span class="text">CLICK ME</span>
        </span>
      </a>
    </div> 
  </body>
</html>
```

By clicking on the link with Selenium IDE recording you will receive the following target: `css=span.content. > span.text`. This is invalid CSS and causes an exception if you try and use that selector in WebDriver. The extra '.' after 'content' is the culprit and should just be dropped.

I did a little sleuthing and apparently the space in "class=content " is the problem here. If I remove that the problem goes away. However, I do not have control over the real site and cannot just make a change. Is this something that can be fixed on the IDE?

**Comment by tourdedave** [comment]
This appears to be fixed.
