### ISSUE TITLE
selectWindow not recognize popup window

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#275]
## 
OS: OSX
Selenium IDE Version: 3.1.1
Browser:
Browser Version: Firefox 60

## Expected Behavior -

Popup window recognize by select Window

## Actual Behavior -

In the old version (2.9) there is no soucy with the function select Window after an action who open popup window

With the new version, the test is stop in this step select Window with Failed : Timeout

![moz-extension___db9f514d-27b1-6e4b-bb8a-7147e3c91782_-_selenium_ide_-_imported_project__et_liste_des_sites_et_addenachat](https://user-images.githubusercontent.com/40666727/42084588-610eb140-7b8e-11e8-8f77-aa92a4fa3686.jpg)

**Comment by tourdedave** [comment]
Commands that interact with new windows have been significantly improved. Please try it now and open a new issue if you have any problems.
