### ISSUE TITLE
Selenium IDE context menu on a object

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#276]
## 
OS: OSX
Selenium IDE Version: 3.1.1
Browser:
Browser Version: Firefox 60
## Expected Behavior -

Selenium IDE context menu. 
Select the "Show Available Commands" option.

## Actual Behavior -

In the old version (2.9) we have a context menu when we do a rigth click on a object with some command and an other menu with Show Available Commands

**Comment by corevo** [comment]
You need to be recording to see the menu.  
![image](https://user-images.githubusercontent.com/888886/42098900-d50f42d6-7bc4-11e8-9076-258d43365b84.png)
