### ISSUE TITLE
Selenium IDE interferes with javascript behavior

### ISSUE THREAD

**Issue by mbrownso** [SeleniumHQ/selenium-ide#278]
## Meta -
OS:  

Selenium IDE Version:  OSX, 3.1.1

Selenium SIDE Runner Version:  n/a

Node version:  

Browser:  

Browser Version:  MAC Chrome Version 67.0.3396.99

## Expected Behavior -
First name (id=id_first-name) should replicate to address line 1 (id=id_addr-line1)
## Actual Behavior -
First name (id=id_first-name) does NOT replicate to address line 1 (id=id_addr-line1)
## Steps to reproduce -

Without Selenium IDE:
Load the html page as shown in attached image (or shown below)
Type in first name, hit tab
First Name is replicated in Addr line1 (as it should)

With Selenium IDE:
Record or insert command...
    Command = type
    Target = id=id_first-name
    Value = first name
Run current command
First Name is NOT replicated in addr line1

==== begin html ====
<html>
<head>
<meta charset="UTF-8">
<title>Onchange Issue</title>
</head>
<body>
<script type="text/javascript">
 function nameChange(selectObj) {
	 document.getElementById("id_addr-line1").value = document.getElementById("id_first-name").value
 }
</script>
	<form action="/action_page.php">
		First name: <input id="id_first-name" onchange="nameChange()" type="text" name="first-name"><br>
		Last name: <input id="id_last-name" type="text" name="last-name"><br> 
		Addr line 1: <input id="id_addr-line1" type="text" name="addr-line1"><br>
		<input type="submit" value="Submit">
	</form>
</body>
</html>
==== end of html ====

**Comment by corevo** [comment]
Please attach the html in a zip, if you drag it over to the issue editor it'll be autolinked for you.

**Comment by mbrownso** [comment]
![screen shot 2018-07-03 at 10 52 44 am](https://user-images.githubusercontent.com/38983972/42227326-43f456d6-7eaf-11e8-93b2-220c6eea4075.png)
[WebContent.zip](https://github.com/SeleniumHQ/selenium-ide/files/2159882/WebContent.zip)

**Comment by mbrownso** [comment]
HTML attached as image and as ZIP

**Comment by mbrownso** [comment]
added html file

**Comment by mbrownso** [comment]
[WebContent.zip](https://github.com/SeleniumHQ/selenium-ide/files/2159994/WebContent.zip)
HTML attached in ZIP file

**Comment by mbrownso** [comment]
![screen shot 2018-07-03 at 10 52 44 am](https://user-images.githubusercontent.com/38983972/42228983-54f6ff52-7eb3-11e8-95ac-38b2b0e7fcfa.png)
HTML attached as image.

**Comment by 98gmarquee** [comment]
For what it's worth, I notice that when I have the SelIDE add on enabled, but not actively being used, that when I go to certain pages, it causes firefox to hang a long time. One site specifically is ebay. Especially when I look at my purchase history for the year. Without ide enabled, it takes a couple seconds to render and the page to be able to be scrolled or functional. With ide enabled, it can take 30 seconds before I can do anything.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity. If this issue is still a problem, please reopen.
