### ISSUE TITLE
Selenium IDE impacting various websites page load time.

### ISSUE THREAD

**Issue by 98gmarquee** [SeleniumHQ/selenium-ide#279]
## Meta -
OS:  Windows 10

Selenium IDE Version:  3.1.1.0

Selenium SIDE Runner Version:   n/a

Node version:  

Browser:  Firefox

Browser Version: 61.0 64bit  

## Expected Behavior -
Site to perform as usual.

## Actual Behavior -
Site hangs for a long time (30+ seconds).

## Steps to reproduce -

I notice that when I have the SelIDE add on enabled, but not actively being used, that when I go to certain pages, it causes firefox to hang a long time. I don't have IDE open and I'm not using it for anything, just browsing the internet.

One site specifically is ebay. Especially when I look at my purchase history for the year. Without ide enabled, it takes a couple seconds to render and the page to be able to be scrolled or functional. With ide enabled, it can take 30+ seconds before I can do anything. 

I've been getting in the habit of leaving it disabled until I want to use it.

**Comment by tourdedave** [comment]
We have made significant improvements regarding Selenium IDE performance and potential leaks like this. Please let us know if you're still experiencing this problem. Also, please provide more details (e.g., pages where this occurs).
