### ISSUE TITLE
There is a error message, "Expected to receive KeyboardEvent instead received Event"

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#281]
## Meta -
OS:  Winodws 10

Selenium IDE Version:  the last of master branch

Selenium SIDE Runner Version:  

Node version:  8

Browser:  Chorme

Browser Version:  Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
There is no message.
## Actual Behavior -
There is a message like this issue's title.
## Steps to reproduce -

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33743343/42302456-efdf505c-8055-11e8-8d67-89257ba23cc2.gif)

I think `handleKeyDown` handler works when I click.

**Comment by tourdedave** [comment]
Is this problem still happening for you?

**Comment by Jongkeun** [comment]
Well.. I don't know. 
I don't pull the latest code anymore.
I hope this problem would be solved.
