### ISSUE TITLE
selenium ide authenticate basic auth, username and password

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#282]
## Meta -
OS:   Windows 10
Selenium IDE Version:  3.1.1

Selenium SIDE Runner Version:  

Node version:  

Browser:  Headless chrome

Browser Version:  

## Expected Behavior -
How to handle authenticate basic auth in Selenium IDE?
When i'm running the .SIDE file (with selenese) it stops at the auth window. Who do i insert a username and password using the IDE?

**Comment by corevo** [comment]
Put the username and password in the open command like so:  
`open | https://username:password@myurl.com/resource`

**Comment by cemol** [comment]
It does not work. But shall I change resource, or just include it ?

**Comment by cemol** [comment]
still not working. I tried to use the chrome driver (insted of the headless), then the site opens but i still have to manually insert my username and password.

**Comment by corevo** [comment]
Say this is the address that gives me the basic auth:  
https://the-internet.herokuapp.com/basic_auth  
Instead I would say:  
https://admin:admin@the-internet.herokuapp.com/basic_auth

**Comment by cemol** [comment]
That works! But not my link, thats strange

**Comment by corevo** [comment]
Then it is an issue specific to the app you're testing.

**Comment by cemol** [comment]
Now it works :) Thank you
