### ISSUE TITLE
Is it posible to make an alert function in selenium ide?

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#286]
## Meta -
OS:  Windows 10
Selenium IDE Version:  3.1.1

Selenium SIDE Runner Version:  

Node version:  

Browser:  Chrome

Browser Version:  

## Expected Behavior -
Is it posible to make an alert function in selenium ide?
Like:
document.querySelectorAll('some button path').onclick = function() {
   alert("button was clicked");
};

Or some other way to get an confirmation that a button was clicked?

**Comment by corevo** [comment]
I wouldn't use an `alert` because it is a blocking operation, and would freeze the IDE.  
Use `console.log` instead, also don't set the `onclick` handler, use [addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).
