### ISSUE TITLE
Selenium-SIDE-Runner not running SIDE files 

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#289]
## Meta -
OS:   Windows 10
Selenium IDE Version:  3.1.1
Selenium SIDE Runner Version:  0.7.0
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version:  npm: 5.6.0, node: v8.11.3
Browser:  Chrome

Browser Version:  

## Expected Behavior -
I tried to run the SIDE file from Selenium IDE with the selenium-side-runner. But I got the error message:

> error:   The project project_1 is of older format, open and save it again using the IDE.

Which version of the SIDE files is selenium-side-runner using?

(I am using the command: selenium-side-runner project_1.side)

**Comment by corevo** [comment]
Try the new beta I published yesterday, 3.1.1 doesn't include the required features.

**Comment by cemol** [comment]
Thanks, where do i find that?

**Comment by corevo** [comment]
https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.2.0-beta.1

**Comment by cemol** [comment]
This might be a stupid question, but how do I execute that? I downloaded both zip's and tried to use the build shell script. But nothing happende to the IDE

**Comment by cemol** [comment]
Got it!

**Comment by cemol** [comment]
What does this error message means?

`FAIL ./Default Suite.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'quit' of undefined

      at WebdriverEnvironment.teardown (../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:30)
          at Generator.throw (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.309s
Ran all test suites.
`

**Comment by corevo** [comment]
What capabilities are you passing?

**Comment by cemol** [comment]
Im just going to a website (with basic auth), selecting some dropdrows options, and then finish.

**Comment by corevo** [comment]
What are you running in the command line?

**Comment by cemol** [comment]
> selenium-side-runner "path to .side file"

**Comment by corevo** [comment]
Do you have `chromedriver` in `PATH`?

**Comment by Name-less** [comment]
Hello, I had the same issue, fixed by running 
`npm install chromedriver -g`

The runner seems to work very well, great job !!!

**Comment by cemol** [comment]
Nope! Thanks :)

**Comment by juanmalunatic** [comment]
Hello!
I'm still getting an error  message under Windows 10, running the command `selenium-side-runner ../scripts/file.side`:

`The ChromeDriver could not be found on the current PATH. Please download the latest version of the ChromeDriver from http://chromedriver.storage.googleapis.com/index.html and ensure it can be found on your PATH.`

I tried adding the binary to my PATH under the key `chromedriver` and it didn't work (first I tried setting it as the full path to `chromedriver.exe` and then as the path of its containing folder). I also tried following the tip from @Name-less to no avail.

Thanks for your efforts!
