### ISSUE TITLE
import of old-styled testcases one-by-one

### ISSUE THREAD

**Issue by Dukuu-Wild** [SeleniumHQ/selenium-ide#296]
## Meta -
OS:  Linux mint 18.2
Selenium IDE Version:  3.1.1.0
Browser:  FF 61.0

## Expected Behavior - 
there is a way to open(import?) old-styled testcases separately (not inside the suite)

## Actual Behavior - 
when trying to open(import?) old-styled testcases SeIDE just do nothing.

## Steps to reproduce -
[Suite login_faulty case in suite+store.zip](https://github.com/SeleniumHQ/selenium-ide/files/2185007/Suite.login_faulty.case.in.suite%2Bstore.zip)
0. In the provided example there is a file, name starting with "Suite ..." - it's a suite that allows to open all other testcases successfully in the SeIDE.
1. on blank window go to open dialog
2. choose any of testcases (except "Suite..." file.)
=> testcase is not opened, window stays blank.

Comment:
Seems that open button allows to open only suites (old style), as other *htm are ignored and not imported. http://i.prntscr.com/z7Hq5wJXS-O1LL2KOeustQ.png

I see similar issue #274, but it seems a little bit messy about the comment - it's more about baseURL than an import actually, though it has same steps about testcases import. If this is a duplicate, may be closed.

**Comment by brentrug** [comment]
I would also like to know how to import test cases from version 2.9.1 (ide) into 3.1

**Comment by mondiaz** [comment]
I would, too. In the interest of time, I've instead had to manually recreate the test cases in the new Selenium IDE format, command line by command line, and then save in the new file format, and am almost ready to test if they even run.

**Comment by tourdedave** [comment]
Importing individual legacy `.htm` test cases is supported. If you open a legacy suite it will prompt you with a dialog to open the individual test case files for that suite to complete the import. Alternatively, you can open/import an individual test case file. I've confirmed this functionality using the zip file provided by @Dukuu-Wild. Closing.
