### ISSUE TITLE
Selenium IDE does not play back decimal numbers properly

### ISSUE THREAD

**Issue by mbrownso** [SeleniumHQ/selenium-ide#297]
## Meta -
OS:  

Selenium IDE Version:  3.1.1

Selenium SIDE Runner Version:  n/a

Node version:  n/a

Browser:  Chrome

Browser Version:  Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
When IDE command is executed, "1.5" should be placed in field with id of "id_number"
## Actual Behavior -
When IDE command is executed, "5" is placed in field with id of "id_number"

## Steps to reproduce -

Using the attached html file, record the action of typing in a decimal number.  The recorded command should look like this:

Command = "type"
Target = "id=id_number"
Value = "1.5"

Clear the field, then execute the command from the recorded script.  The field will have value of "5", not "1.5" which is the Value in the command.

**Comment by mbrownso** [comment]
[WebContent.zip](https://github.com/SeleniumHQ/selenium-ide/files/2185706/WebContent.zip)
HTML file attached

**Comment by mbrownso** [comment]
![screen shot 2018-07-10 at 5 45 45 pm](https://user-images.githubusercontent.com/38983972/42591947-2f74d830-8516-11e8-8fdf-afc44a4b44f3.png)
Screen shot of HTML code

**Comment by corevo** [comment]
fixed in 9bca77a
