### ISSUE TITLE
[Question]A selectWindow command works differently than before.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#298]
## Meta -
OS:  Window 10

Selenium IDE Version:  the last of master branch

Selenium SIDE Runner Version:  

Node version:  

Browser:  Chrome 

Browser Version:  67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior - 
Before, if I called `selectWindow` command which has a `null` target, it just passed.
## Actual Behavior -
returned timeout.
## Steps to reproduce -

Is there any reason why calling the `selectWindow` command in the `ext-command`, differently before?

**Comment by corevo** [comment]
Differently than before when?

**Comment by tourdedave** [comment]
`selectWindow` of `null` is not supported. To switch to the original window, you will have to refer to its window handle name. This metadata is automatically added to the command that opens a new window, and used in `selectWindow`, during recording.
