### ISSUE TITLE
Any plans for Selenium Builder JSON (Selenium2 vs Selenium1 html) support?

### ISSUE THREAD

**Issue by lkende** [SeleniumHQ/selenium-ide#30]
[Selenium Builder](http://seleniumbuilder.github.io/se-builder/) gave us functionality like the original Selenium IDE but created a new [json format](https://github.com/SeleniumBuilder/se-builder/wiki/JSON-Format) called "Selenium2" as opposed to the html "Selenium1".

Now it appears that the Se Builder project has stopped being developed, especially as FF57 will cause the extension to no longer work without a rehaul. [Github comment](https://github.com/SeleniumBuilder/selenium-builder/issues/33#issuecomment-328554027)

However, those of us that used it for a time have lots of these json scripts. It would not only be helpful in being able to import these json scripts into the new IDE, but I think this json-based format is more portable as well.  

Another thing that Se Builder did well is offer an "interpreter" for running these scripts against remote servers like SauceOnDemand.  This is a huge bonus compared to being limited to running these scripts back in Selenium IDE, or having to generate language-binding specific code.

Forward thinking ...

**Comment by zavelevsky** [comment]
Noted. Keeping this issue open so it will be part of the future backlog.
Thanks, keep em' coming.

**Comment by samitbadle** [comment]
It would be nice to support the Selenium Builder JSON format, but it may not be fully supported due to language features and may not be round trippable.

Having a command line runner is nice to have too. The point to keep in mind is that the runner will need all dependent plugins if they are being used in the execution phase. To be able to support this, I had planned to create a new format (JSON) based that stores necessary information.

**Comment by lkende** [comment]
I'm glad to at least bring awareness and interest around the JSON format.  If it can become a core feature of the tool that would be favorable, even with a limited support.  Worst case scenario, we can create an extension that imports and exports "Selenium2" JSON files to the best of it's ability.  

Currently, [Selenium Builder has two interpreters](http://seleniumbuilder.github.io/se-builder/tools.html) or command line runners, one in Java and one in Node.  These will probably need to be re-developed but could at least be a good starting point vs creating something from scratch, assuming licensing permissions etc.

Not sure I can reference them, but would be curious for @Zarkonen from the @SeleniumBuilder team to add his thoughts.

**Comment by corevo** [comment]
Keeping this open in case somebody will want to contribute this, we currently have no official plans on supporting any format other than the legacy IDE.

**Comment by 1083** [comment]
The JSON format is clearly superior and should be favored over the legacy HTML format.

This looks like the starting point for adding Selenium 2 JSON support:

https://github.com/SeleniumBuilder/selenium-builder/blob/master/seleniumbuilder/content/html/builder/selenium2/io/io.js

**Comment by corevo** [comment]
We don't use the HTML format, other than to migrate it, into our new format, which is **json**

**Comment by toddtarsi** [comment]
@lkende @maxterry @corevo - Is it okay if I close this issue? We support json extensively with our side file format. Did everything work out here well enough?

**Comment by lkende** [comment]
You can close this issue. Selenium IDE's JSON pattern differs from the SeleniumBuilder's structure but I suppose one could come up with a conversion.  I never pursued it any further and now it's been long enough to not warrant the work. Thanks.
