### ISSUE TITLE
"select window" can't select the popup window which opened in a new tab

### ISSUE THREAD

**Issue by Fannie-Wang** [SeleniumHQ/selenium-ide#308]
## Meta -
OS:  Windows 7 Professional
Selenium IDE Version:  3.1.1
Browser:  googlechrome
Browser Version:  67.0.3396.99 (64-bit)

Hi,
I'm a new comer to use Selenium IDE. I used 3.1.1 to record case as below screenshot. But "select window" command fails when the window is opened in a new tab. I tried another window which opened in the same tab, the command works well. How can I resolve this issue? Could someone kindly give some suggestions?
![capture](https://user-images.githubusercontent.com/41133955/42794370-f022de96-896d-11e8-97c6-0ac07012c4cd.PNG)

**Comment by p2635** [comment]
Try the information here: https://a9t9.com/kantu/docs/selenium-ide/selectwindow

**Comment by corevo** [comment]
Hey there, as of Selenium IDE 3.5.0 we are changing the way `select window` works, this use case included, you can read more of it [here](https://corevo.io/the-difficulties-of-select-window/).  
I am closing for now, I'll keep you posted once 3.5.0 ships.
