### ISSUE TITLE
If I record text verifies in Chrome, there are '\n' characters in the recordings, then when I run these in Firefox, they fail

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#311]
## Meta -
OS:  

Selenium IDE Version:  3.1.0

Selenium SIDE Runner Version:  

Node version:  

Browser:  
Chrome Version 67.0.3396.99 (Official Build) (64-bit)  AND Firefox 61.0.1 (64-bit)
Browser Version:  

## Expected Behavior -
Recorded Text values should pass in both, Should not have to create different files for each browser
## Actual Behavior -
Passes in Chrome, fails in Firefox

**Comment by Kielmed** [comment]
Removing the \n fails in Chrome.

**Comment by corevo** [comment]
Which OS?

**Comment by Kielmed** [comment]
I am in Windows 10

**Comment by corevo** [comment]
Please make sure to file the OS, as it is required for me to investigate, different OS's have different new line characters.

**Comment by corevo** [comment]
Can you provide a minimal test that reproduces this behavior?  
It is not necessary but it will stall the fix.

**Comment by Hexahydra** [comment]
@corevo I noticed simmilar problems with \n chracters, you should see it in attached .side (two asserts - first assertText recorded in Firefox, the second in Chrome)
[AssertText Recorded in CHROME vs FIREFOX.zip](https://github.com/SeleniumHQ/selenium-ide/files/2253297/AssertText.Recorded.in.CHROME.vs.FIREFOX.zip)

**Comment by Kielmed** [comment]
What was the solution?

**Comment by corevo** [comment]
I'm using Selenium atom's algorithm to get the elements' visible texts, instead of the Selenium 1.0 one.  
Seems to be working across browsers from my testing.

**Comment by Kielmed** [comment]
Are the Selenium atom's the same that are accessed by right clicking while recording and selecting verify text?

The \n's are not that common, I tried recording and still get them.   I have over 1000 lines and less than 20 have the \n's.  I cannot give access to my assets.

**Comment by corevo** [comment]
Firefox and Chrome recorded new lines in a different manner, which means that whichever solution there is, one of them will still break and will have to port.  
What I can definitely tell you, is that it uses the same algorithm used in WebDriver to determine the inner text, both in recording and playback, if something else was recorded beforehand, then it recorded a bug.
