### ISSUE TITLE
Firefox Selenium does not display failed tests in Red and Passed in Green

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#312]
## Meta -
OS:  Windows

Selenium IDE Version:  3.1.0

Selenium SIDE Runner Version:  

Node version:  

Browser:  Firefox

Browser Version:  

61.0.1 (64-bit)
## Expected Behavior -
Passed Tests are Green, Failed are Red
## Actual Behavior -
No colors on tests

**Comment by corevo** [comment]
Please try that again using [v3.1.1](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.1.1) as it was one of the issues resolved in that release.  
Closing for now, if the issue persists even in 3.1.1 comment again and I'll reopen.

**Comment by Kielmed** [comment]
I tried to upgrade my Selenium Firefox to 3.1.1 but still have 3.1.0. How do I get 3.1.1?

**Comment by corevo** [comment]
Try [here](https://addons.mozilla.org/en-GB/firefox/addon/selenium-ide/versions/?page=1#version-3.1.1.0)

**Comment by Kielmed** [comment]
I installed it and see it on the Extensions page, but when I use the icon to open it, 3.1.0 opens instead.
________________________________

**Comment by corevo** [comment]
What version does it show you in the extension page?

**Comment by Kielmed** [comment]
I see it on the What's new popup off the menu on the right.
________________________________

**Comment by corevo** [comment]
What do you see in `about:addons`?

**Comment by Kielmed** [comment]
Selenium IDE: Flow Control
Selenium XML Formatter

**Comment by corevo** [comment]
I meant what version of Selenium IDE do you see there?

Cheers,
Tomer
