### ISSUE TITLE
Javascript console error when Selenium Extension is installed in Chrome: Uncaught in promise

### ISSUE THREAD

**Issue by td2014** [SeleniumHQ/selenium-ide#313]
## Meta -
OS:  
OSX
Selenium IDE Version:  
3.1.0 Chrome Extension
Selenium SIDE Runner Version:  
N/A
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version:  

Browser:  
Chrome
Browser Version:  
Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
No console errors when loading webpage
## Actual Behavior -
Javascript console error occurs:
Uncaught (in promise) "Could not establish connection. Receiving end does not exist."
## Steps to reproduce -
1. Install Selenium web extension in Chrome.
2. Open cnn.com
3. Examine javascript console to see error mentioned above.
NOTE: This error does not seem to occur when Selenium web extension dialog is actually open. Also, I already filed bugs with Chromedriver/chromium teams, and they told me to file bug with Selenium since they don't think it is with them.
I hope this helps.
Thanks.

**Comment by KyleFairns** [comment]
This issue is occurring in chrome on Windows 10 too.

![selenium ide bug](https://user-images.githubusercontent.com/18209178/43088533-4a995fc2-8e9a-11e8-993b-6490c750949c.png)

**Comment by corevo** [comment]
A version with the fix has yet to be published to the addon stores

Cheers,
Tomer
