### ISSUE TITLE
selenium side runner - how to generate a report, for example xml, etc.

### ISSUE THREAD

**Issue by smithhero1994** [SeleniumHQ/selenium-ide#318]
OS:  
Windows 10

Selenium SIDE Runner Version:  
3.2.0-beta.4

Node version:  
10.7.0

I use the console to run the code

is it possible to generate a report? preferably in xml etc.

**Comment by corevo** [comment]
What do you mean by report?

**Comment by smithhero1994** [comment]
in the report, I would like the result of the test

**Comment by corevo** [comment]
I think it's a pretty good addition, that I'll make sure to see through.  
Unless you want to retract this suggestion, I'm going to reopen this.

**Comment by p2635** [comment]
What was the outcome of this ticket? I was going to put forth a suggestion but I didn't want to create a duplicate ticket.

It would be ideal for me to have a feature to output the test results in a .log/.txt file. At the moment, I am having to copy and paste the test results manually. This time adds up when I have like 20 tests I have to copy paste for each text file.

**Comment by Name404** [comment]
> What was the outcome of this ticket? I was going to put forth a suggestion but I didn't want to create a duplicate ticket.
> 
> It would be ideal for me to have a feature to output the test results in a .log/.txt file. At the moment, I am having to copy and paste the test results manually. This time adds up when I have like 20 tests I have to copy paste for each text file.

I'm facing this same situation, do you have any solution now?

**Comment by tourdedave** [comment]
There's a PR in the works to add junit-xml reporting ([link](https://github.com/SeleniumHQ/selenium-ide/pull/660)). In the meantime, you can get a JSON report of the test run by specifying `--output-directory` as an additional run-time argument and the directory where you'd like it (see the comments above for details).
