### ISSUE TITLE
How to save substrings for further validation?

### ISSUE THREAD

**Issue by cinnest** [SeleniumHQ/selenium-ide#320]
After creating a new code a message is shown like: "transaction code: 1234". This code is then shown in a table with a list of transactions. For validating it on this table I'd like storing just the substring "1234".  I've tried the following but I always get a message the storedVars is not defined. How it should be done using the new selenium-IDE (3.1.0)?

```
{
"id": "b64d23c7-72af-48f2-957a-3929281cb2ec",
"comment": "",
"command": "storeText",
"target": "css=span.ui-messages-summary.ng-star-inserted",
"value": "trxCodeMsg"
}, {
"id": "0365bcc1-d263-4417-829d-da68debd2c20",
"comment": "",
"command": "executeScript",
"target": "return storedVars['trxCodeMsg'].substring(18,22)",
"value": "trxCode"
}
```

**Comment by corevo** [comment]
Please open an issue

Cheers,
Tomer

**Comment by cinnest** [comment]
Issue #321
Thanks
