### ISSUE TITLE
selenium-side-runner README update

### ISSUE THREAD

**Issue by VincentMeier** [SeleniumHQ/selenium-ide#322]
## 🚀 Feature Proposal

Was just about to post an issue, that `selenium-side-runner@3.2.0-beta4` doesn't even work, since the most basic `selenium-side-runner --version` command created an exception, but then I noticed this in the Bug Report template `Please note that selenium-side-runner supports Node.js 8 - 10`
Would have been nice to see this in the selenium-side-runner README.md as well. Would have saved me a lot of time.

## Motivation

I had just installed Node.js on our teams development server using the `geerlingguy.nodejs` Ansible role, which by default is set to install Node.js 6.x . We've never needed Node in any of our projects before, so I wasn't aware which version was the standard nowadays. Now I know (after having visited the Node.js homepage and seeing that 8 is the LTS version). This is a super small 'nice to have' addition, but it probably will prevent others from wasting a bunch of time, like I did today.

**Comment by corevo** [comment]
No problem, will update.  
Please note that Node.js 6.x is only covered for security maintenance until April 2019, after that any security vulnerability will not be patched.  
The project guarantees support for Node's LTS major version at all times, when the LTS moves, we will no longer guarantee support for it, tests will not run against it, and it may break at any version.

**Comment by VincentMeier** [comment]
That's completely reasonable. 

Had I worked with Node in the past or opened their homepage first I would have noticed which is the LTS version and used that straight away. This request is based solely on the fact that there might be more edge cases like myself, where their first real work with Node is with trying out this tool.

Thanks for the feedback.

**Comment by corevo** [comment]
Fixed in 9e55ce6
