### ISSUE TITLE
How to set window size in selenium-side-runner (and to emulate the device size)?

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#325]
## 💬 Questions and Help
I would like to test the selenium .side test on different devices (windows), and I would like to use switches like `window-size`, `user-agent` and `use-mobile-user-agent`.

The command:
`selenium-side-runner -c chromeOptions.args=[window-size=400x400] project.side`

did not work. What am I doing wrong?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
The `-c` flag is specifically used for capabilities, and nothing else.  
You can read a readme on setting capabilities [here](https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-side-runner#passing-capabilities).  
There is also a list of valid [WebDriver capabilities](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities) as well.  
If this is indeed impossible to be done using capabilities (browsers do not accept window size as a capability, you may open a feature request for it).
