### ISSUE TITLE
Running selenium-side-runner with firefox

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#328]
## 💬 Questions and Help
I'm trying to run selenium-side-runner with firefox on windows (and linux), but with no luck. I have downloaded the `geckodriver-0.21.0`, and included it in PATH. But when I run 
`selenium-side-runner -c "browserName=firefox" project.side`

I got this error:
```
FAIL ./project.test.js
  ● Test suite failed to run

    SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

```

What am I dointg wrong or forgetting?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
Make sure `geckodriver` is in `PATH` by running `which geckodriver`.  
Make sure it returns a path to it.  
Again this is an issue with the environmental setup and no the runner, closing.

**Comment by tourdedave** [comment]
To add on to @corevo's comment, take a look at https://github.com/mozilla/geckodriver#mozfirefoxoptions

**Comment by cemol** [comment]
Thanks! Now I have able to fix it :)
