### ISSUE TITLE
Issue with selenium-side-runner and firefox

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#329]
## 💬 Questions and Help
I have an issue when running selenium-side-runner with browser firefox. I am not sure if this is an issue with the selenium-side-runner, or firefox, or both. But when I run:
`selenium-side-runner -c "browserName=firefox" project.side`

Firefox starts and the test starts, but it failes very quickly. My test workes fine with browser chrome and with firefox trough the selenium IDE. What could be wrong? I am currently running my test on Windows 10.

This is the error message I got:

```
(node:22384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addExpectationResult' of undefined
(node:22384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22384) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
FAIL ./project.test.js
  ● Test suite failed to run

    SessionNotCreatedError: Tried to run command without establishing a connection

      at Object.throwDecodedError (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:514:15)
      at parseHttpResponse (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:519:13)
      at doSend.then.response (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.quit()
      at Driver.schedule (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Driver.quit (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:840:23)
      at WebdriverEnvironment.teardown (../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:37:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        13.189s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

```

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
It stems from this [issue](https://github.com/SeleniumHQ/selenium/issues/4564), once it's fixed in the JavaScript Selenium bindings yours will be resolved.

**Comment by cemol** [comment]
Thanks for your help @corevo ! But what do you mean by "JavaScript Selenium bindings"?
Shall I implement the code `driver.actions({bridge:true})` somewhere? I'm not sure how to fix this.

**Comment by corevo** [comment]
What I meant is that it's not fixable on my end, I need that issue to be resolved, and update the underlying Selenium version of the runner.  
Bottom line it's an issue I'm aware of, that you can't fix on your own.

**Comment by cemol** [comment]
Ok, thank you so much for your help!

**Comment by corevo** [comment]
Closing since upstream issue is now closed.
