### ISSUE TITLE
Module not found: Error: Can't resolve 'selianize'...

### ISSUE THREAD

**Issue by KhanhLanHuynh** [SeleniumHQ/selenium-ide#330]
Getting the error when trying to build
```
ERROR in ./plugin/manager.js
Module not found: Error: Can't resolve 'selianize' in 'D:\selenium-ide\packages\

selenium-ide\src\plugin'
 @ ./plugin/manager.js 17:15-35
 @ ./neo/IO/filesystem.js
 @ ./neo/containers/Panel/index.jsx
 @ ./neo/containers/Root/index.jsx
 @ multi react-hot-loader/patch ./neo/containers/Root
```

In the file, I see the command `import { RegisterConfigurationHook, RegisterSuiteHook, RegisterTestHook, RegisterEmitter } from "selianize";` but the `selianize` folder is set in `selenium-ide\packages`. Anyone help!

**Comment by corevo** [comment]
Run yarn in the project root, to set up the monorepo correctly.
Then run yarn build:selianize prior to building the extension.

Cheers,
Tomer

**Comment by KhanhLanHuynh** [comment]
Thank, I can build this Selenium IDE with master code now.
