### ISSUE TITLE
Uncaught TypeError: goog.provide is not a function

### ISSUE THREAD

**Issue by KhanhLanHuynh** [SeleniumHQ/selenium-ide#331]
Getting the "Uncaught TypeError: goog.provide is not a function" error" when run recording with Selenium IDE 3.2.0-beta. (build from master code)
![image](https://user-images.githubusercontent.com/20237732/43877600-0525da8c-9bc5-11e8-8b85-b9456477c228.png)

**Comment by corevo** [comment]
Seems you did not run peru sync.
Follow the build instructions to the fullest.

Cheers,
Tomer

**Comment by KhanhLanHuynh** [comment]
Thank, I tried to re-build following the instructions agains but my build extension still doesn't work.
It looks like return the error in this line: https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/plugin/communication.js#L51

My steps for building extension are:
```
peru sync
yarn
yarn build:selianize (refer: https://github.com/SeleniumHQ/selenium-ide/issues/330)
yarn build:ext:prod
```

I'm using yarn v 1.9.4 and NodeJS v 8.11.3-x86

**Comment by corevo** [comment]
Whats the build output?

**Comment by KhanhLanHuynh** [comment]
Sorry @corevo, I don't get your question.
Here is the build log
[build_log.txt](https://github.com/SeleniumHQ/selenium-ide/files/2276164/build_log.txt) and Chrome log when running my built extensions [jggaciekcikjnjlojnfbofgndagjjndc-1533857783587.log](https://github.com/SeleniumHQ/selenium-ide/files/2276166/jggaciekcikjnjlojnfbofgndagjjndc-1533857783587.log)

Here is my built extension [build.zip](https://github.com/SeleniumHQ/selenium-ide/files/2276169/build.zip), could you please take a look and give me some advise.

Thank a lot!

**Comment by KhanhLanHuynh** [comment]
Thank @Jongkeun I'll try to re-build with Linux.

**Comment by KhanhLanHuynh** [comment]
@Jongkeun I setup Windows Subsystem for Linux and use the Ubuntu as you suggestion, however, I can not build the Selenium IDE with this error: [error_linux.txt](https://github.com/SeleniumHQ/selenium-ide/files/2277305/error_linux.txt). Please give me some advises.

cc: @corevo

**Comment by KhanhLanHuynh** [comment]
after running `yarn lerna clean`, the `yarn` print some other err:
```
$ lerna bootstrap
lerna info version 2.11.0
lerna info Bootstrapping 4 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn install --mutex network:42424 --non-interactive
lerna ERR! warning package.json: No license field
lerna ERR! warning No license field
lerna ERR! error An unexpected error occurred: "/home/lanhuynh/.cache/yarn/v2/npm-babel-plugin-syntax-async-generators-6.13.0-6bc963ebb16eccbae6b92b596eb7f35c342a8b9a/.yarn-metadata.json: Unexpected end of JSON input".
lerna ERR! Process stalled
lerna ERR! Active handles:
lerna ERR!   - Socket
lerna ERR!   - Socket
lerna ERR!   - Socket
lerna ERR! yarn install v1.9.4
lerna ERR! [1/4] Resolving packages...
lerna ERR! [2/4] Fetching packages...
lerna ERR! info If you think this is a bug, please open a bug report with the information provided in "/home/lanhuynh/selenium-ide/packages/selenium-side-runner/yarn-error.log".
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/home/lanhuynh/selenium-ide/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
```

**Comment by KhanhLanHuynh** [comment]
@corevo @Jongkeun Thank you a lot, I can make the Selenium IDE and it worked with my Chrome browser.

**Comment by KhanhLanHuynh** [comment]
@corevo Do we need update the README for "building on Linux" only? I confuse this a lot when trying to build with Windows OS.

**Comment by corevo** [comment]
Yes, I'll make sure to update it accordingly.
