### ISSUE TITLE
It will be nice to have copy or duplicate a test - Selenium IDE Chrome, Firefox extentions

### ISSUE THREAD

**Issue by AysKrmn** [SeleniumHQ/selenium-ide#333]
## 🚀 Feature Proposal
Copy or duplicate a test 
A clear and concise description of what the feature is.
-Copy content of a test to another test to enable to make small changes for similar tasks.
Or duplicate a test to be able to rename and make small changes to use another suite orderly.
## Motivation
- It shortes the time on  recording on long, similar repeating tests.
Please outline the motivation for the proposal.
-Test and test cases usually need to crop, repeat, modify, move around during testing. I am using first time the new Selenium and find it difficult not to copy a test.
## Example
Please provide an example for how this feature would be used.
I am creating test for about 30 forms (templates like), a lot of features similar on each form but with slight differences. I was trying ages to copy a few test to save repeating recording time as they do run on other forms only fails a few test that require to delete and modify.
Thank you!
Ayse

**Comment by corevo** [comment]
In the next released version you will have a "Duplicate" options in the context menu of the test.

**Comment by AysKrmn** [comment]
Thank you!
