### ISSUE TITLE
After installing 3.2.0 script stops and throws "Cannot read property 'next' of undefined" error where it used to run smoothly

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#336]
## 🐛 Bug Report

My scripts log into text books, then test the functionality of the text book.  I had a release over the weekend on Fri and then again Sat.  These scripts ran without fail.  I got an install of 3.2.0 Monday morning and now the scripts fail executing the first command in the book.  Cannot read property 'next' of undefined is thrown when I try to click on the menu.  The login page is different from  the book page so I was wondering if I now have to select the new page to get access.  Either way this disables 45 of my critical cases.

## To Reproduce

Open a login page
then login
select the menu item from the next (different) page
 Failed:
Cannot read property 'next' of undefined
'Algebra 1 CCSS TE' ended with 1 error(s)

## Expected behavior

The days before the release of 3.2.0 the script logged in and was able to login to the book, then click on the book

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.
Unable to supply book logins
Issues without a reproduction project are likely to stall.

## Environment

OS:  Windows 10 -->
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by Kielmed** [comment]
This error is thrown only when running the script, if I manually execute the commands they work.

**Comment by tourdedave** [comment]
Hey @Kielmed, since you can't provide the .side file, can you at least provide a working example (e.g., something against a public website like Google or [the-internet](http://the-internet.herokuapp.com))?

**Comment by tourdedave** [comment]
Or at lease a screenshot showing the commands you're trying to run?

**Comment by Kielmed** [comment]
![image](https://user-images.githubusercontent.com/40494799/44032014-d5fc0666-9ed3-11e8-9819-d566f13af9ab.png)

**Comment by Kielmed** [comment]
SORRY WRONG ERROR in last image
![image](https://user-images.githubusercontent.com/40494799/44032132-43e9fa5c-9ed4-11e8-8f19-d98fdfba7edd.png)

**Comment by Kielmed** [comment]
![image](https://user-images.githubusercontent.com/40494799/44033408-4c9d1a5e-9ed8-11e8-8be8-163dc2728af7.png)

**Comment by tourdedave** [comment]
Hey @Kielmed, thanks for the screenshot. Unfortunately I can't reproduce the issue on my end. We need more info to go on, so either a reproducible test case or access to the application under test in order to step through debugging the test commands would be required.

**Comment by Kielmed** [comment]
My Firefox 3.1.0 still runs this code, so that proves it is in the release.

I also had to re-record some of my links to books, but that is not part of this issue. (I don't think it is)

**Comment by corevo** [comment]
We are aware it is a regression of this release, but this release introduced an almost complete rewrite of the way we handle playback to support control flow.  
Therefore it is hard to reproduce, and deduce where this pesky bug comes from.

**Comment by mking23** [comment]
Having the same issue as Kielmed.

3.2.0 returns the same error message.

![image](https://user-images.githubusercontent.com/13658944/44042906-6f04af12-9f19-11e8-9705-be8b5cc43004.png)

**Comment by tourdedave** [comment]
I was able to reproduce this on my end. Thanks all! Working on a fix now.

**Comment by tourdedave** [comment]
Published the fix in [version 3.2.1](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.2.1). If the issue persists, please re-open.
