### ISSUE TITLE
"Play From Here" command starts executing the script from the Beginning instead of the step selected

### ISSUE THREAD

**Issue by saradhit** [SeleniumHQ/selenium-ide#337]
## 🐛 Bug Report

"Play From Here" command starts executing the script from the Beginning instead of the step selected

## To Reproduce

Use Selenium IDE 3.2.1
Open ".side" file
Right click on any step and select "Play from Here". 

## Expected behavior

Script should start executing from the step selected.
This was working in Selenium IDE 3.1.0

## Project file reproducing this issue (highly encouraged)
I am not supposed to provide .side file. This bug can be reproduced with any .side file. 

## Environment

OS: Windows 10 E 64-bit
Selenium IDE Version:  3.2.1
Selenium SIDE Runner Version:  3.2.0

Node version: 

Browser: Firefox
Browser Version: 61.0.1 (32-bit)

**Comment by tourdedave** [comment]
Confirmed. I see the problem. We'll get a fix in soon. Thanks!

**Comment by saradhit** [comment]
Thanks for the quick fix @tourdedave, When this fix will be available?

**Comment by tourdedave** [comment]
Whenever we cut the next release. I just cut one earlier today. So I think we'll wait to see if any more issues come in and try to push tomorrow.

**Comment by saradhit** [comment]
@tourdedave Thank You.

**Comment by tourdedave** [comment]
You're welcome!

**Comment by tourdedave** [comment]
Great!

**Comment by GmaClaus** [comment]
I am on version 3.5.8 and this issue has returned.  Play from here always starts a new window in chrome from the beginning.
