### ISSUE TITLE
Mouse Over doesn't appear to be working when used as a command

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#341]
## To Reproduce

Use this site with hover over:
https://www.arthritis.org
Hover over the menu items and try to select a sub-menu item

## Expected behavior
In the past I could select the sub-menu item without hovering over the menu item, but now I can't do either.  On the arthritis site, I was able to record the mouse over, but it did not work when I ran the script

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
Can you attach a project file?

**Comment by Kielmed** [comment]
My Projects all have proprietary logins that cannot be shared.  I supplied a site that has similar mouse over menus that behaved in the same manner.  Sorry

**Comment by Kielmed** [comment]
I am able to get mouse over to work in another book, recording relative X-Path recorded from the Chrome Addon Relative XPath Helper.  I will try this on the other book, but it is a different style of drop down.

**Comment by corevo** [comment]
I meant a recording from https://www.arthritis.org

**Comment by Kielmed** [comment]
I am going through making release related changes to my script base now, I will try to clear my project and create this for you today.

**Comment by Kielmed** [comment]
I was able to automate mouse over and mouse out on the arthritis site, but not ours using the same linkText= commands.  I will work internally to find out if it can be fixed.
