### ISSUE TITLE
Prompt, Confirm, Alert functionality

### ISSUE THREAD

**Issue by hohnan** [SeleniumHQ/selenium-ide#342]
## 🚀 Feature Proposal

Allow the user to input/store variables by presenting boxes for them to interact with during playback.

## Motivation

We work with account creations and there is a need to enter a code or a specific URL to verify that you have received an email. These codes are generated ad hoc and cannot be pasted into the code until they after a specific event.

I also have tests where sometimes I don't want to test a certain feature, example: validating colors on the page, where I will "confirm("Testing Colors? Ok - Yes or Cancel - No")".

## Example
I understand the storeEval is not going to happen, but maybe execute script could perform this function.

storeEval | prompt("Enter Password Reset ID from database ?") | URL

storeEval | prompt("Enter URL from email?") | URL

storeEval | confirm("Testing Colors? Ok - Yes or Cancel - No") | primaryColor

storeEval | alert("Go to file location \\\\aaaaa\\aaaaa\\aaa\\${appId} to verify there is no FD file") |

**Comment by toddtarsi** [comment]
V4 handles this better by just using native driver stuff, so we don't have to do anything with fake confirms or such.
