### ISSUE TITLE
Input with mask - assert value problem

### ISSUE THREAD

**Issue by Hexahydra** [SeleniumHQ/selenium-ide#343]
## 🐛 Bug Report

Input (type=text) with mask - assert value problem - does not working anymore (in new IDE 3.2.1) but was working in 3.1.1.
I use this command sequence:
sendKeys > clickAt >assertValue
ClickAt caused rendering value in 3.1.1 but not in 3.2.1 (just try attached .side)
I am not able to reach requested masked shape by simulating any other user interaction. (May be fireEvent - blur? (command was in old IDE, not suported in new IDE yet), but I am not sure if this solve the problem.

The fact is that somethin was changed in IDE 3.2.1 against v 3.1.1. I see different behavior. Run attached .side file in both versions.

## To Reproduce

Try attached .side file.

## Expected behavior

Command sequence: sendKeys > clickAt >assertValue will be working as in IDE 3.1.1

## Project file reproducing this issue (highly encouraged)

[PHONE_project.zip](https://github.com/SeleniumHQ/selenium-ide/files/2287524/PHONE_project.zip)

## Environment

OS: Windows 7
Selenium IDE Version:  3.2.1

Browser: Firefox
Browser Version: 61.0.2 (64 bit)

**Comment by Hexahydra** [comment]
https://github.com/SeleniumHQ/selenium-ide/issues/536

**Comment by toddtarsi** [comment]
I'm going to close this. It may not be resolved in v3, but v4 uses webdriver commands directly, so this is either resolved there, a problem for selenium-webdriver, or broken in a myriad of other ways I will be party to later.
