### ISSUE TITLE
Pause command not working

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/selenium-ide#346]
## Last working version

Worked up to version:
3.1
Stopped working in version:
3.2
## To Reproduce

Load the commands below

## Expected behavior

Should pause for 5 seconds

## Project file reproducing this issue (highly encouraged)

{
  "id": "8413be77-dd59-490b-bd1b-51bf22b44552",
  "name": "Untitled Project",
  "url": "",
  "tests": [{
    "id": "d56afcd8-f11d-420e-8ba7-d4fd6e34f212",
    "name": "Untitled",
    "commands": [{
      "id": "7934a4fe-75e1-4b67-ab00-c4a1a357fd19",
      "comment": "",
      "command": "open",
      "target": "https://google.com",
      "targets": [],
      "value": ""
    }, {
      "id": "5082d1aa-f8dd-4170-ade3-69c6ac4d0669",
      "comment": "",
      "command": "type",
      "target": "css=#lst-ib",
      "targets": [],
      "value": "wikipedia"
    }, {
      "id": "fbf35ed7-1a28-4540-a93d-3cb8ba0e012a",
      "comment": "",
      "command": "pause",
      "target": "",
      "targets": [],
      "value": "5000"
    }, {
      "id": "52630796-fff0-46d6-9111-1f3584b7acbd",
      "comment": "",
      "command": "sendKeys",
      "target": "css=#lst-ib",
      "targets": [],
      "value": "${KEY_ENTER}"
    }]
  }],
  "suites": [{
    "id": "e210e86a-b675-4ea8-baa5-967a26bab2cc",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["d56afcd8-f11d-420e-8ba7-d4fd6e34f212"]
  }],
  "urls": [],
  "plugins": [],
  "version": "1.0"
}

## Environment

OS: windows 10
Selenium IDE Version: 
Selenium SIDE Runner Version:  3.2

Browser: firefox
Browser Version: 61.0.2 (64-bit)

**Comment by corevo** [comment]
The next release will fix this, but you can manually do so as well.
