### ISSUE TITLE
opening a new tab as last command as suite  

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/selenium-ide#348]
## 🐛 Bug Report
If a particular test "test 1" in a suite has another test  following it "test 2", and the last command of test 1 is to open a new tab. aside from opening 2 tabs which is a known issue, the first tab gives the preparing to run your test page when switching to the next test. Then it stalls. I don't know if fixing the duplicate window opening will fix it or not. but wanted to document this occurrence.

## To Reproduce

{
  "id": "41418e1b-d0cf-4355-abbd-972161eadc35",
  "name": "Untitled Project",
  "url": "",
  "tests": [{
    "id": "b58440a8-e31c-486d-991e-a7423bfe1caf",
    "name": "2",
    "commands": [{
      "id": "76f124b3-2272-446f-8786-baffbc8722e2",
      "comment": "",
      "command": "verifyElementPresent",
      "target": "css=img > img:nth-child(1)",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "da5d5b45-5ab3-45e4-9428-9960e40f09e4",
    "name": "1",
    "commands": [{
      "id": "890b21d2-42ca-4d96-8efe-614883f99b76",
      "comment": "",
      "command": "open",
      "target": "https://yahoo.com",
      "targets": [],
      "value": ""
    }, {
      "id": "ca22d888-2a27-4b40-ace0-4634ed56cfa3",
      "comment": "",
      "command": "type",
      "target": "css=#uh-search-box",
      "targets": [],
      "value": "google"
    }, {
      "id": "8ce97816-f77e-4b59-9025-2ca003aaf5a1",
      "comment": "",
      "command": "clickAt",
      "target": "css=#uh-search-button",
      "targets": [],
      "value": ""
    }, {
      "id": "e136e4df-c44b-401f-9029-1f1a3c6bf101",
      "comment": "",
      "command": "clickAt",
      "target": "css=.ac-algo",
      "targets": [
        ["id=yui_3_10_0_1_1534427232131_222", "id"],
        ["css=#yui_3_10_0_1_1534427232131_222", "css"],
        ["//b[@id='yui_3_10_0_1_1534427232131_222']", "xpath:attributes"],
        ["//a[@id='yui_3_10_0_1_1534427232131_223']/b", "xpath:idRelative"],
        ["//h3/a/b", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "b1d77f36-de63-4608-94ab-965e68691a5e",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["da5d5b45-5ab3-45e4-9428-9960e40f09e4", "b58440a8-e31c-486d-991e-a7423bfe1caf"]
  }],
  "urls": [],
  "plugins": [],
  "version": "1.0"
}

## Expected behavior

expected to flow into next test

## Project file reproducing this issue (highly encouraged)
see above

## Environment

OS: windows 10
Selenium IDE Version:  
Selenium SIDE Runner Version:  3.2
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 
Browser: firefox
Browser Version: 61.0.2 (64-bit)

**Comment by modnar1226** [comment]
for now adding an implicit pause for 5 seconds seems to be a workaround.

**Comment by tourdedave** [comment]
We've changed how working with new windows occurs. When recording a click, if it opens a new window, metadata for it (e.g., the name of the window handle, and a timeout to wait for the window to appear) will be recorded for that command. The window handle name is stored on a variable. If you want to switch between these windows, you'll need to reference this variable.

The best way to do that, and to make your tests deterministic, is to 1) use the `run` command to execute the second test (e.g., `run | 2`), and 2) use the `selectWindow` command at the beginning of your second test to make sure the correct window has focus (e.g., `selectWindow | handle=${your-window-handle-name}`).

You can see an example of this in practice here: [example.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/3284898/example.side.zip)
