### ISSUE TITLE
selenium-side-runner default pause on open

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#350]
## 🚀 Feature Proposal

Enable default pause for "open"-Command.
Enable overwrite via .side.yml-Configfile.

## Motivation

When switching to Contiuous Integration Processes, Selenium Testcases are not working out of the Box, since often Elements are not present at DOM yet. 
Exchange *.side-Files from manual Execution inside Selenium-IDE with ones from CI/CD-Environments  and vice versa is therefore not possible.
Current workaround: insert pause-Command after loading Contents from new URL. 

## Example
capabilites:
  defaultPauseOnPageLoad: 1000

**Comment by corevo** [comment]
Sounds more like a bug than a feature, do you mind posting a test case where the implicit wait works in the browser, and one that fails with the runner?

**Comment by M3ssman** [comment]
Sure, but it is related to a Back-Office Application I cannot access right now, so please give me a Day or two and I'll can provide more Information.

**Comment by corevo** [comment]
If you can try and add a stripped down version of a website that replicates this issue, just `html`s if possible, that can replicate this.  
I want to see if I can add a solution without introducing an extra wait mechanism, because the in-browser wait mechanism takes care of it.

**Comment by M3ssman** [comment]
Unfortunately, it's really complex and I am not quite sure but right now it looks like the Problem is on our side. I was able to narrow the Problem down to a single execution step, so the different Failure do _not_ occur with any click resulting in Page Requests.

Further, the Test Setup itself is dockerized. We are using the selenium/hub and node-chrome Containers, no real local Browser, so the different Behaviors can originate from this, too.

(Please confer Attachment for more details.)
Failure arises any time at command#10 , which fires an asynchronous Request to the Backend. When pause at command#11 is omitted, side-runner fails with subsequent Assertions, whereas running the same Suite inside the Browser Selenium IDE succeeds. Command#12 fails and indicates next Page isn't loaded yet, since the Headline Text still has the value from command#5 .

Finally, I cannot exclude programmatical Misuses. The suspicious asynchronous Request only makes sense under certain conditions. If so, the test and the tool and the Selenium Crew did a great Job pointing us towards our own Errors ;)

[pause-bug-bachelor-1f.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2305209/pause-bug-bachelor-1f.side.zip)

**Comment by M3ssman** [comment]
I'm not able to construct a minimal not working example or come around with a similar context. 

Side-runner crashes where a button is dynamically generated due the outcome of an async Javascript Request that takes about 100ms (Request,Response,Button render). Maybe that's a Problem. 
The form-button between the suspect Formular stages is identified by the same Expression, maybe side-runner caches something that shouldn't be remembered ...
Finally it could also originate from the chrome-node behavior of the dockerized selenium-grid.

Since it can't be reproduced and seems to be fairly exotic, I'll close this one if you don't mind.
