### ISSUE TITLE
Move to prettier

### ISSUE THREAD

**Issue by corevo** [SeleniumHQ/selenium-ide#353]
## 🚀 Feature Proposal

Move to an automatic code formatter, like [prettier](https://github.com/prettier/prettier).

## Motivation

Currently contributors and maintainers have to manually format their code according to eslint's rules, prettier's spirit is to format the code for you automatically.  
Prettier supports almost all of the code editors out there.

## When?

Since changing the linter will cause re-linting of all source files, it will create conflicts for all pending prs, I will finish up with old ones like #139 and #144, I don't currently see a way for #228 and #230 to make it in.  
But we should probably make sure #220 and #241 make it in soon.

**Comment by tourdedave** [comment]
This looks to be done in 2b2be508ee6bfd7218abdddb0db519f89bd0ab1c. @corevo, good to close?
