### ISSUE TITLE
Disable Jest Validation Warnings

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#354]
## 💬 Questions and Help

Hello out there, 

is it possible to silence Jest Validation Warnings for the Unknown options that are currently shown up at Test Start? Did I miss some regarding Configuration Flag?

**Comment by corevo** [comment]
It is a bug, due to the semver we used in the runner, `npm` installs a version of jest that is newer than the one we use for testing (it is a common practice, to get important security upgrades).  
We will have to move to the current way jest suggests doing so.

**Comment by M3ssman** [comment]
Aren't you using npm 5.x+ with the package-lock-Mechanics? I suppose not, since there's a yarn.lock inside the side-runner package. Which node/npm-Versions do you use for Development? 
My previous company moved last year from yarn back to npm and was pretty happy with it.

**Comment by M3ssman** [comment]
If it's not such a big Issue, I can try to adopt the new jest format myself?

**Comment by corevo** [comment]
The lock files are ignored when you install a package, they are only used when you `npm` install your own project.

**Comment by corevo** [comment]
Quoting:
> During install Yarn will only use the top-level yarn.lock file and will ignore any yarn.lock files that exist within dependencies

**Comment by corevo** [comment]
Appears to be a bug in [jest](https://github.com/facebook/jest/pull/6852).  
They still haven't released a new version, for the time being I'll freeze the runner to run against jest 23.4.2 instead of 23.5.0.
