### ISSUE TITLE
Can it be possible to merge projects? Selenium IDE

### ISSUE THREAD

**Issue by AysKrmn** [SeleniumHQ/selenium-ide#355]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
To be able to merge projects. Seems we are only able to open 1 at a time currently. I decided to redesign my plan, some parts already recorded but cannot copy them over from the other projects (test plan).
## Motivation
It will make it easy copy, paste, change and re-use the tests between the projects as it will save time from re-doing.
Please outline the motivation for the proposal.
I created separate projects but I noticed actually it will be good to keep them together.
## Example
 I noticed after creating different projects, my test plan will be better organised if I keep them according to login profile rather than keeping them according to their subjects.
Please provide an example for how this feature would be used.
This feature would be used by adding another project to already opened one in Selenium IDE. Or to get Add, Merge function.

**Comment by RichardHaynes** [comment]
This would be really useful.  Particularly helpful for migrating old tests.  Migration is failing for my old suite and so I need to bring the individual tests in to isolate and fix the issues but then they're saved in separate projects.

**Comment by sarfarazpk** [comment]
It is quite easy through notepad ++, let you have two projects named pro1 and pro2 and want to merge pro2 into pro1, do following step
1-open pro1 project add a new test with same name as in pro2, add run at last of pro1 and in target write the name of pro2 test
2- open pro1.side  and pro2.side in note pad ++, copy all json steps of required test of pro 2 but with out the first step and paste in pro1 new test. And safe the file. You will get the updated merged project

**Comment by toddtarsi** [comment]
This isn't a feature I'm interested in writing, but any PR someone wants to write is encouraged.
