### ISSUE TITLE
In debug mode "Execute this command" operation contunues scenario instead of executing a single command

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#356]
In debug mode "Execute this command" operation contunues scenario instead of executing a single command

**Comment by corevo** [comment]
Took me a bit to understand the issue, the toolbar button works, the `X` shortcut fails.

**Comment by barancev** [comment]
Ah, yes, my bad, I did not localize it properly, did not check the toolbar, sorry.

**Comment by corevo** [comment]
If we are in debug mode, executing a command not in order is probably not something we want to allow.  
Outside debug mode we allow them to run archaic commands, to act as a "repl" of sorts, in debug I'm thinking changing the behavior to step over, like in the toolbar?  
Is that too confusing? or keep it as is, just execute this and nothing else?  

\cc @tourdedave

**Comment by barancev** [comment]
Well, well, stop... There is no such a toolbar button when you're in debug mode!

**Comment by barancev** [comment]
What I want to say is: we need a "one step forward" action in debug mode.

**Comment by corevo** [comment]
The wording of that button is incorrect, it should be "step over next command", rather than "run current command".

**Comment by corevo** [comment]
The question is, should I change `x` to be "step over" is debug mode, or execute this, to act more of a repl?

**Comment by barancev** [comment]
Ignore my previous comment, just upgraded from 3.2.3 to 3.2.4 and now I have a new toolbar button that works as expected.

So, we have an issue with 'X' shortcut and the corresponding context menu item. I'd expect it to be equivalent to "step over".

**Comment by corevo** [comment]
In Chrome debugger, I am able to execute any arbitrary line of code, as well as stepping over, I'm thinking about keeping `x` as execute this arbitrary command, and have another shortcut for stepping over.

**Comment by tourdedave** [comment]
+1 to keeping `x` as execute and adding another shortcut for stepping over

**Comment by corevo** [comment]
We'll need to abstract the run single command away from the execution loop, to allow a single command run without breaking the tree.

**Comment by corevo** [comment]
Fixed in e6397326ffbf05427d6020e8f6711cc2ad712104
