### ISSUE TITLE
Pause command and jest timeout

### ISSUE THREAD

**Issue by wilfi00** [SeleniumHQ/selenium-ide#357]
## 🐛 Bug Report

When i use the pause command with a value of, let's say 600000ms, i have the following message : 

> Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.

Indeed, the default jest timeout is set at 300000ms so the test fails...

## To Reproduce

Use the pause command with > 30000ms value : 
```
}, {
      "id": "1d283ba2-9aeb-4fe6-aa5f-65b926d5dc18",
      "comment": "",
      "command": "pause",
      "target": "600000",
      "targets": [],
      "value": ""
    }, {
```

## Expected behavior

Maybe the selenium-side-runner should increase the jest timeout value if necessary ? 
Am i missing something ?

## Environment

OS: Linux Mint 18
Selenium SIDE Runner Version:  3.2.0
Node version: 8.11.4
Browser: Firefox
Browser Version: 60.0.2 (64 bits)

**Comment by corevo** [comment]
You can change jest's timeout via the suite settings.  
![image](https://user-images.githubusercontent.com/888886/44471502-bb8eac80-a634-11e8-9987-9909900c5027.png)
There is no way for us to know how long a test will take, so you have to manually adjust that further.
