### ISSUE TITLE
Ignore Command

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#360]
## 🚀 Feature Proposal

Please add the Ability for a command to be ignored/disabled/deactivated without removing it.

Expected Behavior when ignoring a Command:

1. Log ignored Command to Console (optional with command target)
2. Proceed with any succeeding Commands, if exist

## Motivation

1. With Requirements rapidly changing or being very agile and elastic, it is often the case that a single Command or a sequence of Commands temporarily in development just won't work as expected. In high integrated work flows with automated E2E-Tests and alike, fails an inconvenient command a test and therefore can halt the whole continuous integration/deployment pipeline. 
2. Deleting a Command deletes in complex test scenarios a reminder of what has been left out.
3. When experimenting with Commands, one often just wants just to disable a step or a sequence of commands and not really to delete them. 

Tests can be filtered to achieve similar behavior at suite/file Level, it would be nice to enable such mechanics for a single Command of a single Test. 

## Example

Include short prefix ignore marker for a single command with letter "x" (used by mocha-Framework) or as regular single-line comment markers in a wide range of programming languages like "#", "//" or "--".

**Comment by corevo** [comment]
Great idea, maybe see how other tools are doing it?  
I tend towards `//` in front of the command name.  
I think specifically `$ignore{command name}` is not comfortable, because I would have to reactivate it by deleting characters from both ends.  
eslint is doing `// eslint-disable-line`, too long though.

**Comment by M3ssman** [comment]
You're right, if it's way easy to implement choose the prefix path. 
Users familiar with Mocha might favor a simple "x", since that's how they usually disable mocha-tests. Put the "x" in front of the command, like "xopen", "xassert text", and so on. According to [114-selenium-ide-complete-list-of-commands](http://seleniummaster.com/sitecontent/index.php/introduction-to-selenium-automation/selenium-ide/114-selenium-ide-complete-list-of-commands) No selenese command starts with an "x", there should be no conflicts.

**Comment by 98gmarquee** [comment]
I usually change the command to just be echo, then leave the other two fields as they were so I didn't lose the target and value, then it just echo's the target/value out into the log. Then to put the command back, I'd put the actual command back in the field. Granted, that was on the old ide. 

Also, that way gets iffy when you do a handful of various commands. Then you have to remember multiple commands, and if your workday is anything like mine, it could be 30 seconds between the time you deleted them or 3 hours.

**Comment by 98gmarquee** [comment]
It appears in the current ide though, if you put any text in the comment, it now comments the entire command without losing the command. Although, it doesn't show the command in the list unless you hover your mouse over the comment, then you can see the command/target/value again. Removing the text out of the Comment field then shows it normal again.

**Comment by 98gmarquee** [comment]
@M3ssman I'm not sure using x would be a great idea, since pressing x while on a command executes the command. Would make executing a command when you don't want to a more frequent thing.

**Comment by M3ssman** [comment]
@98gmarquee Your 're right with the IDE, but I meant to place the "x" straight into the Command input field. If you do so, nothing gets triggered. I personally suspect a pure exclamation represents more some kind of negation than ignorance.  

The major point regarding this is, IMHO, that the Log doesn't complain alike "Failed: Unknow command: xopen | //xopen | #open | !open" (or whatever ignore marker will be), but to log something like "Ignored: command open [with target: some-valid-url]" and continues fine with the following test-commands. I will point this out in the initial proposal.

**Comment by corevo** [comment]
I'm thinking of a keyboard shortcut that would make sense of the change, for example:  
<kbd>⌘ + /</kbd> would add a `/` in front of the command, `x` is already used, it wouldn't make a good key, and also would prevent adding commands that starts with `x` in the future.

**Comment by M3ssman** [comment]
Very well, I wasn't aware of keyboard shortcut dimensions. 

Semantically it'd straight forward to use something like "shift+x" to insert an ignore command marker, in opposite to just pressing mere "x" to execute a command. Some IDEs use the tabulator key for indention and shift+tab for the reverse command.

But these are implementation details, independent from the markers representation. If you can't got with an "x" (right now I can't recall a command making sense and starting with this letter anyway, but nevermind), a double-slash is also fine.

**Comment by corevo** [comment]
Will be shipped in the next version, there will be a button next to the command name to disable and enable the command.  
Moreover this can also be achieved by adding `//` in front of the command name.
