### ISSUE TITLE
Selenium IDE marks a project as "saved" even if a user canceled save operation

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#364]
## 🐛 Bug Report

Open a project from a file, modify the project, watch asterisks, click "save" button, cancel saving -- there are no more asterisks as if the project has been saved.

Screencast: https://www.screencast.com/t/7VXn4SSD

## Environment

OS: Windows 7
Selenium IDE Version: 3.2.4
Browser:
Browser Version: Firefox 61

**Comment by toddtarsi** [comment]
Desktop save is a bit less cancelable so this is resolved in v4
