### ISSUE TITLE
An inserted command should take focus immediately

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#365]
## 🚀 Feature Proposal

When a user inserts a new command they is going to enter command name and target.

It would be reasonable to make the new command current and put focus to the "Command" field of the added command.

Currently a user should perform three actions:
1) click "Insert a new command" menu item
2) click the added command line
3) click "Command" field to put focus into it

**Comment by MuntedKiwi** [comment]
+1
Super keen on this. Have 14,000 rows to migrate to the new Selenium. And often have to insert a new command because the many of the commands are new in the "new" Selenium.

**Comment by toddtarsi** [comment]
Done in v4
