### ISSUE TITLE
Selenium-Side-Runner | Issue/error when trying to use chromeOption.arg["user-data-dir=Default"]

### ISSUE THREAD

**Issue by Sirdcryot** [SeleniumHQ/selenium-ide#366]
Hi,

When using single value chromeoptions.args like incognito or start-maximized (see below) I  experience no issues. 

selenium-side-runner -c chromeOptions.args=[incognito] rave.side
selenium-side-runner -c chromeOptions.args=[start-maximized] rave.side**

Although when using the user-data-dir argument in accordance to below

selenium-side-runner  -c chromeOptions.args=[user-data-dir=Default] rave.side

my test halts and I receive a devtoolsactiveport error. 

 WebDriverError: unknown error: Chrome failed to start: crashed
      (unknown error: DevToolsActivePort file doesn't exist)
      (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)

selenium-side-runner -V
3.2.4
chromedriver -V
ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e)
node -v
v8.11.4
Selenium IDE
3.2.4

However, chrome gets started but remains inactive after the crash. Format error on the argument?

**Comment by tourdedave** [comment]
This appears to be resolved now. Closing. Please let us know if you're still experiencing problems.
