### ISSUE TITLE
Test list on the UI no longer scrollable

### ISSUE THREAD

**Issue by wangchj** [SeleniumHQ/selenium-ide#370]
## 💥 Regression Report

Updated to Selenium IDE 3.2.0 (not sure my previous version), but now the tests list cannot be scrolled up or down. I have a long list of tests and now I can't see all of them.

## Last working version

Worked up to version: < 3.2.0

Stopped working in version: 3.2.0

## To Reproduce

Steps to reproduce the behavior: have enough tests and try to scroll the list

## Expected behavior

The list should be scrollable.

## Environment

OS: MacOS Sierra
Selenium IDE Version:  3.2.0
Selenium SIDE Runner Version: ?
Node version: 10.1.0
Browser: Chrome
Browser Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by corevo** [comment]
Fixed in bcbfa652
