### ISSUE TITLE
Element ID target is no longer valid

### ISSUE THREAD

**Issue by wangchj** [SeleniumHQ/selenium-ide#372]
## 💥 Regression Report

Recently updated to Selenium 3.2.4. After the update, many of our tests are broken. Selenium IDE used to take only the id of a page element as the command target as following:

```
command: click
target: showJson
```

However, new version doesn't appear to support this kind of target.

## Last working version

Worked up to version: < 3.2.0

Stopped working in version: 3.2.0

## Expected behavior

Support element id as command target

## Environment

OS: MacOS Sierra
Selenium IDE Version:  3.2.5
Selenium SIDE Runner Version: ?
Node version: 10.1.0
Browser: Chrome
Browser Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by corevo** [comment]
It was removed by mistake, although it is not something we wish to support.  
I will make sure to re-add this, and include a deprecation notice.  
We are planning on removing all implicit locators, you will have to specify which one you with to use.  
Meaning `showJson` will become `id=showJson`.  
We will provide a seamless migrator to all scripts to work with explicit locators (when loading a project to the IDE, it will seamlessly convert your locators).
