### ISSUE TITLE
copy/cut/paste commands as TSV via clipboard

### ISSUE THREAD

**Issue by hiroshitoda** [SeleniumHQ/selenium-ide#377]
## 🚀 Feature Proposal

copy/cut/paste commands as TSV via clipboard.

## Motivation

If this feature is available, we can copy/cut/paste commands from testing plan data on spreadsheet(like Microsoft Excel, Google Spreadsheet) or plain text editor.

## Priority

I think #189 is prior than this feature.

**Comment by toddtarsi** [comment]
Exists in v4
