### ISSUE TITLE
Default Suite.test.js: Unexpected token, expected ; for domains in URLs starting with Number ?

### ISSUE THREAD

**Issue by calaba** [SeleniumHQ/selenium-ide#380]
## 🐛 Bug Report

Hello, seems SIDE Runner doesn't generate proper code for some URLs, our SIDE url is:
https://dev-asmarter.33aplus.cz - the SIDE file works in Selenium IDE AddOn (Chrome).

Trying to run same SIDE file using SIDE Runner ends with error:

 FAIL  ../../../../../side-suite-Untitled Project/Default Suite.test.js
  ● Test suite failed to run

    ..... side-suite-Untitled Project/Default Suite.test.js: Unexpected token, expected ; (10:16)

         8 | describe("Default Suite", () => {
         9 |   it("33a", async () => {
      > 10 |     await tests .33 a(driver, vars);
           |                 ^
        11 |     await driver.getTitle().then(title => {
        12 |       expect(title).toBeDefined();
        13 |     });

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.753s
Ran all test suites.
Test results written to: Untitled Project.json

## Environment

OS: Window 7 64-bit
Selenium IDE Version:  3.3.1
Selenium SIDE Runner Version:  3.3.1
Node version: v8.11.1

Browser:
Browser Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by M3ssman** [comment]
That's interesting, previously ( < 3.3.x) one could do something like `assert | 42 | 42 ` or store '42' als Value and then do assertions, but now this has changed, also in the current IDE version.

**Comment by corevo** [comment]
This has nothing to do with the URL, the URL is stored as string.  
This is the way that the test name is interpolated into a function name, what is the test name you are trying to run?

**Comment by calaba** [comment]
I think it has to be realted to the URL as the test doesn't refer anything special .. anyway ... attching the SIDE file:

{
  "id": "a5eaf03b-6274-4879-bcc2-55fab727bc0a",
  "version": "1.1",
  "name": "Untitled Project",
  "url": "https://dev-asmarter.33aplus.cz",
  "tests": [{
    "id": "5f3273c7-cbc1-40f3-81b5-f891a62c927b",
    "name": "33a",
    "commands": [{
      "id": "9362086c-add7-49fe-844a-1e127240e12b",
      "comment": "",
      "command": "open",
      "target": "/monitor/agenti-v-okoli",
      "targets": [],
      "value": ""
    }, {
      "id": "9069499c-7247-4285-9f5c-8625babcd1a4",
      "comment": "",
      "command": "type",
      "target": "id=username",
      "targets": [
        ["id=username", "id"],
        ["css=#username", "css"],
        ["xpath=//input[@id='username']", "xpath:attributes"],
        ["xpath=//div[@id='modal-body']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "user-name"
    }, {
      "id": "f4eb0812-95bb-40e3-a77f-61097624b787",
      "comment": "",
      "command": "type",
      "target": "id=password",
      "targets": [
        ["id=password", "id"],
        ["css=#password", "css"],
        ["xpath=//input[@id='password']", "xpath:attributes"],
        ["xpath=//div[@id='modal-body']/div[2]/input", "xpath:idRelative"],
        ["xpath=//div[2]/input", "xpath:position"]
      ],
      "value": "secret-password"
    }, {
      "id": "8714ccfe-f5d5-43f7-9756-2515898df800",
      "comment": "",
      "command": "click",
      "target": "css=span.ng-binding",
      "targets": [
        ["css=span.ng-binding", "css"],
        ["xpath=//span", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "eed41d1c-1a63-43c5-a645-238825ddf5b0",
      "comment": "",
      "command": "click",
      "target": "linkText=UME",
      "targets": [
        ["linkText=UME", "linkText"],
        ["css=a.ng-scope", "css"],
        ["xpath=//a[contains(text(),'UME')]", "xpath:link"],
        ["xpath=//div[@id='navigation']/ul/li[4]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/ume')]", "xpath:href"],
        ["xpath=//li[4]/a", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "f3ff58a5-4049-44d2-a60f-01dd674d18d8",
      "comment": "",
      "command": "click",
      "target": "linkText=test",
      "targets": [
        ["linkText=test", "linkText"],
        ["xpath=//a[contains(text(),'test')]", "xpath:link"],
        ["xpath=//a[contains(@href, '/ume/uzivatele/e6bbc2cb-771d-44ef-8ddd-c901b956d413')]", "xpath:href"],
        ["xpath=//tr[8]/td/div/div/a", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "7ac8ad28-5985-4b55-9be8-651e55509c22",
      "comment": "",
      "command": "click",
      "target": "css=div.userMenu",
      "targets": [
        ["css=div.userMenu", "css"],
        ["xpath=//div[3]", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "cc053a3f-c5cb-430a-a661-10d425fa5fac",
      "comment": "",
      "command": "click",
      "target": "linkText=Odhlásit",
      "targets": [
        ["linkText=Odhlásit", "linkText"],
        ["css=a.userMenu__item", "css"],
        ["xpath=//a[contains(text(),'Odhlásit')]", "xpath:link"],
        ["xpath=//div[3]/a", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1c6a07f0-f692-462a-ae0f-e23df13912b8",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["5f3273c7-cbc1-40f3-81b5-f891a62c927b"]
  }],
  "urls": ["https://dev-asmarter.33aplus.cz/"],
  "plugins": []
}

**Comment by calaba** [comment]
Ok, you were right -> after renaming test from "33a" to "test1" - it started to work ... so bug is in the logic of parsing the test name and using it for generated code.

**Comment by calaba** [comment]
Unfortunatelly another bug I am getting now is:

  Default Suite
    × test1 (6468ms)

  ● Default Suite › test1

    NoSuchElementError: no such element: Unable to locate element: {"method":"link text","selector":"Odhlásit"}
      (Session info: chrome=68.0.3440.106)
      (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

      31 |   });
      32 |   await driver.wait(until.elementLocated(By.linkText(`Odhlásit`)), configuration.timeout);
    > 33 |   await driver.findElement(By.linkText(`Odhlásit`)).then(element => {
         |                ^
      34 |     element.click();
      35 |   });
      36 | }

I am suspecting the National Characters in the link:

     "target": "linkText=Odhlásit",

Are now the issue ??? How to overcome this ???

**Comment by corevo** [comment]
The test name issue is known and will get fixed.  
The location is a bit more complex, can you post a test case with localized characters that fail?  
I'll make sure to have a look into that.

**Comment by calaba** [comment]
Ok. It is the JSON (SIDE) posted above - here attaching it again as file. It contains logout link ("Odhlásit") containing the national characters. This SIDE file was recorded in Chrome Selenium IDE Plugin and works fine in it. I had to change user/password values in the SIDE file, so you cannot really test it agains our site now. (security reasons).


[test1-err.zip](https://github.com/SeleniumHQ/selenium-ide/files/2345850/test1-err.zip)

**Comment by calaba** [comment]
And to be more exact - the error (findElementBy name) is confirmed for both scenarios:

- Local run with chromedriver 2.41
- remote run on WebDriver using the -s parameter (-s http://my-selenium-server:4444/wd/hub) - build from latest docker selenium/standalone-chrome

**Comment by calaba** [comment]
Additional details about the problem - maybe the bug is not in the National Characters used in the Link Name .... attaching very similiar SIDE file - there is only one difference - less clicks on some UI elements ... see windiff output comparing test1-err.side and test2-ok.side.


Test1-err.side - fails with the error above
Test2-ok.side - doesn't fail

[test1-test2.ZIP](https://github.com/SeleniumHQ/selenium-ide/files/2348360/test1-test2.ZIP)

**Comment by corevo** [comment]
Fixed in 78c4e290d717fc4a83d02e41c787d5cbea513158
