### ISSUE TITLE
Userfriendly Test Failure Log in the runner

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#381]
## 🚀 Feature Proposal

When a Testcase fails, provide user-friendly information about failed context like the Number of the Step that failed, like the IDE does.

## Motivation

Within larger Testcases (100+ Steps and lots of Repetitions), it can be quite hard to locate the Statement that the Test did fail, especially for a non-programmer. Currently, side-runner provides some Promise rejection Stacktrace. This is, of course, handy for the Developer, but less meaningful to the Framework User that precisely needs to know, which Assertion crashed a Test.

**Comment by tourdedave** [comment]
Closing. Will track in #564.
