### ISSUE TITLE
CSP error when using assert command in Firefox

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#382]
@julienb81 commented on [Mon Sep 03 2018](https://github.com/SeleniumHQ/selenium/issues/6357)

Command assert does not work any more with variable in the target. It works with the previous version 3.2.5. The variable value is considered undefined.

## Meta -
OS:  Windows 7
Selenium Version: IDE 3.3.1
Browser:  Firefox 62.0.1 and Chrome 68

**Comment by corevo** [comment]
Can you share the `assert` that you've written?

**Comment by M3ssman** [comment]
I doesn't work with the Selenium IDE either, so the problem might be introduced to side-runner from this Direction. Last week, before 3.3.x, I'm sure it was possible to have something going like 
```
| store   | 42        | myVar |
| assert  | ${myVar}  | 42    |
```

which yields right in the IDE Console (Selenium IDE, Firefox 61.0.1 (64-Bit) Ubuntu)

```
 assert on ${myVar} with value 42... Failed:
call to eval() blocked by CSP
```

**Comment by tourdedave** [comment]
We updated the usage of `assert` and `verify` in 3.3.1 so you can specify the variable name without interpolation brackets (e.g., `${}`). It looks like we didn't cover backwards compatibility, or make this difference clear in the reference docs. Apologies for the confusion.

**Comment by tourdedave** [comment]
@M3ssman do you get a CSP error when using `|assert | myVar | 42 |`?

**Comment by julienb81** [comment]
With the 3.3.1 version, | assert | myVar1 | myVar2 | doesn't work. 
In 3.2.5 version,  | assert | ${myVar1} | ${myVar2} | works. 
The error message is :  Failed:
Actual value '145.00' did not match 'myVar2'

**Comment by M3ssman** [comment]
@tourdedave 

I did the Test (see above) right now, Selenium IDE 3.3.1. 

In chromium (68.0.3440.106 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) it says
```
assert on ${n} with value 42... Failed:
Actual value 'undefined' did not match '42'
```

and Firefox (Ubuntu 16.04 LTS, 61.0.1 (64-bit)) yields that CSP-thing

```
assert on ${n} == 42... Failed:
call to eval() blocked by CSP
```

**Comment by tourdedave** [comment]
@M3ssman not `| assert | ${n} | 42 |` but `| assert | n | 42 |` (it's different than the example you provided above). Please try that and let me know if you still get CSP errors.

**Comment by tourdedave** [comment]
@julienb81 Try `| assert | myVar1 | ${myVar2} |`

**Comment by julienb81** [comment]
@tourdedave Thanks, it works

**Comment by M3ssman** [comment]
@tourdedave 

using 
```
store  | 42 | n 
assert | n  | 42
```

in Firefox (61.0.1 (64-Bit) Mozilla Firefox for Ubuntu)
still gives
```
1.store on 42 with value n... OK
2.assert on n with value 42... Failed:
  call to eval() blocked by CSP
```

and Chromium-Browser ( 68.0.3440.106 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit))
```
1.store on 42 with value n... OK
2.assert on n with value 42... OK
```

so Chromium Ubuntu succeeds, Firefox Ubuntu still fails.

**Comment by 98gmarquee** [comment]
FWIW, I ran into the same issue while tinkering on Windows10 FF61.0.2.
`store|42|myVar1
store|42|myVar2
assert|myVar1|myVar2`

As well as various combinations of the assert using `${}` or not.

I also tried using echo to show what I had in var1/2 and it throws another error:
`echo|${myVar1}|${myVar2}
or
echo|${myVar1} - ${myVar2}|`
![2018-0904_172714-snap](https://user-images.githubusercontent.com/33339926/45060956-f4347a00-b067-11e8-9b46-62799dcf7391.jpg)

**Comment by 98gmarquee** [comment]
Ok, I'm not sure what I did different, but it appears to work now when used without the braces on the target.
![2018-0904_180641-snap](https://user-images.githubusercontent.com/33339926/45062171-622f7000-b06d-11e8-8bb8-92fa962b7f8d.jpg)

**Comment by tourdedave** [comment]
Thanks for the additional info. I'll add a migration to offer backwards compatibility when using brackets. As for the CSP eval error on FF, it's a bug that we'll need to look into.

**Comment by toddtarsi** [comment]
v3 is going to be gone soon, and v4 is an electron app
