### ISSUE TITLE
Test Failed: Close | win_ser_local undefined

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/selenium-ide#384]
## 🐛 Bug Report

Close command throwing an error "a.Commands.list.get(...)" is undefined

## To Reproduce

Command: close
Target win_ser_local

## Expected behavior

it should close the current window

## Project file reproducing this issue (highly encouraged)

{
  "id": "90b21b4f-2cab-45b9-ba14-38fab6536db4",
  "version": "1.1",
  "name": "Bug ",
  "url": "",
  "tests": [{
    "id": "a024ace9-3c48-40ad-a6f6-95ca15492347",
    "name": "Untitled",
    "commands": [{
      "id": "28d503fa-922b-49b2-87cb-3d76e1524947",
      "comment": "",
      "command": "open",
      "target": "https://google.com",
      "targets": [],
      "value": ""
    }, {
      "id": "9421e538-5e83-4597-9ebb-7bc80feaf55b",
      "comment": "",
      "command": "selectWindow",
      "target": "win_ser_local",
      "targets": [],
      "value": ""
    }, {
      "id": "f6ac25f1-9af3-4132-93e6-29b2f55809db",
      "comment": "",
      "command": "close",
      "target": "win_ser_local",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "07dbc549-e340-4aa8-bfda-5ba6bbdd6958",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["a024ace9-3c48-40ad-a6f6-95ca15492347"]
  }],
  "urls": [],
  "plugins": []
}

## Environment

OS: windows 10
Selenium IDE Version:  3.3.1
Selenium SIDE Runner Version: 
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 
Browser: firefox
Browser Version: 61.0.2 (64-bit)

**Comment by hohnan** [comment]
When I am trying to close a popup, I get - 

"close on win_ser_1... Failed: Cannot read property 'target' of undefined"

Is this an issue because "close" has not been officially implemented as I do not see it in the list of Commands?

**Comment by tourdedave** [comment]
We've changed how new windows are handled in the IDE. This issue should be resolved. Please let us know if you're still experiencing issues by filing a new issue.
