### ISSUE TITLE
Can I check "Adding a Locator" WIKI link to know when custom locator feature is operational?

### ISSUE THREAD

**Issue by gwtuser** [SeleniumHQ/selenium-ide#387]
My understanding is that the custom locators are still not supported due to a few remaining bugs.  Coincidentally (or not?) I noticed that the "adding a locator" WIKI link just jumps to the main WIKI page.

I can I monitor that link to know when the feature is operational?  Will there be a clear announce in the release notes when it is?  We're going to launch some work when the feature is operational.

Thanks.

**Comment by corevo** [comment]
There will be an announcement in the release notes, plus the wiki page will be up with details.
