### ISSUE TITLE
Project is working fine in IDE but not with side runner (do | storeXpathCount | repeatIf = TimeoutError)

### ISSUE THREAD

**Issue by jayree** [SeleniumHQ/selenium-ide#388]
## 🐛 Bug Report

The following Project is waiting for a checkbox to be activated:
[testproject2.side](https://github.com/jayree/selenium-loop-test/blob/master/testproject2.side)

In this example the checkbox gets activated after 10 seconds.

- Project is working fine in IDE
- but, side runner stops with the following error:

> TimeoutError: Waiting for at least one element to be located By...

## To Reproduce

run the Project in IDE:

1.open on /?https://raw.githubusercontent.com/jayree/selenium-loop-test/master/looptest.html... OK
2.storeXpathCount on xpath=//input[@id='edit' and @disabled] with value count... OK
3.do on ... OK
echo: 1
5.storeXpathCount on xpath=//input[@id='edit' and @disabled] with value count... OK
6.repeatIf on ${count} > 0... OK
echo: 1
echo: 1
echo: 1
echo: 1
7.click on id=edit... OK
8.pause on 10000... OK

run the Project in side runner:

selenium-side-runner testproject2.side

`TimeoutError: Waiting for at least one element to be located By(xpath, //input[@id='edit' and @disabled])
Wait timed out after 15002ms`

       8 |   do {
       9 |     console.log(`${vars.count}`);
    > 10 |     await driver.wait(until.elementsLocated(By.xpath(`//input[@id=\'edit\' and @disabled]`)), configuration.timeout);
         |                  ^
      11 |     await driver.findElements(By.xpath(`//input[@id=\'edit\' and @disabled]`)).then(elements => {
      12 |       vars["count"] = elements.length;
      13 |     });

      at ../../../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/promise.js:2201:17
      From: Task: Waiting for at least one element to be located By(xpath, //input[@id='edit' and @disabled])
      at Object.wait [as Untitled] (commons.js:10:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        39.319s
Ran all test suites.
## Expected behavior

side runner keeps running the Project as long as the checkbox is disabled

## Project file reproducing this issue (highly encouraged)

https://github.com/jayree/selenium-loop-test

## Environment

OS: OSX/Windows
Selenium IDE Version:  3.3.1
Selenium SIDE Runner Version:  3.3.1

Node version: v10.9.0
Browser: chromedriver (2.41)/geckodriver (0.21.0)

**Comment by jayree** [comment]
`        {
          "id": "2eb1cf8f-89e2-4426-ad86-436f31da92df",
          "comment": "",
          "command": "executeScript",
          "target": "return document.evaluate(\"//input[contains(@id,'edit')]\", document.body, null, XPathResult.ANY_TYPE, null).iterateNext().getAttribute('disabled');",
          "targets": [],
          "value": "edit"
        },`

I've found a workaround to query the attribute of the checkbox using executeScript. It seems that javascript is more stable if the page is changing in the background.

**Comment by toddtarsi** [comment]
I imagine this to be a lot less likely now that the runtime in v4 is shared between the ide and the side runner
