### ISSUE TITLE
Viewing the tests tab while paused in debug mode whites out the IDE

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#389]
@Theexplor3r commented on [Mon Sep 10 2018](https://github.com/SeleniumHQ/selenium/issues/6388)

I created a random tests. While running one of the test I paused it in debugger and switched from Execute tab to Tests tab and ran the test with start button. What happened is that it whited-out.
![whited-out](https://user-images.githubusercontent.com/41435915/45297821-3dc11100-b50f-11e8-9aea-c5490bc9b9af.PNG)

**Comment by corevo** [comment]
Can't reproduce, please provide with more information, or better steps to reproduce the problem.

**Comment by corevo** [comment]
@Theexplor3r

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
