### ISSUE TITLE
Importing legacy IDE scripts errors when no base URL provided and using relative paths in open commands

### ISSUE THREAD

**Issue by hohnan** [SeleniumHQ/selenium-ide#395]
## 🐛 Bug Report

Unable to import old test cases that have an "open" command in them.

## To Reproduce

1. Open new Selenium IDE
2. Click Open Project
3. Select an old Selenium IDE test case(.html in my case)
4. Nothing happens

If I change the "open" command to say "verifyText" the file will import.

## Expected behavior

1. Open new Selenium IDE
2. Click Open Project
3. Select an old Selenium IDE test case 
4. Old file is imported and adjusted to new format

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

- Not a '.side' file but the html file is below adjusted to a log file.

Issues without a reproduction project are likely to stall.

[Login Quick Test.log](https://github.com/SeleniumHQ/selenium-ide/files/2394264/Login.Quick.Test.log)

## Environment

OS: Windows 10
Selenium IDE Version:  3.3.0
Browser: Chrome
Browser Version: Version 68.0.3440.106

**Comment by tourdedave** [comment]
There's no base URL specified in your test script and the `open` command uses a relative path. So the  IDE faults since it doesn't know how to construct a valid URL.

**Comment by hohnan** [comment]
Thanks for the explanation @tourdedave . 

I have removed the baseURL's from all my tests as I use them in test, UAT, and production environments at the same time and having a baseURL in a test messes this up. Maybe this isn't an issue in the new IDE as changing the baseURL works across all the tests as there are not really separate test cases any longer but rather one big test case with labels that act as test cases?

If that is the case, I can find a way to import the files I need going forward and use the new IDE's baseURL functionality so that you can close this bug.

**Comment by tourdedave** [comment]
Yes, that's right, the base URL in the new IDE is global (whereas it was localized to each test in the legacy IDE). You just need to change the base URL in in the menu bar, and then all of the test will use it (assuming the tests use relative paths in their `open` commands). If you need to persist a test to a given environment then you can use an absolute URL in an `open` command.

Also, you can use the command-line runner to achieve the same result (e.g., point the tests at different environments), while also gaining the ability to wire the tests up to CI, execute everything in parallel, and run them cross-browser.

https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-side-runner

**Comment by hohnan** [comment]
Thanks @tourdedave . Closing this bug.

**Comment by tourdedave** [comment]
\o/
