### ISSUE TITLE
"white screen" when attempting to edit select frame target

### ISSUE THREAD

**Issue by jlanawalt** [SeleniumHQ/selenium-ide#396]
## 🐛 Bug Report

When I click in the Target value drop down of a select frame command, the Selenium IDE window goes to a blank white window. This happens in Firefox 62.0 and Chromium 71.0.3556.0 (Developer Build) (64-bit) using Selenium IDE 3.3.1.

I manually loaded and tried SideeX and it didn't crash when clicking in that box for selectFrame commands.

## To Reproduce

Browse to a page with a frame, record your actions clicking in the page so that a select frame command is generated. Then select the select frame command from the list of recorded actions and down below click the drop-down value for the Target property.

I was able to reproduce this using this simple jsfiddle page: http://jsfiddle.net/d1fag5Ly/

## Expected behavior

No crash/white screen. The drop down shows at least the index=<value> option. Ideally it shows other options including a by-name and by-id selector. These things seem to work in SideeX.

## Project file reproducing this issue (highly encouraged)

{
  "id": "44d1f651-8f84-4900-84d0-3bd7a28018da",
  "version": "1.1",
  "name": "Untitled Project",
  "url": "http://jsfiddle.net",
  "tests": [{
    "id": "79682b8c-f090-4b27-b62b-7e8119a01061",
    "name": "Untitled",
    "commands": [{
      "id": "16fe6173-3e7b-4323-b592-15cb1528953d",
      "comment": "",
      "command": "open",
      "target": "/d1fag5Ly/",
      "targets": [],
      "value": ""
    }, {
      "id": "65a0b074-8664-4edf-a4ee-884019543143",
      "comment": "",
      "command": "selectFrame",
      "target": "index=0",
      "targets": [
        ["index=0", null]
      ],
      "value": ""
    }, {
      "id": "3d9a61da-28f1-47b7-bbc8-16cd2d6cc293",
      "comment": "",
      "command": "click",
      "target": "css=html",
      "targets": [
        ["css=html", "css"],
        ["xpath=//html", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "2f20d7ef-ff97-4e7f-a1df-b4585ad4c5a3",
      "comment": "",
      "command": "selectFrame",
      "target": "index=0",
      "targets": [
        ["index=0", null]
      ],
      "value": ""
    }, {
      "id": "779e4cce-bb5b-481f-a08f-707e8a5e29ff",
      "comment": "",
      "command": "click",
      "target": "css=html",
      "targets": [
        ["css=html", "css"],
        ["xpath=//html", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "35e07685-9b96-4e85-896c-03a0f6905e90",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["79682b8c-f090-4b27-b62b-7e8119a01061"]
  }],
  "urls": ["http://jsfiddle.net/"],
  "plugins": []
}

## Environment

OS: Windows 10 64 bit.
Selenium IDE Version:  3.3.1
Browser: Firefox
Browser Version: 62.0
Browser: Chromium
Browser Version: 71.0.3556.0 (Developer Build) (64-bit)

**Comment by jlanawalt** [comment]
I would like to match select frame by more than index. Using SideeX I am able to match by id or name by default, or specifically by id or name, or by xpath on id //iframe[@name='foo'] or css=iframe[name='foo'].

I tried editing the .side file and loading it back into Selenium IDE but it didn't seem to work with those patterns either. I don't know if the failure was related to this bug or just lack of support for the feature.

**Comment by tourdedave** [comment]
Thanks for filing an easy to reproduce issue! Regarding your follow-up comment, please file a separate issue for that.
