### ISSUE TITLE
Cannot find module "browser-webdriver"

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#397]
## 🐛 Bug Report

I can't build it. I don't know the exact reason, but I couldn't find the `browser-webdriver`.
3.3..0 version `browser-webdriver` is written on `package.json`, but the actual version does not exist.

## To Reproduce

1. checkout the last code from the master branch.
2. `peru sync` and `yarn`
3.  execute `yarn build:ext`

## Expected behavior

I wanna make it build.

## Project file reproducing this issue (highly encouraged)

Nope. Because this is not a problem with the operation.

## Environment

OS: 
Selenium IDE Version:  3.3.1
Selenium SIDE Runner Version:  
Node version: v8.11.3
Browser: chrome
Browser Version:  Version 69.0.3497.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/33743343/45726643-1519d500-bbfb-11e8-9db8-b7c3eff0cb39.png)

![image](https://user-images.githubusercontent.com/33743343/45726686-4f837200-bbfb-11e8-9eb3-f3297dad103b.png)

This is the result of `yarn build:ext`.
![image](https://user-images.githubusercontent.com/33743343/45726790-c02a8e80-bbfb-11e8-808d-4861ac4b7c2a.png)

Thanks.

**Comment by tourdedave** [comment]
Try running`yarn build:webdriver` and then `yarn build:ext`.

**Comment by Jongkeun** [comment]
It's was resolved after I deleted `yarn.lock` files.
I succeed in a build, but I encountered another problem.
I run a default test script.

![image](https://user-images.githubusercontent.com/33743343/45868761-9327d880-bdc1-11e8-87fc-6702142920b9.png)

![image](https://user-images.githubusercontent.com/33743343/45868788-a470e500-bdc1-11e8-9bc1-a70a98baf5e3.png)

Thanks to your help.
