### ISSUE TITLE
Assert Title does not match

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#398]
IDE 3.3.1 Chrome 67 Windows 10

Our page title is "foo | bar" and we `assert title` with value `foo | bar` - the IDE returns a fail:

> assertTitle on with value foo | bar... Failed:
> Actual value 'foo | bar' did not match ''

As I understand it the IDE does not support wildcards so we can't check for "foo*" and are thus stuck.

Same issue with verifyTitle.

**Comment by tourdedave** [comment]
Are you saying that a text match on an explicit string didn't work for `assert title` (and then tried to perform a wildcard match)? If so, can you provide a reproducible test case for the explicit string match failure?

Support for pattern matching in text verifications is tracked in #141.

**Comment by cawoodm** [comment]
Don't worry about wildcards - it was just a comment, I understand the IDE does not support this yet.

What I mean is: our page title is "myBühler | Login" and the IDE does not recognize this:

![image](https://user-images.githubusercontent.com/498834/46000253-4df8f480-c0a8-11e8-9bf6-1859df719305.png)

Here is the source:

![image](https://user-images.githubusercontent.com/498834/46000265-581af300-c0a8-11e8-89b3-f6d2616d7170.png)

Here are the results (trying encoded and unencoded entities):
![image](https://user-images.githubusercontent.com/498834/46000295-6b2dc300-c0a8-11e8-99d9-29b831c1b3f1.png)

I suspect the IDE is either not handling whitespace or entities correctly.

**Comment by corevo** [comment]
The correct syntax for `assert title` is `assert title | the title to assert`.  
The title text goes in the target field.
