### ISSUE TITLE
Iteratively loop through the available Targets in Selenium IDE before it reports a fail

### ISSUE THREAD

**Issue by joynexa** [SeleniumHQ/selenium-ide#399]
## 🚀 Feature Proposal

It would be good if Selenium IDE can do an iterative loop of the available targets while doing a playback of the recorded session, before it reports a fail.

## Motivation

Sometimes the preferred order in Selenium IDE,..ID, name, css, xpath..fails at the first/second target and quits. it would be good if can check the other available targets as well..

## Example
Thanks

**Comment by corevo** [comment]
This feature was already worked on, and will be shipped in the next version.  
\cc @tourdedave
