### ISSUE TITLE
Selenium IDE identifies command as "type" instead of "send keys" 

### ISSUE THREAD

**Issue by joynexa** [SeleniumHQ/selenium-ide#402]
## 🐛 Bug Report

When recording a text entry containing backslash( For eg: /a/b/c/d) , Selenium IDE records it as 

type | /a/b/c/d

However when I do a playback, it stops at this step with an error.
If I manually change to:

send keys | /a/b/c/d

it works..

Cant Selenium IDE auto detect the "/" special character and identify the command as send keys.
I guess it happens for other special characters like $..

## To Reproduce

Start Session Record with Selenium IDE, 
Input  an entry containing "/" into text box.Eg: /a/b/c/d)
The recorded command is: **type | /a/b/c/d**

## Expected behaviour

Expected that the Step gets recorded as:
**send keys | /a/b/c/d**

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
Please provide the environment information, and the error the IDE spits out.  
I think it originates from something entirely different than your suggestion `/a/b/c` looks like a file path in unix based systems, and therefore, the IDE tries to upload such file.

**Comment by joynexa** [comment]
Yes, what was provided was a file path in UNIX. However Test recorded and run on Windows Machine-Google Chrome.

The actual error Logs:
type on id=fl-input-1 with value /a/b/c/d... Failed:
{"code":-32000,"message":"Node is not a file input element"}

**Comment by corevo** [comment]
Make the CDP side of the IDE precheck if the input is `input[type="file"]` before proceeding, if not pass the command to SeleniumAPI.

**Comment by alpha4021** [comment]
Windows 10 
Chrome 78.0.3904.108 
Selenium IDE 3.16.0

The same is still reproduced. `type | /value/with/slash/` must be worked around by `send keys | /value/with/slash/` even it is not meant to be a path or file in the context (instead it is a unique id).

**Comment by toddtarsi** [comment]
@alpha4021 - I tried this in v4, and found the type command played back slashes just fine. I think there are some underlying runtime tweaks that probably have fixed this.
