### ISSUE TITLE
Unrecognized menu with id

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#403]
## 🐛 Bug Report

I have an unrecognized menu with id

I do a recording and i get this code : 

click    id=m_balparc.saisieArticle

When i execute the test i have this message : 

Trying to find id=m_balparc.saisieArticle... Failed:
Implicit Wait timed out after 30000ms

For information, when i use search tool :

- the object is highlighted in the page of application
- i have a popup on selenium window : "Element not found / Could not find id=m_balparc.saisieArticle on the page"

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: OSX
Selenium IDE Version:  3.3.1
Browser: Firefox
Browser Version: 61

**Comment by rob1gr** [comment]
The same code in the old version is OK. 

What do you want ? The .side file ?

**Comment by rob1gr** [comment]
![ano menu saisie](https://user-images.githubusercontent.com/40666727/45884175-797f9480-bdb3-11e8-81a7-7e708a75a468.jpg)

**Comment by corevo** [comment]
In which version did it work last?

**Comment by rob1gr** [comment]
2.9.1

**Comment by corevo** [comment]
I need a away to reproduce this, either via a working project file, or you could create a small html file that reproduces it, and attach it.

**Comment by rob1gr** [comment]
[menu.html.txt](https://github.com/SeleniumHQ/selenium-ide/files/2405588/menu.html.txt)

**Comment by rob1gr** [comment]
You have juste to rename the txt file in html (because it's impossible to put an html file) and

you can try to click to menu with name "Saisie Article" with the command click and target id=m_balparc.saisieArticle

**Comment by rob1gr** [comment]
[menu 2.html.txt](https://github.com/SeleniumHQ/selenium-ide/files/2405833/menu.2.html.txt)

This is the new one with a message when click on menu

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity. If this is still a problem for you, please reopen the issue.
