### ISSUE TITLE
To integrate testSuite in HUDSON (old version of JENKINS)

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#406]
## 🚀 Feature Proposal

With the old structure of testSuite (html file) it's good to integrate in HUDSON to plan testing in an automnic way

How to do this with the new structure (.side file)

![suitefile in hudson](https://user-images.githubusercontent.com/40666727/45886420-6374d280-bdb9-11e8-870b-50aa3f96d8ce.jpg)

## Motivation

Plan testing in an automnic way

## Example

Please provide an example for how this feature would be used.

**Comment by corevo** [comment]
This is not a HUDSON development forum, you would have to contact HUDSON to add integration for the new `side` format.
