### ISSUE TITLE
Unknown Locator when starting with trailing whitespace

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#410]
## 🐛 Bug Report

When a locator starts with a space, the side-runner reports:
`throw new Error("Unknown locator  //span[@class")` , which looks quite strange at fist glance.
This can happen quite easy when editing a lot manually inside the Target column. 

## To Reproduce

Add space before a command with a locator and run as usual. Explicit locator, implicit locator, Chromium-Container, Firefox-Container - all produce the same error with no difference.

## Expected behavior

Selenium IDE can handle this, obviously stripping the leading space. Would be nice to behave similar.

## Project file reproducing this issue (highly encouraged)
[selenium-side-runner-trailing-space.zip](https://github.com/SeleniumHQ/selenium-ide/files/2415233/selenium-side-runner-trailing-space.zip)

## Environment

OS: Ubuntu 16.04 LTS
Selenium IDE Version:  3.3.1
Selenium SIDE Runner Version:  <!-- e.g.: 0.7.0
Please note that selenium-side-runner supports Node.js 8 - 10
Node version: 8

**Comment by M3ssman** [comment]
How does the IDE handle this? Since it's not a problem when working with the GUI, this must be taken care of somewhere?

@corevo 
What do you mean by fixing automatically? Write trimmed version back to *.side File?

**Comment by corevo** [comment]
Closed with #499
