### ISSUE TITLE
Disable Commands

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#413]
## 🚀 Feature Proposal

It would be nice to have an option to disable a command so that it is skipped during test execution.

## Motivation

Often, during test creation we may have additional checks (e.g. assert) which cause problems. Instead of removing them we could comment them out as we do with normal code.

## Example

In our case we are creating tests with the IDE, exporting the `.side` file and running with a separate tool. That tool needs certain extra commands which are not available in the IDE and should be ignored.

**Comment by corevo** [comment]
Duplicate of #360
