### ISSUE TITLE
clickAndWait Command

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#416]
## 🚀 Feature Proposal

A `clickAndWait' to complement the plain old `click` command is required. See the Kantu IDE.

## Motivation

Some clicks are client-side (e.g. a tab) but some require waiting for the page to reload (e.g. a submit button). The test designer needs to be able to specify this.

## Example

https://a9t9.com/kantu/docs/selenium-ide/click

**Comment by corevo** [comment]
`clickAndWait` is a command that introduces implicit wait (waiting for a page to load), we are doing that automatically.  
If you have an example test case in which the implicit wait does not work, open a bug about it, with a reproducible test case.

**Comment by cawoodm** [comment]
I have lots of examples where I have a click which loads content and I sometimes need to wait (for images or XHR to load) and sometimes not (simple tab click to display a hidden div). I see no way to manage this today without resorting to `pause`. You really need to consider these cases.

One example: I have a button which pops up a new div with an image which loads slowly. I want to verify the image is loaded. Currently the IDE does not wait and immediately tries to verify the image and fails. How can I say that it should wait for the element to appear? Where are implicit waits handled and configured?

**Comment by cawoodm** [comment]
![image](https://user-images.githubusercontent.com/498834/46198592-20f94b80-c30d-11e8-99eb-a23494a8fbd3.png)

As shown above the IDE does not implicitly wait for elements. I've had to add my own directives to the comments (e.g. !WAIT) to work around such problems.
