### ISSUE TITLE
Imported Assert Text is not working

### ISSUE THREAD

**Issue by Hexahydra** [SeleniumHQ/selenium-ide#417]
## 🐛 Bug Report

Imported Assert Text is not working if target is element containing other elements.
If I try record Assert Text targetting for example `<ul>`tag, I see '\n' character after every list item. But '\n' characters are missing in imported text asserts.

## To Reproduce

Migrate attached old IDE test. Or see the .side contains both recorded and migrated asserts.

## Expected behavior

Migrated text asserts will be working.

## Project file reproducing this issue (highly encouraged)

[oldTextAsserts.zip](https://github.com/SeleniumHQ/selenium-ide/files/2419971/oldTextAsserts.zip)

## Environment

OS: Windows 7
Selenium IDE Version: 3.3.1

Browser:
Browser Version: Firefox 62.0 (64 bit)

**Comment by tourdedave** [comment]
In the legacy .html project you provided there are no `\n` characters in the assert commands. If you add them to the file and then do an import the characters will be preserved.
