### ISSUE TITLE
Is there a solution for generating python test scripts?

### ISSUE THREAD

**Issue by 17radix** [SeleniumHQ/selenium-ide#424]
Hello, I am a python developer, because the test front end needs to use selenium-ide that you developed, it is excellent.
I have used the sahi test suite before, and the scripts it generates are relatively readable. I tried to change selianize package to meet my own needs like screenshot ,record the time of each step, but the changes were not easy.
Is there a solution for generating python test scripts? If not, I can contribute.
It will be provided like a pip package,like npm package.
It will convert the side file into a python test case file and call webdriver to execute
And attach my screenshots and timing features

**Comment by corevo** [comment]
Currently there is not support to export test cases into python, you are more than welcome to develop that.

**Comment by 17radix** [comment]
I want to confirm the data structure of the .side file, is it like this?

class Command():
    id = "",
    comment = "",
    command = "",
    target = "",
    targets = [],
    value = ""

class TestCase():
    id = "",
    name = "",
    commands = List(Command)

class Tests():
    id = "",
    version = "",
    name = "",
    url = "",
    tests = List(TestCase)

 is there a standard format description file and standard command set for the side file?

**Comment by 17radix** [comment]
Ok, I get it, I found that the selianize update is still frequent now, I will support  stable commands temporarily , such as click, double click, assert.... I plan to release the version at the end of last month, but I am worried that the data structure is not stable.

**Comment by johanneswilm** [comment]
@17radix Where are you developing the python exporter? Or have you given up on doing it?

**Comment by vvccool** [comment]
可以导出成python3了吗？

**Comment by tourdedave** [comment]
It will be released later this week.

You can track the progress in #592.

**Comment by darkartswizard** [comment]
Awesome!
