### ISSUE TITLE
Command "choose ok on next confimation" fails in 3.3.1.

### ISSUE THREAD

**Issue by Nachikethan1** [SeleniumHQ/selenium-ide#427]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
My test works, please provide a reproducing test case.

**Comment by corevo** [comment]
Potentially a duplicate of #392

**Comment by corevo** [comment]
@tourdedave seems the same issue as #392, is it a duplicate?

**Comment by tourdedave** [comment]
Seems like a duplicate, but will need to confirm against their repro steps.

**Comment by tourdedave** [comment]
When I record the steps outlined, a `choose ok on next confirmation` command is not recorded because I there aren't any JS confirmation dialogs. We'll push the fix we have for this command in the next release. Then you confirm if it resolves your issue.

**Comment by Nachikethan1** [comment]
Fixed in 3.4.1 version
