### ISSUE TITLE
Execution failed: TypeError: this.playingFrameLocations[this.currentPlayingTabId] is undefined

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#43]
Trying to run SeIDE in Firefox, execution fails with "Execution failed: TypeError: this.playingFrameLocations[this.currentPlayingTabId] is undefined"

See the screencast: https://www.screencast.com/t/TQYXHrSy

**Comment by Jongkeun** [comment]
I think that this situation's reason is similar to [this](https://github.com/SeleniumHQ/selenium-ide/issues/42).
If you create new tab like github, then it works fine.
But  you try to run SeIDE in tabs such as Add-ons(about:debugging#addons) or default tab,
It seems like this situation is happening.
Thanks you for your report.

**Comment by corevo** [comment]
I'll add a better error message to indicate that the user has to use the extension in a "normal" tab
