### ISSUE TITLE
 How do I add variable with integer value ?

### ISSUE THREAD

**Issue by khalid123456** [SeleniumHQ/selenium-ide#431]
ex:

<tr>
    <td>store</td>
    <td>${i}+1</td>
    <td>i</td>
</tr

**Comment by corevo** [comment]
`store` does not evaluate variables, use `execute script` instead:  
`execute script | return ${i} + 1 | i`

**Comment by khalid123456** [comment]
can i know why below while loop doesn't work properly ?
store | 1 | i
while | ${i}<10 |
echo | hello
execute script | return ${i}+1
end

**Comment by corevo** [comment]
`store` stores strings, so `i` is initially `"1"` rather than the real number `1`.  
Use instead `execute script` like so:  
`execute script | return 1 | i`

**Comment by khalid123456** [comment]
infinite loop 
how i can print "hello" 10 times ?

**Comment by corevo** [comment]
![image](https://user-images.githubusercontent.com/888886/46344216-19a5ab00-c649-11e8-8246-7b724777bbd9.png)
