### ISSUE TITLE
is there a commanad can I use it instead of "go back"?

### ISSUE THREAD

**Issue by khalid123456** [SeleniumHQ/selenium-ide#432]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
Duplicate of #393
