### ISSUE TITLE
Ability to adjust the default wait time.

### ISSUE THREAD

**Issue by 98gmarquee** [SeleniumHQ/selenium-ide#438]
## 🚀 Feature Proposal

It would be useful to be able to override the default "wait" time. In the old IDE, you could change the default in the settings, but I'm not seeing a way to do that anymore. 

## Motivation

I usually set it to something really high like 5 minutes or more as we have things that load a database into cache and on large setups, it can take 3+ minutes on the first hit after java is restarted for the site to "open". It's also helpful when there's a web service that is taking over a minute to return data, then the "wait for visible" function doesn't throw an error.

## Example

Just something as simple as "set wait time"|300000|" as the first command on a script before "open|<url>|" is called.

**Comment by corevo** [comment]
That is not the implicit wait time, I should probably clarify this in the dialog, this is for the [selenium-side-runner](https://www.npmjs.com/package/selenium-side-runner), it is the timeout for each test in the suite.  
But adding an implicit wait override makes quite a bit of sense there.

**Comment by 98gmarquee** [comment]
Being able to change it directly in a scripts steps would prove useful. Then if you have to filter through 15 pages, and you have a couple that have things that lag on you, you can increase the wait time for those elements alone, or sections of the script vs using a global for all scripts in a suite. Kind of like the "setSpeed" setting used to let you do which was more to create a static pause between steps.

Setting it globally is fine as well. If that's how it works.

**Comment by Yrds** [comment]
@98gmarquee now you can use "wait" commands in selenium 3.4.0 in that cases

**Comment by 98gmarquee** [comment]
Yeah, just wish they wouldn't have made the new window popup/open thing as that's really annoying to me.

**Comment by ChrisLMerrill** [comment]
I will second the request for changing the default wait timeout. My customer wants to use SeleniumIDE to gather performance data on their system. I've cobbled together some rudimentary performance measurement recording within SeleniumIDE and I am considering writing an extension to make it more elegant. But some of the operations take >30 seconds - which of course kills the test and prevents gathering the data they need.  (Yes, they know that 30sec is unacceptable - which is why they want to start tracking changes in performance as they work to improve it)

**Comment by steve-hyde** [comment]
Does anyone know how to execute a task at an exact time? I need to take a turn to fast

**Comment by toddtarsi** [comment]
How exact are we talking here? I'd say for either v3 or v4, you probably want to use the browser.
Something like an executeAsyncScript would work. I believe this would check every 50 ish ms:

```
new Promise(function(done) => {
  const handler = setInterval(() => {
    if (Date.now() < ${yourTargetTime}) return;
    clearInterval(handler);
    done();
  }, 50);
});
```

I'm not sure what the exact format is for executeAsyncScript is right now, so trying some stuff out might be necessary. Further, I'm not sure if there is like time zone stuff this has to account for, but its at least decently illustrative.

**Comment by toddtarsi** [comment]
This exists as a configurable timeout property.
