### ISSUE TITLE
Unable to use the option "Play from here" in 3.4.1 IDE

### ISSUE THREAD

**Issue by Nachikethan1** [SeleniumHQ/selenium-ide#445]
Unable to use the option "Play from here" in 3.4.1 IDE version.
After recording the test case, if i choose a particular step -> Right click and choose the option "Play from here" will open a new tab with below URL
---------
chrome-extension://mooikfkahbdckldjjndioackbalphokd/bootstrap.html 
-----------------
Previous version was working good on this option.
I am using Chrome browser (Version 69.0.3497.100 (Official Build) (64-bit))
Windows 10 OS

**Comment by corevo** [comment]
Duplicate of #440
