### ISSUE TITLE
legacy imports / testcase without .html extension can no longer be loaded

### ISSUE THREAD

**Issue by alexisdal** [SeleniumHQ/selenium-ide#448]
While importing legacy TestSuite, Selenium IDE does offer to import corresponding files with their correct name. 
But when their extension is *NOT* html, trying to drag&drop them results in the rectangle being red without any indication whatsoever. 

A clear message should indicate that the testcase extension must be .html to be imported (in the past it wasn't a requirement)

## To Reproduce

Create the following legacy test suite

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="testBackupDatabase.seleniumTest">Backup / Restore / Upload Database</a></td></tr>
</tbody></table>
</body>
</html>

```

![image](https://user-images.githubusercontent.com/5380181/46764472-d13b5c80-ccdc-11e8-926b-c8f44fc1f4ab.png)

observe that selenium IDE prompts you to drag'n drop the file `testBackupDatabase.seleniumTest` (that does not end up with .html)
so it looks like the import did work. 

However, while trying to drag'n drop the file, the selection window gets red, hinting that something's not right, even though the import did seem to have worked so far.

## Expected behavior

A clear message at test suite import time should indicate that test cases without a .html will not be loaded, and maybe offer a link towards a migration guide.

## Environment

OS: Windows 10
Selenium IDE Version:  3.4.2
Browser: Chrome    
Browser Version: 69.0.3497.100 (64 bits)
(reproduced in firefox 56.0 (32 bits))

**Comment by capoerafreak** [comment]
corevo has already written something about this in #93
So I think we can close this.

**Comment by alewater** [comment]
I opened the file which is saved by Selenium IDE using my ultraedit. I found that the content format of the file is JSON. I really was confused by Selenium IDE. Why can it not open the file that was saved by itself.

**Comment by tourdedave** [comment]
That's helpful feedback @alexisdal, thanks!

@alewater, your issue is similar but different. Please see my comments in #457.

**Comment by capoerafreak** [comment]
@corevo: 598363e0 solve this problem right?

**Comment by corevo** [comment]
@capoerafreak correct
