### ISSUE TITLE
Test is de-synchronized among panels

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#451]
We have a test called "myParts Basic" which we ran in Selnium IDE and then modified. When we save the .side file our changes are not reflected, When we view the same test in the "Tests" panel we see only the old state which is identical to what is saved. So basically we have 2 versions of the same test and only the old (wrong version) is saved. Test Suites shows it correctly.

1. Tests Executing (new version)
![image](https://user-images.githubusercontent.com/498834/46861642-63de1780-ce13-11e8-973e-1db1c5809c96.png)

2. Test Suites (new version)
![image](https://user-images.githubusercontent.com/498834/46861666-75272400-ce13-11e8-8ca1-d527b210637b.png)

3. Tests (old version)
![image](https://user-images.githubusercontent.com/498834/46861718-98ea6a00-ce13-11e8-9ab9-51acdcdd8eb3.png)

4. .side Project file (old version)
![image](https://user-images.githubusercontent.com/498834/46861736-a4d62c00-ce13-11e8-9e78-fbaebd7805f6.png)

**Comment by tourdedave** [comment]
@cawoodm I'm not sure I fully understand your issue, so let me see if I can repeat it in my own words.

1. You have .side project file which you open in the IDE.
2. You edit the `myParts Basic` test and then save the project again (overwriting the original project file or just saving it to another project file?)
3. The new project file does not reflect the changes you just made
4. The IDE shows different versions of the `myParts Basic` test between the Tests and Test Suites views

Is that accurate, or did I miss something?

**Comment by cawoodm** [comment]
So this issue was reproduced and fixed? Because I'm having it today:
1) Open a project
2) Edit a comment
3) Save
Changes are not saved to .side file.

**Comment by cawoodm** [comment]
What certainly seems to be an issue is changing a test which you are running in the "Executing" panel. Any changes made there are never saved.
