### ISSUE TITLE
Selenium IDE can't click print page elements that is displayed in front of main window

### ISSUE THREAD

**Issue by giznaj** [SeleniumHQ/selenium-ide#453]
## 🐛 Bug Report

We have an internal page that can't be accessed by the selenium community here, but I have included 2 other examples that have the same behaviour (included in attached .side script).

Run the selenium.side script attached to this bug and you will have 2x tests that exhibit the same behaviour that we see internally.

Previously to the current version of Chrome (or even a bit earlier), when you clicked print on a page, the windows.print.dialog window was presented to the user and selenium IDE/WD would fail as it is not able to click those types of controls (OS level).  You used to have to use AutoIt or something similar. 

With the new version of Chrome, the print dialog now is in HTML.  You can actually inspect the page and see the html and elements.

The issue is that I can't get selenium IDE to select that window (HTML print dialog).  I've tried the ID, Name and Title and I can't get it to work.  There is actually a related problem with this as it doesn't timeout ever.  It just hangs infinitely.

The two examples I provided are for a Test Print page and a test page on W3Schools.  The W3Schools script works a bit where you can select the print popup window, but I can never get back to the main windows using (select Window | Null).  The Test Print page breaks on being able to even select the print dialog and it also hangs infinitely.

Also, on the one test case in my attached script (Print Test Page), Selenium IDE is able to click the button to bring up the print dialog, but selenium IDE doesn't think this happened until the window is closed.  So you will see selenium IDE hang on this click command, but if you take over and close the window (print dialog) with your mouse, the 'click' command will now turn green and the script carries on.

## To Reproduce
1. Run the attached .side file to see similar behaviour.  Also, you can find any page that allows you to print which opens a browser print dialog box

## Expected behavior
1. Selenium IDE should be able to select the print dialog window either by ID or Name/Title and then click the "print" or "cancel" button on the page. 

## Project file reproducing this issue (highly encouraged)
See attached

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 7
Selenium IDE Version:  3.4.4
Selenium SIDE Runner Version:  NA
Node version: NA
Browser: Chrome
Browser Version:  67.0.3396.87
[Test.Project.zip](https://github.com/SeleniumHQ/selenium-ide/files/2480272/Test.Project.zip)

**Comment by corevo** [comment]
My assumption is that it is a chrome page e.g. begins with chrome:// just like the settings page.
Those pages are elevated, and extentions can't interact with them.
I would have to confirm, but I'm pretty sure it falls under that category.

Cheers,
Tomer

**Comment by giznaj** [comment]
Hi corevo,

You were right.  I've included a screen shot for us to refer to.  Just to be sure, there will be no way to handle this right?  Now or later?  If so, I'll change that test immediately and stop at that point.
![chrome print](https://user-images.githubusercontent.com/5216071/47016540-fa654e00-d11d-11e8-9392-4950d9b10e5d.PNG)

**Comment by corevo** [comment]
For the same reason explained in #469 this page can't be interacted with as well.
