### ISSUE TITLE
throw Error("Cannot set the selection end");  when setting text in input with type email.

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#454]
@MintLucky commented on [Tue Oct 16 2018](https://github.com/SeleniumHQ/selenium/issues/6540)

## Meta -
OS:  any
Selenium Version:  3.5
Browser:  any

## Expected Behavior -
The input field value should change to the appropriate text value entered like it does with other types or nontype input fields.

## Steps to reproduce / Actual Behavior
When attempting to sendKeys (Selenium IDE) on an input field of type email or number, the error of "Cannot set the selection end" is thrown.

## How it is happening
The sendKeys command calls the selection.js goog.dom.selection.setText function which checks for the ability to use selectionStart (via goog.dom.selection.useSelectionProperties_ function), which returns false, and thus throwing the error.

Per the W3 standards (https://www.w3.org/TR/html5/forms.html#the-input-element) the number/email input field types do not have IDL attributes selectionStart/selectionEnd. This is why goog.dom.selection.useSelectionProperties_ function returns false.

## Possible solution
Implement specific logic in selenium atoms for inputs that not have IDL attributes selectionStart/selectionEnd ( email and number )  and not check them for the ability to use selectionStart.

## The same issue was raised over a year ago
https://github.com/SeleniumHQ/selenium/issues/4361
Is there any progress in fixing this issue in WebDriver, Selenium IDE or SideeX ?

---

@barancev commented on [Tue Oct 16 2018](https://github.com/SeleniumHQ/selenium/issues/6540#issuecomment-430188369)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

---

@MintLucky commented on [Tue Oct 16 2018](https://github.com/SeleniumHQ/selenium/issues/6540#issuecomment-430197812)

See it now please

---

@barancev commented on [Tue Oct 16 2018](https://github.com/SeleniumHQ/selenium/issues/6540#issuecomment-430201965)

Is it related to WebDriver or Selenium IDE?

---

@MintLucky commented on [Tue Oct 16 2018](https://github.com/SeleniumHQ/selenium/issues/6540#issuecomment-430206080)

I'm using SideeX code. SideeX inherited this bug from Selenium IDE. Seems that Selenium IDE inherited this bug from WebDriver. 
In my case it is more related to Selenium IDE, but in common seems this bug is related for both.

**Comment by corevo** [comment]
@barancev `send keys` is implemented by deferring the action to [bot.action.type](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/content/selenium-api.js#L1288).  
It is an atoms issue, you should re-open the original.

**Comment by barancev** [comment]
@corevo Can you at least reproduce it?

**Comment by corevo** [comment]
It doesn't reproduce in the IDE, but if it is an issue then it would originate in the atoms.  
The IDE itself doesn't throw when sending keys to inputs of either type email or number.

**Comment by barancev** [comment]
If it can't be reproduced in IDE and can't be reproduced in WebDriver -- why it's an issue anyway? :)

**Comment by corevo** [comment]
OP seemed to have a thorough explanation of the issue with seemingly not working repro case, I'm closing unless a repro is submitted.

**Comment by barancev** [comment]
@MintLucky Note the verdict
