### ISSUE TITLE
Let me know where the code is.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#456]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

Thanks to keeping this application improved.
I wonder somethings.
I asked on slack before, but I couldn't get responses of it.

When I click the "Choose File" button on this site(http://the-internet.herokuapp.com/upload), 
the dialog doesn't show up in scripts.
But If I execute a command separately, the dialog shows up.
I know that this is under your intention.
Is there any reason why file dialog, alert, confirm dialog don't show up?
And where is the code which prevented dialogs?
I want to know. So I have tried, but I couldn't find it out. 
Please let me know the part of the code.
Thanks.

**Comment by sporthcophcop** [comment]
Hi Jongkeun,
Long story short: Selenium IDE acts on browsers tabs and windows which contain HTML. 
The file dialog, alert, confirm dialog are browser application windows (They are part of the browser. They are not from the web application). The Selenium project makes the clear choice to only support clicks in browser windows which contains HTML.

**Comment by corevo** [comment]
@sporthcophcop partially correct, native dialogs such as these, not only we can't automate, but more than that they halt javascript execution, which means that if a dialog opens up for any of these cases the IDE will be stuck until the user manually closes them.  
[This](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/content/prompt.js) is where it is defined.

**Comment by Jongkeun** [comment]
Thanks, @sporthcophcop, @corevo.
