### ISSUE TITLE
Fail to open an exist project which is saved before by Selenium IDE

### ISSUE THREAD

**Issue by alewater** [SeleniumHQ/selenium-ide#459]
I can not reopen the issue which is not really solved. So I need to make it open here.

The previous issue is https://github.com/SeleniumHQ/selenium-ide/issues/457.

Please there are someone really trying the steps!

**Comment by corevo** [comment]
I'll gladly reopen the issue and get the bottom of this with you, there is no reason to open a new issue, it just creates confusion for us, as the conversation is split among threads.

**Comment by alewater** [comment]
> I'll gladly reopen the issue and get the bottom of this with you, there is no reason to open a new issue, it just creates confusion for us, as the conversation is split among threads.

Thank you for help!
