### ISSUE TITLE
Window is too high by default

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#46]
1) Set resolution to 1280x720
2) Open Selenium IDE -- its window does not fit the screen:
https://www.screencast.com/t/Wi49RRgBcnS

**Comment by corevo** [comment]
I can't replicate this on my machine (mac nor windows)
![selenium ide 1280x720](https://user-images.githubusercontent.com/888886/33128747-27c3fab6-cf96-11e7-8937-54cff8ce8d8e.png)
Which commit have you checked out?

**Comment by Jongkeun** [comment]
I seems to occur in Windows 7.
If not, isn't it affected by the display resolution?

**Comment by corevo** [comment]
I'll try to get my hands on a Windows 7, in the meanwhile the extension remember the last size it was opened in.  
Resizing is persistent, just first time in Windows 7 machines is a bit clunky

**Comment by barancev** [comment]
Yes, this issue happens on the first start after installation only.

**Comment by corevo** [comment]
I can open it smaller, so that in the case of Windows 7 that does not shrink to fit, the first time use will be pleasant
