### ISSUE TITLE
ExecuteScript | return var | $var with persist session enabled is not allowing for variable re-use test-2-test

### ISSUE THREAD

**Issue by giznaj** [SeleniumHQ/selenium-ide#460]
## 🐛 Bug Report

This was handled in StoredVars previously (which is not available in the new selenium ide) which would allows you to save a string into a storedVars which could be later called by another test with the value still intact.  Now that StoredVars is not available, I am seeing to use Execute Script + "Persist Session", however that is still now working for me

## To Reproduce

1. Enable "Persist Session" in the selenium IDE settings for the test suite in question (being run)
2. Use the execute script with the return key word and save a string into a variable (pass)
3. Echo the variable to make sure the value is retained/saved in the same test where it was defined (pass)
4. Echo the variable another test case during the same session, just echo's the the variable name, and not the value contained within.  It looks like you can't share variables right now across tests (fail)

## Expected Results:
1.  Like StoredVars, the test suite should be able to re-use variable values from test to test in the same session.

## Environment
OS: Windoze 7
Selenium IDE Version:  3.4.4
Selenium SIDE Runner Version:  N/A
Node version: N/A
Browser: Chrome
Browser Version: 67.0.3396.87

**Comment by giznaj** [comment]
@corevo - Any ideas or suggestions on how to handle this?

**Comment by corevo** [comment]
Can you post a test case file, it will shorten my time to get to this.

**Comment by giznaj** [comment]
I will do one right now and update the issue.  Thanks for getting back to me!  :-)

**Comment by giznaj** [comment]
@corevo - While putting together the .side file for you to reference and troubleshoot against, I found more information that might help you.  If you run the suite as a suite (2 tests run sequentially), the variables are retained and can be used from test to test.  However, if you run a test individually, then the next test individually the variable is not retained.  

This test suite does not have the 'persist session' option enabled.
[Variable.Reuse.zip](https://github.com/SeleniumHQ/selenium-ide/files/2562857/Variable.Reuse.zip)


I have still attached the .side file for you to reference.

**Comment by tourdedave** [comment]
For reference, there are several ways to store things in variables. They're all listed in the docs ([link](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#store)).

With the changes to playback made since v3.4.4, this issue resolved itself.

Closing. Let us know if you're still experiencing problems.
