### ISSUE TITLE
Test Search should be case-insensitive

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#465]
Searching lowercase should find results, instead:
![image](https://user-images.githubusercontent.com/498834/47444935-f1c4e580-d7b7-11e8-8719-f129d0df8ecc.png)

No search should be case-sensitive in the world ever...
![image](https://user-images.githubusercontent.com/498834/47444965-030df200-d7b8-11e8-887d-9ba61629c2f2.png)

**Comment by cawoodm** [comment]
Point taken.

**Comment by corevo** [comment]
Fixed in 0c70405d
