### ISSUE TITLE
Selenium IDE can't interact with elements on chrome://extensions/

### ISSUE THREAD

**Issue by giznaj** [SeleniumHQ/selenium-ide#469]
## 🐛 Bug Report

in the previous most recent version of Selenium IDE you were able to interact with the elements on the chrome://extensions/ page.

To run accessibility tests in an automated way, you used to be able to (w Selenium WD and the IDE 2.9.1) click/interact with the elements on the page chrome://extensions/ which would allow you to run WAVE evaluation with shortcut keys

## To Reproduce
1. With Selenium IDE go to chrome://extensions/ (pass)
2. Attempt to interact with any of the elements on the page (links, buttons, by ID, XPATH) and the commands just hang.

![image](https://user-images.githubusercontent.com/5216071/47604705-3d031200-d9cb-11e8-840e-3c1d4e4152f9.png)

## Expected behavior
1. Expectations are that selenium IDE can interact with the elements on this page.

## Project file reproducing this issue (highly encouraged)
See attached. 

[Selenium.IDE.zip](https://github.com/SeleniumHQ/selenium-ide/files/2521786/Selenium.IDE.zip)

## Environment
OS: Windows 10
Selenium IDE Version:  3.4.4
Selenium SIDE Runner Version:  N/A
Node version: N/A
Browser: Chrome
Browser Version: 69.0.3497.100 x64

**Comment by giznaj** [comment]
Right!  @corevo - Do you want me to close it?

**Comment by corevo** [comment]
That is correct, the IDE can't interact with chrome protected pages, the same is true for firefox ones.  
e.g. `about:debugging`, `chrome://extensions` and the sorts.
