### ISSUE TITLE
Encourage DRY tests by allowing tests to be included within other tests

### ISSUE THREAD

**Issue by janedallaway** [SeleniumHQ/selenium-ide#471]
## 🚀 Feature Proposal

I'd like to have the ability to include tests within another test to allow for the building of core test modules and the use of testing personas without having to duplicate commands.

(If this is already in place somewhere, please point me at an example)

## Motivation

I'd like to cut down on copy/paste or duplication within my test cases. Currently I feel that my tests are contributing to technical debt as I have to make changes in multiple places when core functionality changes.

## Example

Imagine I'm working on a system which requires a user to login. 
I'd, obviously, like to have a set of tests which test the negative/validation aspects of login and then have one (or more) which works successfully. When I then want to test another aspect of the system, I'm going to be required to log in. So I'd like to use my successful login script as a building block without duplicating the commands within that test. If my login functionality subsequently changes I won't need to re-record every subsequent test.

**Comment by tourdedave** [comment]
@janedallaway Have a look at the `run` command. You can specify a test case name in the target input field of the command to execute that test from within the current one.
