### ISSUE TITLE
Run Pyhton File From Selenium IDE

### ISSUE THREAD

**Issue by thais781** [SeleniumHQ/selenium-ide#473]
Hi,

First sorry for my english, I am a french girl.
I am using for the first time Selenium IDE and just a question.
I have no problem to save my work in python, but is there a way to launch/run a python file when I have modify it ?
Launch it. from the Selenium IDE as we can do with a Html file

Thanks for your help

Thais

**Comment by giznaj** [comment]
Hi thais781,

What type of Python file are you trying to run in the IDE?  Can you provide an example?

**Comment by capoerafreak** [comment]
The IDE doesn‘t support Python right now, maybee take a look at #424

**Comment by corevo** [comment]
Closing under the impression of duplicate of #424.  
If this isn't please explain the differences and I'll gladly reopen the issue.
