### ISSUE TITLE
Chrome IDE suddenly becomes slow to run tests

### ISSUE THREAD

**Issue by felipeccastro** [SeleniumHQ/selenium-ide#476]
## 🐛 Bug Report

When I installed the Selenium IDE in Chrome, any tests I recorded ran very fast - so fast I couldn't keep up with what they were doing, but it was working.
Then, suddenly the tests started to become painfully slow, out of no apparent reason. A test that would run in 2 seconds now takes 30 seconds, taking almost 2 seconds to run each step of the script.
I didn't change the default velocity (it's on fastest), and I couldn't find any suspicious setting at the .side file. 

## To Reproduce

I don't know what caused this exactly. The one thing I've noticed is that if I uninstall the extension and install it again, it returns being super fast. I ran all my tests (the exact same .side file as before) and it was working fine, until it encountered the first failing test (waiting for an element that never appeared). After failing this one test, all tests started to run super slow again, so it might be related to that somehow.
I've also noticed that if I change the test velocity to be slower, instead of staying 2 seconds per step of the script, it takes 5 seconds, so it's still respecting the velocity, but the fastest it gets is 2 seconds per step for some reason.

## Expected behavior

It should stay fast :) 

## Project file reproducing this issue (highly encouraged)

I have attached the project I'm working on, but I don't think it's related to the side file, since the problem is (temporarily) fixed by simply reinstalling the plugin.

[side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2536400/side.zip)

## Environment

OS: macOS High Sierra
Selenium IDE Version:  3.4.4
Browser: Chrome latest

**Comment by tourdedave** [comment]
Thanks for trying to provide a reproducer. Unfortunately since we can't run it (e.g., since we can't access the app) we can't use it to confirm the issue. If you're able to provide project file which demonstrates the issue against a publicly available site then that would be a big help.

**Comment by vishal-lehar** [comment]
Hi,

I have experienced similar issue with IDE, when running test on MAC OS, running on chrome continuously , test run becomes very slow.
But when I minimize test browser window test execution takes normal speed.

Chrome: Version 70.0.3538.110 (Official Build) (64-bit)
chromedriver: ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)


[grab.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2606363/grab.side.zip)

**Comment by mjachowdhury** [comment]
Hi, 
Did you check on Selenium IDE test speed options fast or slow....

**Comment by tourdedave** [comment]
I'm unable to reproduce. Please try running your tests with the latest version of the IDE and Chrome.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
