### ISSUE TITLE
Blank screen after test files are migrated 

### ISSUE THREAD

**Issue by nylemenon** [SeleniumHQ/selenium-ide#481]
I am trying to load old Selenium test suites using IDE v3.4.4. I use FF 63.0.1 and open an old test suite and migrate the test files one by one. I see blue tick next to all my test cases, but as soon as the last one is migrated the screen turns blank and there is no other way around it except closing out the window. Not sure how to work around it...

- All my files are .html

**Comment by capoerafreak** [comment]
this is a known bug #449, it looks like the base url is empty right?

**Comment by nylemenon** [comment]
You are right, that worked, thanks, closing this.
