### ISSUE TITLE
Log panel filter

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#483]
## 🚀 Feature Proposal

The filter of the Log panel.

## Motivation

I needed to see only the `echo` logs. 
I hope that there are filters like Error, Debug, Warn, Info.

## Example

This is one of old selenium.
![image](https://user-images.githubusercontent.com/33743343/48601230-656ea280-e9b2-11e8-91a6-dcd85b0bb2b6.png)

**Comment by toddtarsi** [comment]
I don't even have a console panel rigged up yet 😬 
Closing this in favor of actionable things in v4 like any logging at all

**Comment by darkartswizard** [comment]
Y’all blowing up my email! 😀👍
Sounds like some exciting stuff is happening!

**Comment by toddtarsi** [comment]
@darkartswizard - Haha, no nothing exciting just me housekeeping and being grumpy. There's a lot of v3 issues, and I've been fully invested in the v4 alpha for a few months now, and I'm not even sure how v3 is supposed to work with manifest v3 come january, so I'm just trying to shift the focus of the github repo to really be about v4 issues and fixes.

**Comment by Jongkeun** [comment]
How cool! 
I've been really looking forward to this project coming back to alive.
Cheers @toddtarsi !

**Comment by toddtarsi** [comment]
Lol don't be that excited - it's really bad and missing a lot of features. If you want to mess with the alpha, feel free to try it out here:

https://github.com/SeleniumHQ/selenium-ide/releases
