### ISSUE TITLE
Unable to type and select from combobox.

### ISSUE THREAD

**Issue by vishal-lehar** [SeleniumHQ/selenium-ide#489]
## 🐛 Bug Report

After login to staging portal need to go to user portal by type and select user name from combobox.
Combobox has 10K entries.

But selenium-runner stuck on this and never go to user portal.
Test run fails after timeout.

## To Reproduce

Steps to reproduce the behaviour:
login to portal
it opens page to select user portal(combobox entries, 10k entries, takes 10 secs to load).
manually type user name and select value and go to user portal (it works manually)
but saved  script does not work.

[test_fail.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/2602285/test_fail.side.txt)

Logs:
Running 'test_1_login_to create_xxx'
1.open on https://xxx-stag-xxx/xxx/home.php... OK
2.setWindowSize on 1280x721... OK
3.type on id=myusername with value xxxxx@yyyy.xxx... OK
4.type on id=mypassword with value xxxxxx... OK
5.click on name=Submit... OK
6.type on css=.custom-combobox-input with value xxxx yyyy ( - Account No: xxxxx )... OK
7.click on id=submitlogin... OK
8.Trying to find css=area[alt="Purchasing"]... Failed:
Implicit Wait timed out after 30000ms
'
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: MACOS 
Selenium IDE Version:  3.4.2 
Selenium SIDE Runner Version:  3.4.2 
Node version: v10.12.0 
Browser: Chrome
Browser Version: 70.0.3538.77

**Comment by corevo** [comment]
These are not reproduction steps, please provide either a project file we can test against.
Or specific steps against a website that shows this problem.
As the information you've provided is insufficient to reproduce the bug, this issue can not be resolved.

Cheers,
Tomer

**Comment by vishal-lehar** [comment]
updated with .side file

**Comment by tourdedave** [comment]
Thanks for the .side file, but it's incomplete. We need a way to reproduce the issue. The file you attached is not runnable for us to see the problem and fix. If you're able to provide a reproducible test case (including an application we can run the test against) we'll happily take a look.

**Comment by vishal-lehar** [comment]
@tourdedave, the issue was with type and search box...some how Selenium ide was not able to run the exact steps... I'll try to provide you new .side file...thanks!

**Comment by tourdedave** [comment]
Okay, thanks. I've updated the labels and will re-open it for now.

**Comment by vishal-lehar** [comment]
Please find attached updated side file and screen recording ( what i want to do)


[wms_new.zip](https://github.com/SeleniumHQ/selenium-ide/files/3572894/wms_new.zip)

**Comment by tourdedave** [comment]
@vishal-lehar Can you provide the markup for the select/combobox? You can right-click, click inspect, and take a screenshot of the markup from the developer tools.

**Comment by vishal-lehar** [comment]
Here it is...
![image](https://user-images.githubusercontent.com/23118311/64397211-130e8780-d093-11e9-9189-274b374d4ff7.png)

**Comment by toddtarsi** [comment]
This should work on latest (v4)
