### ISSUE TITLE
Getting error while running selenium-side-runner *.side.

### ISSUE THREAD

**Issue by vishal-lehar** [SeleniumHQ/selenium-ide#491]
## 🐛 Bug Report

I have my project.side file and chromebrowser in Downloads/ dir, when i try to run test, it seems it runs successfully but i am getting below error message:-

[grab.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/2603435/grab.side.txt)

UrbanFoxs-MacBook:Downloads xxx$ sudo selenium-side-runner  grab.side 
Password:
info:    Running grab.side
 FAIL  ./Default Suite.test.js (16.029s)
  Default Suite
    ✕ test (12081ms)

  ● Default Suite › test

    WebDriverError: invalid session id
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.1 x86_64)

       9 |   it("test", async () => {
      10 |     await tests["test"](driver, vars);
    > 11 |     await driver.getTitle().then(title => {
         |                  ^
      12 |       expect(title).toBeDefined();
      13 |     });
      14 |   });

      at Object.checkLegacyResponse (../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/error.js:546:15)
      From: Task: WebDriver.getTitle()
      at Object.getTitle (Default Suite.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        16.553s
Ran all test suites.

## To Reproduce

Logs with --debug option:

sudo selenium-side-runner  grab.side --debug
Password:
debug:   Could not load .side.yml
info:    Running grab.side
debug:   jest worker args
debug:    0=--testMatch, 1={**/***/*.test.js,**/***.test.js}
debug:   jest work opts
debug:    cwd=/Users/vishalpaliwal/Downloads/side-suite-grab, stdio=inherit
 FAIL  ./Default Suite.test.js (14.604s)
  Default Suite
    ✕ test (10344ms)

  ● Default Suite › test

    WebDriverError: invalid session id
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.1 x86_64)

       9 |   it("test", async () => {
      10 |     await tests["test"](driver, vars);
    > 11 |     await driver.getTitle().then(title => {
         |                  ^
      12 |       expect(title).toBeDefined();
      13 |     });
      14 |   });

      at Object.checkLegacyResponse (../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/error.js:546:15)
      From: Task: WebDriver.getTitle()
      at Object.getTitle (Default Suite.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        15.08s, estimated 16s
Ran all test suites.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: MacOS
Selenium IDE Version:  3.4.2 
Selenium SIDE Runner Version:  3.4.2
Node version: 10 
Browser: Chrome
Browser Version:

**Comment by tourdedave** [comment]
Can you confirm that you are able to run the command `chromedriver` from a terminal window?

You should see something like this if you're able to:

```sh
> chromedriver
Starting ChromeDriver 2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8) on port 9515
Only local connections are allowed.
```

If you're not able to, then make sure that ChromeDriver has been added to your system path and then try running the runner again.

**Comment by vishal-lehar** [comment]
I am able to run chrome driver:-

 ./chromedriver 
Starting ChromeDriver 2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052) on port 9515
Only local connections are allowed.
^C

**Comment by corevo** [comment]
chromedriver is not in PATH

Cheers,
Tomer

**Comment by vishal-lehar** [comment]
Added chromedriver location to PATH and chromedriver running as command, but still getting error message . Check below:-

-MacBook:Downloads$ chromedriver
Starting ChromeDriver 2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052) on port 9515
Only local connections are allowed.
^C
-MacBook:Downloads$ 
-MacBook:Downloads$ 
-MacBook:Downloads$ 
-MacBook:Downloads$ sudo selenium-side-runner grab.side 
info:    Running grab.side
 FAIL  ./Default Suite.test.js (15.943s)
  Default Suite
    ✕ test (11454ms)

  ● Default Suite › test

    WebDriverError: invalid session id
      (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.1 x86_64)

       9 |   it("test", async () => {
      10 |     await tests["test"](driver, vars);
    > 11 |     await driver.getTitle().then(title => {
         |                  ^
      12 |       expect(title).toBeDefined();
      13 |     });
      14 |   });

      at Object.checkLegacyResponse (../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/error.js:546:15)
      From: Task: WebDriver.getTitle()
      at Object.getTitle (Default Suite.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        16.423s
Ran all test suites.

**Comment by tourdedave** [comment]
Try updating your ChromeDriver to [2.44](https://sites.google.com/a/chromium.org/chromedriver/downloads). Also, can you confirm what version of Chrome you're running?

**Comment by vishal-lehar** [comment]
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by vishal-lehar** [comment]
Updated to 2.44, chromedriver version

chromedriver --version
ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)

But still seeing issue...

sudo selenium-side-runner grab.side 
Password:
info:    Running grab.side
 FAIL  ./Default Suite.test.js (13.747s)
  Default Suite
    ✕ test (10102ms)

  ● Default Suite › test

    WebDriverError: invalid session id
      (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.1 x86_64)

       9 |   it("test", async () => {
      10 |     await tests["test"](driver, vars);
    > 11 |     await driver.getTitle().then(title => {
         |                  ^
      12 |       expect(title).toBeDefined();
      13 |     });
      14 |   });

      at Object.checkLegacyResponse (../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/error.js:546:15)
      From: Task: WebDriver.getTitle()
      at Object.getTitle (Default Suite.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        14.25s, estimated 16s
Ran all test suites.

**Comment by tourdedave** [comment]
Try updating your Chrome Version to latest as well (e.g., Version 70.0.3538.110 (Official Build) (64-bit))

**Comment by vishal-lehar** [comment]
Google Chrome is up to date
Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
And what happens with the updated Chrome Version?

**Comment by vishal-lehar** [comment]
Issue still persists.... with latest chrome and chromedriver 

chrome
Version 70.0.3538.110 (Official Build) (64-bit)
chromedriver
ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)

sudo selenium-side-runner grab.side 
Password:
info:    Running grab.side
 FAIL  ./Default Suite.test.js (13.423s)
  Default Suite
    ✕ test (10097ms)

  ● Default Suite › test

    WebDriverError: invalid session id
      (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.1 x86_64)

       9 |   it("test", async () => {
      10 |     await tests["test"](driver, vars);
    > 11 |     await driver.getTitle().then(title => {
         |                  ^
      12 |       expect(title).toBeDefined();
      13 |     });
      14 |   });

      at Object.checkLegacyResponse (../node_modules/jest-environment-selenium/node_modules/selenium-webdriver/lib/error.js:546:15)
      From: Task: WebDriver.getTitle()
      at Object.getTitle (Default Suite.test.js:11:18)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        13.929s, estimated 14s
Ran all test suites.

**Comment by tourdedave** [comment]
Is this still an issue for you?

If so, please do an `echo $PATH` and confirm that the directory containing `chromedriver` is listed from the terminal window you're running your tests in.

**Comment by corevo** [comment]
Try to not close the initial window at the end of the test, we do that for you.

Cheers,
Tomer

**Comment by tourdedave** [comment]
Is this still a problem?
