### ISSUE TITLE
Test suite failed to run: Your test suite must contain at least one test

### ISSUE THREAD

**Issue by JamesCullen2** [SeleniumHQ/selenium-ide#493]
## 🐛 Bug Report

Running Selenium IDE using Selenium Side Runner, the browser opens but then immediately exits and fails test citing 'Test suite failed to run: Your test suite must contain at least one test'.  

`debug:   Could not load .side.yml
info:    Running CHA_Test.side
debug:   jest worker args
debug:    0=--testMatch, 1={**/***/*.test.js,**/***.test.js}
debug:   jest work opts
debug:    cwd=/Users/jamescullen/projects/CHA_tests/side-suite-CHA Tests, stdio=inherit
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at ../../../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest/node_modules/jest-cli/build/TestScheduler.js:256:22

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.442s
Ran all test suites.
`

## To Reproduce

1. Download Selenium IDE for Chrome. 
2. Record Test and save. 
3. npm install -g selenium-side-runner
4. install ChromeDriver 2.44 
5. add ChromeDriver to /usr/local/bin
6. $ selenium-side-runner -c "browserName=chrome" test.side

## Expected behavior

` PASS  ./Default Suite.test.js (7.983s)
  Default Suite
    ✓ Test_A (5984ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        8.223s
Ran all test suites.
`
## Project file reproducing this issue (highly encouraged)

`{
  "id": "146871c8-31bc-4702-9408-3811e339b663",
  "version": "1.1",
  "name": "CHA Tests",
  "url": "http://www.[protected for data protection purposes].com",
  "tests": [{
    "id": "ac7dd84f-30b1-44a2-bd93-f1865e3c3427",
    "name": "Test_B",
    "commands": [{
      "id": "68dcfb69-2f37-405c-86ac-49a84b8511f1",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "8dadcbf1-9a22-462b-a1dd-ddb55e6869af",
      "comment": "",
      "command": "setWindowSize",
      "target": "1920x1080",
      "targets": [],
      "value": ""
    }, {
      "id": "84e50f9a-3fa6-4fe2-9026-2e3e5982e2cd",
      "comment": "",
      "command": "click",
      "target": "linkText=Explore",
      "targets": [
        ["linkText=Explore", "linkText"],
        ["css=#primaryNav li:nth-child(3) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Explore')]", "xpath:link"],
        ["xpath=//nav[@id='primaryNav']/ul/li[3]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/explore')]", "xpath:href"],
        ["xpath=//li[3]/a", "xpath:position"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "702b3248-f2ed-4455-ac0d-cf1a38c00494",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": []
  }],
  "urls": ["http://www.[protected for data protection purposes].com/"],
  "plugins": []
}`

## Environment

OS X 10.14.0
Selenium IDE Version:  3.4.4
Selenium SIDE Runner Version:  3.4.2

Node version: 11.3

Browser: Chrome
Browser Version: 70.0.3538.102

**Comment by JamesCullen2** [comment]
Forgot to mention that the test runs successfully when ran from the Selenium IDE browser interface.

**Comment by corevo** [comment]
Your suite is empty and does not have tests in it, add your recorded test to a test suite before attempting to use the runner.

**Comment by JamesCullen2** [comment]
> Your suite is empty and does not have tests in it, add your recorded test to a test suite before attempting to use the runner.

Thank you @corevo
