### ISSUE TITLE
some questions about seleniumIDE when it's executed in chrome

### ISSUE THREAD

**Issue by pyhacx0f** [SeleniumHQ/selenium-ide#495]
Environment:

os:windows7
seleniumIDE: 3.4.4
browser:chrome

Doubts:
I've found some differences between firefox and chrome when it use seleniumIDE to playback.just may be some unique of playback.js

part code of playback.js:
 function w(e, t, o) {
                if (e.commands) {
                    if ("waitPreparation" == e.commands) p["doWaitPreparation"]("", p.preprocessParameter("")),
                    o({});
                    else if ("prePageWait" == e.commands) p["doPrePageWait"]("", p.preprocessParameter("")),
                    o({
                        new_page: window.sideex_new_page
                    });
------
what's the mean of the patterns 'e.commands', 'waitPreparation' and ‘doWaitPreparation’?and why this playback.js works well in firefox but not very smooth in chrome.because i can find some patterns such as window.setNewPageValue and others in firefox but can't in chrome.is the code below doesn‘t work in chrome? 
part of the code below(just some code of playback.js):
---
w.prototype.doWaitPreparation = function() {
                this.eval('function setNewPageValue(e) {window.new_page = true;};                window.addEventListener("beforeunload", setNewPageValue, false);                if (window.XMLHttpRequest) {if (!window.origXMLHttpRequest || !window.ajax_obj)......              _win.addEventListener("DOMSubtreeModified", setDOMModifiedTime, false);', [], !1)
            },
---
What is the difference between chrome and firefox when playback.js works?how this javascript works?and why i can't find some patterns in chrome which i found in firefox? hope for your answer.thanks!

**Comment by pyhacx0f** [comment]
and what's the command of 'WaitPreparation' mean'?how to use this command?

**Comment by corevo** [comment]
Please use code blocks to post code, putting it in bold makes your issue very unreadable.  
Moreover it seems you have copied code from the production build of the extension, which is uglified, helping you around uglified code is a very tedious process, instead I suggest looking over the human-readable code in this repository, and linking to it.  
We will be happy to help you understand the code, but pasting uglified pieces of the code in an issue, is not the way to go about it.

**Comment by corevo** [comment]
Again link to a file in [this repository](https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-ide), the code you are referring to is uglified, and not the original version we are authoring.

**Comment by pyhacx0f** [comment]
> Again link to a file in [this repository](https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-ide), the code you are referring to is uglified, and not the original version we are authoring.

this is a latest extension for chrome,name seleniumIDE and version 3.4.4. it‘s downloaded from https://chrome.google.com/webstore/. ’it’s not your original version???this is the code of your version.which can found by the way src/content/selenium-api.js.and what the code mean and how to trigger it?thanks
![3](https://user-images.githubusercontent.com/42615898/48979681-8beeb500-f0f9-11e8-916d-c9d5a383ddb9.png)

**Comment by pyhacx0f** [comment]
> > Again link to a file in [this repository](https://github.com/SeleniumHQ/selenium-ide/tree/master/packages/selenium-ide), the code you are referring to is uglified, and not the original version we are authoring.
> 
> this is a latest extension for chrome,name seleniumIDE and version 3.4.4. it‘s downloaded from https://chrome.google.com/webstore/. ’it’s not your original version???this is the code of your version.which can found by the way src/content/selenium-api.js.and what the code mean and how to trigger it?thanks
> ![3](https://user-images.githubusercontent.com/42615898/48979681-8beeb500-f0f9-11e8-916d-c9d5a383ddb9.png)

![4](https://user-images.githubusercontent.com/42615898/48979693-ab85dd80-f0f9-11e8-988e-311588395641.png)

**Comment by corevo** [comment]
https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/content/selenium-api.js#L685

**Comment by pyhacx0f** [comment]
> https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/content/selenium-api.js#L685

can you explain more about that function.I have seen it many times, but confused.thanks.

**Comment by corevo** [comment]
It is called [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/neo/IO/SideeX/playback.js#L166), as part of the implicit wait.

**Comment by pyhacx0f** [comment]
> It is called [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/neo/IO/SideeX/playback.js#L166), as part of the implicit wait.

thanks.
