### ISSUE TITLE
selenium-side-runner can't handle path to Firefox executable that contains spaces

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#496]
## 🐛 Bug Report

selenium-side-runner can't handle path to Firefox executable that contains spaces

## To Reproduce

`selenium-side-runner -c "browserName=firefox moz:firefoxOptions.binary='c:\Program Files\Mozilla Firefox\firefox.exe'" -f Search Litecart.side`

Output:
```
info:    Running Litecart.side
 FAIL  ./Search.test.js
  ? Test suite failed to run

    SessionNotCreatedError: Failed to start browser 'c:\Program: no such file or directory
```

## Environment

OS: WIndows 7
Selenium SIDE Runner Version:  3.4.2
Node version: v10.13.0

**Comment by corevo** [comment]
The workaround for now is to use double quotes.
