### ISSUE TITLE
setSize does not work in Internet Explorer

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#498]
## 🐛 Bug Report

Run the attached project:
`selenium-side-runner -c "browserName=ie" Test.side`

Exception:
```
info:    Running Test.side
 FAIL  ./Default Suite.test.js (8.33s)
  Default Suite
    ? TestCase (2750ms)

  ? Default Suite > TestCase

    WebDriverError

      2 | tests["TestCase"] = async (driver, vars, opts) => {
      3 |   await driver.get((new URL("/", BASE_URL)).href);
    > 4 |   await driver.manage().window().setSize(...(`1228x979`.split("x").map
((s) => parseInt(s))));
        |                                  ^
      5 |   await driver.wait(until.elementLocated(By.linkText(`About`)), config
uration.timeout);
      6 |   await driver.findElement(By.linkText(`About`)).then(element => {
      7 |     element.click();

      at parseHttpResponse (../../AppData/Roaming/npm/node_modules/selenium-side
-runner/node_modules/selenium-webdriver/lib/http.js:536:11)
      at doSend.then.response (../../AppData/Roaming/npm/node_modules/selenium-s
ide-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.manage().window().setSize(1228, 979)
      at Driver.schedule (../../AppData/Roaming/npm/node_modules/selenium-side-r
unner/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Window.setSize (../../AppData/Roaming/npm/node_modules/selenium-side-ru
nner/node_modules/selenium-webdriver/lib/webdriver.js:1672:25)
      at Object.setSize [as TestCase] (commons.js:4:34)
```

## Environment

OS: Windows 7
Selenium IDE Version:  3.4.4
Selenium SIDE Runner Version:  3.4.2
Node version: v10.13.0
Browser: Internet Explorer 11

[Test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2614183/Test.zip)

**Comment by corevo** [comment]
In the newer versions of the bindings the method was renamed to [setRect](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Window.html#setRect), the new version of the runner will support that.  
I will make sure to test it against ie.

**Comment by InkUisitor** [comment]
@corevo and @barancev Hello !
My environment is : IE11, Win 10, Selenium Hub 3.14 + Web Driver 3.14 for IE
We have developped some code to help us compare our website with different browsers and different resolution and IE is the only one that didn't allow us to modify the resolution. Is this feature solved today, what can we do to make 
Here is a screenshot of what I get today (the resolution is shown on top of the table) :
![image](https://user-images.githubusercontent.com/15886298/54840978-829fde80-4cce-11e9-8668-d31f55ed36ce.png)

**Comment by tourdedave** [comment]
This fix was deployed.
