### ISSUE TITLE
Set focus to a newly inserted command

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#501]
## 🚀 Feature Proposal

When a user inserts a new command to an exitsting scenario they most probably are going to edit this command immediately. So it would be wise to make the newly inserted command active and set focus to its first field ("Command")

**Comment by tourdedave** [comment]
Duplicate of #365

**Comment by barancev** [comment]
OMG, I forgot my own issue... Sorry :(

**Comment by tourdedave** [comment]
No worries :-)

--
Cheers,
Dave H
