### ISSUE TITLE
Add confirmation after selecting "Clear all" menu item

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#502]
## 🚀 Feature Proposal

"Clear all" operation removes all the commands from the current scenario without ability to restore the removed command. It's extremely unsafe operation.

1) This command should be moved to a less easily reached place (e.g. a tree-dots menu in the top-right corner), in the center of the context menu it's too easy to click it unintentionally.

2) There should be a confirmation dialogue that explain subsequences of using this command and allows to cancel it.

**Comment by tourdedave** [comment]
This is fixed in f4ef79c746d0aaa504d5f894d6eea6bad8981004

**Comment by barancev** [comment]
OK, thank you! And what about item 1? Do you want me to raise a new issue on this?

**Comment by tourdedave** [comment]
The top-right corner has nothing to do with the test table. It's for generic IDE level stuff. Do you have a better idea of where to place it? We think that with the modal to inform the user (and protect them from an accidental click) is sufficient, but we're open to suggestions.

**Comment by barancev** [comment]
The toolbar may be? Or a context menu on a test case in the left pane?

Context menu on a command contains operations related to the specific command (set breakpoint, execute this command, etc), and "Clear all" seems to be an alien there.
