### ISSUE TITLE
Save scroll position separately for each test 

### ISSUE THREAD

**Issue by Yrds** [SeleniumHQ/selenium-ide#510]
## 🚀 Feature Proposal

Save scroll position separately for each test 

## Motivation

This behavior could by handy, in cases editing two or more tests at same time. Sometimes it's annoying switch between tests and have to back to previously scroll position

## Example

On Test 1:
Scroll to top

On Test 2:
Scroll to bottom

Expected Result:

When back to Test 1, scroll position(top) should be on position i was before

## Screenshots

![captura de tela de 2018-12-03 11-55-53](https://user-images.githubusercontent.com/8484114/49377963-a248d200-f6f2-11e8-9a7d-d78c2ac7cf07.png)

**Comment by Yrds** [comment]
Sorry to not specify. I added a screenshot highlighting the scrollbar

**Comment by Yrds** [comment]
For sure, this would a leap of productivity

**Comment by dvd900** [comment]
@corevo or anyone, have you started this? taking it now if not.

**Comment by corevo** [comment]
@dvd900 great!
