### ISSUE TITLE
need help with little project

### ISSUE THREAD

**Issue by saroar** [SeleniumHQ/selenium-ide#512]
i am able to pay you to need some guideline and help about my project fillup form via CL `selenium-side-runner` so can you please add me ur skype so we can discuss and i cant show you saroarkhandoker1 < this is my skype id thanks

**Comment by tourdedave** [comment]
Hey @saroar, issues are for tracking bugs and feature requests in the project. You're better off hopping on the Selenium chat channel and asking for assistance there.

http://elementalselenium.com/tips/20-irc-chat
