### ISSUE TITLE
The console window has weird. I think the viewport is not working properly.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#519]
## 🐛 Bug Report

![ezgif com-optimize](https://user-images.githubusercontent.com/33743343/49784707-8af88d00-fd61-11e8-80e3-34a62283f176.gif)

## To Reproduce

1. Run any test case to leave some logs.
2. Change the window size by using the bottom of the window like the gif
3. Then you can notice that something is weird.

## Expected behavior

The size of viewport will change with the bottom.

## Project file reproducing this issue (highly encouraged)

basic test case
[seed project.zip](https://github.com/SeleniumHQ/selenium-ide/files/2666437/seed.project.zip)

## Environment

OS: Windows 10 64bit
Selenium IDE Version:  3.5.0-beta.0
Selenium SIDE Runner Version:  
Node version: 
Browser: Chrome
Browser Version:  Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by Jongkeun** [comment]
Ah Okay, I see.
`isProduction` version is working properly.

**Comment by corevo** [comment]
Since we keep that in local storage, and local storage is disabled in development, we disable that specific behavior.
