### ISSUE TITLE
TypeError: "alert" is read-only Firefox

### ISSUE THREAD

**Issue by corevo** [SeleniumHQ/selenium-ide#52]
Firefox does not let monkey patching the `alert`, which causes incompatibility with alert using test cases

**Comment by corevo** [comment]
Yes it is, the extension is preparing every page to be tested regardless of wether the window is open or not, its a behavior I'm planning on changing.  
That error happens specifically due to firefox not letting me rebind `window.alert` so that I can record the calls to it

**Comment by acs047** [comment]
I think I have the same problem. Is there any solution?

**Comment by justnewbee** [comment]
i would like to report this too, it gets very annoying, please fix this
btw, selenium-ide is cool, thank you

**Comment by toddtarsi** [comment]
Noting here, the fix for this is to finish the re-write of Selenium IDE v4 in Electron / Node.

**Comment by toddtarsi** [comment]
Closing, v4 is in alpha now
