### ISSUE TITLE
Selenium have support to translation or any kind of localization?

### ISSUE THREAD

**Issue by Yrds** [SeleniumHQ/selenium-ide#522]
## 💬 Questions and Help

I would like to know if selenium has support for translation/localization, because i have interest on contribute making translation to Portuguese.

**Comment by corevo** [comment]
Hey, we've had several requests from other languages for i18n, we think it's a great idea.  
We'll start working on support for i18n next month or so, but we will need your help with translations.

**Comment by p2635** [comment]
Any updates on this one? I would like to help as well
