### ISSUE TITLE
I don't know why seed project has fails when running on selenium-side-runner.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#532]
## 🐛 Bug Report

`click at` and  `frames` have errors on `selenium-side-runner`.
If I run the script on `selenium-ide`, that's fine.
And If I run the `test` alone in `Suite` on `selenium-side-runner`, that's fine as well.
But If I run the `test` with others on `selenium-side-runner`, it has errors like this.

![image](https://user-images.githubusercontent.com/33743343/50954843-e2258500-14fa-11e9-8a67-10598d1d5c38.png)

Could you tell me why? I don't know the reason at all.

## To Reproduce

1. Run this [test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2744271/test.zip) project on `selenium-side-runner`.

## Expected behavior

Come out without errors

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.
[test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2744271/test.zip)

## Environment

OS: Windows 10 64bit
Selenium IDE Version:   3.5.0-beta.0
Selenium SIDE Runner Version:   3.5.0-beta.0
Node version:  8.11.2
Browser: Chrome
Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
Are you still experiencing this problem?

**Comment by Jongkeun** [comment]
Well... I have no idea. I've not used after this project changed to Electron.
If I can check this out later again, I will reopen this issue.
