### ISSUE TITLE
Log output displaying slightly incorrectly after 100 commands

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#533]
## 🐛 Bug Report

The log output doesn't show quite right after 100 commands and beyond on the Chrome addon. See below for details.

## To Reproduce

1. Create a side file with over 100 commands
2. Run the test
3. Check the log output and any over 100 shows as something like "142click on linkText=Submit new issue...". You can see the beginning is not quite right.

## Expected behavior

Log entry should retain the format as "(number). (message)..." as "142. click on linkText=Submit new issue..." (apart from echo).

## Project file reproducing this issue (highly encouraged)

Don't think it's necessary to reproduce but let me know if you need more info.

## Environment

OS: Windows 10
Selenium IDE Version:  3.4.5 (although in the What's New section it still says 3.4.4) for Chrome

**Comment by tourdedave** [comment]
Repro case: [log-padding.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/3293943/log-padding.side.zip)

<img width="283" alt="Screen Shot 2019-06-16 at 11 35 07" src="https://user-images.githubusercontent.com/457137/59561586-ed8d5700-902a-11e9-912f-2189190b08a9.png">
