### ISSUE TITLE
Log output > Include test duration reporting

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#534]
## 🚀 Feature Proposal

For every test that runs, it would be extremely useful to include the duration it took for each test to run. Perhaps each test could begin by logging the start time, then when the test ends, it will log the end time and also the duration in minutes. Maybe this could apply for suites as well.

## Motivation

Provides a key measurement of how effective automated testing can be against manual testing. This also provides a metric for managing time for test automation.

## Example

As a simple suggestion, we can start with 2 additions:

1. Adding the start time, so it says 'Running (test name) at (start time)' for the beginning of a test.
2. Adding the end time and duration, so it says ''(test name)' completed successfully at (end time), (duration) minutes elapsed'.

**Comment by twnew** [comment]
In the [Kantu IDE](https://a9t9.com/kantu/) this is solved with the [runtime internal variable](https://a9t9.com/kantu/docs#!runtime).

**Comment by p2635** [comment]
@twnew , thanks I didn't even know about Kantu IDE, I will explore that

**Comment by p2635** [comment]
I just looked at Kantu IDE, it seems more advanced and even contains data driven testing from csv... is there a particular reason why Selenium IDE hasn't incorporated these changes? Is it because of team size?

**Comment by corevo** [comment]
It comes down to prioritization and manpower, if you want to contribute we'll greatly appreciate that.
Eventually we'll get to all the features that users are asking for.

Cheers,
Tomer
