### ISSUE TITLE
IDE interacts with invisible elements, when it should fail like WebDriver

### ISSUE THREAD

**Issue by wangchj** [SeleniumHQ/selenium-ide#535]
## 🐛 Bug Report

We have tests that were created in Selenium IDE and run successfully in IDE, but fails when we run the same tests using `selenium-side-runner`. This is the behavior with or without `headless` option.

The error we're getting from command line is:

```
WebDriverError: unknown error: Element <input type="radio" class="awsui-radio-native-input" override-focus="" id="awsui-radio-button-1" value="fileGroup" name="awsui-radio-group-0"> is not clickable at point (127, 209). Other element would receive the click: <circle class="awsui-radio-button-styled-circle" stroke-width="30" cx="50" cy="50" r="35"></circle>
      (Session info: headless chrome=71.0.3578.98)
      (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.12.6 x86_64)

       8 |   await driver.wait(until.elementLocated(By.css(`input[type=\"radio\"][value=\"fileGroup\"]`)), configuration.timeout);
       9 |   await driver.findElement(By.css(`input[type=\"radio\"][value=\"fileGroup\"]`)).then(element => {
    > 10 |     element.click();
         |             ^
      11 |   });
      12 | }
      13 | module.exports = tests;
```

## To Reproduce

1. Log into AWS Console http://console.aws.amazon.com/console
2. Run `selenium-side-runner test.side --base-url https://console.aws.amazon.com`

## Expected behavior

Test result should be the same between IDE and selenium-side-runnder

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

`test.side`

```
{
  "id": "7fb4b753-4629-4a0d-aee9-c1522ae4ceaa",
  "version": "1.1",
  "name": "Untitled Project",
  "url": "http://localhost:12089",
  "tests": [{
    "id": "8e3427b4-2863-48b7-97c2-627d46177bd4",
    "name": "test",
    "commands": [{
      "id": "d3dd7c20-f7e5-43c3-9f01-a1492e622c7c",
      "comment": "",
      "command": "open",
      "target": "/mediaconvert/home#/jobs/create",
      "targets": [],
      "value": ""
    }, {
      "id": "6e55f7a6-52fb-4527-9bea-ca432fb24106",
      "comment": "",
      "command": "click",
      "target": "xpath=//awsui-button[@id='addOutputGroupBtn']/button",
      "targets": [],
      "value": ""
    }, {
      "id": "4c57cd2e-e55e-47d0-a983-997b80a9a519",
      "comment": "",
      "command": "click",
      "target": "css=input[type=\"radio\"][value=\"fileGroup\"]",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "bd6e7561-324d-4b06-b6f2-3023c60699c4",
    "name": "default",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["8e3427b4-2863-48b7-97c2-627d46177bd4"]
  }],
  "urls": ["http://localhost:12089/"],
  "plugins": []
}
```

## Environment

OS: OSX
Selenium IDE Version:  3.4.5
Selenium SIDE Runner Version:  3.4.2
Node version: 10.1.0
Browser: Chrome
Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by corevo** [comment]
I can't login, could you please save the html with the styling, we'll try to repro using that.

**Comment by corevo** [comment]
I was able to fix my credit card info, the bug is actually not in the runner! it is in the IDE, twofold at that!  
In your example you have an element that looks like a radio button which masks the real radio button underneath. This causes the IDE to run into 2 bugs:  
 - The IDE records the wrong element, it records the element underneath, rather than the element that looks like the radio button.
 - The IDE clicks the element although it is hidden, the IDE should fail just like the runner.

What we need to fix is what we record, which will fix what the runner will click and in turn fix how the IDE decides if elements are visible.

**Comment by corevo** [comment]
This is the locator Selenium IDE recorded for me:  
`css=#awsui-radio-button-3-label .awsui-radio-button-styled-circle`  
Can you share with me how you got this selector `css=input[type=\"radio\"][value=\"fileGroup\"]` to get recorded as it is wrong.

**Comment by wangchj** [comment]
Hi @corevo thanks for looking into the issue. I usually write selector by hand to make them shorter and more readable in tests.

**Comment by corevo** [comment]
No problem, in CI we check for element visibility, so if there's an element covering it, in this case the styled radio button, you want to click that one.  
In future version of the IDE it will also check for elements visibility.

**Comment by wangchj** [comment]
I guess to fix the test, I just have change the selector to something that's actually visible. Thank you for the advice.

**Comment by corevo** [comment]
I'm going to keep the issue open until we fix the bug in the IDE.

**Comment by bethy0100** [comment]
I have a similar problem, 
maybe, do you know what the solution is?

 ElementClickInterceptedError: element click intercepted: Element <a href="#" id="solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink" name="solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink" onclick="A4J.AJAX.Submit('_viewRoot','solicitudesForm',event,{'similarityGroupingId':'solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink','parameters':{'ajaxSingle':'solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink','solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink':'solicitudesForm:solicitudesDataTable:4:agergarDetalleCommandLink'} ,'actionUrl':'/gestionTI/pages/pasos/nuevaSolicitud.jsf'} );return false;" tabindex="0">...</a> is not clickable at point (1070, 612). Other element would receive the click: <div class="dr-mpnl-mask-div dr-mpnl-mask-div-opaque rich-mpnl-mask-div" id="waitPanelDiv" style="z-index: 1;">...</div>
      (Session info: chrome=77.0.3865.120)

      162 |   });
      163 |   await driver.wait(until.elementLocated(By.xpath(`//td[@id=\'solicitudesForm:solicitudesDataTable:4:detallesColumn\']/a`)), configuration.timeout);
    > 164 |   await driver.findElement(By.xpath(`//td[@id=\'solicitudesForm:solicitudesDataTable:4:detallesColumn\']/a`)).then(element => {
          |   ^
      165 |     return element.click();
      166 |   });
      167 |   await driver.wait(until.elementLocated(By.id(`detalleSolicitudForm:tipoObjetoCombo`)), configuration.timeout);

      at Object.throwDecodedError (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)
      at mixin.execute (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
      at Object.<anonymous>.tests.PRUEBAS_GTI_DES_01 (commons.js:164:3)
      at Object.<anonymous> (DefaultSuite.test.js:11:5)

Thanks.

**Comment by florian-asche** [comment]
It whould be cool, to just disable the visibility check.

**Comment by toddtarsi** [comment]
This is resolved in v4 since we're using a real webdriver.
