### ISSUE TITLE
Send Keys not triggering JS events

### ISSUE THREAD

**Issue by halbri** [SeleniumHQ/selenium-ide#540]
## 🐛 Bug Report

I am using Selenium IDE 3.4.5 - with firefox or chrome.
On firefox i am unable to get the automated test to trigger any JS events when filling input fields, text areas etc. There fore no data is saved.
I tried many options:
click
type
send keys

but nothing helped.

Doing the same on chrome did fire the JS event in the textarea but then again the input fields are still not working at all  (with the same click, type, send keys). 
My co worker has tried the same but it doesn't work by him either.

Any ideas or examples would be really appreciated.
I am unable to post the test id did - Sorry.

**Comment by corevo** [comment]
Please file the issue again following the issue template [here](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md)

**Comment by halbri** [comment]
I’ve just found someone posted my issue a couple of days ago, Issue #536

But so far no solution there

 

Thanks for your help so far….
