### ISSUE TITLE
Execute script doesn't escape the script

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#543]
## 🐛 Bug Report

I'm trying to assign an string array from stored IDE variables, I'm not sure if this is a bug but I am unable to do it.

## To Reproduce

See image (ignore my mistake in step 7, just look at steps 3-6)

![default](https://user-images.githubusercontent.com/4522927/51536060-3c4f1000-1e42-11e9-965e-701b143785a0.png)

## Expected behavior

No error.

## Project file reproducing this issue (highly encouraged)

[test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2782776/test.zip)

## Environment

OS: Windows 10
Selenium IDE Version: 3.4.5
Browser: Chrome
Browser Version: 71.0 (64 bit)

**Comment by corevo** [comment]
The correct syntax is  
`execute script | return [1,2,3] | testArray`

**Comment by corevo** [comment]
Also please note that storing locators using `store` will not store Web Elements, we are going to add `store element` which will do exactly that.

**Comment by p2635** [comment]
Hi @corevo, thanks for your help but changing the syntax doesn't seem to solve it. I understand your point about the store element, but I can't wait until that is released, I am trying to figure out how to store the locators as simple strings that can be accessed via the array.

**Comment by corevo** [comment]
`execute script` doesn't escape the input `"` causes the JSON serialization to fail.

**Comment by myfrndjk** [comment]
Hi,

any alternative solution  to this problem

Thanks

**Comment by MikeVelazcoMtz** [comment]
@myfrndjk  and anyone trying to add any kind of character that doesn't allows:

Look for the unicode character and convert it into a variable that you can use.

`
const LINE_BREAK = String.fromCharCode(parseInt("0x0A",16));
`

**Comment by anovasia** [comment]
> Hi @corevo, thanks for your help but changing the syntax doesn't seem to solve it. I understand your point about the store element, but I can't wait until that is released, I am trying to figure out how to store the locators as simple strings that can be accessed via the array.

is there a solution for this yet?

**Comment by KaushalKhamar** [comment]
Hello,

Any solution found to use variable in script? If so, please let me know or any workaround?

**Comment by zoyeb-xoyal** [comment]
Hi @corevo,

You merged issue #548 in this ticket. But I am not getting any solution to overcome Line brake <BR> tag issue. 

I am getting below error while trying to access my variable to execute the script.
**Unexpected token in JSON at position 28**

Please help me with this.
