### ISSUE TITLE
Add a 'Help' link to the top right menu

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#545]
## 🚀 Feature Proposal

In the top right menu, I believe it would be of great help to new users if there was a 'Help' button which links to the Selenium IDE Documentation: https://www.seleniumhq.org/docs/02_selenium_ide.jsp#
![default](https://user-images.githubusercontent.com/4522927/51538439-33157180-1e49-11e9-9169-5f8a47926fe5.png)

## Motivation

As above.

## Example

As above.

**Comment by corevo** [comment]
We have a new documentation [here](https://www.seleniumhq.org/selenium-ide/), and this is a great place to link to it.  
Great suggestion.
