### ISSUE TITLE
Add a 'GitHub Project' link to the top right menu 

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#546]
## 🚀 Feature Proposal

Further on #545, in the top right menu, I believe it would be of great help to the Selenium IDE team if there was a button which links to the GitHub repo: https://github.com/SeleniumHQ/selenium-ide. I'm not sure what the button text would be though, perhaps 'report a bug' or 'contact us', something like that.

## Motivation

- Help new users report features/bugs more easily
- (possibly?) Help more devs to submit PRs to the project

## Example
As above.

**Comment by corevo** [comment]
I think that information belongs in the website, specifically we have a [help](https://www.seleniumhq.org/selenium-ide/help/) section in the website where I think that information belongs to.

**Comment by p2635** [comment]
I'll leave that up to you, just thought it would be easier to access for some people.

**Comment by corevo** [comment]
I think they can easily enough get to us through the website, I'd like to keep the menu thin.
