### ISSUE TITLE
[Minor bug] Firefox addon shows extension ID

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#551]
## 🐛 Bug Report

When using Selenium IDE in Firefox, it shows an ID which in the window name as below:
![default](https://user-images.githubusercontent.com/4522927/51606229-42f48a80-1f09-11e9-8790-ce12790a2a75.png)

## To Reproduce

Launch Selenium IDE in Firefox.

## Expected behavior

We can make it consistent with Chrome and just removed that part, so it shows like this: 
![default](https://user-images.githubusercontent.com/4522927/51606276-5c95d200-1f09-11e9-9f00-97e72882416b.png)

## Project file reproducing this issue (highly encouraged)
N/A

## Environment

OS: Windows 10
Selenium IDE Version: 3.5
Browser: Firefox
Browser Version: 64.0.2

**Comment by corevo** [comment]
Please open this issue with Mozilla, as it is forced by them.
