### ISSUE TITLE
Log output > Include timestamp against each command

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#552]
## 🚀 Feature Proposal

When running tests, it would be useful if there was an option to include the timestamp (and date?) in the log output. For example [01/01/2019 13:49] 1. click on bob OK.

## Motivation

- Useful for debugging
- Useful for checking how long it took for particular parts of the test

## Example

Perhaps we can add a settings section and in there, the user can select whether or not they want the date/time to be included.

**Comment by corevo** [comment]
Is there a standard we can follow, there is a probable need for localization.
