### ISSUE TITLE
[Firefox] Strange behaviour when renaming a project

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#554]
## 🐛 Bug Report

In the case detailed below, when renaming a project, entering a space causes the keyboard focus?(can't remember what you call it) to jump to the start of the line. 

## To Reproduce

Create a new project
1. Start a new project
2. Input random data just to skip the dialog boxes
3. Stop recording
4. Click into the project name field to edit it
5. Clear the existing name by deleting all the text
6. Type 'test' and hit space
7. You will see that the cursor jumps to the beginning of the line
![default](https://user-images.githubusercontent.com/4522927/51609309-b3070e80-1f11-11e9-9f2f-033abb503f9f.png)

Open an existing project
Open a project and follow steps 4-7 above.

## Expected behavior

It should output a normal space character.

## Project file reproducing this issue (highly encouraged)

N/A

## Environment

OS: Windows 10
Selenium IDE Version:  3.5
Browser: Firefox
Browser Version: 64.0.2 (64 bit)

**Comment by wycabuoncha** [comment]
I have also encountered same behaviors in v3.8.0  firefox 67.0
