### ISSUE TITLE
executescript > the 'return' command isn't saving to variable when value is 0

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#556]
## 🐛 Bug Report

Possible regression, the return command doesn't seem to be saving to a variable properly. This caused one of my tests to loop forever.

## To Reproduce

Steps to reproduce the behavior, create a test with these steps:

1. execute script | return 0 | i
2. echo | ${i}

![bildo](https://user-images.githubusercontent.com/4522927/51621088-a8f20980-1f2b-11e9-9959-f2ab564d1a5b.png)

The output is echo: ${i}

## Expected behavior

The output should be 0.

## Project file reproducing this issue (highly encouraged)

[Test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2788183/Test.zip)

## Environment

OS: Windows 10
Selenium IDE Version: 3.5
Browser: Firefox 64.0.2 (64bit) and Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by test1234ab** [comment]
Did you tryed to use : return Number(0) ?

**Comment by corevo** [comment]
The problem is specific to false values `0`, `undefined`, `null` and so forth.

**Comment by p2635** [comment]
Is there any workaround for this for the time being?
