### ISSUE TITLE
Wait for Element Present not working after update

### ISSUE THREAD

**Issue by e0holl01** [SeleniumHQ/selenium-ide#557]
## 🐛 Bug Report
In my test, I have a wait for element present that worked up until the update went out. Now my tests fail. 
Can this try to be duplicated. Apologies but the link cannot be provided.
The wait for element present just errors automatically.
Error given Cannot read property 'result' of undefined

## Environment

Selenium IDE Version:  
Chrome Browser

![selenium issue](https://user-images.githubusercontent.com/39104984/51639533-23705880-1f2f-11e9-83d7-d4aedc72aabe.JPG)

**Comment by p2635** [comment]
Is there a project file you can supply to us? Is it on a public website? Please provide all the information given in the bug template.

**Comment by e0holl01** [comment]
Who has access to view these issues? That will depend if I can share the company site.

On Jan 24, 2019, at 6:41 AM, Phil <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a project file you can supply to us? Is it on a public website? Please provide all the information given in the bug template.

**Comment by e0holl01** [comment]
It is not a public site.

On Jan 24, 2019, at 6:41 AM, Phil <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a project file you can supply to us? Is it on a public website? Please provide all the information given in the bug template.

**Comment by corevo** [comment]
Can you build us a reproducer? Is the element written in-house, or is it a component library?  
If you write a new test without other commands, the shortest test that can have this single command, is the bug reproducing?

**Comment by e0holl01** [comment]
Let me try creating a reproducer.

On Jan 24, 2019, at 8:45 AM, Tomer Steinfeld <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you build us a reproducer? Is the element written in-house, or is it a component library?
If you write a new test without other commands, the shortest test that can have this single command, is the bug reproducing?

**Comment by malvarezcastillo** [comment]
Can reproduce this on a private website as well, cannot reproduce on other websites.

But my educated guess is that it would seem that the IDE is not really waiting for the page to load, instead it jumps to the "wait for element present" and as soon as the next page loads it overwrites whatever the IDE was observing and it crashes with "Cannot read property 'result' of undefined".

If you _really_ need a way to reproduce it I could work something out.

**Comment by malvarezcastillo** [comment]
Indeed, if I introduce a long pause between the click and the wait, or explicity re-open the URL via "open" the "wait for element editable/present" doesn't crash. It really seems like it is referencing the "old" page and as soon as it refreshes it crashes.

If we had a "wait for page load" command or something like that it could work (?)

**Comment by e0holl01** [comment]
It’d be great for it to be reproduced and resolved if that’s the case. I can’t share my company page, but your assumption relates to the issue I think.

Sent from my iPad

On Feb 13, 2019, at 6:47 AM, Martín Álvarez Castillo <notifications@github.com<mailto:notifications@github.com>> wrote:


Can reproduce this on a private website as well, cannot reproduce on other websites.

But my educated guess is that it would seem that the IDE is not really waiting for the page to load, instead it jumps to the "wait for element present" and as soon as the next page loads it overwrites whatever the IDE was observing and it crashes with "Cannot read property 'result' of undefined".

If you really need a way to reproduce it I could work something out.

**Comment by malvarezcastillo** [comment]
Okay, so I got it to fail consistently 100% of the time on a very simple test. @e0holl01 Can you please test and confirm it fails for you too so the devs can take a look?

I'm on Chrome Version 72.0.3626.96 (Official Build) (64-bit)

Here's the project file 
[gadisline_fail.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2860407/gadisline_fail.side.zip)

Just run the "BUG" test case and wait, It should select a postal code for delivery and wait for the "shopping cart icon" on the next page, it waits but when the page loads it crashes the test instead of asserting true.

![image](https://user-images.githubusercontent.com/6960749/52713219-09a6bc00-2f97-11e9-8ec9-45cbbfcbf31a.png)

**Comment by corevo** [comment]
Thank you for the repro case @malvarezcastillo

**Comment by e0holl01** [comment]
Yes. I received the same failure.


[cid:fc6c4c0c-49df-4f34-9d3c-c86b6a5af96f]
________________________________
