### ISSUE TITLE
nested End loop are not well perform 

### ISSUE THREAD

**Issue by test1234ab** [SeleniumHQ/selenium-ide#559]
## 🐛 Bug Report

Nested End loop are not well perform. When selenium find "end", my test goes to the end of the top loop.

## To Reproduce

1) Create a while loop.
2) Add a If condition inside the loop.
3) after the if add a task

## Expected behavior

 at the  IF "end", the test goes to the start of the while loop.
My task after my IF is not verified. 

## Project file reproducing this issue (highly encouraged)

store | 0 | nb_a
store | 2 | nb_b
store | url | url2
store | url | url

open | ${url}
while | ${nb_a}>${nb_b}
     if | ${nb_a} == 0
           open | ${url}
     end 
execute script |  return Number(${nb_b})+Number(1) | nb_b
open | ${url2}
end

## Environment

OS: WINDOWS 7
Selenium IDE Version:  What's new: 3.5.0

Browser:
Browser Version: Chrome 70.0.3538 and Firefox 64.0

**Comment by p2635** [comment]
Can you please provide the project file so I can try and reproduce it?

**Comment by giznaj** [comment]
I am seeing the same behaviour now under the new version 3.5.0.  My scripts worked previously, now nested control sequences are broken.  For instance, I have a if/else inside a while loop.  If I remove the end for the nested if, it complains about the while loop termination.  If it put it back, the loop is stuck on that nest if.  When it reaches the end block for the if, it goes back to the top of the if.

**Comment by corevo** [comment]
@test1234ab please attach this as a project file

**Comment by p2635** [comment]
@test1234ab FYI you can attach it as a zip file

**Comment by tony-gutierrez** [comment]
Same issue. 
https://www.dropbox.com/s/nnzj2rakmzom4qy/Screenshot%202019-01-25%2014.45.01.png?dl=0

Line 23 returns to line 10, and 24-26 never get ran.
Indentation is correct in the ide, but it looks like it is associating the "end" with the "times" instead of the "if"

**Comment by tony-gutierrez** [comment]
Is there a way to downgrade from 3.5.0 in order to keep working ?

**Comment by tourdedave** [comment]
@tony-gutierrez Yes, you could install an earlier release build as a developer extension in your browser. But we don't recommend it.

We should have this rolled out in a hot fix soon.

**Comment by tony-gutierrez** [comment]
This fixed some of the flow control problems, but I am now having a problem where a "times" command inside a while block only runs once. Is there something special that has to be done to make the "times" command reset?

**Comment by tony-gutierrez** [comment]
Im on 3.5.2 btw.

**Comment by tourdedave** [comment]
Please file a new issue and follow the issue template (including a repro case).

**Comment by giznaj** [comment]
Working as expected now.  Just re-confirming for the group.
