### ISSUE TITLE
Please support Page Objects, Flow Control, Keywords, Multi Search and Replace, Resouce folders, and a CSS/Xpath creator.

### ISSUE THREAD

**Issue by Eggroll9000** [SeleniumHQ/selenium-ide#56]
Please support Page Objects, Flow Control, Keywords, Multi Search and Replace, Resouce folders, and a CSS/Xpath creator.

I'm not pretending to be creative with my suggestions as they already exist in other frameworks and software. But they are scattered across different pieces of software or in compiled languages like Java or Python and are difficult/impossible to step thru 1 line at a time. Also, many don't record and playback (like RIDE) which gets you started from 0 to Hero so quickly in a rapidly changing agile environment.

I've tried most of the popular frameworks and feel the IDE is still the best. I love the IDE much more than any compiled language framework largely because of the ability to test my tests (Who knew a tester would want to test their tests?... :P). The ability to step thru the script 1 line at a time and execute a single line without going thru the entire sequence is a Godsend. It's nearly impossible to test for false passes in compiled language frameworks like TestNG/Java or RobotFramework/Python as I can not create an intentional fail condition because the script needs to run from beginning to end/breakpoint. Because I am unable to test for false passes efficiently, I have very little confidence in the results even when the lights turn green.

The IDE lacks the ability to support Page Objects. It would be great to be able to organize drag and drop Page Objects. Much like Katalon Studio. During record and playback, objects are recorded in a page object. This would make organizing page objects much more convenient and would bring the IDE in line with the more common layered design. We can have toggle switch that records using page objects or inline in case a user would benefit more from the original inline approach.

I've able to create the equivalents of classes and instances using Flow Control and that has been a life saver. I've been able to create scripts to detect login conditions, wait for emails to arrive before continuing, and create image diffs. The ability to use Flow Control has been absolutely vital to my tests. Please make sure Flow Control is in the feature set.

A super long wall of script in IDE makes it very difficult to discern the test intent. Therefore, I comment before each sequence with a test intent statement. RobotFramework does a decent job of making the test intent understandable by allowing a coder to create a keyword in a human readable sentence so a tester or a business user can understand the intent of the test. For this, we should either support keywords (so that it can be reusable across tests), or support collapsing script sequences under comments to clean up the view like a caret that collapses a sequence under a comment.

Sometimes, we don't do a good job of creating best Page Objects but we still need to maintain our tests. So being able to Multi Search and Replace xpaths and css identifiers would be amazing. I currently use an IDE (TextWrangler) to multi search and replace instances of the same css or xpath when that changes. It's a good tool to have and something we all use when the identifier of a field or button changes.

It is common to need to upload something like an image, video, or some other file. Having a resource folder on hand with a universal file path to store test assets should be a norm such that it works with Git. Having assets stored on my MacBook's desktop currently does not work with any user when they Git Pull since the path includes my name. Having a generic resource folder in the IDE would solve this.

Currently, I rely on FireBug and FirePath to find css selectors and xpaths. It would make sense if such a feature exists on the Selenium IDE itself such that creating xpaths and css selectors does not require a 3rd party app.

Thanks for reading all the way down to here. We love you guys for all your hard work and rely on it every day. Our devs seem to cause regressions for fun and if it wasn't for IDE, we would be hopeless to find any of them at a reasonable time frame. IDE is by far the best. Even when people boast about their frameworks, and we've built them, we simply don't trust their results as much as the IDE. The IDE's line by line execution simply outclasses any compiled language test framework as we can prove each line of code.

Thank you and we look forward to using the new Selenium IDE.

**Comment by corevo** [comment]
First off, could you split the issue per feature, so that it would be easier for us to track each one individually.  
Other than that, while we currently don't support those features, I can recommend a few productivity tips.  
On Chrome which we support in the new IDE, you can select xpath or CSS selector like so:
![image](https://user-images.githubusercontent.com/888886/33314349-0786bf14-d436-11e7-813d-ea2de02fe4ca.png)

And with file upload you can always try and use relative paths, it might work, or you could try setting an environment variable with the path to the files, each one will set the variable differently, depending on where they clone to.  

I'd love to respond to each feature individually, but I fear it will create chaos, I'm closing the issue, please refile it per feature, so it would be easier to track.

**Comment by Heizer1971** [comment]
Ja bitte bleib dran Eggroll9000.
Das waren für mich ebenfalls sehr interessante Vorschläge.
Ich nutze in der alten IDE flow control (ohne geht es einfach nicht).
Ich habe hunderte sehr komplexe Tests und viel Erfahrung mit der IDE.
Sel IDE TNG reicht an die Möglichkeiten der alten noch lange nicht heran zB. fehlt die user-extension schmerzlich und start punkte und Ausführung per doppelklick....
