### ISSUE TITLE
selenium-side-runner complaining about missing webdriver when module is actually installed

### ISSUE THREAD

**Issue by Xnyle** [SeleniumHQ/selenium-ide#563]
## 🐛 Bug Report

The following error is reported:
```
Cannot find module 'selenium-webdriver' from 'Default Suite.test.js'

      1 | // This file was generated using Selenium IDE
      2 | const tests = require("./commons.js");
    > 3 | global.Key = require('selenium-webdriver').Key;
```

## To Reproduce

First of all  I had to install the following dependencies manually to even get to this point (which the documentation doesn't mention at all?)

npm install -g jest-environment-node@latest selenium-side-runner@latest jest-cli@latest jest-environment-selenium@latest selenium-webdriver@latest

Results in the following modules being installed:

+ jest-environment-node@24.0.0
+ selenium-side-runner@3.5.1
+ jest-cli@24.0.0
+ jest-environment-selenium@2.1.0
+ selenium-webdriver@4.0.0-alpha.1

Then I run 

```
selenium-side-runner --server http://localhost:4444/wd/hub -c 'browserName=chrome' selenium/my.side
```

which results in the error above.

## Expected behavior

Side runner converts tests and connects to running hub for tests to be executed.

## Project file reproducing this issue (highly encouraged)

https://gist.github.com/Xnyle/8ff51176719c4b800e6b8c1821cba394

## Environment

OS: Alpine Linux x86_64
Selenium IDE Version:  3.5.2 on Chromium
Selenium SIDE Runner Version:  3.5.1
Please note that selenium-side-runner supports Node.js 8 - 10
Node version: 10
Browser: Chromium 72

**Comment by corevo** [comment]
There should be no need to install all these dependencies manually, the fact that you had to means that there is an issue with the dependency resolution, as they are bundled with `selenium-side-runner`.  
Can you run `NODE_ENV=development selenium-side-runner -e your-side-file.side`, this will create a directory named `side-suite-your-side-file` and attach the `package.json` that is inside?

**Comment by corevo** [comment]
Make sure you pass the `-e` flag

**Comment by corevo** [comment]
I've just published `selenium-side-runner@3.5.3` try using that after removing all of the other global things you may have installed.

**Comment by Xnyle** [comment]
Using this newest version:
```
+ NODE_ENV=development selenium-side-runner --server http://localhost:4444/wd/hub -c 'browserName=chrome' -e selenium/VV.side
[33mwarn[39m:    This feature is used by Selenium IDE maintainers for debugging purposes, we hope you know what you're doing!
[32minfo[39m:    Running selenium/VV.side
```
No additional output. Although it seems to work now:

```
+ selenium-side-runner --debug --server http://localhost:4444/wd/hub -c 'browserName=chrome' selenium/VV.side
[34mdebug[39m:   Could not load /home/jenkins/workspace/pa-records/.side.yml
[34mdebug[39m:   { capabilities: { browserName: 'chrome' },
  params: {},
  runId: 'ef04ac1d2eb6d5e03e670bde0f2347a8',
  path: '/usr/local/lib/node_modules/',
  server: 'http://localhost:4444/wd/hub',
  timeout: 15000,
  baseUrl: undefined }
[32minfo[39m:    Running selenium/VV.side
[34mdebug[39m:   jest worker args
[34mdebug[39m:    0=--no-watchman, 1=--testMatch, 2={**/***/*.test.js,**/***.test.js}
[34mdebug[39m:   jest work opts
[34mdebug[39m:    cwd=/home/jenkins/workspace/pa-records/side-suite-VV, stdio=inherit
PASS ./Default Suite.test.js (11.408s)
  Default Suite
    ✓ Login (7649ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        11.731s
Ran all test suites.
```

**Comment by corevo** [comment]
I'm glad it worked out, can I close the issue?

**Comment by Xnyle** [comment]
Yeah, thanks for your help.

OT: Is there already something (or something planned) to get the reports from --output-directory back to jenkins?

**Comment by corevo** [comment]
The reports are generated from jest, maybe there is a parser for that for jenkins, I would suggest looking around there.
