### ISSUE TITLE
Add an option to selenium side runner to create junit reports via jest-junit

### ISSUE THREAD

**Issue by Xnyle** [SeleniumHQ/selenium-ide#565]
## 🚀 Feature Proposal

Selenium side runner should be able to create JUnit style reports via command line option.
Nothing new has to be programmed for this, but configuration changes have to be bundled.

## Motivation

In order to use test reports in Jenkins it would be nice to have a JUnit style report.
There is already a jest plugin that does this (jest-junit).

But (at least for a npm noob) it seems there is no easy way to integrate jest-junit without patching the selenium side runner distribution. 

The plugin is targeted at JS developers.There currently seems to be no easy way to just use the plugin and convert existing json results.

It would have to be bundled with side runner and included in the distributions package.json (see below).

## Example

```
{
  ...
  "jest": {
    "coverageReporters": [
      "text"
    ],
    "reporters": [
      "default",
      "jest-junit"
    ],
    ...
  },
  "jest-junit": {
    "output": "junit.xml",
  }
}
```

**Comment by tourdedave** [comment]
This is available now. See [the docs](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#output-test-results-to-a-file) for details.
