### ISSUE TITLE
Timeout value for (implicit wait on) click&wait?

### ISSUE THREAD

**Issue by n3phtys** [SeleniumHQ/selenium-ide#567]
Our whole project is huge and slow. When testing edge cases of our app the first few calls will take quiet a lot of time. Our CI server often takes longer to process the first request than SIDE runner waits for, so the test cases fail. As dev environments are kept alive for hours at a time we don't have that issue anywhere else besides when running our integration test suite on our CI.

If I understand correctly there seems to be a 30s/15s timeout on that first request by default when using Selenium. In our case this is not long enough.

Normally I would use the 'classic' / programmatic way of using Selenium, where this timeout can be easily configured but we need to have SIDE-style point-and-click-generation of new tests for our testers in this project.

Is there a CLI option or something similar to configure this timeout and increase it to e.g. 60s when using SIDE test suites + SIDE runner?

Additional information: at the moment we are using headless chromium as the actual browser, but I don't think this kind of option would be part of the browser or webdriver, as the wait normally happens within the overlaying library.

**Comment by tourdedave** [comment]
Headless execution shouldn't matter.

All commands (not just the first) respect an implicit wait/retry of 30 seconds if the action can't be immediately completed. If you need to wait longer on an a targeted command, we have added some explicit wait commands with adjustable timeouts (configurable in milliseconds).

You can see a full list here: https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#wait-for-element-editable

There's no way to conditionalize it to work only in the runner. But it's a dynamic wait, and you only need it for the initial command, so performance should be OK. Give it a try and let us know your results.

**Comment by n3phtys** [comment]
Thank you, and if I weren't blind / lazy I would have seen --help documents exactly that.
