### ISSUE TITLE
v0.1 and v0.2

### ISSUE THREAD

**Issue by Zaanmedia** [SeleniumHQ/selenium-ide#57]
All versions seems to have files/folders that are missing is there somewhere already a working version te be found for testing?

**Comment by corevo** [comment]
These versions were tested, what files and folders are missing?  
You do need to build them from source, maybe you are missing the `node_modules`  

In any case, the next version will be published with a `crx`

**Comment by Zaanmedia** [comment]
Looking forward to it... Yes was forgetting to build it again...

**Comment by corevo** [comment]
Closing the issue
