### ISSUE TITLE
Python export already available?

### ISSUE THREAD

**Issue by triple-it** [SeleniumHQ/selenium-ide#574]
## 🚀 Feature Proposal

I understood the Python export is already available?

## Motivation

Automation currently happens mainly in the Python Language. Therefor it would be handy to have this automation also be available for the Python programmers.

## Example

Selenium IDE gets the hard work started  and automated, and with an export to Python the programmer gets to focus on the fine details...

**Comment by corevo** [comment]
We don't accept issues about code export, we are aware this is a very important feature, that will be available in the IDE, it is very high on our roadmap, and we will get to it.  
Currently we are going to work on Java > C# > Javascript > Python > Ruby, but you are more than welcome to help with the python export.
