### ISSUE TITLE
Selenium Side Runner does not find tests in .Side file

### ISSUE THREAD

**Issue by lonwheeler** [SeleniumHQ/selenium-ide#576]
## 🐛 Bug Report

After default install of Selenium IDE and Siderunner, I am unable to run a simple test which opens chrome. I am new to this tool, however I unable to find any resolution in documentation. I appreciate any help that can be afforded.

Get following error
 
selenium-side-runner test.side
info:    Running test.side
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in c:\users\user_profile\node_modules\side-suite-test.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches

## To Reproduce

selenium-side-runner test.side

## Expected behavior

Side Runner opens chrome at google page

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

{
  "id": "12d70a4d-f0e6-40dd-9cd3-293f0c255ba9",
  "version": "2.0",
  "name": "test",
  "url": "https://www.google.com",
  "tests": [{
    "id": "a2b75cbd-7ec5-43af-9e98-528cfd9d2d9a",
    "name": "test",
    "commands": [{
      "id": "6292a107-1de3-4119-a166-262aa26939da",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "f685240e-7d02-4db1-a6f0-6195a22b2f45",
    "name": "Test",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["a2b75cbd-7ec5-43af-9e98-528cfd9d2d9a"]
  }],
  "urls": ["https://www.google.com/"],
  "plugins": []
}

## Environment

OS: Windows 7
Selenium IDE Version:  3.57
Selenium SIDE Runner Version:  3.5.6
Node version: 10.15.1
Browser: Chrome
Browser Version: Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by aacom007** [comment]
I am also facing the same issue.

**Comment by lievi** [comment]
I have this problem to. Do you guys have any solution?

**Comment by lievi** [comment]
I found the problem, at least in my case, The list of tests and the name on the suite was empty. After i put the list, the side runner works.

Before:
  "suites": [{
    "id": "4243ca1b-1f84-4762-b880-9de02495b7e3",
    "name": "",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": []
  }],
  "urls": ["https://www.santander.com.br/?segmento=negocios-empresas"],
  "plugins": []


After:
  "suites": [{
    "id": "4243ca1b-1f84-4762-b880-9de02495b7e3",
    "name": "Default Suite  ",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["577f944e-198b-4519-b151-21ffe2d5a918"]
  }],
  "urls": ["https://www.santander.com.br/?segmento=negocios-empresas"],
  "plugins": []

**Comment by corevo** [comment]
Worked on my end
![image](https://user-images.githubusercontent.com/888886/57081628-cccca480-6cfd-11e9-940d-986ece5e4170.png)

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
