### ISSUE TITLE
Target dropdown in Chrome Extension

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#578]
@nzhome commented on [Wed Feb 20 2019](https://github.com/SeleniumHQ/selenium/issues/6952)

Target dropdown in Chrome Extension always goes downwards, and always gets cropped, and you can't click xpath:position

Potential solutions?
a) How to make the dropdown always go upwards instead?
b) How to make the default target always be xpath:position instead of id?   

reason: my pages always change id every time you reload the page.

**Comment by tourdedave** [comment]
@barancev Please provide the details required for in our bug report template: https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md

**Comment by barancev** [comment]
Not me :)
@nzhome please provide the requested information

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
