### ISSUE TITLE
New Selenium IDE for chrome is throwing error Unsupported locator strategy: class

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#580]
I have imported old selenium IDE test where we have used to identify the element using class name
But when it is executed in new IDE for chrome it is showing this error in log 
Unsupported locator strategy: class

Ex: assertElementPresent on class=icon icon-plus2 Failed:
Unsupported locator strategy: class

Can you some help me why this error is coming.Is new selenium IDE not supporting class identifier. This used to work fine with old selenium IDE in firefox

**Comment by corevo** [comment]
Use `css=.icon .icon-plus2`
