### ISSUE TITLE
Selenium IDE execute script current date?

### ISSUE THREAD

**Issue by TL-fwmoc** [SeleniumHQ/selenium-ide#581]
Hi there,

I'm searching through the web with no result.What do I've had to do to generate the current date with current time?
I want to check if this specific time format is on my page. My format looks like this: 20.02.2019 17:01

For me it is to hard to figure out how to do. I've tried it with the basics but it didn't works either:
`execute script | new Date() | currentdate`
`echo | ${currentdate}`

My result is 
> echo: undefined

What I've had to do?

Greetings
TL

**Comment by corevo** [comment]
Please follow the [issue format](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md) when opening an issue.
