### ISSUE TITLE
Open the second bullet window on a bullet window, and the selenium plug-in is stuck (the first bullet window is closed, these two bullet windows are used to query the returned results)

### ISSUE THREAD

**Issue by EmerJuny** [SeleniumHQ/selenium-ide#583]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
Please re-open the issue following the issue template.  
The fact that it is empty and the title is very vague about the problem makes understanding the issue very difficult for us.
