### ISSUE TITLE
How to extract substring from Main string in Selenium IDE Record and Play?

### ISSUE THREAD

**Issue by Kumar2k17** [SeleniumHQ/selenium-ide#585]
I have text "Welcome to the Automation World". Now i want to extract the word "Automation" from the main string in new Selenium IDE Record and Play using execute script, but not working. Can one help me with example..thanks in advance.

store | Welcome to the Automation World | asset
execute script | return "${asset}".substring(0,17) | vartest
echo  ${vartest}

output..
executeScript on return "${asset}".substring(0,9) with value vartest OK
echo: arguments[0]

**Comment by corevo** [comment]
`execute script | return ${asset}.substring(0,17) | vartest`  
Please note that this is not a support forum and you should ask questions over either the irc channel or slack.

**Comment by tourdedave** [comment]
Details on how to connect to them are available here: https://www.seleniumhq.org/selenium-ide/help/

**Comment by Kumar2k17** [comment]
Thank you so much for you reply. I found this. But I'm getting a error when I'm trying to extract the substring

execute script | return ${asset}.substring(0,17) | vartest

Failed: Unexpected token in JSON at position 33

**Comment by corevo** [comment]
Open a bug using the issue template, make sure you attach a reproducing test case.
