### ISSUE TITLE
Is there any way in new selenium IDE for chrome where we can reuse the same lines of steps across tests

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#586]
## 🚀 Feature Proposal

In old selenium IDE we have a concept called rollup and user extension.js upload as a developer option.
Where we can write small methods and if we upload user extension those methods will appear as commands(custom commands) to use them in selenium IDE. Rollup is a command where we give target as method and we pass different parameters for method.
Rollup help us to reuse same lines of code across multiple test cases in a suite.

## Motivation
Lot of duplicate steps will be removed. Single point of maintenance if some thing is changed.

## Example
Command : rollup
Target: login (method name in js file)
Value: username=aa, Password=bb

Is there any feature or command there in new selenium IDE ?
If not can we get this rollup and user extension .js upload feature in new selenium IDE as well?

**Comment by corevo** [comment]
Please take a look at the [run](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#run) command.  

Attached an example [test-case-reuse.zip](https://github.com/SeleniumHQ/selenium-ide/files/2899732/test-case-reuse.zip).  

Refer to #96 for information on `user-extensions.js`
