### ISSUE TITLE
How to integrate these new selenium ide tests in Teamcity continous integration

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#588]
Hi, we use to have html plugin to integrate our old selenium ide tests to CI where we use selenium RC to run them. 
So, is there any way that is finalized for new selenium ide tests (.side) files to run and integrate them to Continuous integration like team city. 
Is there any help document with steps available. 

This question is  asked in the early stages of selenium IDE development .At that time it is still in WIP.

Can some one help me on this.

**Comment by tourdedave** [comment]
Yes! We have a command-line runner for Selenium IDE. You can find its documentation here: https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/
