### ISSUE TITLE
Can we export new ide selenium tests to C#Webdriver.cs file.  which we have this feature in old selenium ide

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#591]
I could not see any option from selenium IDE to export a test case to C# web driver cs file. Is that available from ide ?

**Comment by corevo** [comment]
We do not accept issues about code export, we are aware that it is an important feature and it is on our roadmap which is available [here](https://github.com/SeleniumHQ/selenium-ide#what-now)
