### ISSUE TITLE
open command error

### ISSUE THREAD

**Issue by brentrug** [SeleniumHQ/selenium-ide#594]
## 🐛 Bug Report

Normally the open command works well! But from time to time I get an error (can provide the exact error hopefully later)

I have a big test script which runs for hours and opens about a 500x times several different pages with the open command, but just sometimes it does not  work and I can't figure out why.

At the end of the test I always measure the time needed and want to save the test case in my database:

![bildschirmfoto 2019-03-03 um 09 00 49](https://user-images.githubusercontent.com/6370972/53692586-dfc10800-3d92-11e9-80ee-169722bcbdc7.png)

## To Reproduce

I can't reproduce it myself, since it only happens from time to time.

The weird thing is, if I rerun the failed test, it normally passes...

## Expected behavior

Open command should work without error

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: Mac OS Mojave
Selenium IDE Version:  2.9.1
Selenium SIDE Runner Version:  Don't know
Browser: Firefox
Browser Version: 52

PS Please don't tell me I need to update, I know its an old version, but it works!

**Comment by corevo** [comment]
The legacy Selenium IDE is no longer supported, this repo only supports the new IDE.  
We recommend trying to upgrade to the new Selenium IDE.
