### ISSUE TITLE
Selenium Side Runner Error: SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

### ISSUE THREAD

**Issue by patriciasimonep** [SeleniumHQ/selenium-ide#597]
Reference to my previous ticket #1516. 
Is it possible to run **selenium side runner headless without the installing browser**? Just pure running it in a non graphical user environment?
im using the ide tests run thru selenium side runner like this.
**selenium-side-runner -c "browserName=firefox moz:firefoxOptions.args=[-headless]" project.side** and it gave me output of binary error. So i would want to know if i can run it without really installing any browser?

I am trying to run my ide test thru selenium side runner on linux environment for both Chrome and Firefox, **selenium-side-runner -c "browserName=firefox moz:firefoxOptions.args=[-headless]" project.side** and it gave me output of binary error. So i would want to know if i can run it without really installing any browser?

Firefox error:
SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

Chrome error:
WebDriverError: unknown error: cannot find Chrome binary
(Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 3.10.0-957.1.3.el7.x86_64 x86_64)

Linux environment doesnt have any browser installed, and would it still possible to run headless tests without it?If not, do you have any recommendation on this requirement?Your input would be greatly appreciated and helpful. Thank you

**Comment by corevo** [comment]
Please follow the issue template.  

About the issue at hand, running the browser headless-ly doesn't mean that a browser isn't installed, a browser is much more than the GUI at hand, for example the Javascript engine, the css engine, the user data, networking, caching and much much more.  

Browser is one of the most sophisticated pieces of technology, and not simply "GUI", the fact that your test does not need GUI, doesn't mean that it doesn't need Javascript, for that exact reason installing a browser is mandatory.  

That being said, you can run said browser headless-ly, which removed the GUI, but keeps all the functional parts required to run a webpage like Javascript and so forth.
