### ISSUE TITLE
[Firefox] The Components object is deprecated. It will soon be removed.

### ISSUE THREAD

**Issue by axllent** [SeleniumHQ/selenium-ide#598]
## 🐛 Bug Report

The Firefox (65.0.1) developer console produces an **error** on every page load stating `The Components object is deprecated. It will soon be removed.`

I was able to track this down to the Selenium Firefox addon. The extension still works, however it appears this `Components object` is going to be removed very soon (considering it is an error, not a warning), whch will presumably break the extension.

## To Reproduce

Install the Firefox addon from https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/ ; load any page.

## Environment

OS: Linux
Selenium IDE Version:  (Web Extension) 3.5.8
Browser: Firefox
Browser Version: 65.0.1 (64-bit)

**Comment by corevo** [comment]
It is a legacy piece of software from the old IDE, removing it won't break the extension, but we should probably delete that code.

**Comment by ioulai** [comment]
still having an error on every page loaded. 
i am using **Firefox developper edition version 67.0b17 (64 bits)**
with 
**selenium IDE 3.6.1**
**windows 10pro**

**Comment by tourdedave** [comment]
I took a look at this, and it's not straightforward unfortunately. While there are legacy calls to `Components` in the IDE code base, there are also calls to it upstream within the Selenium project (in the atoms -- which the IDE relies on) and potentially further upstream from there (e.g., libraries that the atoms require).

This error will resolve itself when we move to a native app later this year.

While it's an annoying error message in the console, when `Components` get removed, the extension will still work.
