### ISSUE TITLE
Selenium Side Runner Error:  UnexpectedAlertOpenError

### ISSUE THREAD

**Issue by patriciasimonep** [SeleniumHQ/selenium-ide#599]
[xxxxxx@xxxxx uitests]$ selenium-side-runner -c "browserName=firefox moz:firefoxOptions.args=[-headless]" MDMNext_TestSuite_02_ChecksforDecode.side
info:    Running MDMNext_TestSuite_02_ChecksforDecode.side
 FAIL  ./MDMNext_TestSuite_02_ChecksforDecode.test.js (5.577s)
  MDMNext_TestSuite_02_ChecksforDecode
    ✕ TS02-TC01-Decode button-KeyCore-Language (3040ms)

  ● MDMNext_TestSuite_02_ChecksforDecode › TS02-TC01-Decode button-KeyCore-Language

    UnexpectedAlertOpenError

      at Object.throwDecodedError (../../nodejs/node-v10.15.1-linux-x64/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../nodejs/node-v10.15.1-linux-x64/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (../../nodejs/node-v10.15.1-linux-x64/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.141s
Ran all test suites.

Just wondering how we can resolve this? In the IDE tool we can set the execution speed, but then when running in command line im encountering this error. I already tried putting set speed and pause and waiting for element visible to my steps, but i keep getting same error. 

What am i missing here?

Thank you in advance.

**Comment by tourdedave** [comment]
Apologies for the delay in responding, but we've noticed you've filed an issue without filling out the template. We are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
