### ISSUE TITLE
SideEx team contribution: license, notice and credit

### ISSUE THREAD

**Issue by zavelevsky** [SeleniumHQ/selenium-ide#6]
We should properly credit the SideEx team for their contribution and also edit the NOTICE file accordingly - as customary under Apache.
quoting:
"The SideeX repo looks clean and correctly licensed under the Apache License 2.0.  As long as you follow the same conventions re: attribution and notice requirements as you would with any other Apache-licensed code, you should be fine.  The SideeX contributors will retain ownership of the copyrights in their code; Selenium IDE contributors will retain ownership of the copyrights associated with any modifications they make to the SideeX code.  And, of course, Selenium shouldn't call the forked version of SideeX "SideeX."

While Selenium would be required to retain in the forked code all existing attributions to the SideeX contributors (as per the terms of the Apache license), you're not necessarily required to acknowledge SideeX on your website and/or blog.  But, seeing as: a) the SideeX project acknowledges Se IDE on the front page of their site, and b) Doron has already reached out to the SideeX team lead, giving SideeX a shout out is probably the community-friendly thing to do. "

**Comment by tourdedave** [comment]
I followed up with the Software Freedom Conservancy (SFC) on this issue to get their take on best practice for managing the copyright notices in existing source code files as they change over time.

They said we should keep original copyright notices and recommended we review a white paper that discusses this topic ([link](http://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html)). It's for a slightly different context (e.g., GPL) but it should still be relevant here.

And for what it's worth, they also said that nearly every project in FLOSS has copyright notices that are not ideal and to get them in a pristine and "great" state is generally more work than developers want to do.

**Comment by tourdedave** [comment]
The tl;dr from the Software Freedom Conservancy is this:

1. Leave existing copyright notices intact.
2. When creating new files in the project, use the Selenium project's stated license header ([link](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#license-headers))
3. Reconcile copyrights at a later date in batch (if need be).

The SFC has queued up my request for legal review just to confirm, but it will take at least a month before we get a "belts and suspenders" answer. For now, though, the above should be sufficient.
