### ISSUE TITLE
Can't click browser after run test selenium-ide

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#60]
I pulled lastest code from master repository.
There is something two strange situation.

1. after running test case, scroll is appeared at right bottom
![image](https://user-images.githubusercontent.com/33743343/33695083-bc1c1bd6-db3e-11e7-9c26-1077e05cf952.png)

2. I can't click '**selenium-highlight**' section on browser.
![image](https://user-images.githubusercontent.com/33743343/33695137-fc90192e-db3e-11e7-86a4-c8916b04e37c.png)

I have used chrome.

**Comment by Jongkeun** [comment]
I have figured out what is cause.
But I didn't modify. 
Because I can't understand what is your intend.

If I removed the selected 4 lines in prompt.css, it worked fine.
![image](https://user-images.githubusercontent.com/33743343/33699957-b2e0385c-db59-11e7-9ab2-d83a4bccd498.png)

If I removed only bottom, I could click, But scroll was still remained.

Check it please.

**Comment by corevo** [comment]
It was an oversight on my part, I added `mouse-events: none;` on the content but not the pseudo class, I'll fix it

**Comment by corevo** [comment]
I fixed the 2nd point, but I need the website in question to fix the first point

**Comment by Jongkeun** [comment]
Sorry This video has no mouse pointer.
But you can see that scroll bar is appeared at right bottom after starting selenium-ide

[https://drive.google.com/file/d/1YtRshNPimORstLR5JyakbERoB8OOdtE0/view?usp=sharing](url)
