### ISSUE TITLE
Working with variables in Selenium IDE 3

### ISSUE THREAD

**Issue by OleanderRose** [SeleniumHQ/selenium-ide#600]
I have a Selenium IDE 2.9.1 TestSuite with the following code:
store            vanGogh                 fieldentry
type             name=fieldname    ${fieldentry}
The new SeleniumIDE does not work with this code, since ${fieldentry} is not recognized as as variable that contains another value.
How can I migrate this code?

**Comment by capoerafreak** [comment]
I can not confirm this issue, i created a old test, like yours
[IDE 2.9.1 Tesfile.txt](https://github.com/SeleniumHQ/selenium-ide/files/2946735/IDE.2.9.1.Tesfile.txt)

and it works without any problems ...
can you please check this tes file?

**Comment by OleanderRose** [comment]
Ok, sorry. I didn't understand which was really the problem and I wrote an example which is too simple.
What I need is these commands: 
store    12345   var1
store    ${var1}    var2
store   javascript{storedVars['var2'].substring(1,4)}   var3
type name=anyfield   ${var3}

the first command works, but from the second on the ${} are not evaluated correctly.
Do you have a hint for me, how I can map These Selenium 2 code into Selenium 3?

**Comment by capoerafreak** [comment]
the problem is the javascript ...
try execute script | return ${var2}.substring(1,4); | var3

attached the test side file (please rename from ".txt" to ".side"
[Test#600.txt](https://github.com/SeleniumHQ/selenium-ide/files/2953700/Test.600.txt)

and the linß to the docs:
https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#execute-script

**Comment by capoerafreak** [comment]
I think this is done right? Lets close it.

**Comment by OleanderRose** [comment]
yes, it's fine now!
Thank you!! :-)
