### ISSUE TITLE
SeleniumIDE / Side-runner React app date-time input inconsistencies. Passes on sIDE, fails on side-runner

### ISSUE THREAD

**Issue by YOU54F** [SeleniumHQ/selenium-ide#603]
## 🐛 Bug Report

Tests created via SeleniumIDE Chrome & Firefox Add-ons do not exhibit the same behaviour when run in  Selenium Side Runner which can cause consistent failures.

This appears to be specific to a date-time field. The specific one tested with is provided via `react-jsonform-schema` and can be seen here https://mozilla-services.github.io/react-jsonschema-form/

## To Reproduce

Steps to reproduce the behaviour:

Run provide side file which will

Visit https://mozilla-services.github.io/react-jsonschema-form/
Click on the date/time button
Attempt to type `21/12/1984` into the `root_native_date` control

## Exhibited behaviour

- Run the provided `side_test.side` via Chrome extension - Test passes
```
Running 'react_form_date'
...
9.assertValue on id=root_native_date with value 1984-12-21 OK
'react_form_date' completed successfully
```

- Run the provided `side_test.side` via Firefox extension - Test passes

```
Running 'react_form_date'
1.open on /react-jsonschema-form/ OK
...
9.assertValue on id=root_native_date with value 1984-12-21 OK
'react_form_date' completed successfully
```

- Run `selenium-side-runner -c "browserName=firefox" side_test.side` - Test Fails

```
    expect(received).toHaveValue(expected)

    Expected value to be (using Object.is):
      "1984-12-21"
    Received:
      ""
```

- Run `selenium-side-runner -c "browserName=chrome" side_test.side`  - Test Fails

```
    Expected value to be (using Object.is):
      "1984-12-21"
    Received:
      "41221-08-19"
```

- Run `selenium-side-runner -c "browserName=safari" side_test.side` - Test Fails

```
    Expected value to be (using Object.is):
      "1984-12-21"
    Received:
      "19--"
```

## Expected behaviour

SeleniumIDE tests which pass in Chrome & Firefox extensions should also pass in Selenium-side-runner

## Project file reproducing this issue 

see the following download link for a `.side` file named `side_test.side`

https://www.dropbox.com/s/tzrk06ql8jll1hq/side_test.side?dl=0

## Environment

OS: OSX 10.14.3
Selenium IDE Version:  3.5.8 chrome & firefox runner
Selenium SIDE Runner Version:  3.5.9
Node version: v.8.15.0

Browser:
Chrome 72.0.3626.121 
ChromeDriver 2.46.628411
Firefox 65.0.1 
geckodriver 0.24.0
Safari  12.0.3

**Comment by nmklong** [comment]
@YOU54F i'm experiencing the same issue. May i know if you had a solution to this?

**Comment by corevo** [comment]
Try [this](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/faq/#why-don-t-numbers-that-are-typed-into-a-date-input-field-appear-correctly)

**Comment by nmklong** [comment]
@corevo this is actually a bigger issue with the inconsistency between the side runner and Selenium IDE, i added more of my comment to this [issue](https://github.com/SeleniumHQ/selenium-ide/issues/673)

**Comment by YOU54F** [comment]
@nmklong I had tried that flag, back when I raised the original issue, as suggested by @corevo but to no avail.

Might spin this up again to investigate further at some point, but it’s fully parked for me at the moment hence me closing the issue, also due to lack of response.

Thanks to @corevo and the team for bringing the tool back, the option to run in a CLI, really is the killer feature but it just seemed a bit too beta at the moment for me to be able to happily roll out for my client atm, but keeping an eye on developments 🤙
