### ISSUE TITLE
How can I reuse the test case in other side file?

### ISSUE THREAD

**Issue by shenlian8** [SeleniumHQ/selenium-ide#604]
### Test cases and test suit are all in one side file

The side file saves a whole test project with test cases and test suit. Is it possible to save the test case separate so I can use that test case somewhere else?

Tanks!

Lian

**Comment by BaluErtl** [comment]
Hi @shenlian8, it depends on what do we mean under _"somewhere else"_:

- If you need that test case to use in **an other .side file**, then you can freely edit that, it's in JSON format. Find the `"tests":` block and copy out the lines of the necessary steps.
- If you need that test case to use in **the same .side file**, then you can add a new suite at the end of the file in extra, which refers to other set of steps.

**Comment by corevo** [comment]
Not at the moment, it is a technological limitation in the current version of the IDE, which we will be looking into changing in the future.

**Comment by 98gmarquee** [comment]
Do the ID's in the json file mean anythign?

Such as: 
`  "tests": [{
    "id": "f87e134e-22fc-42fe-a067-9fda34497c66",
    "name": "VariableStorage-Compare",
    "commands": [{
      "id": "55efc58c-89ae-4928-b97c-1aad871fa94e",
`

Can then be duplicated in a JSON or removed entirely or do they serve a purpose?

**Comment by BaluErtl** [comment]
> Do the ID's in the JSON file mean anything?

@98gmarquee yes, the ID of the steps makes each step unique in the scope of the entire file. They're optional to have. However, for example needed for the UI to know at which step is the current running on at the moment, so can highlight that line on the list. You can assign them arbitrary values (eg. A, B, C... or  01, 02, 03, etc.) until they're different for each, not necessary to stick with the original hash number implementation.

**Comment by shenlian8** [comment]
Is it possible to use a url to indecate test case in an other .side file?
So that I do not neet to COPY out the necessary steps.

**Comment by BaluErtl** [comment]
@shenlian8 Up to my current knowledge there's no such or similar feature implemented. If I understand you correctly, that would require that the Selenium IDE (which is still a browser add-on, keep in mind) be able to form queries, send them as HTTP-requests to the wild web, fetch the response data, parse and validate them, then hook into them for running.

Maybe I'm wrong, but I do feel it would be a far over complexity to build into a single web browser add-on.

**Comment by 98gmarquee** [comment]
> 
> 
> > Do the ID's in the JSON file mean anything?
> 
> @98gmarquee yes, the ID of the steps makes each step unique in the scope of the entire file. They're optional to have. However, for example needed for the UI to know at which step is the current running on at the moment, so can highlight that line on the list. You can assign them arbitrary values (eg. A, B, C... or 01, 02, 03, etc.) until they're different for each, not necessary to stick with the original hash number implementation.

Sorry to belabor the point, but does this cause issues if you copy steps/tests from one test case into another test case, or the same test within the same json? If you do that, then I'm guessing you have to then manually modify the hash to be unique. Right?

Just trying to figure out the easiest/quickest way to copy tests then to change them using the UI for the specific scenario. When 90% of the scenario is just getting to and leaving the section your testing, with only 10% of the test being different, I'd copy the entire test case, then change what I needed to in the UI.

**Comment by shenlian8** [comment]
@BaluErtl I'd like to have the feature, that the test suit can link the test case in another file. Url in this case means that the location of the file which contains the test case. 
This feature should be very useful as we can create reuseable modules and conbine them to some big test suits.
Actrually this is the feature in the old selenese html. Test cases are saved in separate files and test suit loads them.
