### ISSUE TITLE
Minor - Section: Navigation Panel - right s/b left

### ISSUE THREAD

**Issue by newbie-ET** [SeleniumHQ/selenium-ide#605]
Wrong:
Navigation between test cases and test suites is done through the right hand side of Selenium IDE.
Right:
Navigation between test cases and test suites is done through the left hand side of Selenium IDE.

**Comment by diemol** [comment]
@newbie-ET there is an issue template, would you please be more specific?

**Comment by newbie-ET** [comment]
Thanks for the replies!   On the website, the text in the section mentioned, is wrong.  Saysi it is on the right side of the panel, when it is on the left
I know it is minor, but reflects badly on the newbie reading and trying to follow it.    On Thursday, March 7, 2019, 10:21:57 a.m. EST, Diego Molina <notifications@github.com> wrote:  
 
 
@newbie-ET there is an issue template, would you please be more specific?

**Comment by diemol** [comment]
If you are talking about the Selenium IDE docs, you can find them here https://www.seleniumhq.org/selenium-ide/

**Comment by newbie-ET** [comment]
Yes, I see that, and in that documentation, the section is correct in what it says. As per image 1 below.
But in the documentation i was looking at, in " https://www.seleniumhq.org/docs/02_selenium_ide.jsp  ", the documentation, as per image 2, is wrong.


IMAGE 1.




IMAGE 2.


    On Thursday, March 7, 2019, 10:31:03 a.m. EST, Diego Molina <notifications@github.com> wrote:  
 
 
If you are talking about the Selenium IDE docs, you can find them here https://www.seleniumhq.org/selenium-ide/

**Comment by capoerafreak** [comment]
Thanks for the Info I opend a pull request: 
https://github.com/SeleniumHQ/www.seleniumhq.org/pull/215

**Comment by diemol** [comment]
Fixed via https://github.com/SeleniumHQ/www.seleniumhq.org/pull/216
We removed duplicated docs and only point to the new Selenium IDE site.
