### ISSUE TITLE
Section: Alerts, Popups, and Multiple Windows - Getting "uncaught reference error" on clicking buttons 

### ISSUE THREAD

**Issue by newbie-ET** [SeleniumHQ/selenium-ide#606]
Posted it into Chrome. No directions given as to what should be pasting that page into.  Get the referencec error when click the buttons.

**Comment by diemol** [comment]
@newbie-ET there is an issue template, would you please be more specific?

**Comment by diemol** [comment]
Fixed via https://github.com/SeleniumHQ/www.seleniumhq.org/pull/216
We removed duplicated docs and only point to the new Selenium IDE site.
