### ISSUE TITLE
Save dialog broken once a Selenium IDE plugin is registered

### ISSUE THREAD

**Issue by zewa666** [SeleniumHQ/selenium-ide#607]
## 🐛 Bug Report / Documentation request

When registering a custom plugin, the save button does not anymore open up a Dialog.
I've worked around the issue by listening to the `emit` action and sending a `true` response

```typescript
chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {
  // tslint:disable-next-line:no-console
  console.log("Event from IDE:", message);
  if (message.action === "emit") {
    sendResponse(true);
  }
});
```

## To Reproduce

* Use a minimal Extension sample
* Startup Selenium IDE
* Register with the plugin
* Click on the save 

## Expected behavior

The save dialog should popup without having to respond. Alternatively it'd be nice to have some documentation that tells that this has to be done and about what we're supposed to do here. Is this meant as a check for the plugin to prohibit saving unstable projects?

Moreover the action emit and entity project is barely understandable and might conflict with other calls, so how is the consumer supposed to know the event is about saving the project?

## Environment

OS: MacOS
Selenium IDE Version: 3.5.8  
Browser: Chrome
Browser Version: 72

**Comment by corevo** [comment]
It is a bug with Chrome that I've filed with them [here](https://bugs.chromium.org/p/chromium/issues/detail?id=922373), due to this bug you are required to always answer the `browser.runtime.onExternalMessage` or the Promise won't resolve in the IDE side.  
Once Chrome fixes it you won't have to have this workaround in place.

**Comment by zewa666** [comment]
Where can I update the docs to add the workaround info? It seems the repositories docs aren't in sync with the website.

**Comment by tourdedave** [comment]
You could add it to the FAQ -- https://github.com/SeleniumHQ/selenium-ide/blob/master/docs/introduction/faq.md
