### ISSUE TITLE
Right click and store text and store title doesn't work

### ISSUE THREAD

**Issue by ashkaps** [SeleniumHQ/selenium-ide#609]
## 🐛 Bug Report
Selenium IDE fails to store text and store title from right click quick menu. 

## To Reproduce

1. Start a test and navigate to any url
2. Right click on button or text or something and open the sub-menu for Selenium IDE. 
3. Store text and Store title doesn't save the command to store text or the title

## Expected behavior
1. Start a test and navigate to any url
2. Right click on button or text or something and open the sub-menu for Selenium IDE. 
3. IDE should open an alert to ask for variable name
4. The command should be saved with that variable

side note: verify text, assert text etc works fine. 

## Environment

OS: OSX
Selenium IDE Version:  3.5.8

Browser: Chrome
Browser Version: Version 72.0.3626.119 (Official Build) (64-bit)

I have also tried on windows chrome. 
I have tried to checked that pop-ups are allowed on my browsers.

**Comment by capoerafreak** [comment]
I can confirm this.

**Comment by ashkaps** [comment]
@capoerafreak, any idea if there i a further approach that needs to be taken to get this in front of the developers?

**Comment by capoerafreak** [comment]
@corevo: can you take a look at this?

**Comment by ashkaps** [comment]
Will this issue be prioritised?
I am not a js developer myself but if someone can point in the direction as to where to look at, I can try and fix the issue.
