### ISSUE TITLE
Unintetional inheritance of browser chrome config

### ISSUE THREAD

**Issue by BaluErtl** [SeleniumHQ/selenium-ide#610]
## 💥 Selenium IDE add-on UI background color

1. Mozilla Firefox **60.5.1esr**, 64-bit (tested as Tor Browser 8.0.6 based upon this FF version)
![Selenium-ide-addon-background-color-macos-ff-tor](https://user-images.githubusercontent.com/3431339/54086181-11137800-433f-11e9-99f2-dc0952cc22cb.png)

1. Mozilla Firefox "Developer Edition" (formerly Aurora release channel) **66.0b14**, 64-bit on Ubuntu
![Selenium-ide-addon-background-color-ubuntu-ff-deved](https://user-images.githubusercontent.com/3431339/54086368-be3ac000-4340-11e9-8140-84eead564da9.png)

1. Mozilla Firefox "Developer Edition" (formerly Aurora release channel) **66.0b14**, 64-bit on macOS X
![Selenium-ide-addon-background-color-macos-ff-deved](https://user-images.githubusercontent.com/3431339/54086371-c5fa6480-4340-11e9-8972-8100afffcf9f.png)

Just for reference, this was not an issue in the "XUL-era", because that time the UI was built in a different fashion:

Selenium IDE **2.9.1.1** on Firefox **54.0.1**, 64-bit:
![Selenium-ide-addon-background-color-macos-old-ff](https://user-images.githubusercontent.com/3431339/54086415-11ad0e00-4341-11e9-8530-805872c4bccd.png)

## Last working version

Worked up to version: FF 60.5.1

Stopped working in version: FF 66.0b14

## To Reproduce

1. Open Mozilla Firefox's `about:config` panel, accept the warning message.
1. Search for the term "background", double-click the row of `browser.display.background_color` and set a hexadecimal value of any dark shaded colour.
1. Open the Selenium IDE the usual way.

## Expected behavior

UI of Selenium IDE should appear on a white background, so together with the default black text color visibility of the UI supposed to be kept normal.

## Project file reproducing this issue (highly encouraged)

_No `.side` project file (SSCCE) is applicable to provide, because issue is about the UI appearance, not functionality._

## Environment

OS: Ubuntu 18.04 LTS & macOS X 10.13.6
Selenium IDE Version:  3.5.8
Selenium SIDE Runner Version: n.a.
Node version: n.a.
Browser: Mozilla Firefox
Browser Version: see above

**Comment by BaluErtl** [comment]
Regarding the possible resolutions I have the following ideas:
1. **Quickfix:** define an exact hexadecimal value of a light color (probably #ffffff) in Selenium IDE's UI description files
2. **Long-term solution:** prepare the Selenium IDE to be usable on dark background colors. This way definitely more "logic" is needed to be implemented, but a _Dark theme support_ would offer a major feature addition to hopefully capture attention of the mainly developer audience.

**Comment by corevo** [comment]
We have no plans on adding dark mode for now, your first solution is great, do you mind sending a pr in?

**Comment by BaluErtl** [comment]
Today I re-tested on mac OS by following the steps described above and now cannot reproduce anymore: in both version combinations IDE's UI appears white as expected.

- Firefox 60.6.1esr + Selenium IDE 3.7.1
- Firefox 67.0b18 + Selenium IDE 3.7.1

I think during the last 2 months since the reporting some CSS improvement somehow solved it.

**Comment by corevo** [comment]
Then we can close?

**Comment by BaluErtl** [comment]
Sure, why not?
