### ISSUE TITLE
Default profile firefox is not working with profile moz:firefoxOptions

### ISSUE THREAD

**Issue by tatototino** [SeleniumHQ/selenium-ide#616]
## 🐛 Bug Report

I´m trying to use a default firefox profile using selenium-side-runner adding in package.json on side-suite dir:

                  "moz:firefoxOptions": {
                                        "binary": "/usr/bin/firefox",
                                        "args": ["-profile", "/root/.mozilla/firefox/w7eerp9r.default"]
                                }

/usr/bin/node /usr/lib/node_modules/selenium-side-runner/dist/child.js --debug --no-watchman --testMatch {**/***/*.test.js,**/***.test.js}/selenium-side-runner--debug --no-watchman --testMatch {**/***/*.test.js,**/

or

selenium-side-runner --debug  -c "browserName=firefox  moz:firefoxOptions.args=["-profile", "/root/.mozilla/firefox/w7eerp9r.default"]"  --timeout 90000   /root/Desktop/***.side

following full package.json
{
        "name": "cherwel",
        "version": "0.0.0",
        "jest": {
                "extraGlobals": [],
                "modulePaths": [
                        "/usr/lib/node_modules/selenium-side-runner/node_modules",
                        "/usr/lib/node_modules"
                ],
                "setupFilesAfterEnv": [
                        "/usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/setup.js"
                ],
                "testEnvironment": "jest-environment-selenium",
                "testEnvironmentOptions": {
                        "capabilities": {
                                "browserName": "firefox",
                                "moz:firefoxOptions": {
                                        "binary": "/usr/bin/firefox",
                                        "args": ["-profile", "/root/.mozilla/firefox/w7eerp9r.default"]
                                }
                        },
                        "params": {},
                        "runId": "0f64768fe536ea3e8f267fd7a2042a6b",
                        "path": "/usr/lib/node_modules/",
                        "timeout": 60000
                }
        },
        "dependencies": {}
}

 /usr/bin/node /usr/lib/node_modules/selenium-side-runner/dist/child.js --debug --no-watchman --testMatch {**/***/*.test.js,**/***.test.js}/selenium-side-runner --no-watchman --testMatch {**/***/*.test.js,**/

When a execute the cli above it trigger the firefox but after a while a get a error:

[root@toti-2 side-suite-cherwel]# /usr/bin/node /usr/lib/node_modules/selenium-side-runner/dist/child.js --debug --no-watchman --testMatch {**/***/*.test.js,**/***.test.js}
{
  "configs": [
    {
      "automock": false,
      "browser": false,
      "cache": true,
      "cacheDirectory": "/tmp/jest_0",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "/root/side-suite-cherwel",
      "dependencyExtractor": null,
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "extraGlobals": [],
      "filter": null,
      "forceCoverageMatch": [],
      "globalSetup": null,
      "globalTeardown": null,
      "globals": {},
      "haste": {
        "computeSha1": false,
        "providesModuleNodeModules": []
      },
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "json",
        "jsx",
        "ts",
        "tsx",
        "node"
      ],
      "moduleNameMapper": {},
      "modulePathIgnorePatterns": [],
      "modulePaths": [
        "/usr/lib/node_modules/selenium-side-runner/node_modules",
        "/usr/lib/node_modules"
      ],
      "name": "f800fea9406d28eb83d79abab9a04bfb",
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "resolver": null,
      "restoreMocks": false,
      "rootDir": "/root/side-suite-cherwel",
      "roots": [
        "/root/side-suite-cherwel"
      ],
      "runner": "jest-runner",
      "setupFiles": [],
      "setupFilesAfterEnv": [
        "/usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/setup.js"
      ],
      "skipFilter": false,
      "snapshotSerializers": [],
      "testEnvironment": "/usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js",
      "testEnvironmentOptions": {
        "capabilities": {
          "browserName": "firefox",
          "moz:firefoxOptions": {
            "binary": "/usr/bin/firefox",
            "args": [
              "-profile",
              "/root/.mozilla/firefox/w7eerp9r.default"
            ]
          }
        },
        "params": {},
        "runId": "0f64768fe536ea3e8f267fd7a2042a6b",
        "path": "/usr/lib/node_modules/",
        "timeout": 60000
      },
      "testLocationInResults": false,
      "testMatch": [
        "**/***/*.test.js",
        "**/***.test.js"
      ],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": [],
      "testRunner": "/usr/lib/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/index.js",
      "testURL": "http://localhost",
      "timers": "real",
      "transform": [
        [
          "^.+\\.[jt]sx?$",
          "/usr/lib/node_modules/selenium-side-runner/node_modules/babel-jest/build/index.js"
        ]
      ],
      "transformIgnorePatterns": [
        "/node_modules/"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "collectCoverage": false,
    "collectCoverageFrom": null,
    "coverageDirectory": "/root/side-suite-cherwel/coverage",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "coverageThreshold": null,
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "extraGlobals": [],
    "filter": null,
    "globalSetup": null,
    "globalTeardown": null,
    "json": false,
    "listTests": false,
    "maxConcurrency": 5,
    "maxWorkers": 3,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "failure-change",
    "passWithNoTests": false,
    "projects": null,
    "rootDir": "/root/side-suite-cherwel",
    "runTestsByPath": false,
    "skipFilter": false,
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testResultsProcessor": null,
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": null,
    "watch": false,
    "watchman": false
  },
  "version": "24.1.0"
}
 FAIL  ./DefaultSuite.test.js
  ● Test suite failed to run

    WebDriverError: connection refused

      at Object.throwDecodedError (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        60.343s
Ran all test suites.

If I take away the following config It works but with a random profile from tmp rust_mozprofile.*.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by tatototino** [comment]
I code a simple script to test the bug, when you do it specifying a profile arguments it just open the browser and do nothing:

const {Builder} = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');
let options = new firefox.Options();
options.addArguments("-profile /root/.mozilla/firefox/w7eerp9r.default");
let driver = new Builder()
  .withCapabilities(options)
  .build();
  driver.get("http://google.com.br");

When a just commented profile line just works fine:

const {Builder} = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');
let options = new firefox.Options();
// options.addArguments("-profile /root/.mozilla/firefox/w7eerp9r.default");
let driver = new Builder()
  .withCapabilities(options)
  .build();
  driver.get("http://google.com.br");

Selenium-webdriver version: selenium-webdriver@4.0.0-alpha.1

**Comment by tourdedave** [comment]
@tatototino If you're able to reproduce the issue in code then the problem isn't with Selenium IDE or the runner. Please double-check the guidance from [the geckodriver documentation regarding profiles](https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#capability-profile). If you think there's a bug with Firefox & Selenium, then please file an issue with [geckodriver](https://github.com/mozilla/geckodriver/issues). You can also ask for help on the Selenium chat channel ([link](http://elementalselenium.com/tips/20-irc-chat)).

**Comment by tatototino** [comment]
Hi tourdeclave,

I think the selenium-webdriver can´´t handle moz:firefoxOption   in the capabilities section because it contains ":" in the json object:

when I pass any value in moz:firefoxOption I get the same error:

      at Object.throwDecodedError (../../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../node_modules/selenium-webdriver/lib/http.js:545:13)
      at Executor.execute (../../node_modules/selenium-webdriver/lib/http.js:468:26)

Response {
  status: 500,
  body: '{"value":{"error":"unknown error","message":"invalid argument: can\'t kill an exited process","stacktrace":""}}',
  

Maybe It happen because http.js can't parse when a object json contain colon like "moz:firefoxOption", you can reproduce using -c from side-runner or edit the package.json directly in side-suite dir.



Regards,
