### ISSUE TITLE
Set the value to a default when using a "wait for" command

### ISSUE THREAD

**Issue by 98gmarquee** [SeleniumHQ/selenium-ide#618]
## 🚀 Feature Proposal

When using commands that require a wait time such as ones that start with "wait for", it would be nice if it set the value to a default value like 30000 (30 seconds).

## Motivation

Helps make writing tests quicker

## Example

Select command "wait for element not visible", set the wait time to 30000 automatically.

**Comment by corevo** [comment]
That's a great idea, sure!

**Comment by 98gmarquee** [comment]
I think I saw the same thing happen when importing old IDE scripts and it would change whatever the old command was to the new command, but leave the field blank, so it would fail when you ran it. I couldn't find my example of that, so I didn't include it. Just thought I'd mention it here in case someone gets a chance to look at it.

**Comment by 98gmarquee** [comment]
Just updating for a reminder about the setting of a default wait when importing an old ide script.

**Comment by harsha509** [comment]
Closing as resolved!
