### ISSUE TITLE
"Relative=parent" locator doesn't work in side runner for select frame command

### ISSUE THREAD

**Issue by ediklutsyk** [SeleniumHQ/selenium-ide#619]
## 🐛 Bug Report

In your documentation for new selenium IDE there is such note for SELECT FRAME command: "To select the parent frame, use 'relative=parent' as a locator" and its works fine in IDE. But when I tried to run it with side runner i got "Unknown locator relative" error

## To Reproduce

Add command select frame with locator "relative=parent" and run it with side runner 

## Expected behavior

Parent frame successfully selected

### Actual behavior

"Unknown locator relative" error occurred 

## Environment

OS: Ubuntu 18
Selenium IDE Version: 3.5.8
Selenium SIDE Runner Version: 3.5.10
Node version: 8.10.0
Browser: Chrome
Browser Version: chrome=72.0.3626.121

**Comment by lucascudo** [comment]
I am having this issue too! Side runner prints:
Unknown locator relative

      100 |     return element.click();
      101 |   });
    > 102 |   throw new Error("Unknown locator relative");

How do you "unselect" a iframe?

**Comment by ediklutsyk** [comment]
> How do you "unselect" a iframe?
Sorry, but i can't solve this issue and this question is still open for me too

**Comment by corevo** [comment]
Fixed in 799bec18

**Comment by lucascudo** [comment]
Wich version should we use at package.json to include this bugfix? I am currently using 3.5.10

**Comment by spatel-37** [comment]
How do you apply this bug fix? I'm using v3.5.10

**Comment by corevo** [comment]
It will be released in v3.5.11

**Comment by lucascudo** [comment]
Sorry to bother you again, but now that I updated to version 3.5.11, I am getting a new error:

UnknownCommandError: Unrecognized command: switchToFrameParent

      at buildRequest (../node_modules/selenium-webdriver/lib/http.js:375:9)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:455:19)
      at Driver.execute (../node_modules/selenium-webdriver/lib/webdriver.js:696:38)

**Comment by corevo** [comment]
What version of chrome and chromedriver are you using?

**Comment by lucascudo** [comment]
I'm running Chrome Version 73.0.3683.75 (Official Build) (64-bit) on Manjaro Linux.
Didn't download any specific chromedriver from anywhere, so I believe that composer are using some driver from Selenium dependencies. How can I confirm it?

**Comment by corevo** [comment]
Try running `chromedriver --version`

**Comment by lucascudo** [comment]
$ chromedriver --version
ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926)

**Comment by yonixw** [comment]
@corevo @lucascudo I had the same problem:

>     UnknownCommandError: Unrecognized command: switchToFrameParent
> 
>       at buildRequest (../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/
>       lib/http.js:375:9)
>       at Executor.execute (../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/
>       lib/http.js:455:19)
>       at Driver.execute (../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/
>       lib/webdriver.js:696:38)

And I was able to fix it by adding the line:
` [cmd.Name.SWITCH_TO_FRAME_PARENT, post('/session/:sessionId/frame/parent')],`
to file 
`selenium-side-runner/node_modules/selenium-webdriver/lib/http.js` after line 216.
which source code is in another repo, link for master branch:
[SeleniumHQ/selenium/...../selenium-webdriver/lib/http.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/http.js#L216)

For some reason it was not written there. Hope it helps and @lucascudo can apply those changes faster than any pull-request I will do.

**Comment by lucascudo** [comment]
@yonixw, solved it here to. @corevo, I am waiting anxiously for v3.5.12.

**Comment by jonesp100** [comment]
@corevo  - So is this now fixed?  Should this now work in latest version>

Thanks!

**Comment by corevo** [comment]
We need to publish a new version of `selenium-webdriver`, I'll update once done.

**Comment by jonesp100** [comment]
@corevo thanks!  Any idea of timefreame?

**Comment by jonesp100** [comment]
@corevo - Sorry just noticed that you mentioned 'web-driver'  this will resolve the issue with side runner?

**Comment by corevo** [comment]
Yes it will, it is the webdriver code that runs the playback, it is developed in the [monorepo](https://github.com/SeleniumHQ/selenium).  
The work done on webdriver is mostly voluntary and because of it we don't give timeframes.

**Comment by yonixw** [comment]
Apparently someone already suggested it and was denied ? 
https://github.com/SeleniumHQ/selenium/pull/6432
Maybe worth a look @corevo

**Comment by corevo** [comment]
It doesn't matter, I've already fixed it on master, we need to release a new version, that's all.

Cheers,
Tomer

**Comment by tourdedave** [comment]
This was released. Closing.

**Comment by tourdedave** [comment]
Whoops, closed prematurely. The code change in the runner was released. We still need to release a new version of the Selenium JS bindings and and updated version of the runner that uses the bindings.

**Comment by tourdedave** [comment]
This is released. Available in version [3.9.0](https://www.npmjs.com/package/selenium-side-runner/v/3.9.0) of the runner.
