### ISSUE TITLE
v3.5.8 where is saved file? How can i export the .side file?

### ISSUE THREAD

**Issue by HolidayOfPandora** [SeleniumHQ/selenium-ide#620]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
Please use the right channels for questions.
