### ISSUE TITLE
How can I migrate: assertAttribute commands from Selenium IDE 2.9.1?

### ISSUE THREAD

**Issue by OleanderRose** [SeleniumHQ/selenium-ide#623]
In our testuite I use assertAttribute | link=FAQ@href  | *any text* to check if the URL contains the words "any text" somewhere in the URL behind the link.

Is there an equivalent in Selenium 3?

**Comment by corevo** [comment]
Please use the [issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose)
