### ISSUE TITLE
Error saving project

### ISSUE THREAD

**Issue by marcoiai** [SeleniumHQ/selenium-ide#626]
Can't save project. When i save it sends it to browser download, then fails with "Network error".
I've checked my connection and it's fine.

## Environment

OS: Ubuntu 18.04
Selenium IDE Version: 3.5.8
Browser: Chrome
Browser Version: Version 72.0.3626.81 (Official Build) (64-bit)

**Comment by corevo** [comment]
It's working on my end, including different setups, try creating a new user profile in Chrome and installing the extension there, I think there is some misconfiguration in Chrome that's causing it.

**Comment by marcoiai** [comment]
I'll give it a try, in Firefox 66.0.2 it's working, same PC.

**Comment by tourdedave** [comment]
@marcoiai Any update?

**Comment by marcoiai** [comment]
As pointed by @corevo, I have tried with other profile and it worked. Thanks guys!
