### ISSUE TITLE
Tests don't run in command line (.setRect is not a function)

### ISSUE THREAD

**Issue by Ygilany** [SeleniumHQ/selenium-ide#627]
## 🐛 Bug Report

Tests run alright when running it through chrome Selenium IDE

Tests aren't running using command line. It throws an error
```
    TypeError: driver.manage(...).window(...).setRect is not a function
    > 74 |   await driver.manage().window().setRect({
```
I'm ran it both using my local machine as well as through a standalone chrome container

## To Reproduce
running a test that contains an instruction to resize the window

## Expected behavior
window is resized properly

## Project file reproducing this issue (highly encouraged)
I can only drill it down to the `setRect`. It seems that another implementation is expected 
      
at Object.setRect [as 1. Go to site] (commons.js:74:34)

Please provide a project file `.side` that reproduces this issue.
```json
{
  "id": "72635211-cd4c-462f-8716-d5bf2ac34022",
  "version": "2.0",
  "name": "Google",
  "url": "https://www.google.com/",
  "tests": [{
    "id": "4cf2cc08-d74a-400d-be0e-04a3a91e16e4",
    "name": "1. Go to site",
    "commands": [{
      "id": "f0058164-e229-4e04-881f-e30d0bf06e33",
      "comment": "Go to site",
      "command": "open",
      "target": "/login",
      "targets": [],
      "value": ""
    }, {
      "id": "8ab5ef75-4107-415c-999a-8cacaa19b6b5",
      "comment": "",
      "command": "setWindowSize",
      "target": "1440x900",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "260f05a1-abda-4b8f-b5f8-25ebf5738f98",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["4cf2cc08-d74a-400d-be0e-04a3a91e16e4"]
  }],
  "urls": ["https://www.google.com/"],
  "plugins": []
}
```

## Environment

OS:  OSX 10.14.2
Selenium IDE Version:    3.5.8 
Selenium SIDE Runner Version:   3.5.9
Node version:  10.15.1

Browser: Chrome
Browser Version:  73.0.3683.86 (Official Build) (64-bit)

Also using Docker image: selenium/standalone-chrome:3.141.59-krypton

command used to run the tests
```
selenium-side-runner --server http://localhost:4444/wd/hub --debug ./myTestFile.side
```

**Comment by Ygilany** [comment]
So it works on another computer that is setup with the exact versions and everything. 

But It still fails in my CI builds. with the same errors

**Comment by corevo** [comment]
Which CI do you use?

**Comment by bviale** [comment]
Reproduced on windows with a simple  `selenium-side-runner myTestFile.side`
Using the latest version of the packages : 

- selenium-side-runner 3.6.0
- chromedriver 74.0.0
- Google Chrome 74.0.3729.108 (Official Build) (64-bit)
- I pulled the 74.0.3729.6 version from [](http://chromedriver.storage.googleapis.com/index.html) and added the exe to my path

**Comment by corevo** [comment]
@bviale I tried using your setup and couldn't reproduce it

**Comment by juampick** [comment]
I'm having the same issue creating the tests using SeleniumIDE, and running it using `selenium-side-runner` on command line.
I tried on CircleCI, locally with MacOs and on different setups, and it's displaying the same error: 
` TypeError: driver.manage(...).window(...).setRect is not a function`

These are my versions: 

- selenium-side-runner `3.11.0`
- chromedriver: ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40})

Can someone know what is throwing this error? It's when trying to do a `setWindowSize` command. 

Thanks,

**Comment by audioscavenger** [comment]
same here with mocha when I run a _JS mocha_ **export** of chrome Selenium IDE:
- windows 10 x64
- Node v12.6.0
- NPM 6.9.0
- ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40})

**Comment by tourdedave** [comment]
@audioscavenger If you're having trouble with code export, double check your setup against what's recommended in the docs ([link](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/code-export/#javascript-mocha)). If the exported syntax is _incorrect_, then you can either send a PR w/ a fix, or open an issue and follow the template ([link](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md)).

@Ygilany, @bviale, @juampick, and anyone else who runs into this with the runner, I'm going to make the `setWindowSize` command optional in the runner. Once we have a way to reproduce the issue on our end, we'll get a proper fix in.

**Comment by tourdedave** [comment]
The workaround is available in version `3.12.0` of the runner.

**Comment by tourdedave** [comment]
Is this still a problem?

**Comment by minaairsupport** [comment]
I am the same issue, I uploaded a sample 
https://github.com/minaairsupport/mochaTest

anyone could tell me how to fix it

**Comment by williamhatch** [comment]
@minaairsupport I have the same issue. Seems pytest works fine if you are using code export -

**Comment by williamhatch** [comment]
@tourdedave still have the issue

**Comment by williamhatch** [comment]
@tourdedave @minaairsupport change to await driver.manage().window().setRect(1920, 1057) it works ...

**Comment by williamhatch** [comment]
@tourdedave But this one not works: await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//h1[contains(.,\'Dashboard\')]"))), 30000) it complains that it cant locate the element...

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
