### ISSUE TITLE
Every second test fails to run in Chrome plugin

### ISSUE THREAD

**Issue by sschweigert11** [SeleniumHQ/selenium-ide#628]
## 🐛 Bug Report

When I run tests individually, every test passes.

When I run all tests together, every second test fails on the'open' command, showing the following error: No tab with id: 166.

The tests all start by launching an internal server URL.

## To Reproduce

Run the suite of test cases attached.

## Expected behavior

Every test runs self-contained successfully.

## Environment

OS: Windows 10
Selenium IDE Version:  3.5.8
Browser: Chrome
Browser Version: 72.0.3626.121 (Official Build) (64-bit)

**Comment by sschweigert11** [comment]
Please see the attached. 

I've noticed that if I specify the full URL in the 'open' command, all test run successfully.
If I set the base URL to my FQDM, then use the 'open' command with the remainder of the URL, this issue occurs.

[628_Side.zip](https://github.com/SeleniumHQ/selenium-ide/files/3004049/628_Side.zip)

**Comment by sschweigert11** [comment]
After further testing, it appears as though if the previous test ends in a close statement, then the following test will fail on the open.

If you remove all close statements, the tests appear to run successfully.

**Comment by corevo** [comment]
Putting `close` at the end of the test causes issues, we should remove it from being recorded.
