### ISSUE TITLE
Unable to execute selenium-side-runner through npm script

### ISSUE THREAD

**Issue by sschweigert11** [SeleniumHQ/selenium-ide#629]
## 🐛 Bug Report

I am able to run test scripts successfully through the CLI: 
     selenium-side-runner 'GVH 5-Series Integration.side'

When I try to run a script defined in my package.json file, nothing happens:
     "test": "selenium-side-runner 'GVH 5-Series Integration.side'",

For example:
PS C:\Repos\Quality\gvh-tests\5SeriesIntegration> npm run test
> gvh-functional-test@1.0.0 test C:\Repos\Quality\gvh-tests\5SeriesIntegration
> selenium-side-runner 'GVH 5-Series Integration.side'
PS C:\Repos\Quality\gvh-tests\5SeriesIntegration>

This is my current configuration:
    "devDependencies": {
        "chromedriver": "2.46.0",
        "geckodriver": "1.16.0",
        "selenium-side-runner": "^3.5.10",
        "selenium-webdriver": "^4.0.0-alpha.1"
    },

## To Reproduce

Run the selenium-side-runner through an npm script.

## Expected behavior

The command executes successfully.

## Project file reproducing this issue (highly encouraged)

Any project file is failing for me.

## Environment

OS: Windows 10
Selenium IDE Version:  3.5.8
Selenium SIDE Runner Version:  3.5.10
Node version: v10.15.3
Browser:
Browser Version: Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by corevo** [comment]
Does it work when not used as an npm script?

**Comment by sschweigert11** [comment]
Yes, it runs as expected when running on the command line.

**Comment by sschweigert11** [comment]
Sorted it out.

Path was defined incorrectly. This functions as expected: "test": "selenium-side-runner \".\\5SeriesIntegration\\GVH 5-Series Integration.side\"",
