### ISSUE TITLE
Locator type link instead of linkText/partialLinkText

### ISSUE THREAD

**Issue by zewa666** [SeleniumHQ/selenium-ide#631]
## 🐛 Bug Report

Looking through the initial seed project, used when building the extension locally and starting up in devmode, in the test-suite `all tests` there is a test called `click` and it's 5th step is a click step using `link=Dropdown` as target.

Now I've not been able to find this type selector anywhere else mentioned in the IDE so I guess it's a typo and was intended to be either `linkText` or something similar.

## To Reproduce

* Seed project when opening the locally built extension

## Expected behavior

Fix link to whatever the proper locator type is

## Project file reproducing this issue (highly encouraged)

The default seed project built here from code
https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide-extension/src/neo/stores/seed.js#L312

## Environment

Selenium IDE Version: latest

**Comment by corevo** [comment]
It's not a bug, I am testing that the warning shows in the console.
