### ISSUE TITLE
Is there a way to read test data from excel using selenium-ide?

### ISSUE THREAD

**Issue by umakant18** [SeleniumHQ/selenium-ide#633]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by tourdedave** [comment]
No, not at the moment. It's on our roadmap but work on it hasn't been prioritized yet.

**Comment by tourdedave** [comment]
https://github.com/SeleniumHQ/selenium-ide/issues/183
