### ISSUE TITLE
selenium-side-runner screenshot

### ISSUE THREAD

**Issue by jaysooon** [SeleniumHQ/selenium-ide#634]
## 💬 Questions and Help

Is the side runner already had an screenshot? like taking a screenshot for the web driver (Nodejs) Thank you

**Comment by tourdedave** [comment]
Duplicate of #182.

For questions and help, please see [the project's help page](https://www.seleniumhq.org/selenium-ide/help/). The issue tracker is for filing bugs and feature request.
