### ISSUE TITLE
There is no 'selenium-core-scripts' files.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#64]
I can't build selenium project.
please add these files.

selenium-core-scripts/htmlutils.js
selenium-core-scripts/selenium-browserdetect.js

**Comment by corevo** [comment]
try to `peru sync` again, I changed the `peru.yaml` to include more of the selenium code base

**Comment by Jongkeun** [comment]
Hmm...
It is not working on my company's computer.
I don't know whether this computer is fine or not.
I will try to check it at my home.
If It work, I will close this issue.

**Comment by corevo** [comment]
[This commit](https://github.com/SeleniumHQ/selenium-ide/commit/87da20132c869b54d30eb286af4c0a0b5d6e0530) adds the `selenium-core-scripts`, but also changes `peru.yaml` accordingly.

**Comment by Jongkeun** [comment]
It's a long wait, so it works.
