### ISSUE TITLE
Is it possible running mutiple instances with the same .side file on different urls?

### ISSUE THREAD

**Issue by Name404** [SeleniumHQ/selenium-ide#641]
Hi there,
    I'm trying to test my little website with sele-IDE, and here I have a problem.
    Is it possible that I init like 10 instances with a same .side file, testing 10 different urls at one time?
    I get some virtual sites on cloud server, so is it possible?
    Many thanks!

**Comment by corevo** [comment]
Please follow the issue template when opening issues, there are instructions on places where you could ask questions.  

That being said, you definitely can, set your suite to parallel in the settings and use it in conjunction with the [-w flag](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#specify-the-number-of-parallel-processes).

**Comment by Name404** [comment]
> Please follow the issue template when opening issues, there are instructions on places where you could ask questions.
> 
> That being said, you definitely can, set your suite to parallel in the settings and use it in conjunction with the [-w flag](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#specify-the-number-of-parallel-processes).

Hello corevo, I got some error while installing selenium-side-runner, both on my CentOS and win.
Installation log guide me to file an issue here, would you please also take a look. Thanks!
https://npm.community/t/trying-install-selenium-side-runner-failed-log-shows-its-npm-bug-and-guide-me-here/6924

**Comment by corevo** [comment]
This is a problem with npm, either seek help with them or try a different node package manager like yarn.

**Comment by Name404** [comment]
I do downloaded src selenium-side-runner-3.6.0, but got no idea on how to use it...
Is there a guide or etc?
