### ISSUE TITLE
Current release depends on versions of react-tooltip and react-dom with XSS vulnerabilities

### ISSUE THREAD

**Issue by maxrev17** [SeleniumHQ/selenium-ide#642]
## 🐛 Bug Report

react-tooltip@3.6.1 and react-dom@16.4.1 have XSS vulnerabilities and therefore the info sec department who approve this software for my use are saying it cannot be used as they are dependencies of the browser extensions.

## To Reproduce

Check the vulns in the affected libs.

## Expected behavior

All dependencies should be secure.

**Comment by corevo** [comment]
fixed in 9973c26

**Comment by maxrev17** [comment]
@corevo do you have any idea when this will be released mate?
