### ISSUE TITLE
Test error in browser firefox from selenium-side-runner

### ISSUE THREAD

**Issue by pbezpal** [SeleniumHQ/selenium-ide#645]
## 🐛 Bug Report

Hello! My test return error after run selenium-side-runner in the browser firefox.
If run test from selenium-side-runner in the browser chrome, then  test is success
At run from application in browser firefox test is success.

My test .side
[https://gist.github.com/pbezpal/68068c766675cc4f777182612e6bcce3](https://gist.github.com/pbezpal/68068c766675cc4f777182612e6bcce3)
## To Reproduce

[Test in browser firefox](https://gist.github.com/pbezpal/43b4d18bb4cdb6f2214789c35e90eed2)
[Test in browser chrome](https://gist.github.com/pbezpal/4f6c52b469bff0efe9319d3991cbf640)

## Environment

OS:  Windows 10
Selenium IDE Version:  3.5.8
Selenium SIDE Runner Version:  3.5.11
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: v10.15.3
Only required if using selenium-side-runner
-->
Browser: Firefox
Browser Version: 66.0.22 (64-bit)

**Comment by tourdedave** [comment]
Try removing the `close` command from your test and running it again in Firefox.

This command is not required since the IDE and the runner both handle the browser lifecycle (e.g., documented [here](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#close)).

**Comment by pbezpal** [comment]
Thank you. It is helped)

**Comment by tourdedave** [comment]
Great!
