### ISSUE TITLE
I have recorded some  selenium tests by Selenium IDE 3.5.8 and I want to run those tests in Jenkins, how can I do that.

### ISSUE THREAD

**Issue by JabbarHanane** [SeleniumHQ/selenium-ide#646]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
Hey, you have links there to tell you where to ask questions, I recommend you check out [selenium-side-runner](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/).
