### ISSUE TITLE
ExportCode

### ISSUE THREAD

**Issue by OrangeHeroDavid** [SeleniumHQ/selenium-ide#653]
When to support Python3？Export Python3 code？Why close it?

**Comment by OrangeHeroDavid** [comment]
Why cancel the export code function of v2.9.1？It is wise to seek help.

**Comment by OrangeHeroDavid** [comment]
The answer has been found. Thank you. https://github.com/SeleniumHQ/selenium-ide/issues/592

**Comment by barancev** [comment]
Please follow #592
