### ISSUE TITLE
Applitools Eyes not capturing during a called run test

### ISSUE THREAD

**Issue by Krys-P** [SeleniumHQ/selenium-ide#656]
## 🐛 Bug Report

when using "eyes check window" in a test that is called via another test. The checks say OK but do not generate an applitools image.
This works if added to a test suite.

## To Reproduce
Steps to reproduce the behaviour:
Create two tests. 
The first is to do any eyes check window. 
The second calls the first check via run command

## Expected behavior

The applitools images are recorded, verified and sent to the applitools repository.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

Would love to, but not a supported file type!

## Environment

OS: Windows 10
Selenium IDE Version:  3.5.8
Selenium SIDE Runner Version:  
Please note that selenium-side-runner supports Node.js 8 - 10

Node version: 
Only required if using selenium-side-runner

Browser: Chrome
Browser Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by corevo** [comment]
This issue tracker is for Selenium IDE and not any 3rd party integrations, please contact [Applitools support](https://support.applitools.com) for help.
