### ISSUE TITLE
Stored variables are not loaded in test if it runs with selenium-side-runner command

### ISSUE THREAD

**Issue by MaryQ** [SeleniumHQ/selenium-ide#657]
##  Meta
OS: Windows 10
Selenium IDE Version: 3.6.0
Selenium SIDE Runner Version: 3.6.0
Node version: npm: 6.7.0
Browser: Chrome

## Expected Behavior
I have added in the suit two test cases. In the first one url is stored in 'host' variable and in the second test this url should be opend by 'open|${host}' command. When I run this suit in Selenium IDE, it works correctly. But when I run it through 'selenium-side-runner test.side' command, error appears.
![image](https://user-images.githubusercontent.com/16049859/56584153-db230e00-65e3-11e9-98ce-5f95d292b4fb.png)

Here I attempt my test.side file:
[test.txt](https://github.com/SeleniumHQ/selenium-ide/files/3107716/test.txt)

Why is this wrong? How should I use stores variables?

**Comment by corevo** [comment]
Fixed in 6d51e1b2c5c5b5af16e8758303f76b4cbc1e90fc
