### ISSUE TITLE
CLI executing

### ISSUE THREAD

**Issue by hiroshitoda** [SeleniumHQ/selenium-ide#66]
Are there any plans for executing on Command Line Interface with Selenium IDE TNG?
I think we already have some plans like below:

* plan 1: feature of exporting WebDriver code with some general languages.
* plan 2: `.side` format test runner "selenium-side-runner.jar" like selenium-html-runner.jar
* plan 3: something new and smart plan I don't know :)

**Comment by corevo** [comment]
Yes, it is planned, it is going to be one of the next features to be worked on.  
I don't have an ETA yet, I'll update this issue when I have one.

**Comment by corevo** [comment]
I've started working on a way to export the code to WebDriver code, that we'll ship with a runner, or could be ran with other test suite runners.  
Once I have something more concrete I'll post a candidate on the releases for testing.
