### ISSUE TITLE
Is possible run the HtmlUnit with file .side?

### ISSUE THREAD

**Issue by raimundoalves** [SeleniumHQ/selenium-ide#665]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
No, you can try using [selenium-side-runner](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/)
