### ISSUE TITLE
Extensions: Allow extension to provide meta-locators

### ISSUE THREAD

**Issue by ChrisLMerrill** [SeleniumHQ/selenium-ide#669]
## 🚀 Feature Proposal

This is a little different from #104 (Extensions: Provide a means for extensions to add and implement new Locator types). It would allow an extension to return the locator to be used. So it isn't implementing a locator - rather it is dynamically deciding which (standard) locator should be used in the step.

## Motivation

This could drastically reduce maintenance cost as the AUT changes.

## Example

Take this xpath locator:
`xpath=//div[contains(@class,'cimm_headerSettingsMenu')]/ul/li[2]/a`
Lets assume that despite being fragile, it is the best alternative. Now imagine that this locator or slight variations are used in many places:
```
xpath=//div[contains(@class,'cimm_headerSettingsMenu')]/ul/li[2]/a
xpath=//div[contains(@class,'cimm_headerLoginMenu')]/ul/li[2]/a
xpath=//div[contains(@class,'cimm_navHome')]/ul/li[2]/a
xpath=//div[contains(@class,'cimm_navReports')]/ul/li[2]/a

```
The meta-locator support would simplify a click step in the test to something like:
`click | metalocator=custom,navHome`

The rest of the xpath would be maintained in just one place (managed by the extension?). When the step executes, SeleniumIDE would pass the parameter to the extension, which would then return the locator to be used - in this case _xpath=//div[contains(@class,'cimm_navHome')]/ul/li[2]/a_

Now, when changes in the AUT affect this xpath pattern, it must only be changed in one place.

There are some details that need would need further exploration, such as:

- how to specify which extension should resolve the locator
- how to format arguments sent to the extension
- how to store the information from the extension in the .side file (optional) to keep everything in one place

**Comment by corevo** [comment]
I like the idea, but I think we can merge it as another use case of #104, what do you think?

**Comment by ChrisLMerrill** [comment]
If you think so, then yes, sure. I got a little lost reading the full conversation, particularly when referencing eval()ing code provided by the plugin. I'm hoping that this suggestion does not get into those restrictions (it doesn't even need to access the DOM), so maybe could be one of the _first_ custom locator features :)

**Comment by corevo** [comment]
Okay, then I'm closing this and we'll make sure to support this use case in #104
