### ISSUE TITLE
Run test case with variable name fails with selenium side runner

### ISSUE THREAD

**Issue by oliguti** [SeleniumHQ/selenium-ide#671]
## 🐛 Bug Report

Command run | ${VarTestCaseName} fails in side runner

## To Reproduce

Test case A store a test name in a variable and then calls it with run | ${VarTestCaseName} command
Running the test case A is OK in Selenium IDE (chrome)
Running it in side runner fails : (details available in "Project file reproducing this issue")

## Expected behavior

Side runner is running the test case with varName

## Project file reproducing this issue (highly encouraged)
Project file content :
...
{
  "id": "5541dabc-7dde-4d2e-aeca-89a0ed10bbad",
  "version": "2.0",
  "name": "Issue_TestCaseCalledWithVarName",
  "url": "https://duckduckgo.com/",
  "tests": [{
    "id": "6b473cd2-81d2-4ec7-980c-f00e89776a47",
    "name": "MainTest",
    "commands": [{
      "id": "410d4821-8d75-467a-874c-fc20e68db51f",
      "comment": "",
      "command": "open",
      "target": "https://duckduckgo.com/",
      "targets": [],
      "value": ""
    }, {
      "id": "ad85814e-380e-4438-8f0c-07bb41fba74b",
      "comment": "",
      "command": "store",
      "target": "checkPageTitle",
      "targets": [],
      "value": "VarTestCaseName"
    }, {
      "id": "22b119dd-17bd-482f-828a-f0fce6cbe462",
      "comment": "",
      "command": "run",
      "target": "${VarTestCaseName}",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "3152d0f3-d0ef-4740-a7a0-e1f3761ce211",
    "name": "checkPageTitle",
    "commands": [{
      "id": "10875fab-cdf2-47ad-9eb3-ea6726f0c1ca",
      "comment": "",
      "command": "verifyTitle",
      "target": "DuckDuckGo — Confidentialité, simplifiée.",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "d2d869fe-880c-46a2-8356-dd47e21bc1bc",
    "name": "SuiteToRunWithSideRunner",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["6b473cd2-81d2-4ec7-980c-f00e89776a47"]
  }],
  "urls": ["https://duckduckgo.com/"],
  "plugins": []
}
...

Cmd execute test suite with side runner :
...
selenium-side-runner C:/.../Issue_TestCaseCalledWithVarName.side -c "browserName=chrome" --params="eyesLogsEnabled=true"
info:    Running C:/.../Issue_TestCaseCalledWithVarName.side

 RUNS  ./SuiteToRunWithSideRunner.test.js

 RUNS  ./SuiteToRunWithSideRunner.test.js
 RUNS  ./SuiteToRunWithSideRunner.test.js
 RUNS  ./SuiteToRunWithSideRunner.test.js
 FAIL  ./SuiteToRunWithSideRunner.test.js (43.037s)
  SuiteToRunWithSideRunner
    × MainTest (38086ms)

  ● SuiteToRunWithSideRunner › MainTest

    TypeError: tests.${vars.VarTestCaseName} is not a function

      4 |   await driver.get("https://duckduckgo.com/");
      5 |   vars["VarTestCaseName"] = `checkPageTitle`;
    > 6 |   await tests["${vars.VarTestCaseName}"](driver, vars, {
        |         ^
      7 |     isNested: true
      8 |   });
      9 | }

      at Object.<anonymous>.tests.MainTest (commons.js:6:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        43.449s
Ran all test suites.
...

## Environment

OS: Windows 10
Selenium IDE Version:  3.6.1
Selenium SIDE Runner Version: 3.6.1
Node version: v10.15.3
Browser: Chrome
Browser Version: 74.0.3729.131 (64 bits)

**Comment by toddtarsi** [comment]
Works in latest (v4)
