### ISSUE TITLE
Selenium-side-runner For Test fails

### ISSUE THREAD

**Issue by ykthinkbig** [SeleniumHQ/selenium-ide#673]
## 🐛 Bug Report

Hello, Presently I keep getting an error whenever I tried to run my test suites in my terminal. Thou all my test suites runs successfully on the Selenium IDE.

## To Reproduce

Steps to reproduce the behaviour:
 presently created and saved my first project as bloom.side. 
-> I have installed the following on my MAC PC:
>> node.js
>> selenium-side-runner, 
>> chromedriver. 

Then In my Terminal, ran selenium-side-runner [path to side], and got the following output:
Input:
ibironke $ selenium-side-runner /Users/ibironke/Downloads/Automation_Test/Bloom.side
Output:
 ```info:    Running /Users/ibironke/Downloads/TESTIFY/Automation_Test/Bloom.side
 FAIL  Bloom/bloom_login_valid.test.js
  ● Test suite failed to run

    ReferenceError: Cannot access 'chrome' before initialization

      at Object.<anonymous> (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:1:1)
      at Object.<anonymous> (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:7:26)

 FAIL  Bloom/bloom_login_invalid.test.js
  ● Test suite failed to run

    ReferenceError: Cannot access 'chrome' before initialization

      at Object.<anonymous> (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:1:1)
      at Object.<anonymous> (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:7:26)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.326s
Ran all test suites.
```
## Expected behaviour

Once I run it, i expect all the test cases in my test suites should run successfully just as it does on the selenium IDE.

## Project file reproducing this issue (highly encouraged)

Project file URL to reproduces this issue: https://github.com/ykthinkbig/Test-Automation-University/blob/master/Bloom.side

## Environment

OS: macOD Mojave Version 10.14.4 (18E227)
Selenium IDE Version: 3.6.1 (Chrome add-on)
Selenium SIDE Runner Version: 3.6.1
Node version: 12.1.0
Browser Version: Chrome 4.0.3729.131 (64-bit)

**Comment by nmklong** [comment]
I have the same issue as well. I know it has something to do with the speed of the side runner, it's too fast and there's no way to set the speed when executing the side runner, usually to fix it, i will have to add 'wait for element' or implicit pause, but what i would expect is the consistency between the Selenium IDE and the side runner, tests would past on Selenium IDE but fail in the side runner

**Comment by ykthinkbig** [comment]
@nmklong Do you think adding a wait for element function will solve the issue? If yes, where do I add it?

**Comment by nmklong** [comment]
@ykthinkbig i just took a look at the output of your error, i had the same error message but with firefox, and it was because i didn't have firefox installed, in your case you said you already ran it on Selenium IDE, so i assume you already have Chrome installed?

**Comment by tourdedave** [comment]
That's a real head scratcher. Haven't seen this error message before.

A couple of things to confirm:
- The installation of Chrome is in the standard location (e.g., Applications directory)
- ChromeDriver is accessible from the path (e.g., run `chromedriver --version` from the terminal and let me know the result)

If these were out of line then you should have received a helpful error message so I'm assuming these aren't the problem but wanted to double-check.

Did you use `sudo` when installing anything from the command-line? It's possible it could be a permissions issue.

**Comment by ykthinkbig** [comment]
On my terminal, 

- I changed directory to Applications with cd /Applications. 

- On cd /Applications directory, I run chromedriver --version, output = [ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) ]

- I also used sudo, but still getting the same issue.

**Comment by corevo** [comment]
Don't put `chromedriver` in `/Applications` put it in your `PATH`, to find a directory that belongs to the `PATH` run `env | grep PATH`.

**Comment by corevo** [comment]
If you're using mac you should try [brew](https://brew.sh/) it's the easiest way to install chromedriver.

**Comment by tourdedave** [comment]
@ykthinkbig Were you able to get it working?

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity. If you're still having this issue, please let us know.
