### ISSUE TITLE
"run script" command does not work when running via selenium-side-runner

### ISSUE THREAD

**Issue by rebrov44** [SeleniumHQ/selenium-ide#675]
## 🐛 Bug Report

Javascript placed in value for command "run script" is not execute through selenium-sdie-runner

## To Reproduce

Run project from this issue through selenium-side-runner

## Project file reproducing this issue (highly encouraged)

{
  "id": "07b92297-1958-44a6-b85b-abff8436b489",
  "version": "2.0",
  "name": "test",
  "url": "https://google.com",
  "tests": [{
    "id": "bf023501-42fa-463b-ae52-42f51856c703",
    "name": "test",
    "commands": [{
      "id": "23ec79b9-8f48-4df8-b1f8-d68826cd2507",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "45db63f8-e949-4a12-8c4c-4460c95f1704",
      "comment": "",
      "command": "runScript",
      "target": "name=q",
      "targets": [],
      "value": "javascript{alert('test');}"
    }]
  }],
  "suites": [{
    "id": "5ec02398-6e73-42e5-891c-d9acfe43163f",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["bf023501-42fa-463b-ae52-42f51856c703"]
  }],
  "urls": ["https://google.com/"],
  "plugins": []
}

## Environment

OS:  Windows 10 
Selenium IDE Version:  3.6.0 
Selenium SIDE Runner Version:  3.5.3

Node version: 10.15.1

Browser:
Browser Version:  70.0.3538.67 (64-bit) (Chrome Driver)

**Comment by corevo** [comment]
Can you post the logs from CMD as well?  
Also try using `execute script`, `run script` is a compatibility solution and you should move, if possible to `execute script`.

**Comment by rebrov44** [comment]
I tried the "execute script", it still works in Selenium IDE and does not work in selenium-side-runner

There are no any logs, script runs further and falls in next step (after the "execute script")

**Comment by corevo** [comment]
I see the issue, you are misusing the commands the API is as follows:  
`execute script | alert()`  
This works in the IDE due to a bug, the `javascript{}` tag will also go away in a (near) future release of the IDE, so I suggest replacing it with correct usage of `execute script`.  

Please next time view the official [documentation](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#execute-script) regarding command usage.
