### ISSUE TITLE
POM Locators

### ISSUE THREAD

**Issue by hchiam** [SeleniumHQ/selenium-ide#676]
## 🚀 Feature Proposal

Be able to reference POM for use as locators.

## Motivation

I love how easy it is to get tests set up and running. It took me seconds to figure out loops, ifs, and delays. However, my team really wants to use POM for long term maintainability.

## Example
* I would be able to import a POM file (either as Java or maybe as a simple UI generated from nested JSON).
* Then, instead of just `xpath=//div[...` or `css=...`, there would also be the option to type in `pom=...`.

**Comment by corevo** [comment]
This falls under #104
