### ISSUE TITLE
Hi Team, Is there any way to integrate Selenium IDE plugin in web application.

### ISSUE THREAD

**Issue by savtambe** [SeleniumHQ/selenium-ide#679]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by tourdedave** [comment]
Please follow the issue template and provide more detail with your request.

Closing.
