### ISSUE TITLE
Command plugin "waiting to start" in Chrome

### ISSUE THREAD

**Issue by ChrisLMerrill** [SeleniumHQ/selenium-ide#680]
## 🐛 Bug Report

I have a SeleniumIDE plugin that works fine as a Firefox extension, but in Chrome, it prevents tests from running. Specifically, the status bar in SeleniumIDE/Chrome says:

"Preparing plugins for test run..." 
which takes several seconds and then
"Waiting for {myplugin} to start {spinner}"
and then it just hangs there.

I think I've been through all the plugin docs and don't see any startup event that a plugin should be responding to. What am I missing?

I've dropped a breakpoint in my onMessageExternal and I see the project-open and playback-started events. In both cases, my plugin just returns. Do I need to respond to those events in some way when running in Chrome?

```
browser.runtime.onMessageExternal.addListener((message,sender,sendResponse) => {
    if (message.action === "execute" && message.command) {
        const command = message.command.command;
        const target = message.command.target;
        if (command === "wp_start_timer") {
            console.log("Start timer " + target);
            timers[target] = Date.now();
            return sendResponse(true);
        }
        else if (command === "wp_end_timer") {
            const duration = Date.now() - timers[target];
            console.log("End timer " + target + ":" + duration);
            store.dispatch({type: "finish-measurement", payload:{testid:message.options.testId,runid:message.options.runId,name:target,duration:duration}});
            return sendResponse(true);
        }
        return sendResponse({error:"Mesaurements plugin received unknown command:" + command,status:"fatal"});
    }
});
```

Any advice is much appreciated!  TIA.

## Environment

OS: Windows 10
Selenium IDE Version:  3.7.0
Browser: Chrome
Browser Version: 74.0.3729.131 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
If your plugin returns nothing, it needs to return `undefined`. This could lead to the behavior you're describing. I don't see this in the docs either. I'll be sure to get that updated.

**Comment by ChrisLMerrill** [comment]
I tried returning undefined for anything other than my two commands, but there was no change in the behavior. New version of the external message listener is:

```
browser.runtime.onMessageExternal.addListener((message,sender,sendResponse) => {
    if (message.action === "execute" && message.command) {
        console.log("received command: " + message.command.command);
        const command = message.command.command;
        const target = message.command.target;
        if (command === "wp_start_timer") {
            console.log("Start timer " + target);
            timers[target] = Date.now();
            return sendResponse(true);
        }
        else if (command === "wp_end_timer") {
            const duration = Date.now() - timers[target];
            console.log("End timer " + target + ":" + duration);
            store.dispatch({type: "finish-measurement", payload:{testid:message.options.testId,runid:message.options.runId,name:target,duration:duration}});
            return sendResponse(true);
        }
        return sendResponse({error:"Measurements plugin received unknown command:" + command,status:"fatal"});
    }
    else if (message.action === 'event' && message.event)
        console.log('received event: ' + message.event);
    return undefined;
});
```

Any other suggestions for where I should look?  If not, then I'll try to boil down the code a bit and post a full example. I'm probably just doing something stupid somewhere else.

TIA!

**Comment by ChrisLMerrill** [comment]
I tried returning undefined for anything other than my two commands, but there was no change in the behavior. New version of the external message listener is:

```
browser.runtime.onMessageExternal.addListener((message,sender,sendResponse) => {
    if (message.action === "execute" && message.command) {
        console.log("received command: " + message.command.command);
        const command = message.command.command;
        const target = message.command.target;
        if (command === "wp_start_timer") {
            console.log("Start timer " + target);
            timers[target] = Date.now();
            return sendResponse(true);
        }
        else if (command === "wp_end_timer") {
            const duration = Date.now() - timers[target];
            console.log("End timer " + target + ":" + duration);
            store.dispatch({type: "finish-measurement", payload:{testid:message.options.testId,runid:message.options.runId,name:target,duration:duration}});
            return sendResponse(true);
        }
        return sendResponse({error:"Measurements plugin received unknown command:" + command,status:"fatal"});
    }
    else if (message.action === 'event' && message.event)
        console.log('received event: ' + message.event);
    return undefined;
});
```

Any other suggestions for where I should look?  If not, then I'll try to boil down the code a bit and post a full example. I'm probably just doing something stupid somewhere else.

TIA!

**Comment by tourdedave** [comment]
Try `sendResponse(undefined)` instead of just returning undefined.

**Comment by ChrisLMerrill** [comment]
Thanks!  That does seem kinda obvious now that you've pointed it out. 

It doesn't look like the docs are in GitHub...so should I open a new issue here for updating the examples?

**Comment by tourdedave** [comment]
You're welcome!

I updated the docs yesterday to cover this use case ([link](https://www.seleniumhq.org/selenium-ide/docs/en/plugins/ide-events/#edge-cases-when-responding-to-events)).

But for future reference, the docs are in GitHub ([link](https://github.com/SeleniumHQ/selenium-ide/tree/v3/docs)).
