### ISSUE TITLE
Issues While Building Locally

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#681]
ERROR in ./src/content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (D:\selenium-ide-3\packages\selenium-ide\node_modules\closure-loader\index.js:114:19)
    at D:\selenium-ide-3\packages\selenium-ide\node_modules\closure-loader\index.js:48:22

**Comment by tourdedave** [comment]
You need to build following the `v3` instructions ([link](https://github.com/SeleniumHQ/selenium-ide/tree/v3)). Make sure you are able to successfully run `peru sync`.

**Comment by corevo** [comment]
Also please make sure to follow the issue template, if you'd told us what OS you are using, and the reproducing steps (what things you ran in the command line), the we would easily be able to help you and resolve the issue.

**Comment by vinay95garg** [comment]
> Also please make sure to follow the issue template, if you'd told us what OS you are using, and the reproducing steps (what things you ran in the command line), the we would easily be able to help you and resolve the issue.

I was runnung on windows environment (8.1)  installed using yarn-install all the dependencies where code-export was not found under npm registry and browser webdriver package has been updated to 3.6.0-aplha-0.These were fixed but error i was getting in src/polyfills.ts closure dependency bot it was raised because of record.js and command/api.js which were using them.

**Comment by corevo** [comment]
Building on Windows is currently not supported, and it is outlined in the instructions that are linked, as we move to the new version of Selenium IDE, we will make sure that building on Windows is possible.  

Please in the future follow the issue template when submitting, so we can help you faster and save both ends time.

**Comment by vinay95garg** [comment]
> Building on Windows is currently not supported, and it is outlined in the instructions that are linked, as we move to the new version of Selenium IDE, we will make sure that building on Windows is possible.
> 
> Please in the future follow the issue template when submitting, so we can help you faster and save both ends time.

i tried running same on ubuntu as well but was getting same error .ERROR in ./src/closure-polyfill.js

**Comment by tourdedave** [comment]
If that's the case, then please open a new issue for it, following the issue template.
