### ISSUE TITLE
runId  How to generate

### ISSUE THREAD

**Issue by 520promise** [SeleniumHQ/selenium-ide#684]
## 🚀 Feature Proposal

selenium-ide 

It is not possible to add values in batches. There are a lot of duplicate values that need to be added manually. The efficiency is too slow. Runid is also generated randomly. I'm not sure how runid is generated.

## Motivation

Reduce workload

## Example

For example, when searching for different things, the action is the same and only the replacement value is needed.

**Comment by corevo** [comment]
I'm sorry but I don't understand, can you please elaborate?

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
