### ISSUE TITLE
How to run project locally without making it as a extension? It is build successfully and working fine if added as extension. Is there any way to debug it in a normal browser without making it is a extension.

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#687]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
