### ISSUE TITLE
Code Export - Unable to add new export item

### ISSUE THREAD

**Issue by stebli** [SeleniumHQ/selenium-ide#689]
## 🐛 Bug Report

Defect Created as per request from @tourdedave in issue https://github.com/SeleniumHQ/selenium-ide/issues/592

We are attempting to add a new export item in the code export functionality. I have followed the guide however this has failed. There seems to be further unknown dependancies which have not been catered for. 

## To Reproduce

Follow the guide, attempt to get a new item in the list for code export. 

## Expected behavior

The new item is added and when exporting the output file contains the changed/new code.

## Project file reproducing this issue (highly encouraged)

Any .side file can be used. 

## Environment

OS: OSX
Selenium IDE Version:  V3 branch
Selenium SIDE Runner Version:  V3 branch
Node version: 12.1

Browser: Chrome
Browser Version: 74

**Comment by tourdedave** [comment]
`yarn build:ext:prod` builds a production ready version of the extension and runs just once (unless you pass the `-w` flag). It takes a long time to complete and does a lot of things that aren't necessary for daily development.

You're better off using `yarn watch`. Try that and confirm that you've saved your changes to `code-export/src/index.js`.

**Comment by stebli** [comment]
interesting change using watch... 

i now see this output ...

 Module not found: Error: Can't resolve 'code-export-new-java' in '/Users/xxx/projects/SeleniumIDE/selenium-ide/packages/code-export/dist'

Seems the dist file needs to change too?

**Comment by tourdedave** [comment]
What happens when you run just `yarn`? This should resolve the dependency. Then you can run `yarn watch` to pick up everything.

**Comment by stebli** [comment]
progress is made. :) 

So yarn installed a single missing dependency. Strange as ive run this before. The result now when i open the plugin in chrome is the ide opens with a "seed project" loaded.

Attempting to export shows the new item in the list, Excellent 👍 

Clicking export however doesnt do anything when I select the new item in the list. There are also no plugin errors listed. Default java export still works and downloads a file, the new item however does not.

**Comment by tourdedave** [comment]
Okay. Is your new language export just a copy of the existing java-junit one?

Try opening the developer console in the IDE (e.g., right-click & inspect). It should show an error in the console when you click to export for your language.

**Comment by stebli** [comment]
ah biscuit. Nice. sorted out the issue. 

Resolved. Thanks @tourdedave This issue can be closed. To summarise...

1) additional step for dependancies
2) Rerun of yarn command( for some odd reason didnt pull down a single dep)
3) Third issue was my mistake, typo, resolved and tested with successful export.

**Comment by tourdedave** [comment]
Great!
