### ISSUE TITLE
There is error in main browser and not working IDE.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#69]
After merging with 'use-atoms', selenium ide was not working normally.
I did "peru sync" by waiting a long time.

Browser has error like this.

![image](https://user-images.githubusercontent.com/33743343/34198712-b0a4d0b6-e5ae-11e7-91a5-e96239017bc0.png)

How can I fix it?

**Comment by corevo** [comment]
Does `webpack` exit with no errors?  
It seems that either `peru sync` fails, or you did not merge with the correct commit, can you also post your base SHA?

**Comment by Jongkeun** [comment]
webpack had no errors.
I was using the lastest master code.
sha-1 is "7e4a8d81cea225797e71205c6935295a2466456f"
I have checked  almost branches by building(`webpack`).

I will try to do` peru sync` again.

**Comment by Jongkeun** [comment]
I Failed to remove the errors.....
Let me show your `npm ls --depth=0` and `npm ls -g --depth=0`?
I've been trying.

**Comment by corevo** [comment]
[yarn list --depth=0](https://github.com/SeleniumHQ/selenium-ide/files/1579060/deps.txt)  
Everything is installed locally on my machine

**Comment by Jongkeun** [comment]
my Development environment is windows 10 64 bit.
Is it influence on this situation?

**Comment by Jongkeun** [comment]
I did a test in Ubuntu.
And it is fine. 
Could you try to do  in Windows?
It is normal to compile from Linux and run from Windows.
I would working in linux.

**Comment by corevo** [comment]
Building in macOS works on a Windows machine.  
The problem you see is when you specifically build it on Windows?

**Comment by Jongkeun** [comment]
Yes, just if I see my situation.
The build result file is different like injector.js.
I think the reason why the situation is  happening is the error that I commented.

And welcome back.😢

**Comment by corevo** [comment]
Alright, I think the issue is because of incompatibility of `peru` with Windows.  
I'll look further into it, but if so, I won't fix it, because when [5204](https://github.com/SeleniumHQ/selenium/pull/5204) is merged `peru` won't be necessary anymore.

**Comment by Jongkeun** [comment]
yes I will close this issue.
