### ISSUE TITLE
Selenium IDE 3.5.0 add-on does not work on FireFox ESR 52.9.0 (32-bit).  

### ISSUE THREAD

**Issue by YongChenSciex** [SeleniumHQ/selenium-ide#692]
## 🐛 Bug Report

Selenium IDE 3.5.0 add-on does not work on FireFox ESR 52.9.0 (32-bit).  
The error message says: 
Could not start recording. 
i.default.webNavigation.onCreatedNavigationTarget is undefined

For some reason (NPAPI or Java applet support), we have to use FireFox ESR 52.9.0 (32-bit). The only Selenium IDE add-on available to download is V3.5.0.

Related URLs:
https://archive.mozilla.org/pub/firefox/releases/52.9.0esr/win32/en-US/
https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/versions/
https://addons.mozilla.org/firefox/downloads/file/1279666/selenium_ide-3.5.0-fx.xpi

## To Reproduce
1. Download and install FireFox ESR 52.9.0 (32-bit).
2. Install Selenium IDE add-on V3.5.0
3. Start add-on, and "Record a new test in a new project"
4. Use any base URL, like: https://www.google.com/, then start recording
5. Get error: i.default.webNavigation.onCreatedNavigationTarget is undefined

## Environment
OS: Windows 10
Selenium IDE Version:  3.5.0
Browser: FireFox ESR
Browser Version: 52.9.0 (32-bit)

**Comment by tourdedave** [comment]
Selenium IDE only works in Firefox 56 and up. If you want to use Selenium IDE with an older version of Firefox then you'll need to look into downloading the legacy IDE, which is no longer supported ([link](https://www.seleniumhq.org/selenium-ide/legacy/)).

**Comment by YongChenSciex** [comment]
FireFox ESR 52.9.0 (32-bit) is the latest version that supports NPAPI.  Selenium IDE V3.5.0 is the latest version that claims to be working on FireFox ESR 52.9.0, but unfortunately it does not work.

**Comment by corevo** [comment]
It is an oversight on our part, selenium IDE requires Firefox 56, we will update the release Metadata accordingly.

Cheers,
Tomer

**Comment by YongChenSciex** [comment]
May I ask what may work with FireFox 52?

**Comment by 98gmarquee** [comment]
> 
> 
> May I ask what may work with FireFox 52?

Not sure about 52, but I still use the legacy ide with FF 54.0.1 daily. I only use that version of FF for work testing and nothing else. I used portableapps.com to install 4 or 5 profiles/installs of 54.0.1 so I could run things concurrently without tripping over cache.
