### ISSUE TITLE
Create How To Plug In video for a ‘Clear Cache’ keyword

### ISSUE THREAD

**Issue by darkartswizard** [SeleniumHQ/selenium-ide#695]
## 🚀 Feature Proposal
Would someone consider creating a brief ‘Clear Browser Cache’ How To Demo video to show off the power of Selenium IDE PlugIn feature?

## Motivation

I’m not asking others to do work for me. 
I’m an admitted Selenium IDE JavaScript noob looking for a real world starting point.

I’ve watched Dave’s video on Plugins, but could use a little more in depth tutorial. If I weren't a total JavaScript / Selenium IDE noob at this I would do it myself, and will do some videos in the future. Just need a little bit more guidance to get rolling.

## Example

‘How to add a ‘Clear Cache’ keyword feature to SE IDE using calls to Selenium JavaScript calls’ Getting Started video.

**Comment by corevo** [comment]
We'll take it under consideration to improve our getting started webpage, for plugin creation and the sort.  
Currently we are putting less effort as there are other areas in documentation that require more attention and are more immediate to users (e.g. basic usage etc).

**Comment by darkartswizard** [comment]
Cool. More documentation would be awesome.
