### ISSUE TITLE
Getting error while installing Selenium IDE extension manually

### ISSUE THREAD

**Issue by savtambe** [SeleniumHQ/selenium-ide#696]
## 🐛 Bug Report

Getting error while installing Selenium IDE extension manually

Error Description: 
Failed to load extension
File: D:\selenium-ide-3\packages\selenium-ide\src
Error: Cannot load extension with file or directory name __test__. Filenames starting with "_" are reserved for use by the system.
Could not load manifest.

## To Reproduce
1. Download Selenium IDE from: https://github.com/SeleniumHQ/selenium-ide/tree/v3
2. Go to chrome://extensions/ and check the box for Developer mode in the top right.
3. Locate the ZIP file on your computer and unzip it.
4. Go back to the chrome://extensions/ page and click the Load unpacked extension button and select the unzipped folder having manifest in it. 
Path: D:\selenium-ide-3\packages\selenium-ide\src

## Expected behavior
Selenium IDE should be added in Chrome 

## Environment
OS: Windows 10
Selenium IDE Version:  3.7.4
Browser:
Chrome: 73

**Comment by tourdedave** [comment]
To install it manually, you can either:

1. Use a release build (e.g., `selenium-ide.zip` from [the latest release](https://github.com/SeleniumHQ/selenium-ide/releases/latest))

2. Build the project and load the contents of the build directory (e.g., see [the v3 readme](https://github.com/SeleniumHQ/selenium-ide/tree/v3#building))

**Comment by savtambe** [comment]
thank you so much tourdedave.

**Comment by savtambe** [comment]
Hi tourdedave,

Is there any way to integrate Selenium IDE with web application and launch it on button click, instead of using it as a chrome extension.

I am creating web based Selenium framework, providing feature to record user journeys using Selenium recorder through web based interface.

Thanks in advance.

**Comment by tourdedave** [comment]
Right now it's not possible. But you can open a [new feature request issue](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=feature.md) to open the discussion for it.
