### ISSUE TITLE
It will start a new firefox for each test cases of testsuite when I try to playback it on IDE

### ISSUE THREAD

**Issue by JackJiaJJ** [SeleniumHQ/selenium-ide#703]
## 🐛 Bug Report

I recorded an script and then I structure it to testsuite format, when I try to playback it on IDE, it will start a new firefox for each test cases of testsuite

## To Reproduce

a. record a testcase
b. structure it to testsuite 
c. try to playback this testsuite on IDE
d. it will start a new firefox for each testcase and it would end the previous firefox, and the playback failed at the second testcase since the newly started firefox doesn't include url

## Expected behavior

It should playback the whole testsuite successfully

## Project file reproducing this issue (highly encouraged)

{
  "id": "2fd365a7-ab52-41cf-8ced-2a6961d3f8dd",
  "version": "2.0",
  "name": "linux-test",
  "url": "https://cn.bing.com",
  "tests": [{
    "id": "6449b7df-3667-4386-a5ae-5639bbeb942e",
    "name": "step-1-login",
    "commands": [{
      "id": "25ef67e3-f676-4174-9aaa-dbf1bf472a1c",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "3ab4e378-1823-4be0-8c8b-4908487f595a",
      "comment": "",
      "command": "type",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "linux"
    }, {
      "id": "34ff5851-8d78-46ef-8fc2-0705f1f564a2",
      "comment": "",
      "command": "sendKeys",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "${KEY_ENTER}"
    }]
  }, {
    "id": "e0a237b5-9661-4353-be07-9945d61ea78c",
    "name": "step-3-images",
    "commands": [{
      "id": "873d8577-51df-4ebd-ad17-af16bcda38fc",
      "comment": "",
      "command": "click",
      "target": "xpath=//a[contains(text(),'Images')]",
      "targets": [
        ["linkText=Images", "linkText"],
        ["css=.b_scopebar li:nth-child(2) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Images')]", "xpath:link"],
        ["xpath=//header[@id='b_header']/nav/ul/li[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/images/search?q=linux&FORM=HDRSC2')]", "xpath:href"],
        ["xpath=//li[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Images')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "4f780369-38fb-4166-940a-da47f1225ef3",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "144d1dd2-ccf7-4933-99b3-3d9f20573b03",
    "name": "step-2-video",
    "commands": [{
      "id": "5477eed0-e8e2-433f-8803-009fde7dad59",
      "comment": "",
      "command": "pause",
      "target": "5000",
      "targets": [],
      "value": ""
    }, {
      "id": "b2d36c61-192d-4449-9e3b-1bc618bf29bb",
      "comment": "",
      "command": "click",
      "target": "xpath=//a[contains(text(),'Videos')]",
      "targets": [
        ["linkText=Videos", "linkText"],
        ["css=.b_scopebar li:nth-child(3) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Videos')]", "xpath:link"],
        ["xpath=//header[@id='b_header']/nav/ul/li[3]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/videos/search?q=linux&FORM=HDRSC3')]", "xpath:href"],
        ["xpath=//li[3]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Videos')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "0d1b364d-7c45-471c-9bc5-9a54c8f1ff18",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["6449b7df-3667-4386-a5ae-5639bbeb942e", "144d1dd2-ccf7-4933-99b3-3d9f20573b03", "e0a237b5-9661-4353-be07-9945d61ea78c"]
  }],
  "urls": ["https://cn.bing.com/"],
  "plugins": []
}

## Environment

OS: Windows 7
Selenium IDE Version:  3.7.4
Selenium SIDE Runner Version: not used, I don't know
Node version: not using selenium-side-runner

Browser: Firefox
Browser Version: 60.6.1 ESR (64-bit)

**Comment by JackJiaJJ** [comment]
![screenshot-error](https://user-images.githubusercontent.com/39511725/58160090-52fe5a00-7cb0-11e9-9d75-24f33fc7e62d.png)

**Comment by corevo** [comment]
This is the expected behavior, each test runs in its own context, if you'd like to share the context use the [run](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#run) command to execute them within the same test.

**Comment by JackJiaJJ** [comment]
@corevo , hi Tomer, I have two questions about it:

1. from which version of IDE starts working as this behavior ?

2. IDE will keep this behavior afterwards ?

Thanks a lot !

**Comment by corevo** [comment]
1. I do not remember
2. Yes this is the intended behavior, each test will use it's own browser

But again you can use the `run` command to achieve this behavior, this is exactly what it is meant for.

**Comment by JackJiaJJ** [comment]
@corevo , thanks for your explanation ! I am looking forward to this new function !
