### ISSUE TITLE
Chrome confirmation popup window is not closed when test runs in Selenium IDE

### ISSUE THREAD

**Issue by MaryQ** [SeleniumHQ/selenium-ide#705]
## 🐛 Bug Report
'choose ok on next confirmation' and 'webdriver choose ok on visible confirmation' commands are not worked with chrome confirmation popup windows ,when test is run in Selenium IDE.

## To Reproduce
1. Run test 1 by clicking on 'Run current test' in Selenium IDE
2. Test is freezing on '6. click on id=brand-logo' step. Chrome confirmation popup window is opened in browser. But this window can not be opened before clicking on element with 'id=brand-logo'. 'choose ok on next confirmation' and 'webdriver choose ok on visible confirmation' commands are presented in test, but non from them doesn't close popup window.

## Project file reproducing this issue
[1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3207783/1.zip)

## Environment
OS: Windows 10
Selenium IDE Version: 3.7.4
Selenium SIDE Runner Version: 3.7.4
Node version: npm: 6.7.0
Browser: Chrome 74.0.3729.157

**Comment by corevo** [comment]
Did Selenium IDE record this interaction?  
The page shows a [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload), this is not a **confirmation dialog** and thus `choose ok on next confirmation` doesn't work.  

I'll have to refer to the w3c spec to see if there is information about `onbeforeunload` dialogs, but I need to know if Selenium IDE recorded this, because if it did then it is a bug in the recording.

**Comment by MaryQ** [comment]
No, this test wasn't recorded.

Following test I recorded in Selenium IDE - [1Recorded.zip](https://github.com/SeleniumHQ/selenium-ide/files/3208081/1Recorded.zip). I ran it in Selenium IDE and it doesn't finished too.

'choose ok on next confirmation' and 'webdriver choose ok on visible confirmation' works with such dialog window if test is run in command line.

**Comment by tourdedave** [comment]
The provided test file works for me on the latest version of Selenium IDE. Can you please try again and let us know if the problem still exists?

**Comment by Kirinfm** [comment]
> 
> ## 🐛 Bug Report
> 
> 'choose ok on next confirmation' and 'webdriver choose ok on visible confirmation' commands are not worked with chrome confirmation popup windows ,when test is run in Selenium IDE.
> ## To Reproduce
> 
>     1. Run test 1 by clicking on 'Run current test' in Selenium IDE
> 
>     2. Test is freezing on '6. click on id=brand-logo' step. Chrome confirmation popup window is opened in browser. But this window can not be opened before clicking on element with 'id=brand-logo'. 'choose ok on next confirmation' and 'webdriver choose ok on visible confirmation' commands are presented in test, but non from them doesn't close popup window.
> 
> 
> ## Project file reproducing this issue
> 
> [1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3207783/1.zip)
> ## Environment
> 
> OS: Windows 10
> Selenium IDE Version: 3.7.4
> Selenium SIDE Runner Version: 3.7.4
> Node version: npm: 6.7.0
> Browser: Chrome 74.0.3729.157

`choose ok on next confirmation` mens choose ok on **next confirmation**, move the `5 choose ok on next confirmation` before `4 click | xpath=//button[@id='externalUrlDialogOkButton'] `

[1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3304398/1.zip)
