### ISSUE TITLE
Support SideeX test suites/cases

### ISSUE THREAD

**Issue by umphy** [SeleniumHQ/selenium-ide#71]
Since the old Selenium IDE stopped working, I have started writing test cases using SideeX, from which this project started. I am thinking of migrating to this official IDE, but I can't open the test suites and cases that I have recorded using SideeX. Is this is a bug or will this be supported in the future?

Thanks for the hard work by the way.

**Comment by corevo** [comment]
Not currently, we have ditched the SideeX format, for a new better extensible format.  
And have kept support for the old format for legacy reasons.  
I'll leave this open, in case someone else would contribute, or in case I'll get to have the time to work on this.
