### ISSUE TITLE
chromeOptions.args with comma

### ISSUE THREAD

**Issue by vnerozin** [SeleniumHQ/selenium-ide#711]
Hi, Selenium Team!
I have question about passing chromeOptions.args to selenium-side-runner
```
selenium-side-runner -c "chromeOptions.args=[disable-infobars, headless]"
```
Is it possible to pass "window-position=0,0"? I tried chromeOptions.args=[window-position=0,0] and it did nothing. I feel that it is not parsed well since has comma?

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

**Comment by darkartswizard** [comment]
Tomer is right on following the process.

When you resubmit I’d be curious to know if 
     chromeOptions.args=[window-position=0, 0]
with comma space works. 
In that case an update in the documentation might be the easy fix.

**Comment by vnerozin** [comment]
I found other way to do what I want (more complex - using fluxbox). @darkartswizard  comma space does not work.

**Comment by darkartswizard** [comment]
I’d still repost.

It looks valid to me.
