### ISSUE TITLE
Values between concurrent runs?

### ISSUE THREAD

**Issue by jhardcastle-veroscreening** [SeleniumHQ/selenium-ide#713]
I am trying to use Selenium IDE for a smoke test, login, move around click a few buttons etc.

This all seems to work fine.

I'd like to get this running concurrently using Side Runner.

The problem I have is the login credentials can only be used one at a time, subsequent logins logout the previous..

I have found a way to store a complex array of 'LoginCredential' objects, which i can reference as an array and access UserName and Password properties.

What I need now is a global counter so that each Side Runner instance using the nth item.

How can this be done?

I tried defining a variable with global scope but its value is lost between runs.

Thanks

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

**Comment by jhardcastle-veroscreening** [comment]
By 'follow the template' do you mean use IRC or Slack?

I didn't spot that - but I also can't mine.. and alot of corporate environment block both of these. 

Does that mean I can't ask a question?

**Comment by corevo** [comment]
Follow the link to open a ticket for the correct issue.  

Of course you can ask questions, just use the right forum for it, this forum is strictly for issues.

**Comment by tourdedave** [comment]
To add more context -- the issue tracker or for us to track bugs and feature requests for the project. Asking questions is better suited elsewhere -- e.g., the Slack/IRC channel and selenium-users Google group. Are you able to post to the Google group?

**Comment by jhardcastle-veroscreening** [comment]
Sadly not.. I have raised this with Infrastructure.. but it may not change.
