### ISSUE TITLE
Trouble running Selenium IDE test using selenium side runner

### ISSUE THREAD

**Issue by ojake13** [SeleniumHQ/selenium-ide#714]
Good morning!

I have installed selenium IDE as an extension on Firefox, created a test suite and a test, and it is able to run through (on the GUI) and do exactly what I need it to do. However, when it comes to running the *.side file using selenium side runner on windows command prompt, I am given the following output:

`info:    Running C:/Users/admin/Documents/VRA_scoring.side
 FAIL  ./DefaultSuite.test.js (6.434s)
  Default Suite
    × VRAscores (2934ms)

  ● Default Suite › VRAscores

    InsecureCertificateError:

      at Object.throwDecodedError (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (../node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:468:26)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        7.298s
Ran all test suites.`

I know I have installed gecko web driver, npm, node, etc. The only thing I can think of is that maybe some of these files aren't installed in the correct system path? What exactly is the system path? It is never specifically mentioned in documentation.

I am also unable to run a simple 'hello.js' w/ console.log output on the command prompt, although I'm not sure if that relates. Any help is appreciated.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
