### ISSUE TITLE
Error Selenium side runner: UnsupportedOperationError: pointer movements relative to viewport are not supported in bridge mode

### ISSUE THREAD

**Issue by BB64BIT** [SeleniumHQ/selenium-ide#715]
Hi, I’m having some issues with test execution with Selenium side runner. 
I create test with Selenium IDE, I start them from IDE and they don’t give me back errors, but if I try to execute tests from Selenium side runner I find these errors: 

> UnsupportedOperationError: pointer movements relative to viewport are not supported in bridge mode
>       at executeLegacy (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/input.js:1129:17)
>       at Actions.perform (../../../../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/input.js:971:16

Can you help me? Thank you in advance. 

Best regards

**Comment by tourdedave** [comment]
Happy to help, but you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
