### ISSUE TITLE
Request: Complete example of selenium-side-runner --params flag.

### ISSUE THREAD

**Issue by curiositycasualty** [SeleniumHQ/selenium-ide#720]
I'm currently trying to execute a `.side` project I've created in version `3.8.1` of the Selenium IDE at the command line while passing parameters/variables.
<details><summary>My `.side`</summary>
<p>

```
{
  "id": "85fbff5c-9976-4ab7-8f67-20fd9fff8cfa",
  "version": "2.0",
  "name": "wat",
  "url": "",
  "tests": [{
    "id": "ec213ae6-ead0-4f58-b29a-40b3daebbe8a",
    "name": "wat",
    "commands": [{
      "id": "c2157572-72ff-465b-8165-fd29336c5268",
      "comment": "",
      "command": "store",
      "target": "original",
      "targets": [],
      "value": "input"
    }, {
      "id": "5dd9066d-2164-48ca-9280-40b753455597",
      "comment": "",
      "command": "echo",
      "target": "${input}",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "4405a0e6-440b-4469-abf6-3ccd33effeb9",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["ec213ae6-ead0-4f58-b29a-40b3daebbe8a"]
  }],
  "urls": ["https://google.com/"],
  "plugins": []
}
```

</p>
</details>

Nothing fancy, roughly:
  1. `store` | `original` | `input`
  1. `echo` | `${input}` |

Here's what I thought would get me what I want:
`selenium-side-runner echo.side --debug --params="input='wat'"`

But that doesn't seem to be doing the trick.

What is the proper use of `--params` and is there a complete code example somewhere that demonstrates both how to execute a `.side` project at the CLI using `selenium-side-runner`'s `--params` flag AND how to access `params` within that `.side` project's test suite(s)?

Thanks for your time in advance.

**Comment by tourdedave** [comment]
The opening sentence in [the params section of the docs for the runner](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#additional-params) states:

`Plugins for Selenium IDE can specify their own unique run-time parameters.`

This is a run-time option for plugins that extend Selenium IDE ([link](https://www.seleniumhq.org/selenium-ide/docs/en/plugins/plugins-getting-started/)). It's not for use as part of existing commands in Selenium IDE.

As of right now, there's no way to pass in information externally into test runs in the IDE. This will change when we move to a native app. We'll be able to pass information into test runs through environment variables.
