### ISSUE TITLE
Navigate-back actions are not recorded

### ISSUE THREAD

**Issue by PickHub** [SeleniumHQ/selenium-ide#722]
## 🐛 Bug Report

"Navigate back" back action are not recorded.

## To Reproduce
Record a test that involves navigating back in Chrome at some point.

## Expected behavior
When re-running the test, the navigate-back action should be executed as well.

## Project file reproducing this issue (highly encouraged)
Project file `.side` that reproduces this issue: https://we.tl/t-cWlbhFunLG 

## Environment
OS: OSX 10.14.4
Selenium IDE Version:  3.9.0
Browser: Chrome
Browser Version:  74.0.3729.169 (64 bit)

**Comment by corevo** [comment]
This depends on implementing `back` and `forward`, @tourdedave do you have the ticket for that?

**Comment by tourdedave** [comment]
Yeah, this is already tracked in #393.
