### ISSUE TITLE
Allow for longer Ajax wait period

### ISSUE THREAD

**Issue by nhwood** [SeleniumHQ/selenium-ide#724]
## 🚀 Feature Proposal

To allow the ability to specify a longer Ajax wait period than the default of 30000ms.

## Motivation

I am working to automate an Ajax-heavy application using selenium IDE. This application has Ajax calls that can take longer than 30 seconds, but the browser extension-based selenium IDE version does not seem to have a way to wait longer than 30000ms for these requests.

I am having a hard time working around getting the following errors on my steps:

```
waitForElementPresent on xpath=//some/xpath/value Failed: Ajax Wait timed out after 30000ms
```

## Example

If I could specify a longer timeout period (e.g. 120000ms) I would be able to use selenium IDE, but as it stands I am not sure I can workaround this issue.

**Comment by 98gmarquee** [comment]
Are you using the old ide or the newer one that works with chrome/firefox quantum (v57+)?

The old one let you define the wait time in the settings. 
![2019-0619-SelIDE2 9 1-WaitTimeSetting](https://user-images.githubusercontent.com/33339926/59781994-9bdf0980-9282-11e9-824c-27037b17cfa9.jpg)

The new one requires that you put a wait time in Value field for each command that is a "wait".
![2019-0619-SelIDE3 9 0-WaitTimeUsage](https://user-images.githubusercontent.com/33339926/59782019-aef1d980-9282-11e9-8e90-afc72c27fe1e.jpg)

**Comment by nhwood** [comment]
I am using the new web extension version for FF quantum+. I did use the wait for element visible, but it still seems to ajax timeout regardless of the value. Maybe it's a bug rather than a feature?

![image](https://user-images.githubusercontent.com/3833627/59783031-380e0e00-928d-11e9-9739-f4569aa6003c.png)

**Comment by tourdedave** [comment]
This looks like a bug. Please open [a bug report](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md) and follow the issue template.
