### ISSUE TITLE
Java and Python Export non-function

### ISSUE THREAD

**Issue by darkartswizard** [SeleniumHQ/selenium-ide#730]
## To Reproduce

Record a new script and save.

Right-click test and select Export

Export as Java Junit

Click export.

## Expected behavior

Expected Result: A File Save dialog appears.

Actual Result: No Dialog appears - no export can be 

## Environment

OS: Windows 10
Selenium IDE Version: 3.10.0
Selenium SIDE Runner Version:  N/A

Browser:
Browser Version: Chrome 74.0.3729.169
Firefox 67.0.2

**Comment by tourdedave** [comment]
Does this happen for any test, regardless of what was recorded?

**Comment by qtpmgrossman** [comment]
Whatever changes occurred in the last 15 minutes (Mocha Export + sans-Mocha Export) has appeared to resolve the issue. I saw the issue once 20 minutes ago when I opened an existing project, but it's no longer reproducible.
We can close Dave.

**Comment by tourdedave** [comment]
Okay, thanks!
