### ISSUE TITLE
Selenium IDE File upload "Node is not a file input element"

### ISSUE THREAD

**Issue by ASawyer504** [SeleniumHQ/selenium-ide#732]
I'm trying to upload a file but am getting {"code":-32000,"message":"Node is not a file input element"} even though the button I'm wanting to use opens a file upload window when pressed.

Command: type
Target: css=.ve-doc-attach
Value: T:\...\...\...\Document.txt

I've tried it with various other document types, but it still failed with error {"code":-32000,"message":"Node is not a file input element"}

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
