### ISSUE TITLE
Test Suites will not run all test cases

### ISSUE THREAD

**Issue by Thouxa** [SeleniumHQ/selenium-ide#74]
Test suites will only play the first test case. If I click the pause button and click again, it will play the next test case. Normally in Test suite, should'nt it play all test cases in the Suite?

**Comment by corevo** [comment]
Yes, it's a known bug that was fixed, it'll be included in the next release.

Cheers,
Tom

**Comment by Thouxa** [comment]
Awesome! Thanks!

**Comment by webmayak** [comment]
Waiting for release! Thanks!

**Comment by corevo** [comment]
Sorry for the late response, the fix is already out there
