### ISSUE TITLE
Code export doesn't provide error message for invalid commands

### ISSUE THREAD

**Issue by catalin-florescu** [SeleniumHQ/selenium-ide#742]
## To Reproduce

Record a new script and save.

Right-click test and select Export

Export as Java Junit (or Python/JavaScript)

Click export.

## Project file reproducing this issue (highly encouraged)

Expected Result: A File Save dialog appears.

Actual Result: No Dialog appears - no export can be

## Environment

OS: MacOS Mojave 10.14.5
Selenium IDE Version:  3.11.0 
Selenium SIDE Runner Version: N/A

Browser:
Browser Version: 75.0.3770.100 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
@catalin-florescu can you attach a SIDE project file that this happens with?

**Comment by catalin-florescu** [comment]
The side file code

`{
  "id": "9d0fc554-9227-4a97-af3a-39668cab02c8",
  "version": "2.0",
  "name": "instagram",
  "url": "",
  "tests": [{
    "id": "7df8e44b-32d5-400a-b98d-a21c11bd75a8",
    "name": "Instagram",
    "commands": [{
      "id": "bf93d252-3f8d-419b-96d0-dff1dbff18e5",
      "comment": "",
      "command": "open",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "24fa2679-27a4-4ef9-ad1e-ac8d91fa3f33",
      "comment": "",
      "command": "setWindowSize",
      "target": "",
      "targets": [],
      "value": ""
    }, {
      "id": "7bd8ec56-724a-4a60-a9a2-56c6b5ccac0b",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1185c3c6-d208-43ce-b8a3-7222b5dd179c",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["7df8e44b-32d5-400a-b98d-a21c11bd75a8"]
  }],
  "urls": [],
  "plugins": []
}`

**Comment by tourdedave** [comment]
You have an incomplete command -- `set window size`. You need to specify a resolution size in the target input (e.g., `1024x768`). I'll look into adding better error handling.

**Comment by catalin-florescu** [comment]
Nice! It works. Thanks! It will be better to show an error message when it can't export.

**Comment by tourdedave** [comment]
The fix is available now in v3.12.2 of the IDE.
