### ISSUE TITLE
Can't find closure dependency bot

### ISSUE THREAD

**Issue by J-HECQ** [SeleniumHQ/selenium-ide#744]
## 
Can't find closure dependency bot , bilud v3 throw error . please teller me this module where find. 
###  
 
 
ERROR in ./content/closure-polyfill.js
Module build failed: Error: Can't find closure dependency bot
    at replaceRequire (D:\dvlp\selenimu\selenium-ide-3\packages\sel
enium-ide\node_modules\closure-loader\index.js:114:19)
    at D:\dvlp\selenimu\selenium-ide-3\packages\selenium-ide\node_m
odules\closure-loader\index.js:48:22
    at tryCatcher (D:\dvlp\selenimu\selenium-ide-3\packages\seleniu
m-ide\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\dvlp\selenimu\selenium
-ide-3\packages\selenium-ide\node_modules\bluebird\js\release\promise.js:512:31)

    at Promise._settlePromise (D:\dvlp\selenimu\selenium-ide-3\pack
ages\selenium-ide\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\dvlp\selenimu\selenium-ide-3\pac
kages\selenium-ide\node_modules\bluebird\js\release\promise.js:614:10)

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
