### ISSUE TITLE
Code Export button not working 

### ISSUE THREAD

**Issue by jonesp100** [SeleniumHQ/selenium-ide#749]
## 🐛 Bug Report

The Export button, seems to be very inconsistent - works occasionally but for the most part clicking just has no effect.  I've tried closing IDE, restarting etc.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
