### ISSUE TITLE
Code Export button not working

### ISSUE THREAD

**Issue by jonesp100** [SeleniumHQ/selenium-ide#750]
## 🐛 Bug Report

**The Export button, seems to be very inconsistent - works occasionally but for the most part clicking just has no effect. I've tried closing IDE, restarting etc.**

## To Reproduce

Select 'Export' for any given test in IDE 
Select required language (I have tried all the available ones) 
Click 'Export'  and nothing happens 

**NOTE:**  I have noticed that on the attached SIDE file - some of the test work and some don't

Prod_smoke_Test 
Quote 
Claim3  - All Export as expected 

Student_card_Payment - Will not export 

## Expected behavior

Test is downloaded 

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.
[Regression_v1.2 - Copy.zip](https://github.com/SeleniumHQ/selenium-ide/files/3421284/Regression_v1.2.-.Copy.zip)

## Environment

OS:  Windows 10
Selenium IDE Version:  3.12.0
Browser Version: Chrome  75.0.3770.142 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
There's a known bug in code export that prevents error messages from showing in the IDE when there are invalid commands (e.g., issue #742).

In the test you referenced there is a locator that code export sees as invalid (e.g., command 62 uses `index =2`). If you remove the space it will work.

The other problem is that this locator appears to work in playback in the IDE, but it will break both in code export and in the command-line runner. This kind of disparity will go away once we move everything to playback on WebDriver.

**Comment by jonesp100** [comment]
Great that fixed! Thanks - Yes on the siderunner I noticed that it failed on that line - but I thought I fixed by changing the index to 0 - I must have deleted the space at the same time :)
Thanks again
