### ISSUE TITLE
I am not able to save the record in textng or other format.

### ISSUE THREAD

**Issue by ranjitnayak007** [SeleniumHQ/selenium-ide#756]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

How to save the record in textng or other format like firefox extension had?

**Comment by ranjitnayak007** [comment]
How to save the record in textng or other format like firefox extension had?

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
