### ISSUE TITLE
Record button bug and a fix

### ISSUE THREAD

**Issue by lepantella** [SeleniumHQ/selenium-ide#758]
I found a bug and a fix to a bug. When you press Start/Stop recording button multiple times and record the 'type' command for example, you get multiple type commands recorded instead of one. This is because event listener in the window.document was not killed properly.

In '/packages/side-recorder/src/content/recorder.js' just change this:
```
for (let i = 0; i < handlers.length; i++) {
  this.window.document.addEventListener(
    eventName,
    handlers[i].bind(this),
    capture
  )
  this.eventListeners[eventKey].push(handlers[i])
}
```
To this:
```
for (let i = 0; i < handlers.length; i++) {
  this.eventListeners[eventKey].push(handlers[i].bind(this))
  this.window.document.addEventListener(
    eventName,
    this.eventListeners[eventKey][i],
    capture
  )
}
```
This happens because `.bind(this)` changes the signature, so removeEventListener won't recognize properly which function to remove.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

If providing a fix, please do so as a PR.
