### ISSUE TITLE
How can we use one variable of one test to another test.

### ISSUE THREAD

**Issue by pabitra-itobuz** [SeleniumHQ/selenium-ide#764]
### How can we use one test data to another test file. For example:-

1. In "Create.side" file we are using variable call "user". -> I will create user call John
2. In "Edit.side" file we are editing the same user variable "user". -> I will edit user John.
3. So, how can we use the same variable to the different tests?

**Comment by corevo** [comment]
You can't share variables between projects, instead create two tests in the same `side` file and share the variables between them using the `run` command.
