### ISSUE TITLE
Export test to Python from Chrome calls webdriver.Firefox()

### ISSUE THREAD

**Issue by funkyswank** [SeleniumHQ/selenium-ide#767]
## 🐛 Bug Report

Exporting from the Chrome Selenium IDE to Python produces code that calls 
self.driver = webdriver.Firefox()
instead of 
self.driver = webdriver.Chrome()

## To Reproduce

Save a test from the Chrome version of the IDE and then export to Python.

## Expected behavior

Webdriver should be based on the browser used.

## Environment

OS:  Windows 10 
Selenium IDE Version:   3.12.0 
Browser: Chrome 
Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
The fix is available now in v3.12.2 of the IDE.
