### ISSUE TITLE
.side-format specification

### ISSUE THREAD

**Issue by JacoRuit** [SeleniumHQ/selenium-ide#77]
Is there any (final) specification of the .side-format available yet? I would like to write a small interpreter for the .side files.

**Comment by corevo** [comment]
I'm planning on adding a few backwards compatible changes (a few new keys at project level).  
Then I'll be naming it as version 1 of the .side format.

**Comment by beatngu13** [comment]
Any news regarding the `.side` format specification? I'm working on a test generator and I would like to create `.side`-based test suites/cases, so that I can use the Selenium IDE for playback, code export, etc.

**Comment by tourdedave** [comment]
A blog post would be great! We could cross-post it on [the new SIDE blog](https://www.seleniumhq.org/selenium-ide/blog/), just send us a canonical link.

**Comment by bcmoney** [comment]
@corevo & @tourdedave sorry for the delay, couldn't find much time between my home demands with kids, teaching engagement I've got going on now, and my regular 9-5 gig... but here's the example Durable Selectors annotation and SIDE parser in Java:
http://bcmoney-mobiletv.com/blog/2019/04/27/selenium-ide-side-parser-for-durable-selectors/

I hope it could be of some use to folks, especially as I saw that Java export capability is possibly going into the next SeleniumIDE release? Cheers and thanks again for everything you do on this project!

**Comment by beatngu13** [comment]
Is there a reason why this has been closed? If there is no specification yet, is there anything we as an OSS community can do to help?
