### ISSUE TITLE
Multiple file upload is failed

### ISSUE THREAD

**Issue by ros-mary** [SeleniumHQ/selenium-ide#776]
## 🐛 Bug Report

Multiple file upload was implemented by `type` command where `Value` field was filled with 2 paths to the files.

>  'Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.'

 error appears when test was run in Selenium IDE and 

> 'WebDriverError: invalid argument: File not found : C://1.json,C://2.json'

 error appears when test was run in command line using `selenium-side-runner`
## To Reproduce
1. Create test with multiple uploading file using this command `type | xpath_of_element | path_to_file1,path_to_file2`
2. Run the test in Selenium IDE
3. Run the test in command line using `selenium-side-runner`

## Expected behavior
I expected that fills will be uploaded without errors.

## Project file reproducing this issue

[1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3492247/1.zip)

## Environment

OS: Windows 10
Selenium IDE Version: 3.12.0
Selenium SIDE Runner Version: 3.12.1
Node version: npm: 6.7.0
Browser: Chrome 76.0.3809.100

**Comment by corevo** [comment]
Can you try it again but with a css based locator, another limitation that is [documented](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#type), is that xpath is not supported for file uploads.

**Comment by ros-mary** [comment]
I've changed command on `type | css=#filesToUpload | C://1.json,C://2.json` and it doesn't help. See [screenshot](https://monosnap.com/file/nEjngq9BsIdlZT4yS51vZ2HPklxZup)

**Comment by capoerafreak** [comment]
works for me without any problems.
[1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3493480/1.zip)
![Test](https://user-images.githubusercontent.com/36188654/62881640-82ad8300-bd30-11e9-84aa-81882a661245.PNG)

**Comment by ros-mary** [comment]
@capoerafreak it works! Thank you!
But when I ran it in command line 

> 'WebDriverError: invalid argument: File not found : C:\Users\User\Documents\1.json, C:\Users\User\Documents\2.json'

 error appears.
I use following command `selenium-side-runner -c "browserName=chrome chromeOptions.args=[allow-file-access-from-files]" 111.side`

**Comment by capoerafreak** [comment]
@ros-mary no Problem.
I don‘t use the command line runner, so i can‘t help you there ... 

@corveo: can take a Look?

**Comment by tourdedave** [comment]
You need to specify chromeOptions with the `goog:` vendor prefix.

This is updated in the docs, but hasn't been published to the site yet.

https://github.com/SeleniumHQ/selenium-ide/blob/v3/docs/introduction/command-line-runner.md#chrome-specific-capabilities

**Comment by ros-mary** [comment]
@tourdedave unfortunately, `goog:` prefix doesn't help. 
Here my [cmd log](https://monosnap.com/file/0tpgF6V1eeC7gMcfhGaUcT7fCDAh7j). 1.side file is run without error in Selenium IDE and here [ide log](https://monosnap.com/file/7Si3ERew7rSBvEKAOjFwdhBCZxZdbz). 
Additionally I've noticed that 'Oops! Something went wrong' page opens after files uploading, that doesn't happen when I upload files manually. See [video](https://monosnap.com/file/4puiI96fWQphb5VjrZmVzJj0QZ8KkV)

**Comment by tourdedave** [comment]
@ros-mary Please open a new issue for your problem with the runner and follow the provided template ([link](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md)).
