### ISSUE TITLE
Runner support for insecure certificates on Firefox

### ISSUE THREAD

**Issue by jphilip** [SeleniumHQ/selenium-ide#778]
## 🐛 Bug Report

When using the runner for tests on a staging server with a self-signed SSL certificate, I get an InsecureCertificateError, although I do not get the error for the same tests with Selenium IDE, or for runner with Chrome.
I suppose it has to do with the fact that Selenium IDE uses my Firefox profile where I have an exception for the URL. Not sure for Chrome.
I saw that geckodriver has capabilites to disable insecure certificate errors, but I could not find a way to set them from the .side.yml settings.

## To Reproduce

Steps to reproduce the behavior: Run a test on a https URL which uses a self signed certificate

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
You can set any capability available for firefox in the runner, if you're having a problem setting a capability, then post it here and we'll help you out.

**Comment by tourdedave** [comment]
I believe the capability is `acceptInsecureCerts`. It needs to be set to true. You can pass it with the `-c` capabilities flag in the runner. See the docs for details ([link](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/#run-time-configuration)).

**Comment by mandritac** [comment]
Hi,
I have a similar issue, my company uses self signed certificates in it's corporate proxy and naturally the selenium side runner is getting self signed certificate error. I created a .side.yml file as below -
capabilities:
  acceptInsecureCerts: true
  browserName: "firefox"

But when running the side runner I am getting error - InvalidArgumentError: acceptInsecureCerts is not boolean: "true".
Please help.
Thanks
Mandrita

**Comment by mandritac** [comment]
I have resolved the issue.
