### ISSUE TITLE
'pending' className is remained after click the stop button.

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#78]
Ordinary cases are normal.
But some cases were strange. 
For example, we can execute command by double clicking command.
But if the command can't execute, the command keeps trying until success.
Then there is a test case.

1. I executed a command that can't success.(I called this A command)
2. I execute other command that can't success too.(I called this B command)
3. Now we are waiting two commands. But These can't end.
4. So I stop B command. Then remove the stop button.
5. And I want to stop the A Command too. But There is not the button.

As far as I know, we can't execute multi command in current logic.
I hope to fixed it but I don't know your a road map yet whether You plan to possible to multi command or not.
I suggest some plans.
1. When someone clicked stop button, test table UI was returned to initialize state.
2. If `isPlaying` is true, can't execute new command.
3. Stop other commands when new command is execute.

Other opinion or road map if you have, tell me please.

**Comment by corevo** [comment]
As of version 3.1.0 stop will be graceful meaning, it won't terminate the test case execution, it'll wait until the current command finishes, and then terminates.  
It will make aborting slower, in case of a failed command it may take up to 30 seconds for it to eventually fail, but it is the safest way to do it.
