### ISSUE TITLE
Color disappears after subscript step (with run command)

### ISSUE THREAD

**Issue by nicodmf** [SeleniumHQ/selenium-ide#781]
## 🐛 Bug Report

Color disappears with subscript (with run command), not a the beginning but after return.

## To Reproduce

- create a test
- create a second test running the first
- launch second test

The color appear in the first step, in the child test after launch it, but disappears after return on the parent test.

## Expected behavior

Color are always visibles, in a simple test and in the parent test of a complex  test

## Project file reproducing this issue

https://raw.githubusercontent.com/ZephyrHQ/hippocampe-acceptance/6cadf49bf22b796271ef11ccf2957c7902a71460/tests/boutique-veterinaire.side

test **contact-envoi-valide**

## Environment

OS: linux
Selenium IDE Version:  3.12.0
Browser: Chromium
Browser Version: Version 73.0.3683.75

**Comment by tourdedave** [comment]
@nicodmf Sorry but I don't understand the problem you're describing. Can you attach a screenshot? Also, the project file you provided isn't something I can run. I'm unable to reach the URL in the test. It it publicly available?

**Comment by AutomatedTester** [comment]
Closing as no info returned
