### ISSUE TITLE
Default save uses extension ".txt" and subsequently fails to open the same file

### ISSUE THREAD

**Issue by gakudva** [SeleniumHQ/selenium-ide#790]
## 💥 Regression Report

A clear and concise description of what the regression is.

Since the last upgrade to version 3.12.0; Selenium IDE default save dialog uses ".txt" extension.  However, once saved - fails to open the file.  The error message is: "Error migrating project: Unknown file was received".  If you rename the file to ".side", all is well - and it works.

## Last working version

Worked up to version:
<3.12.0
Stopped working in version:
3.12.0
## To Reproduce

- Open an working test case
- Click on save
- Save dialog offers the save with ".txt" extension -> SAVE
- Open the saved file
- Error! Dialog

## Expected behavior
Either the save must save the file only as ".side" extension.  If it does save it in ".txt", it must also open what it saved.

## Environment

OS: Windows 10
Selenium IDE Version:  3.12.0

Browser:
Browser Version: Google Chrome 78.0.3895.0 (Official Build) canary (64-bit)

**Comment by corevo** [comment]
I have seen this issue before, the other guy fixed it by creating a new profile.

If you don't mind trying to open another profile, installing Selenium IDE and trying it there, I believe this is an issue with Chrome, rather than Selenium IDE.

**Comment by gakudva** [comment]
I can confirm that the problem goes away with new profile!  thanks a lot.
