### ISSUE TITLE
Issue with nested for each commands

### ISSUE THREAD

**Issue by greentalent** [SeleniumHQ/selenium-ide#792]
If you put "for each" in a "for each", only the first iteration of the nested for each will be performed despite having data.

## To Reproduce
[NestedForeach.zip](https://github.com/SeleniumHQ/selenium-ide/files/3562411/NestedForeach.zip)
I provided in the attached ZIP an example that console.log the issue.

## Expected behavior

It should log "Number" from 1 to 15 but it stops at 5.

## Environment

OS: Windows 10
Selenium IDE Version:  Latest in stores.
Browser: Latest Chrome and Latest Firefox tested

**Comment by DaveOoff** [comment]
Same for me. When looking at the javascript generated, the loop always use the variable "i", which is already used by the first loop

**Comment by DaveOoff** [comment]
Hey @tourdedave,

Any news on this issue ? If I can help, I'll be glad to do so.

I can't wait to use that new feature

**Comment by tourdedave** [comment]
I committed a fix for it yesterday. It will go out in today's release. I'll let you know when it's out.

**Comment by tourdedave** [comment]
The fix is available in v3.12.2 of the IDE.

**Comment by david-nowinski** [comment]
I've just updated to 3.12.2.
The issue is somewhat fixed, running the exact same example as provided in the first post, the IDE misses 2 loops in the foreach.
![Capture](https://user-images.githubusercontent.com/6048336/64238997-afa02080-ceff-11e9-9f95-eeb01b40c91a.PNG)

**Comment by tourdedave** [comment]
Ah, off by one. Nice catch.

**Comment by tourdedave** [comment]
The fix is available in `v3.12.3`.

**Comment by greentalent** [comment]
Perfect, the _for each_ is now a true warrior for testing purposes. Thank you for quick fix !

![image](https://user-images.githubusercontent.com/6048336/64246614-60f98300-cf0d-11e9-8dc9-ef639833a387.png)

**Comment by tourdedave** [comment]
You're welcome!

**Comment by DaveOoff** [comment]
Awesome ! Great work ! Thanks for this quick update :)
