### ISSUE TITLE
Increment value with the command "Execute Script"

### ISSUE THREAD

**Issue by DaveOoff** [SeleniumHQ/selenium-ide#795]
## 🐛 Bug Report

Hey guys,

I'm having an issue with the command "Execute script" to increment the value of a variable to +1. I've tried :

## To Reproduce

store | 0 | test
execute script | return ${test} + 1 | test

and it gives me back "01" with an "Echo" command.

## Expected behavior

Increment the value of test variable to +1.

## Project file reproducing this issue (highly encouraged)

[test.zip](https://github.com/SeleniumHQ/selenium-ide/files/3569569/test.zip)

## Environment

OS: Windows 10
Selenium IDE Version:  3.12.0
Browser: Chrome
Browser Version: 76.0.3809.132 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
`store` only gets you a string representation of the input ([link](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#store)).

So your script is just doing `"1" + 1`, which gets you `"11"`.

Right now, the best bet is to use `execute script` to store a number in a variable (e.g., `execute script | return 1 | test`).

**Comment by DaveOoff** [comment]
Thank for the reply.

So no way to increment value for now ?

**Comment by DaveOoff** [comment]
Just understand that the command "execute script" is the one to use to declare your "iterator" variable

Thanks !

**Comment by 98gmarquee** [comment]
You may have to initialize the variable before increment it. I can't recall, but I had this in my notes:
`!-- 
    storing variables and adding to them as math also changed
    if you do not first run execute script to store the value, it treats it as a char
-->

executeScript|return 1|rowNum
executeScript|return ${rowNum} + 1|rowNum



store|1|rowNum
executeScript|return ${rowNum} + 1|rowNum
`

**Comment by DaveOoff** [comment]
Awesome ! Great work ! Thanks for this quick update :)
