### ISSUE TITLE
Regarding disabling SSL certification(Trusted certificate) while executing test case in google chrome

### ISSUE THREAD

**Issue by manuelgeorge** [SeleniumHQ/selenium-ide#799]
Hi,
I'm doing sample testing of a website,
Most of the time ,it is asking for certification check and there is a manual intervention of clicking 'Proceed ' for most of the urls aka testcase.
I would like to skip this step and proceed with the execution.
Please let me know if there is any command to skip this step only for the test case.
Note: I don't have admn rights in chrome.
Please help me in resolving the same
Regards,
Manuel
![Capture](https://user-images.githubusercontent.com/37527938/64470419-697ed300-d132-11e9-9417-dc0cd4aa174b.PNG)

**Comment by tourdedave** [comment]
Hey @manuelgeorge - the is not the best forum to ask questions. This is for filing bugs. See [the help page](https://www.seleniumhq.org/selenium-ide/help/) for other places to look next time. 

If you're doing playback in the browser, then you'll need to click it manually. If you're doing playback in [the command-line runner](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/), then you can use a browser specific capability to ignore insecure certificates (e.g., see #778).
