### ISSUE TITLE
Current test focus does not switch to newly loaded .side file

### ISSUE THREAD

**Issue by NozomiIto** [SeleniumHQ/selenium-ide#80]
When loading .side file to newly launched empty Selenium IDE, the newly loaded test case is not selected on IDE, and no commands are displayed on the test step area.
Although the test steps are displayed when I click the test case name,  it apparently looks like no test step is loaded.

I introduced new Selenium IDE to my customers today, and many of them complained me that they could not load the .side file.
I appreciate if this UX will be improved.

Selenium IDE version: 1.0.1
OS: mac
Browser: Chrome

[Image of not focused test]
![testcaseisnotfocused](https://user-images.githubusercontent.com/4276719/35137041-7f29339a-fd2a-11e7-81bb-ee2188a798c7.png)

**Comment by corevo** [comment]
I see, do you want it to focus the first test?  
What if there are multiple tests?

**Comment by NozomiIto** [comment]
Thanks for your consideration!!
You say about the case when single .side file for a project contains multiple tests, right?

Yes, in such case, the first test case should have the focus when loaded, I think!

**Comment by corevo** [comment]
The fix will be included in the next release, It'll always highlight the first test case.

**Comment by NozomiIto** [comment]
Thanks so much !
