### ISSUE TITLE
Is there any way to dump the HAR file when using selenium-side-runner?

### ISSUE THREAD

**Issue by fmrahman** [SeleniumHQ/selenium-ide#800]
## 💬 Questions and Help

Is there any other node module to dump the HAR when using the selenium-side-runner.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

**Comment by fmrahman** [comment]
Apologize for not following the rules. Will resubmit with the template.
