### ISSUE TITLE
selenium side runner Timeout issue on IE 

### ISSUE THREAD

**Issue by shital17jun** [SeleniumHQ/selenium-ide#805]
## 🐛 Bug Report

: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error:

8 | jest.setTimeout(300000);
9 | describe("Default Suite", () => {

10 | it("fsdfd", async () => {
| ^
11 | await tests["fsdfd"](driver, vars);
12 | expect(true).toBeTruthy();
13 | });

at new Spec (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
at Suite.it (DefaultSuite.test.js:10:3)
NoSuchSessionError: session 0f600db4-b734-4a87-b143-3cd9905e2c39 does not exist

at Object.throwDecodedError (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
at parseHttpResponse (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
at Executor.execute (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/
 error appear 

## To Reproduce

Run command from commant prompt 
selenium-side-runner "form1.side" --timeout 2000 -c "browserName='internet explorer'"

## Expected behavior
Script should run on IE 

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.
[fsdf.zip](https://github.com/SeleniumHQ/selenium-ide/files/3594378/fsdf.zip)

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10 OS 64 bit
Selenium IDE Version:   v3.12.3
Selenium SIDE Runner Version:   0.7.0

Node version: : v10.16.3

Browser: Internet Explore
Browser Version: IE 11.67.17763(64-bit) 
[fsdf.zip](https://github.com/SeleniumHQ/selenium-ide/files/3594475/fsdf.zip)

**Comment by tourdedave** [comment]
@shital17jun Please fill out the Environment section of the template.

**Comment by shital17jun** [comment]
: Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 300000ms timeout specified by jest.setTimeout.Error:

8 | jest.setTimeout(300000);
9 | describe("Default Suite", () => {

10 | it("fsdfd", async () => {
| ^
11 | await tests["fsdfd"](driver, vars);
12 | expect(true).toBeTruthy();
13 | });

at new Spec (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
at Suite.it (DefaultSuite.test.js:10:3)
NoSuchSessionError: session 0f600db4-b734-4a87-b143-3cd9905e2c39 does not exist

at Object.throwDecodedError (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
at parseHttpResponse (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
at Executor.execute (../../../AppData/Roaming/npm/node_modules/selenium-side-runner/
error appear

To Reproduce
Steps to reproduce the behavior:
Run command from commant prompt
selenium-side-runner "form1.side" --timeout 2000 -c "browserName='internet explorer'"

Expected behavior
Script should run on IE
A clear and concise description of what you expected to happen.

Project file reproducing this issue (highly encouraged)
Please provide a project file .side that reproduces this issue.
fsdf.zip

Issues without a reproduction project are likely to stall.

Environment
OS: Windows 10 OS 64 bit
Selenium IDE Version: v3.12.3
Selenium SIDE Runner Version: 0.7.0

Node version: : v10.16.3

Browser: Internet Explore
Browser Version: IE 11.67.17763(64-bit)
fsdf.zip

**Comment by shital17jun** [comment]
Environment
OS: Windows 10 OS 64 bit
Selenium IDE Version: v3.12.3
Selenium SIDE Runner Version: 0.7.0

Node version: : v10.16.3

Browser: Internet Explore
Browser Version: IE 11.67.17763(64-bit)
fsdf.zip
expecting solution

**Comment by tourdedave** [comment]
Can you confirm that you've followed the configuration steps for Internet Explorer?

https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

**Comment by kkd5079** [comment]
I am also experiencing this issue, with the following environment:

OS: Windows 10 - 64 bit
Selenium IDE Version: v3.16.1
Selenium SIDE Runner Version: 3.15.0
Node version: 12.6.0
Browser: Firefox
Browser Version: 71

**Comment by AutomatedTester** [comment]
Closing as no info returned
