### ISSUE TITLE
can't start tests when browser opens special page(ex: Google Chrome's start page, Chrome web store, about:blank)

### ISSUE THREAD

**Issue by hiroshitoda** [SeleniumHQ/selenium-ide#81]
on v1.0.1 .
as general case, many users will open `.side` file and immediately run it on browser's start page.
but Google Chrome's start page can't be run Selenium IDE testcase because of Chrome's start page can't be injected any Selenium IDE resources(like JS, CSS).
so many users will face to simple execution timeout issue, but they can't resolve that.

one idea: before run Selenium IDE testcase, redirect to some general web page that can be injected Selenium IDE resources.
Selenium Builder implements similar features.

**Comment by corevo** [comment]
Yes, I was thinking about doing something like this, checking wether or not the IDE can run on the page, and if it can't automatically redirect.  
But I'll have to redirect to a local resource, as it must work behind firewalls.

**Comment by corevo** [comment]
The `open` command will now work in special pages, so scripts ran in a special page will redirect to their starting point just fine.  
Will be included in the next release.
