### ISSUE TITLE
how to host Selenium IDE api

### ISSUE THREAD

**Issue by rahulshetty1410** [SeleniumHQ/selenium-ide#810]
i want to access Selenium IDE Api to read user actions an store the data in my application for user record and replay option.

**Comment by tourdedave** [comment]
The issue tracker is for bugs, regressions, and feature requests. Open ended questions like this are better suited on the Selenium chat or on the selenium-users Google group. Details on where to find these are available on our help page ([link](https://www.seleniumhq.org/selenium-ide/help/)).

What's currently available through the Plugin API is documented [here](https://www.seleniumhq.org/selenium-ide/docs/en/plugins/plugins-getting-started/).
