### ISSUE TITLE
How to run Selenium-ide as web application instead plugin 

### ISSUE THREAD

**Issue by divz1010** [SeleniumHQ/selenium-ide#815]
### Please note that this issue tracker is not a help form and this issue will be closed.
Hi Team, 
       I want to run selenium-ide as a web application, please let me know how to do it. 
Thanks in advance 
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
This is a question, please refer to the resources provided for help.
