### ISSUE TITLE
Getting Crash most of the times - This extension may have been corrupted.

### ISSUE THREAD

**Issue by Rajib-Codereadr** [SeleniumHQ/selenium-ide#818]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment]
Duplicate of #782
