### ISSUE TITLE
Peru sync error 

### ISSUE THREAD

**Issue by divz1010** [SeleniumHQ/selenium-ide#819]
## 💬 Questions and Help
Hi Team,
           I am getting below error when i am running Peru.sync 
In target "atoms":
  git clone https://github.com/SeleniumHQ/selenium
  Cloning into bare repository 'D:\seleiniumIDE\UpdateSource\selenium-ide-3.13.0 (1)\selenium-ide-3.13.0\.peru\cache\plugins\git\6e7f4f6f3a69656bdba34f5c0659ef281506c2d2\71d99cff4caf6ce66fef7cdca079de
3ab2e3dffe'...
  remote: Enumerating objects: 328, done.
  remote: Counting objects: 100% (328/328), done.
  remote: Compressing objects: 100% (223/223), done.
  fatal: early EOFs:  16% (73887/441037), 637.37 MiB | 1.15 MiB/s
  fatal: The remote end hung up unexpectedly
  fatal: index-pack failed
### Please note that this issue tracker is not a help form and this issue will be closed.
 
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
[Windows](https://github.com/SeleniumHQ/selenium-ide/tree/v3#building) is not supported for building the IDE, PRs to fix the build are welcome.
