### ISSUE TITLE
Improvement: option to disable notifications

### ISSUE THREAD

**Issue by miyajan** [SeleniumHQ/selenium-ide#82]
On v1.0.1, I felt a bit annoying that browser notifications are displayed when each step is saved. It's fantastic if there is an option to disable them.

Thanks for a wonderful extension!

**Comment by corevo** [comment]
I see, I'm running it on a mac on do not disturb, so I didn't realize it might be this annoying.  
An option page is still in the backlog, I'll see what I can do in the meantime.

**Comment by corevo** [comment]
In the meantime I have added it to the project level "more" menu  
<img width="295" alt="screen shot 2018-01-22 at 12 08 49" src="https://user-images.githubusercontent.com/888886/35215515-273bbfdc-ff6d-11e7-86ed-5cee4205581e.png">
It'll be moved to the options page once it will be worked on, this will be included in the next release.
