### ISSUE TITLE
How can i make a build in RHEL 7. 

### ISSUE THREAD

**Issue by creator-cell** [SeleniumHQ/selenium-ide#821]
Followed the below steps. 
-> yarn --ignore-engines
->  yarn build

Gives below error :

ERROR in [copy-webpack-plugin] unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js' at '/selenium-ide-code-export-csharp/packages/selenium-ide/selenium/selenium-core-scripts/selenium-browserdetect.js'
Child html-webpack-plugin for "../index.html":
     1 asset
       [0] ../node_modules/html-webpack-plugin/lib/loader.js!./neo/index.html 720 bytes {0} [built]
        + 3 hidden modules
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
