### ISSUE TITLE
Unable to make a build

### ISSUE THREAD

**Issue by creator-cell** [SeleniumHQ/selenium-ide#829]
Hi team, 

I have cloned the v3 repo to my system. Then i followed the below steps
Added the peru.yaml file . and ran peru sync then 
1 ->  yarn --ignore-engines
2 -> yarn build (Got success response as : Done in 38.74s.)
3 -> yarn watch (Stopped at : @seleniumhq/side-recorder:     + 41 hidden modules. Noting is happening after this . )

Not sure what i am missing out here.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
