### ISSUE TITLE
Improvement Request: Ask test name when saving

### ISSUE THREAD

**Issue by PoohSunny** [SeleniumHQ/selenium-ide#83]
<img width="686" alt="2018-01-19 16 12 32" src="https://user-images.githubusercontent.com/1255565/35138845-bea6c1a0-fd33-11e7-9f91-7aa2cb9c2571.png">

Saving script at the first time, there is nothing to show in left side "Tests" bar. After saving the script and opening the project, there is "untitled" test in Tests bar. I think it is good for users to ask the test title when user saves script at the first time.

Thank you for creating great tool :)

**Comment by corevo** [comment]
It may lead to a new problem, as we can ask the user for two things, project name, and first test name.<br />
If we ask for a test name when saving, the user will instinctively think we ask for a project name,  
and if we ask for a project name then we haven't named the test.

**Comment by p2635** [comment]
I think this can be closed as it's no longer relevant?
