### ISSUE TITLE
Record from here option should start recording instead of playing the recording 

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#833]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Start record and stop it
select any step from the recording
Click on options 
Select Record from here
It starts playing the recording from start

**Comment by corevo** [comment]
This is the intended behavior, when you click record from here, we play up to the point from which you want to continue recording.
