### ISSUE TITLE
Timeout time is too long to wait to get the exception.

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#834]
Record anything
play the recording 

change the screen, so that element should not be found and check the recorder, it will go infinite  to give any exception.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
