### ISSUE TITLE
Cannot import a project file with uppercase file extension.

### ISSUE THREAD

**Issue by 0x70b1a5** [SeleniumHQ/selenium-ide#835]
## 🐛 Bug Report

Cannot import a project file with uppercase file extension.

## To Reproduce

1. Open Selenium IDE 
2. Try to import test.SIDE
3. Observe "Unknown file" error.

Alternatively:
1. Create a new project
2. Save as anyname.SIDE [UPPERCASE file extension]
3. Attempt to open anyname.SIDE 
3. Observe "Unknown file" error.

## Expected behavior

Selenium IDE should open the project file.

## Project file reproducing this issue (highly encouraged)

[cannotOpenUppercaseFileExtension.zip](https://github.com/SeleniumHQ/selenium-ide/files/3663531/cannotOpenUppercaseFileExtension.zip)

## Environment

OS: Windows 10
Selenium IDE Version:  3.13.0
Browser: Chrome
Browser Version: 77.0.3865.90 (Official Build) (64-bit)

**Comment by 0x70b1a5** [comment]
I suspect this will be a good candidate for the good-first-issue tag.

**Comment by corevo** [comment]
Probably, most likely it needs to change to a regex check with `i` flag, I'll add the tag.

**Comment by jeremylorino** [comment]
@corevo build fixed

**Comment by corevo** [comment]
Fixed in #1118
