### ISSUE TITLE
In recording if user adds any description to the step it displays in Command section

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#836]
## To Reproduce

In recording if user adds any description to the step it displays in Command section

## Expected behavior

Maybe we should one have  more coulmn with description and it should have displayed there.

## Project file reproducing this issue (highly encouraged)

Record anything and change in description.

Issues without a reproduction project are likely to stall.

## Environment

chrome browser
Selenium IDE Version:  3.13

**Comment by corevo** [comment]
This is the intended behavior, we tried adding another column, but for small displays it made the IDE unusable.
