### ISSUE TITLE
loading old Suits in Selenium IDE

### ISSUE THREAD

**Issue by flyingHorse1337** [SeleniumHQ/selenium-ide#84]
Hey guys,
maybe I am too stupid, but I am not able to load my old selenium testsuits? Adding old cases works fine ..
cheers
thanks for your great work

**Comment by corevo** [comment]
Indeed you can't import old test suites, we'll need more real world examples in order to design the correct mechanism, iirc we only received one.  
If you can attach some to this thread I'll gladly take a look.
