### ISSUE TITLE
SIDE runner issues

### ISSUE THREAD

**Issue by steckerhalter** [SeleniumHQ/selenium-ide#841]
## 🐛 Bug Report

In a work project I have 5 tests completing successfully with the plugin in Chrome. When I'm running the same SIDE file with the runner (also with Chrome), 4 of these 5 tests fail for various reasons.

What I wanted to know if it is feasible to use the runner in a work project, but judging from this experience I don't think it's ready for that. If the SIDE files do not run with the runner without having to tweak them I think it's easier to export the code and to continue with the Selenium Webdriver.

I thought I want to make an issue here where other people may comment or share their opinion about the state of the SIDE runner. It depends a lot on you what you want to do with this issue. You can close it right away or keep it open for discussion. The thing is, I just lack the time to dig into the runner issues. I need something that mostly works. So if 1 of 5 tests would fail then I would probably look into it, but not like it is now.

Thanks for Selenium IDE. Even like this it's still very useful.

**Comment by tourdedave** [comment]
The issue tracker is for addressing specific problems - not for open discourse. There are other places that are better suited for that (listed on [the project help page](https://www.seleniumhq.org/selenium-ide/help/)). Without knowing the specifics of your problems with the runner we're unable to provider any input to help. Please consider opening a new issue and completing the issue template.

**Comment by steckerhalter** [comment]
Ok, thanks
