### ISSUE TITLE
Color of the step of recording which is disabled should be in other color except green.

### ISSUE THREAD

**Issue by vinay95garg** [SeleniumHQ/selenium-ide#843]
## 🐛 Bug Report

Disable Breakpoints icon does not display the difference whether it is enabled on not.
## To Reproduce
If I record something and disable any command its color also changes to green and doesn't show the exact difference between executed command and disabled command.

## Expected behavior

It should be either marked with yellow or something different from the executed command.

## Environment
chrome

**Comment by tourdedave** [comment]
Can you please provide more detail? Perhaps a video or set of screenshots of the problem?

**Comment by AutomatedTester** [comment]
Closing as no info returned
