### ISSUE TITLE
RUN CI Questions about testsuites？

### ISSUE THREAD

**Issue by tcwaily** [SeleniumHQ/selenium-ide#846]
I ran a test in testsuitest, but there is a run test in this test. Do I need to add the run test to testsuites to run smoothly in CI? Currently running an error in CI.

**Comment by tcwaily** [comment]
ElementClickInterceptedError: element click intercepted: Element <span class="title">...</span> is not clickable at point (98, 387). Other element would receive the click: <div class="el-loading-mask loading is-fullscreen" style="background-color: rgba(0, 0, 0, 0.3); z-index: 2000;">...</div>
      (Session info: chrome=77.0.3865.120)

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
