### ISSUE TITLE
Run selenium ide in webdriver

### ISSUE THREAD

**Issue by JordyvdM** [SeleniumHQ/selenium-ide#848]
I am recording multiple tests using selenium ide, but would like to be able to play the recorded files using selenium webdriver in C#. I would like to use webdriver to be able to take screenshots and do other things in between the steps.

I started with a selenium webdriver, where I defined and created the actions for the different commands form selenium ide that I want to support. However, now I have to add some new commands and I'm wondering if I could do this much easier.

I have 2 different questions regarding the running of selenium ide tests using selenium webdriver:

1. Is it possible to call selenium ide from selenium webdriver? So I would like to play the whole test using selenium webdriver, but want to call selenium ide for every command/step that I want to take in the website.
2. Can I export all possible selenium ide commands, so I can use the definition of these commands within selenium webdriver. The commands that I support in selenium webdriver at the moment are all added to my code, but is there an easier way to get all selenium ide commands with the corresponding code to execute the command?

Can anyone help me with this, so it is easier to play selenium ide tests using selenium webdriver?

**Comment by JordyvdM** [comment]
I am recording multiple tests using selenium ide, but would like to be able to play the recorded files using selenium webdriver in C#. I would like to use webdriver to be able to take screenshots and do other things in between the steps.

I started with a selenium webdriver, where I defined and created the actions for the different commands form selenium ide that I want to support. However, now I have to add some new commands and I'm wondering if I could do this much easier.

I have 2 different questions regarding the running of selenium ide tests using selenium webdriver:
1. Is it possible to call selenium ide from selenium webdriver? So I would like to play the whole test using selenium webdriver, but want to call selenium ide for every command/step that I want to take in the website.
2. Can I export all possible selenium ide commands, so I can use the definition of these commands within selenium webdriver. The commands that I support in selenium webdriver at the moment are all added to my code, but is there an easier way to get all selenium ide commands with the corresponding code to execute the command?

Can anyone help me with this, so it is easier to play selenium ide tests using selenium webdriver?

**Comment by tourdedave** [comment]
@JordyvdM The issue tracker is not for questions -- it's for notifying us of bugs, regressions, and feature requests. There are other avenues which are better suited for your questions listed on [the project's help page](https://www.seleniumhq.org/selenium-ide/help/).

**Comment by tourdedave** [comment]
Also, if you're looking for details on code export, see issue #592
