### ISSUE TITLE
Core extension

### ISSUE THREAD

**Issue by fokcep** [SeleniumHQ/selenium-ide#85]
How do I add the core extension? It used to be possible to add core extension and user extension in the previous versions.

Thanks

**Comment by corevo** [comment]
We are in the midst of designing a new plugin API for the IDE.  
All old extensions will not be compatible anymore, as the old Mozilla extension API is now obsolete.  
New extensions will have to adhere to Chrome's and Firefox's regulations, which may lead to major redesigns and incompatibilities, as both browsers have strict security policy.

**Comment by anshu781126** [comment]
What about extensions which are not present as built in? There is no way to add any user-extenstion.js ?
