### ISSUE TITLE
Unable to upload a file using the "type" command

### ISSUE THREAD

**Issue by jkreis1990** [SeleniumHQ/selenium-ide#851]
When filling out a form, I am unable to use the "type" command to input and upload a file, even though the documentation states otherwise. I'm using Google Chrome, so that might be why- I haven't tried other browsers.

**Comment by BorderCloud** [comment]
@jkreis1990 if your target is a type=file, you have to enable the chrome option "allow access to file urls" for the selenium extension.

But I have the same problem but my target is not a type=file. It's a wiki with a type=selectarea. For the moment, I copy/paste a file in this field. 

Is it possible to allow to upload a file in a text field ? with type or another command ?

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
