### ISSUE TITLE
Can selenium-IDE fail the test when there's js error on console? how?

### ISSUE THREAD

**Issue by bury-source** [SeleniumHQ/selenium-ide#853]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

When there's js error, the page can still be operated, the test will successed.
I want to fail the test when console has js error, but how to do with it?

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
