### ISSUE TITLE
Recording did not include hover needed to activate menu

### ISSUE THREAD

**Issue by david-iterators** [SeleniumHQ/selenium-ide#860]
## 🐛 Bug Report

The recording feature does not include a hover command needed to activate a menu.

## To Reproduce

1)  Turn on the Selenium IDE in Chrome and start recording with a target URL of https://IteratorsTesting.com
2)  Select the Services menu and then the Accessibility Testing item
3)  Stop the recording
4)  Playback the recording.  Note that the Accessibility Testing item was not selected.
5)  Modify the script manually by adding the mouse over command for the Services menu

## Expected behavior

The hover command should be recorded because it triggered a submenu to be displayed.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  3.14.0

-->

[Iterators Testing.txt](https://github.com/SeleniumHQ/selenium-ide/files/3802469/Iterators.Testing.txt)

-->
Browser:
Browser Version: Chrome:  Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
This is an issue we're aware of that is unfortunately quite difficult to automate. We've outlined some workarounds in our FAQ ([link](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/faq/#how-do-i-record-hovers)).
