### ISSUE TITLE
Add all remaining commands to context menu

### ISSUE THREAD

**Issue by carlos-granados** [SeleniumHQ/selenium-ide#867]
## 🚀 Feature Proposal

Add all available Assert, Store, Verify and Wait For commands to the context menu (the menu that is shown when you right click on a page)

## Motivation

Currently only a small subset of these commands is available in this menu. It would be good to be able to choose the full set so that you can easily add any of these commands while recording a test

## Example

For example, you cannot currently add an assertion to confirm that an element is present. You need to resort to workarounds like adding an assertion on the element text and then manually modifying it to an assertion on element present

**Comment by capoerafreak** [comment]
Please close this issue, its solved.
