### ISSUE TITLE
Add a WaitForText command

### ISSUE THREAD

**Issue by carlos-granados** [SeleniumHQ/selenium-ide#869]
## 🚀 Feature Proposal

Add a new wait command that will wait until the text of an element has a specific value.

## Motivation

Sometimes you need to wait until the specific text of an element has a certain value, usually because this text is set by a javascript process, maybe an ajax call. The current functionality of being able for an element to be present or visible is not enough as the element may be present and visible but its text may not have changed yet

## Example

Suppose that you had an editor that lets you edit some properties of a document, for example its title. You do this by clicking on an "edit title" button that loads a javascript dialog where you enter the new title. When you click save, the title is sent to the backend using ajax and once the request finishes correctly, you update the title in the page. If you wanted to write a test to confirm that the title is changed in the page, if you try to assert that the title matches the new title after submitting the dialog it will fail as the title would still have the old title until the ajax request finishes. And since the title is already there you cannot just wait for it to be present or visible before making the assertion

**Comment by sjoerdvanderhoorn** [comment]
Alternative approach proposed at https://github.com/SeleniumHQ/selenium-ide/issues/888#issuecomment-559568446. Instead of adding an additional command, it allows each command to fail repeatedly until either the expected text or element becomes available or until the configuration.timeout period has been reach after it will throw the original error.

**Comment by capoerafreak** [comment]
Please close this issue, its solved.
