### ISSUE TITLE
ClickAt by default

### ISSUE THREAD

**Issue by LauraLaureus** [SeleniumHQ/selenium-ide#874]
Hi!

First of all thanks for developing this useful tool. 

I have a project that renders a game inside a canvas object. And I would like to create test that record all the  mouse positions (with the wait time between them). 

I would like to know if there is any quick way to set up the "clickAt" function as the default one for the IDE. and any way to automatic record the time between them.

In case that is not possible, is there any documentation in order to create a custom version of selenium-ide?

Thank you in advantage.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

**Comment by tourdedave** [comment]
@LauraLaureus Thanks for the kind words! Unfortunately the issue tracker isn’t the best place to ask questions. The selenium-users Google group or Selenium chat are better options. You can find out more info on the project help page: https://www.seleniumhq.org/selenium-ide/help/
