### ISSUE TITLE
Chrome starts the ide to prevent save button events in the page

### ISSUE THREAD

**Issue by yidp** [SeleniumHQ/selenium-ide#876]
## 🐛 Bug Report

Chrome starts the selenium-ide to prevent save button events in the web test

## Environment

OS:  Windows 10
Selenium IDE Version:  3.14
Selenium SIDE Runner Version:  3.14
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 
Only required if using selenium-side-runner
-->
Browser:
Browser Version: 70.0.3538.110

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
