### ISSUE TITLE
Export Support For Javascript Jasmine

### ISSUE THREAD

**Issue by Nabeelhassan** [SeleniumHQ/selenium-ide#880]
## 🚀 Feature Proposal

Export recorded test suites/cases in Javascript Jasmine

## Motivation

Exporting test cases in Jasmine would be great. It is a popular testing framework and many developers/teams use it in their day to day test cases.

**Comment by tourdedave** [comment]
Jasmine is not a test framework that we are interested in supporting as part of the Selenium IDE standard library, but it could be incorporated as a plugin if someone wants to take that up.

https://www.seleniumhq.org/selenium-ide/docs/en/plugins/code-export/
