### ISSUE TITLE
Connect to existing Browser - Run test on webpage that requires 2 Factor Authentication 

### ISSUE THREAD

**Issue by Barry1975** [SeleniumHQ/selenium-ide#882]
## 🚀 Feature Proposal
1) Launch Webdriver from Selenium IDE
2) Manual login (2FA/MFA)
3) Run Test scripts with Attach to existing Browser, feature to leave Browser open after test 

## Motivation

Test are impossible with 2FA / MFA login

## Example

Run test on webpage that requires 2 Factor Authentication 

https://stackoverflow.com/questions/47861813/how-can-i-reconnect-to-the-browser-opened-by-webdriver-with-selenium/47862867

**Comment by tourdedave** [comment]
For the use case you're describing you don't need to reconnect to an existing session -- you just need the session to wait for you to complete a manual step and then continue on. To do that you can set a break point to have the test wait and the resume it once you've completed the manual login.

**Comment by Barry1975** [comment]
Great Idea !, How to manage when a test fails, and 3 other tests need to run as wel ?

**Comment by tourdedave** [comment]
Your use case has a manual step in it. If it fails, you will know, and will likely re-run the test.
