### ISSUE TITLE
Syntax error in selianize.cjs.js

### ISSUE THREAD

**Issue by LucretiaUK** [SeleniumHQ/selenium-ide#884]
## 🐛 Bug Report

I've just installed all prerequisites for running selenium-side-runner in CentOS 7 and when testing with a .side file, I get the following error:

```
[Selenium@PCCSDEV01 ~]$ sudo selenium-side-runner /home/Selenium/SG1/Orbit.side
/usr/lib/node_modules/selenium-side-runner/node_modules/selianize/dist/selianize.cjs.js:64
async function emit(project, options = config, snapshot)
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/selenium-side-runner/dist/index.js:40:42)
```

This happens if I try to run .py files as well as using specific browser drivers; it's always the same error. 

## To Reproduce

Log in as sudo user, execute selenium-side-runner with a .side file saved from Selenium IDE in Firefox.

## Expected behavior

Successful operation identical to results from Selenium IDE tests.

## Project file reproducing this issue (highly encouraged)

[Orbit.zip](https://github.com/SeleniumHQ/selenium-ide/files/3852476/Orbit.zip)

## Environment

OS: CentOS 7
Selenium IDE Version:  v3.15.1
Selenium SIDE Runner Version: 3.15.0
Node version: 6.17.1
Only required if using selenium-side-runner
Browser: Firefox
Browser Version: 70.0.1

**Comment by corevo** [comment]
You are using unsupported node version, please upgrade to either 10 or 12.

Cheers,
Tomer

**Comment by LucretiaUK** [comment]
Hi Tomer,
I have version 13 installed now and I still get the same error.
Thanks.

**Comment by corevo** [comment]
I just ran it with node 13 and it runs fine, make sure that it is the same error & that the installation is correct, try maybe re-running `npm i -g selenium-side-runner`.

**Comment by corevo** [comment]
To make sure I've also tried 12 & 10, and did not get a syntax error.

**Comment by LucretiaUK** [comment]
Hi Tomer,
I ran the script you suggested:

```
[Selenium@PCCSDEV01 ~]$ npm i -g selenium-side-runner
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/home/Selenium/.nvm/versions/node/v13.1.0/bin/selenium-side-runner -> /home/Selenium/.nvm/versions/node/v13.1.0/lib/node_modules/selenium-side-runner/dist/index.js
npm WARN jest-environment-selenium@2.1.2 requires a peer of jest@>=23.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-environment-selenium@2.1.2 requires a peer of jest-environment-node@^23.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-environment-selenium@2.1.2 requires a peer of selenium-webdriver@4.0.0-alpha.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/selenium-side-runner/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ selenium-side-runner@3.15.0
added 527 packages from 524 contributors in 28.443s

```
And I can confirm that the error is still exactly the same as quoted previously.
Thanks.

**Comment by corevo** [comment]
Can you run `which selenium-side-runner`?

**Comment by LucretiaUK** [comment]
[Selenium@PCCSDEV01 ~]$ which selenium-side-runner
~/.nvm/versions/node/v13.1.0/bin/selenium-side-runner

**Comment by LucretiaUK** [comment]
Oh dear, running selenium-side-runner without sudo fixed it. Sorry, Tomer, should have tried that first!

**Comment by corevo** [comment]
Great!

**Comment by corevo** [comment]
I guess since you use `nvm` it installs node locally, and then sudo is referred back to the global node 6 installation.

**Comment by LucretiaUK** [comment]
That would make sense. Thanks for your help!
