### ISSUE TITLE
How to set default  target to xpath  while recording 

### ISSUE THREAD

**Issue by SojinAntony** [SeleniumHQ/selenium-ide#885]
How to set the default  target to XPath while recording.?
my website contains dynamic class names and ids.  so record and play are not working properly.  I want to be recording everything with target XPath. Already forked the package what should I need to do in code?

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
