### ISSUE TITLE
How to set the default target to XPath while recording?

### ISSUE THREAD

**Issue by SojinAntony** [SeleniumHQ/selenium-ide#886]
## 🐛 Bug Report

How to set the default target to XPath while recording.?
my website contains dynamic class names and ids. so record and play are not working properly. I want to be recording everything with target XPath. is there any way to do so

## Expected behavior

An option to record everything with target XPath

## Project file reproducing this issue (highly encouraged)

Issues without a reproduction project are likely to stall.

## Environment

OS: Ubuntu 16.04 
Selenium IDE Version:   3.14.0 
Node version:   10.4

Browser: Chrome
Browser Version:   78.0.3904.70

**Comment by corevo** [comment]
This issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
As of the moment there is no way to re-order the locators strategies, if you wish you can open a feature request, or send a PR.
