### ISSUE TITLE
webdriver choose cancel  not working

### ISSUE THREAD

**Issue by p00t1337** [SeleniumHQ/selenium-ide#887]
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Followed this article to the exact letter:

https://www.qafox.com/new-selenium-ide-using-webdriver-choose-cancel-on-visible-prompt-command-for-cancelling-the-prompt/

Still can't get the webdriver choose cancel on visible prompt command to work properly.
Prompt ok/cancel is clearly displayed but no action is being taken (Selenium IDE just stalls on the step 'web driver choose cancel ..'

Using:
Google Chrome is up to date
Version 78.0.3904.108 (Official Build) (64-bit)

Selenium IDE v3.15.1

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new?template=bug.md) and we'll make sure to look at it.
