### ISSUE TITLE
build firefox extension (.web-extension-id) error

### ISSUE THREAD

**Issue by OrangeManDavid** [SeleniumHQ/selenium-ide#889]
{
yarn build-firefox
yarn run v1.19.1
$ web-ext sign -s build -a dist --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$(cat ../../.web-extension-id)
cat: ../../.web-extension-id: No such file or directory
/bin/sh: 1: web-ext: not found
error Command failed with exit code 127.
}
what's web-extension-id?

**Comment by OrangeManDavid** [comment]
openssl genrsa -out selenium-ide.pem 2048
yarn build-chrome
Chrome build success!!

**Comment by corevo** [comment]
We don't use these scripts anymore, just run `yarn build:ext:prod`
