### ISSUE TITLE
Failed assertion commands do not abort the test case

### ISSUE THREAD

**Issue by xunoaib** [SeleniumHQ/selenium-ide#89]
The active test case does not terminate when an "assert" command fails. Instead, a failure message is displayed and the remaining commands in the test case are still executed. To my understanding, this is how "verify" commands should work, but it's not appropriate for assertions.

The old Selenium IDE 2.9.1 plugin behaves as expected.

Selenium IDE Log (v1.1.0) demonstrating this issue:
```
Running 'assertion_test'
1.Trying to execute assertText on name=btnK with value doesnotexist... Failed:
Actual value '' did not match 'doesnotexist'
2.Trying to execute open on /skipthiscommand... Success
'assertion_test' completed with 1 error(s)
```

**Comment by corevo** [comment]
Aborting test cases due to errors is not yet implemented, it'll be coming as part of [extensibility](https://github.com/SeleniumHQ/selenium-ide/pull/79).  
I'll leave this open until then.
