### ISSUE TITLE
Support export to Robot Framework format

### ISSUE THREAD

**Issue by dews** [SeleniumHQ/selenium-ide#891]
## 🚀 Feature Proposal
Support export to Robot Framework format

## Motivation
Export Robot can help users who use Robt Framework write script more efficient and quick.
And since [katalon-recorder](https://github.com/katalon-studio/katalon-recorder) implement it, which means it's possible to do it.

## Example
Screenshot from [katalon-recorder](https://github.com/katalon-studio/katalon-recorder)
![image](https://user-images.githubusercontent.com/2516523/69496440-310abc00-0f0d-11ea-90ae-9660f2af1a3b.png)

**Comment by corevo** [comment]
As a rule of thumb we are not accepting code export targets that are not to official Selenium bindings.

But, our code export foundation is extensible by plugins, I suggest you write one for Robot framework.
