### ISSUE TITLE
Selenium IDE Date Variable

### ISSUE THREAD

**Issue by jrk12b** [SeleniumHQ/selenium-ide#892]
Hello there,

Is there a way to input "30 days previous to today"? For example, if today is 11/25/2019, I would like Selenium IDE to input "10/26/2019" into a text field. 

Thanks in advance!

**Comment by 98gmarquee** [comment]
Use execute script then js to subract 30 days from the current.
execute script | below js | currentMinus30Days
echo | ${currentMinus30Days|
`var priorDate = new Date(new Date().setDate(new Date().getDate() - 30)); var fd = new Date(priorDate); var date_month = fd.getMonth() + 1; if (date_month < 10) {     date_month = "0" + date_month; }; date_day = fd.getDate().toString(); var n = date_day.length; if (n < 2) {     date_day = "0" + date_day; }; date_hour = fd.getHours().toString(); var n = date_hour.length; if (n < 2) {     date_hour = "0" + date_hour; }; date_min = fd.getMinutes().toString(); var n = date_min.length; if (n < 2) {     date_min = "0" + date_min; }; date_sec = fd.getSeconds().toString(); var n = date_sec.length; if (n < 2) {     date_sec = "0" + date_sec; }; date_year = fd.getFullYear().toString(); date_year = date_year.toString().substr(2, 2); return date_month + "/" + date_day + "/" + date_year + " " + date_hour + ":" + date_min + ":" + date_sec;`

This will give you a formatted date of "now" subtracting 30 days:
dd/mm/yy hh:mm:ss

Any single digit values padded with a leading 0. You can remove the time from the return value easily if you don't want it.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
