### ISSUE TITLE
Exported JavaScript Mocha function setRect not working 

### ISSUE THREAD

**Issue by ThiagoAugustoSM** [SeleniumHQ/selenium-ide#893]
## 🐛 Bug Report

The exported JS Mocha file utilize the function

`driver.setRect()` which had been changed to `driver.manage().window().setRect({width: value, height: value})` in the newest selenium version. And when executing the exported file it raises an error due to that.

## To Reproduce

- Execute and record any test in a website.
- Export it.
- Try to execute the mocha.js file exported with the environment set.

## Expected behavior

It is expected to execute and open the browser but your test with mocha you raise an error:
`TypeError: driver.setRect is not a function`

## Project file reproducing this issue (highly encouraged)

I've not uploaded a .side project, because the problem happens with all .side projects created on my environment.

## Environment

OS: macOS 10.15.1
Selenium IDE Version:  3.16.0
Node version: 10.16.3

**Comment by tourdedave** [comment]
Fixed in d634a03a732fc3fe1320ca5ff00644e620273e5f

**Comment by tourdedave** [comment]
Released in `v3.16.1`
