### ISSUE TITLE
I am unable to run project.side from commandline runner.

### ISSUE THREAD

**Issue by aerosoftn** [SeleniumHQ/selenium-ide#896]
## 💬 Questions and Help

I am unable to run project.side from commandline runner.
selenium-side-runner is installed and path for chrome driver is set.

Pls see below screenshot that show commands typed in command prompt.
![side runner issue in cmd](https://user-images.githubusercontent.com/58318093/69841867-e8456100-1286-11ea-87c9-d7966409198f.jpg)

**Comment by sjoerdvanderhoorn** [comment]
You probably should use quotes to escape the path to your .side file.

> selenium-side-runner -c "browserName=chrome" "C:\Users\sanjay\Desktop\Selenium IDE files\crm new.side"

**Comment by aerosoftn** [comment]
THANKS Sjoerd van der Hoorn !!
ITS WORKING NOW.
