### ISSUE TITLE
Recording should be stopped when Play button is pressed

### ISSUE THREAD

**Issue by SpyMachine** [SeleniumHQ/selenium-ide#90]
If you accidentally leave recording on when you press the play button, the IDE will start recording these commands that are being played back. I've actually seen the recorder get itself stuck in a loop doing this. 

I think it would make sense if the recorder just stopped automatically when play is hit to avoid this problem.

**Comment by pgroot91** [comment]
@SpyMachine well not sure what makes sence... you can also simple disable the play button while you're recording and first need to hit the stop button before continuing doing some other actions.

**Comment by SpyMachine** [comment]
Sure, that could work too.

**Comment by corevo** [comment]
That's an oversight on my part, will be fixed

Cheers,
Tom
