### ISSUE TITLE
What are the Chrome Versions that are compatible with Selenium version 2.53.0? Is Chrome v78 compatible with it?

### ISSUE THREAD

**Issue by Jayita09** [SeleniumHQ/selenium-ide#903]
## 💬 Questions and Help

Hi,

Can you please let us know what are the Chrome Versions that are compatible with Selenium version 2.53.0? Is Chrome v78 compatible with it?

Many thanks
Jayita Das

**Comment by corevo** [comment]
## 💬 Questions and Help

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
