### ISSUE TITLE
Allow the user to run commands against the last visited tab

### ISSUE THREAD

**Issue by pbodnar** [SeleniumHQ/selenium-ide#904]
## 🚀 Feature Proposal

Allow the user to run commands (tests) against the last visited tab (page). Selenium IDE alternatives like Katalon Recorder or UI.Vision Kantu may serve as a working inspiration. Now, the commands are always executed in a dedicated window opened by the Selenium IDE - for a meaningful test, the 1st interactive command needs to be `open`.

If possible, this feature could be easily switchable by the user.

## Motivation

By enabling running commands in the last visited tab, Selenium IDE can get closer to a generic automation tool, as well as simplify prototyping while writing tests.

## Example

1. Open a page of your interest, e. g. a concrete issue page on Github. You can also make some changes that are not expected to be part of a Selenium test, like filling in a text field.
2. Switch to Selenium IDE.
3. Have the proposed feature enabled and run a test which extracts data from the Github page and does whatever else is needed with them. Or, just test various commands against the current page.

**Comment by corevo** [comment]
Selenium IDE is moving away from this method, once Selenium IDE will use WebDriver this will not be possible at all.

Hence we won't add support for a feature we know will not be able to exist in the future.

I understand the frustration, but moving away from this direction will yield us better results in other aspects.

**Comment by pbodnar** [comment]
What a pity, but understandable...

Maybe one day, browsers will evolve and make the connection "from outside" possible, who knows... :)

**Comment by pbodnar** [comment]
Now I can see this was reported / asked many times already (e. g. #440, #480, #788 - all are closed). I guess that putting some note onto the [FAQ page](https://selenium.dev/selenium-ide/docs/en/introduction/faq) or somewhere else would help...
