### ISSUE TITLE
First use issues.

### ISSUE THREAD

**Issue by dailytabs** [SeleniumHQ/selenium-ide#907]
1) Test Suite UX is terrible. Why is it not a tree of Project > Suites > Tests? Creating tests then attaching them to a suite is backwards.

2) Clicking the Record button does not show errors. Using Ctrl+U to start recording does give errors. By "errors" I mean the error message dialog that pops up. I tried starting a recording and nothing happened. Eventually, I tried Ctrl-U and it showed me a message about the base URL missing. I entered a base URL and clicked Record; and, again, nothing happened. I hit Ctrl-U and it showed me a message about `o.something.test.whatever` being undefined. It could have just told me that I hadn't created a Test Case yet, but instead it choose to tell me about your coding error; so, you need to add some better error handling. How could you miss an error message for something as basic as the Test Case not being created? In fact, why are the UI elements even available when none of it can be used without a Test Case existing? It's a UX mess!

3) Automation is basically completely broken due to the new window opening every time I click Record. I really don't understand this decision. I have the page open and ready to begin. Why can't I just start? Also, it makes editing a pain in the ass. I have to click to start recording, let it open the base URL window, switch to Selenium window, click to stop recording, switch back to webpage, navigate to where I left off, switch back to Selenium window, click to start recording, switch back to webpage, and then I can finally continue where I left off.

I am seriously considering downgrading to FF 54 or whatever it was, just so I can use the old Selenium IDE. But, I won't do that. No time. Instead, I am simply uninstalling and doing my task the manual way. I will also never again recommend Selenium IDE for automation purposes.

Feel free to close this ticket, I don't plan on following up on anything and I really don't expect the Selenium team to address them in any kind of a timely manner.

**Comment by corevo** [comment]
Although I can't see you when I type this to you, I want you to know that I understand your points, if you'd like I could elaborate on some of the reasons why we took Selenium IDE more towards the testing environment than to automation.

But that is not the important message I'd like to convey, the team & I are working on Selenium out of belief in what we do, we may make mistakes, but we aren't doing anything out of malice or bad intent, rather we set in our view to do the best job we can.

Although Selenium IDE wasn't a good fit, I sincerely hope that you would find a tool that could help you achieve what you want.
