### ISSUE TITLE
Broken link in selenium.dev/selenium-ide 

### ISSUE THREAD

**Issue by TheTestLynx** [SeleniumHQ/selenium-ide#908]
## 🐛 Bug Report

Clicking the link under 'here' in https://selenium.dev/selenium-ide/docs/en/plugins/plugins-getting-started me to https://github.com/SeleniumHQ/selenium-ide/tree/v3/packages/extension-boilerplate

I would have tried to change it but I don't know where exactly the source code is.

## To Reproduce

Go to https://selenium.dev/selenium-ide/
Click Plugins
Click 'here' --> takes me to 404

## Expected behavior

Go to some website with a plugin example

## Environment

Mac and Chrome but I think it would happen to all.

**Comment by corevo** [comment]
If you want to fix it the source is [here](https://github.com/SeleniumHQ/selenium-ide/blob/v3/docs/plugins/getting-started.md), thanks for pointing it out.

**Comment by TheTestLynx** [comment]
I think this issue has relation with it https://github.com/SeleniumHQ/selenium-ide/pull/661
I could not find the source code for the link, so I could not help, sorry! I checked in other branches but no luck either

**Comment by diemol** [comment]
Is this the correct link @corevo?
https://github.com/SeleniumHQ/selenium-ide/tree/v3/extension/extension-boilerplate
