### ISSUE TITLE
Cannot record "answer on next prompt"

### ISSUE THREAD

**Issue by SpyMachine** [SeleniumHQ/selenium-ide#91]
I tried to record answering a prompt but it is not doing so. For some reason, it's asserting the alert twice instead. I've provided the HTML I am using to test and the side file that is created from my test.

[prompt_side.txt](https://github.com/SeleniumHQ/selenium-ide/files/1687048/prompt_side.txt)
[prompt_html.txt](https://github.com/SeleniumHQ/selenium-ide/files/1687049/prompt_html.txt)

Should probably note, tried this is on Chrome 64/65.

**Comment by corevo** [comment]
I was able to reproduce this, and will work on a fix

**Comment by corevo** [comment]
Will be included in the next release
