### ISSUE TITLE
Export to PHP Codeception

### ISSUE THREAD

**Issue by defro** [SeleniumHQ/selenium-ide#910]
## 🚀 Feature Proposal

Propose a export to Codeception writing in PHP.

## Motivation

I've already create a plugin for Katalon exporter in my previous company.

## Example

Actually Selenium IDE propose a lot of different language but no in PHP. A user can export all command to a file ready to be execute by Codeception.

PS: I've already post a comment on Issue about Export : https://github.com/SeleniumHQ/selenium-ide/issues/592#issuecomment-563299258

**Comment by corevo** [comment]
That was the correct thread to ask that question on, sorry for answering so late, we should probably make it clearer, but as far as we stand now, we as a project don't want to take ownership over unofficial bindings for selenium.

We've worked hard to make the system very much extensible via plugins, and as long as there isn't an official PHP bindings for WebDriver, this will have to be a plugin.

**Comment by defro** [comment]
Thanks @corevo for your answer. Where I can find documentation to develop this plugin ?

**Comment by bcmoney** [comment]
@defro Guessing you found this already, but for anyone else who happens by:
https://selenium.dev/selenium-ide/docs/en/plugins/plugins-getting-started
https://selenium.dev/selenium-ide/docs/en/plugins/code-export
