### ISSUE TITLE
select frame command timeout when repeat the same process

### ISSUE THREAD

**Issue by HabitNature** [SeleniumHQ/selenium-ide#918]
## 🐛 Bug Report

The select frame command will fail with timeout when run it in times command.
I set the times command with 10. The select frame command succeeded in the first time, but failed in the second time.

## To Reproduce

1. Execute the following script.

## Expected behavior

The select frame command should be successfuly in the second time.

## Project file reproducing this issue (highly encouraged)

{
  "id": "a79f117b-656f-4ef6-95bd-3b1b8fa334bf",
  "version": "2.0",
  "name": "ALiYun",
  "url": "https://account.aliyun.com",
  "tests": [{
    "id": "c87698e3-1f70-469a-a1cb-40319e5e18e8",
    "name": "ALiYun",
    "commands": [{
      "id": "c20ce417-742a-4e8c-b344-252ee331bc53",
      "comment": "",
      "command": "times",
      "target": "10",
      "targets": [],
      "value": ""
    }, {
      "id": "54e06238-5a8e-4618-81f8-91dcd29674b9",
      "comment": "",
      "command": "open",
      "target": "/login/qr_login.htm",
      "targets": [],
      "value": ""
    }, {
      "id": "c0840798-b610-4ee9-97df-c6fdc7e9b293",
      "comment": "",
      "command": "setWindowSize",
      "target": "1316x695",
      "targets": [],
      "value": ""
    }, {
      "id": "732d91b7-a8b0-4501-9c6e-3630a28da0da",
      "comment": "",
      "command": "selectFrame",
      "target": "index=1",
      "targets": [
        ["index=2"]
      ],
      "value": ""
    }, {
      "id": "c10fa998-204e-481d-83c5-6abd58938d20",
      "comment": "",
      "command": "selectFrame",
      "target": "index=1",
      "targets": [
        ["index=1"]
      ],
      "value": ""
    }, {
      "id": "25547d93-ea90-4a03-9e1e-df14d3481d1f",
      "comment": "",
      "command": "click",
      "target": "id=fm-login-id",
      "targets": [
        ["id=fm-login-id", "id"],
        ["css=#fm-login-id", "css:finder"],
        ["xpath=//input[@id='fm-login-id']", "xpath:attributes"],
        ["xpath=//form[@id='login-form']/div/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "4c006de4-6885-42b4-8e88-b7604f843ff1",
      "comment": "",
      "command": "type",
      "target": "id=fm-login-id",
      "targets": [
        ["id=fm-login-id", "id"],
        ["css=#fm-login-id", "css:finder"],
        ["xpath=//input[@id='fm-login-id']", "xpath:attributes"],
        ["xpath=//form[@id='login-form']/div/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "test"
    }, {
      "id": "db04abf7-0394-40b1-909f-ca8f5c0a7c04",
      "comment": "",
      "command": "click",
      "target": "id=fm-login-password",
      "targets": [
        ["id=fm-login-password", "id"],
        ["css=#fm-login-password", "css:finder"],
        ["xpath=//input[@id='fm-login-password']", "xpath:attributes"],
        ["xpath=//form[@id='login-form']/div[2]/div/input", "xpath:idRelative"],
        ["xpath=//div[2]/div/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "8d2c9980-76d2-4c6b-8fcc-e089c21ac7ab",
      "comment": "",
      "command": "type",
      "target": "id=fm-login-password",
      "targets": [
        ["id=fm-login-password", "id"],
        ["css=#fm-login-password", "css:finder"],
        ["xpath=//input[@id='fm-login-password']", "xpath:attributes"],
        ["xpath=//form[@id='login-form']/div[2]/div/input", "xpath:idRelative"],
        ["xpath=//div[2]/div/input", "xpath:position"]
      ],
      "value": "test"
    }, {
      "id": "e627ae7b-805f-4f2c-b6d1-36c7dcf09bb7",
      "comment": "",
      "command": "end",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "5927bbd5-5758-4cb5-a4ef-6118b8d2891f",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["c87698e3-1f70-469a-a1cb-40319e5e18e8"]
  }],
  "urls": ["https://account.aliyun.com/"],
  "plugins": []
}

## Environment

OS: windows 10
Selenium IDE Version: 3.16.1
Browser: chrome
Browser Version: 79.0.3945.88 （64-bit）
PS : The selenium ide has the same issue on firefox browser.

**Comment by capoerafreak** [comment]
I‘am not sure, but you are still in the frame „1“ and you don‘t leave it. Try to leave the frame at the end of the test with „select frame relative=top“

**Comment by HabitNature** [comment]
Thanks, capoerafreak.
Indeed, as you said, after I added the “select frame relative=top” command, the script could be executed successfully.
