### ISSUE TITLE
Conflict with client require.js

### ISSUE THREAD

**Issue by mikazp** [SeleniumHQ/selenium-ide#92]
Breaks everything if require.js used on site.

e.g. check http://www.bbc.com with ide enabled

`Uncaught Error: Mismatched anonymous define() module: function () {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}.....`

**Comment by corevo** [comment]
Fixed, will be included in the next release
