### ISSUE TITLE
open new windows https url Exceeded waiting time for new window to appear 2000ms

### ISSUE THREAD

**Issue by tcwaily** [SeleniumHQ/selenium-ide#922]
`"id": "b0eb1ebb-ea28-4dba-b86e-1e94a925fc6a",
  "version": "2.0",
  "name": "select window",
  "url": "https://www.google.com/search?newwindow=1&hl=en&sxsrf=ACYBGNToJG0cKH9bweItnM0tFk0A2oqOgA%3A1578397499702&source=hp&ei=O28UXufXJ4S_wAOz9IKoDQ&q=fsfda&oq=fsfda&gs_l=psy-ab.3..0j0i10l7j0i203.719.1040..1308...1.0..0.148.632.0j5......0....1..gws-wiz.....10..35i362i39j35i39j0i131.OED4U5MnSE0&ved=0ahUKEwin4Z_ytPHmAhWEH3AKHTO6ANUQ4dUDCAg&uact=5",
  "tests": [{
    "id": "62eb33e2-f462-433d-a526-704a7c6f6c13",
    "name": "gg",
    "commands": [{
      "id": "4d063ee2-fcb5-441a-b89c-849e182fa5b8",
      "comment": "",
      "command": "open",
      "target": "https://www.google.com/search?newwindow=1&hl=en&sxsrf=ACYBGNToJG0cKH9bweItnM0tFk0A2oqOgA%3A1578397499702&source=hp&ei=O28UXufXJ4S_wAOz9IKoDQ&q=fsfda&oq=fsfda&gs_l=psy-ab.3..0j0i10l7j0i203.719.1040..1308...1.0..0.148.632.0j5......0....1..gws-wiz.....10..35i362i39j35i39j0i131.OED4U5MnSE0&ved=0ahUKEwin4Z_ytPHmAhWEH3AKHTO6ANUQ4dUDCAg&uact=5",
      "targets": [],
      "value": ""
    }, {
      "id": "c673375b-9c97-464b-9f40-c23341359db5",
      "comment": "",
      "command": "setWindowSize",
      "target": "1368x847",
      "targets": [],
      "value": ""
    }, {
      "id": "41887b4d-8fc6-4264-97fb-b84497448d41",
      "comment": "",
      "command": "click",
      "target": "css=.bkWMgd:nth-child(2) .g:nth-child(1) .LC20lb",
      "targets": [
        ["css=.bkWMgd:nth-child(2) .g:nth-child(1) .LC20lb", "css:finder"],
        ["xpath=//div[@id='rso']/div[2]/div/div/div/div/div/a/h3", "xpath:idRelative"],
        ["xpath=//div/a/h3", "xpath:position"],
        ["xpath=//h3[contains(.,'First South Florida Missionary Baptist District Association')]", "xpath:innerText"]
      ],
      "value": "",
      "opensWindow": true,
      "windowHandleName": "f",
      "windowTimeout": 2000
    }]
  }],
  "suites": [{
    "id": "c2f2d476-d192-4836-9fb2-768fc5c1449c",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": []
  }],
  "urls": ["http://the-internet.herokuapp.com/", "https://sso1.capitalonline.net/pages/login.html?next=https://console.capitalonline.net/", "https://www.baidu.com/", "https://console.capitalonline.net/", "https://sso1.capitalonline.net/pages/login.html", "https://www.capitalonline.net/zh-cn/", "http://www.capitalonline.net/zh-cn/", "https://www.google.com/search?newwindow=1&hl=en&sxsrf=ACYBGNToJG0cKH9bweItnM0tFk0A2oqOgA%3A1578397499702&source=hp&ei=O28UXufXJ4S_wAOz9IKoDQ&q=fsfda&oq=fsfda&gs_l=psy-ab.3..0j0i10l7j0i203.719.1040..1308...1.0..0.148.632.0j5......0....1..gws-wiz.....10..35i362i39j35i39j0i131.OED4U5MnSE0&ved=0ahUKEwin4Z_ytPHmAhWEH3AKHTO6ANUQ4dUDCAg&uact=5"],
  "plugins": [{
    "id": "nknickobkcecmkiiefhjmiaihliikohm",
    "name": "Applitools",
    "version": "1.0.0"
  }]
}%    `

click on css=.bkWMgd:nth-child(2) .g:nth-child(1) .LC20lb Failed:19:48:37
Exceeded waiting time for new window to appear 2000ms

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
