### ISSUE TITLE
I get an error when I want to export the project as XUnit.

### ISSUE THREAD

**Issue by omeratli** [SeleniumHQ/selenium-ide#933]
## Environment

OS: 

Browser: Chrome
Browser Version:

**Comment by omeratli** [comment]
Hi friends, I get such an error when importing. If I close the else commands, I can get the export, but that doesn't work. How can I find a solution? Is there anyone who has encountered and solved this error?

![image (3)](https://user-images.githubusercontent.com/40432014/72445652-1b09d100-37c3-11ea-8a07-56eb4d80109c.png)

**Comment by karenhanson** [comment]
Not sure if this applies in your case @omeratli or maybe helps identify if there is a bug, but I saw this "Test 'x' has a problem. Cannot read property 'isOptional' of undefined" message when using if/end in the Chrome extension and trying to do any export. I had a _Target_ value that returned a boolean and then "true" in the _Value_ field because I thought they needed to match to go into the _if_. I removed "true" from the _Value_ field - the test still worked and I could now export it without the error.

**Comment by kwikwag** [comment]
👍 I isolated this to happen due to an `echo` command which had a `Value` instead of only a `Target`.

**Comment by Kacahuette** [comment]
Hello, I have the same error than @omeratli . But in my test I have no boolean or command with a Value instead of a Target
It does not allow me to export my test on Python :/ 
Any other idea for this problem?
@omeratli did you solve your export problem?
Many Thanxs

**Comment by andyp05** [comment]
Make sure there is no value (just target) for all **verify element present** commands.

**Comment by p2635** [comment]
I get the same problem with export to NUnit as well. I went through what @andyp05 said but I didn't have any verify element present with a value (only target). When I get time I think I will go through all my steps and see what is unusual.

**Comment by tourdedave** [comment]
That error presents when a command is incomplete or invalid (e.g., missing inputs in the correct place) and you're trying to export -- it happens for every language. Although it is supposed to provide more detail so it's more straightforward to identify which command has the problem. That in itself is the bug.

**Comment by citizenfish** [comment]
**OS: Mac OS - Big Sur
Browser: Chrome
IDE Version: 3.17.0**

I am seeing this same error when adding a simple check command

The test runs fine in Selenium IDE but will not export. If I remove this check then export will work.

<img width="835" alt="Screenshot 2020-12-11 at 10 23 18" src="https://user-images.githubusercontent.com/10531204/101892180-fb2d8980-3b9a-11eb-9139-4eec05aefa8e.png">

**Comment by tourdedave** [comment]
Export only exports tests containing legal commands. It throws an error if it reaches a command that is either incomplete or contains extra inputs. For instance, @citizenfish's issue - he's trying to export the [`check`](https://www.selenium.dev/selenium-ide/docs/en/api/commands#check) command with two inputs (both target and value) but check only has 1 input (target).

You can always double check what inputs a command takes by looking at the reference tab in SIDE when editing a command, or by looking at the command docs [here](https://www.selenium.dev/selenium-ide/docs/en/api/commands).

**Comment by daksh23** [comment]
ya, some commands not required a value field.
