### ISSUE TITLE
Selenium IDE not giving option to save the test case in JAVA

### ISSUE THREAD

**Issue by Arish24101985** [SeleniumHQ/selenium-ide#935]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

__NOTE: you can export a test case to Java, see [here](https://selenium.dev/selenium-ide/docs/en/introduction/code-export)__
