### ISSUE TITLE
Selenium-side-runner not clearing input field before typing but works with Selenium Ide

### ISSUE THREAD

**Issue by nischitpradhan** [SeleniumHQ/selenium-ide#936]
I'm trying to enter some text in `input` box so am using `type`. The input box has some default text and want to clear it before typing.

Normally, `type` in `Selenium Ide` should do the work as stated in [here](https://ui.vision/rpa/docs/selenium-ide/sendkeys-type). 

This works well in `Selenium Ide` but when I save it and run the `.side` from `selenium-side-runner` it does not clear the text field. It just appends after it.

To work around this, I decided to use `send keys` with value `${KEY_SHIFT}${KEY_HOME}${KEY_SHIFT}${KEY_BACKSPACE}`. Again, this works as expected in `Selenium Ide` but when I run it from `selenium-side-runner` I get the following error:

    info:    Running login.side
     FAIL  ./DefaultSuite.test.js
      Default Suite
       ✕ login (2775ms)

     ● Default Suite › login

     TypeError: each key must be a number of string; got undefined

      at forEach.key (../../node_modules/selenium-webdriver/lib/webdriver.js:2011:15)
          at Array.forEach (<anonymous>)
      at WebElement.sendKeys (../../node_modules/selenium-webdriver/lib/webdriver.js:2006:31)

**Comment by tourdedave** [comment]
Related to #915

**Comment by nischitpradhan** [comment]
Its not related. I've values set to key commands.

`send key` with`${KEY_SHIFT}${KEY_HOME}${KEY_SHIFT}${KEY_DELETE}` works.

`KEY_BKSP / KEY_BACKSPACE` doesn't seem to work.

Had to do hit and try to get the solution. Theres no documentation either as of now showing supported keys.

**Comment by tourdedave** [comment]
Ah, my mistake. The supported keys are specific to `selenium-webdriver` so you would need to refer to its documentation.

https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Key.html
