### ISSUE TITLE
Open url command not working

### ISSUE THREAD

**Issue by olds97lss** [SeleniumHQ/selenium-ide#94]
I had mentioned this in someone elses thread and was suggested I start my own.

It appears there is an issue with the "open" command. I have tons of scripts and I don't use the base url at all. Instead, the first command I run is to open a website/url. Appears the released version of the new ide doesn't know what to do with that and gets an error. Unless I manually go to the url outside selenium, then run the script. Then it seems to open and run ok.

 I never really used the base url in my scripts since I tend to write them to hop from one site to another for work. Within one script, I'll open an internal use only jsp that fires a query with parameters I add on to the url for updating database items, then I open the same jsp again but with new parameters to do a lookup. After confirming the update was successful, I open the site I need to test, which is a totally different url.

That's just one instance, but I do open full url's directly pretty much all the time since it's easier for me to maintain.

**Comment by corevo** [comment]
`open` can take an absolute url, will be included in the next release.

**Comment by olds97lss** [comment]
I see that it's in the 1.0.2 release, but I'm still not able to use it. Getting an error.

Running 'x10MonthlyLogin'
1.Trying to execute open on https://x10hosting.com/sso/login... Failed:
Invalid tab ID: -1
'x10MonthlyLogin' completed with 1 error(s)

**Comment by corevo** [comment]
We should be more clear with what this error means, as it has nothing to do with the issue at hand.  
This error is caused when the IDE has issues taking control over the current tab to test under it.  
Some pages are protected by Chrome and Firefox, and we can't automate them, for example setting pages, extension pages, or any page that has sensitive user data or administrative capabilities of the browser.  
In that case, open a new tab and navigate to any website, make sure the url reads anything that **DOESN'T** start with `chrome://`.  
I will make sure to make this error more readable.

**Comment by corevo** [comment]
Yes, both Chrome and Firefox, as part of protecting the end user, don't let extensions automate built in browser pages.

**Comment by olds97lss** [comment]
A blank url is a built in page?

**Comment by corevo** [comment]
Yes, you can't see the `chrome://` as in the extensions page, but it is a chrome page.

**Comment by olds97lss** [comment]
Ah. I didn't realize that. Thanks!
