### ISSUE TITLE
Exporting a test with run in it fails.

### ISSUE THREAD

**Issue by FreeFrags** [SeleniumHQ/selenium-ide#940]
## 🐛 Bug Report

I have a test in which uses the run command 2 times, the test runs as it should recursively running the 2 scripts indicated in the run command. 

When exporting i get " Unable to complete code export Invalid command '' ". Tested this with all the export options (c#, Java, JS, etc.)

I would expect that the the export would still work as it would with a "normal test".

#592 was closed so i decided to make this issue

**Comment by tourdedave** [comment]
@FreeFrags can you provide a SIDE project file which demonstrates this?

**Comment by AutomatedTester** [comment]
Closing as no info provided
