### ISSUE TITLE
 Unknown locator error when playing macro with selenium-side-runner

### ISSUE THREAD

**Issue by MiiChiel2000** [SeleniumHQ/selenium-ide#942]
I'm playing the following in selenium ide, it works fine:

![image](https://user-images.githubusercontent.com/59735838/73548271-c3b16500-4440-11ea-9623-daf53b39b3d0.png)

But when I save the macro, try to play it with selenium-side-runner. It gives the following error:
![image](https://user-images.githubusercontent.com/59735838/73548315-d7f56200-4440-11ea-8a07-a4d555cfec3c.png)

I'm using the newest versions of Chrome, Selenium IDE, Windows 10.

**Comment by corevo** [comment]
Try adding css= in front of the locator, or the strategy that you used.

Cheers,
Tomer

**Comment by MiiChiel2000** [comment]
> Try adding css= in front of the locator, or the strategy that you used. Cheers, Tomer
> […](#)
> On 31 Jan 2020, 16:47 +0200, MiiChiel2000 ***@***.***>, wrote: I'm playing the following in selenium ide, it works fine: But when I save the macro, try to play it with selenium-side-runner. It gives the following error: I'm using the newest versions of Chrome, Selenium IDE, Windows 10. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


I'm not fully following you, you mean adding css in the html source page or in selenium, instead of cmd_var2_0@value => css=cmd_var2_0@value?

**Comment by corevo** [comment]
In selenium ide like you suggested.

Cheers,
Tomer

**Comment by MiiChiel2000** [comment]
Unfortunately that does not work... it keeps searching. Would it affect the situation that the html page does not contain the <Body> tag? It's just plain <HTML><HEADER></HEADER><input id="cmdvar2_0" value="random value">

**Comment by capoerafreak** [comment]
You can not store an attribute that isn‘t present ...

**Comment by MiiChiel2000** [comment]
Wait, this forum edited my post cause it i didn't use the code tags, i ment it does not contain the body tag, its just html, header, end of header, then without body tag the input tags start.

**Comment by MiiChiel2000** [comment]
I still have not fixed this. Somehow the header tag appears in the body as well when I open the landingspage.

![image](https://user-images.githubusercontent.com/59735838/75553136-167a3e80-5a38-11ea-8d9b-04780aba53cf.png)

**Comment by MiiChiel2000** [comment]
> Try adding css= in front of the locator, or the strategy that you used. Cheers, Tomer
> […](#)

It does not seem to work, i have multiple input fields with unique ID's, for instance:

`<input type="text" id="cmd_var1" size="75" value="441">`

The following with command Store Attribute does not work when I play it in the Selenium Player:

id=cmd_var1
css=id=cmd_var1
css=id@cmd_var1
css=input#cmd_var1

And more variations on this.

What am I doing wrong in this part?

**Comment by MiiChiel2000** [comment]
Solved: I wrote my html wrong, I used the word header instead of head... that's where selenium was bugging.

**Comment by tourdedave** [comment]
Glad to hear you're all set.
