### ISSUE TITLE
The ChromeDriver could not be found on the current PATH

### ISSUE THREAD

**Issue by JhefersonBR** [SeleniumHQ/selenium-ide#943]
## 🐛 Bug Report

Hi guys!
I have the same problem reported in the issue: https://github.com/SeleniumHQ/selenium-ide/issues/664

I couldn't solve it, I use windows 10, and the chromedriver binary is already defined in the PATH variable.
But for some unknown reason, the selenium-side-runner does not find.

## Environment

OS: Windows 10
Selenium IDE Version:  3.16.1
Selenium SIDE Runner Version:  3.16.0
Node version: v10.16.0
Browser: Chrome
Browser Version: 80.0.3987.87

**Comment by JhefersonBR** [comment]
![image](https://user-images.githubusercontent.com/25249696/73839497-e652cd80-47f4-11ea-8702-1a725c379a74.png)

**Comment by corevo** [comment]
Your `PATH` is incorrect, it should be to the directory that contains `chromedriver.exe` not to the file itself, remove it from the variable, just like the OpenSSH one, to check you can open `cmd` and write `chromedriver`.

If it finds it then it works.

**Comment by JhefersonBR** [comment]
Hello @corevo thanks for the reply.
I did what you said but the problem continues.

![image](https://user-images.githubusercontent.com/25249696/73843158-d6d78280-47fc-11ea-84a8-a53d802756d8.png)

![image](https://user-images.githubusercontent.com/25249696/73843300-26b64980-47fd-11ea-939e-c6e4df971c6e.png)

**Comment by JhefersonBR** [comment]
![image](https://user-images.githubusercontent.com/25249696/73843457-74cb4d00-47fd-11ea-9272-57e5c3344a15.png)

**Comment by corevo** [comment]
Did you open a new CMD window after you changed the PATH?

Changing PATH requires it to be opened again

**Comment by JhefersonBR** [comment]
@corevo 

Yes, and to be sure I restarted the computer.
It is as if the selenium-side-runner does not have access to the PATH variable.
Very strange...

**Comment by JhefersonBR** [comment]
Thanks @corevo I managed to solve it, applying the same settings in the user's environment variable, in addition to the system environment variable
