### ISSUE TITLE
Unclear how to get engine.io server started at port 4445

### ISSUE THREAD

**Issue by Dmitry-Me** [SeleniumHQ/selenium-ide#945]
I'm trying to build, start and debug the extension on Windows Server. I got the sources from master and built them with `yarn build` successfully. I go to Chrome extensions page and use "load unpacked", navigate to packages/side-recorder/build folder and Chrome looks happy to load the extension. The extension is added successfully but when I click onto "Se" icon nothing happens.

There's this error message in Chrome console:

     GET http://localhost:4445/engine.io/?EIO=3&transport=polling&t=SomeThingRandom net::ERR_CONNECTION_REFUSED

Looks like the extension code uses a WebSocket client which is created in packages/side-recorder/src/background/index.js:

     const socket = eio(window.socketUrl || 'ws://localhost:4445')

and for some reasons the "server" part of this doesn't start. I have no idea what step I failed to perform which would cause the "server" part of this to start.

It would be nice if it was explained somewhere, perhaps even the `socket` variable could be renamed to better indicate what the connection is to.

**Comment by corevo** [comment]
The extension is developed in the `v3` branch, what you've built is a component of the very WIP electron port.
