### ISSUE TITLE
is it possible to make RemoteLocalStorage api from selenium ide?

### ISSUE THREAD

**Issue by akshattambe** [SeleniumHQ/selenium-ide#946]
## 💬 Questions and Help
Is it possible to make a call to  RemoteLocalStorage api from selenium ide?

**Comment by tourdedave** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

For questions - please submit to [the Google group](Google group) or ask on [the Selenium chat channel](https://seleniumhq.herokuapp.com/).

**Comment by akshattambe** [comment]
I am following templates now !! what am I doing wrong?

**Comment by tourdedave** [comment]
Unfortunately, no you're not. The question template clearly states `Please note that this issue tracker is not a help form and this issue will be closed.`

It also specifies other places you can go for help with questions.

<img width="638" alt="Screen Shot 2020-02-10 at 15 02 14" src="https://user-images.githubusercontent.com/457137/74152198-768a7b80-4c16-11ea-8b5d-20c178b5900a.png">
