### ISSUE TITLE
Failed to select new tab or new window in New Selenium IDE

### ISSUE THREAD

**Issue by ianhe1** [SeleniumHQ/selenium-ide#949]
## 🐛 Bug Report

I am using the Chrome browser on Windows 10 machine and running Selenium IDE 3.1

I am trying to use **select window** command to select the new tab for example
select window  | tab=1 
It does not work.  I got "No such window locator" error.

I used to use the old Selenium IDE where I can use **selectPopUp** to select the new window and it works fine.

Maybe I don't know how to use the new selenium IDE command. I tried a number of options and none of them seem to work for me.

## To Reproduce
1. In the current browser session, open a root window
2. In the root window, click on the link to open a second window in a new tab.
2. add command in the test case  select window  | tab=1 
2. execute this command
Now I get an error 
   "No such window locator" 

## Expected behavior
I am expecting to see the new window (with tab 1) is selected.  I am expecting the same behavior as in old Selenium IDE seletPopUp command.

## Project file reproducing this issue (highly encouraged)
This is easy to reproduce and no need to provide a project.

## Environment

OS:  Windows 10 
Selenium IDE Version:  3.0.3 
Browser:
Browser Version: Chrome 79.0.3945.130 (Official Build) (64-bit)

## Questions 

1. Do we have anything that is corresponding the old Selenium IDE seletPopUp command in the new Selenium IDE?
2. If not, what is the alternative command in new Selenium IDE that I can use?
3. Do we have official command reference with sample code for new Selenium IDE? I tried to search the website and found some command references but they are not working. Not all commands are working. and not all commands have samples to show user how to use them.

**Comment by tourdedave** [comment]
The tab IDs are not guaranteed to be sequential. When recording, you should get the command added with the correct result. Also, there is a separate setting window for configuring the window handle to use.

You can see a full command list here: https://selenium.dev/selenium-ide/docs/en/api/commands

If you are experiencing issues with a command, then please let us know by filing another issue for it.

**Comment by tourdedave** [comment]
Here's an example script showing the functionality.

[new-window-repro.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/4184683/new-window-repro.side.zip)

**Comment by ianhe1** [comment]
Thank you very much @tourdedave for your quick response on this issue. I tried your sample project it works for me. However, I don't know how can you get the window handle handle=${win1065}. When I tried to record it I get handle=${win8850}. Both works for me in the sample case. I am confused why the two different numbers both works here?
