### ISSUE TITLE
CKeditor not defined in IDE

### ISSUE THREAD

**Issue by mthompson36** [SeleniumHQ/selenium-ide#953]
I'm trying to enter text into an iframe unfortunately it's entering grayed out text and it disappears as soon as you navigate away from the field.  I tried using ckeditor for the field but I get an error message saying `ckeditor is not defined`?  Can anyone help with this? 

![Screen Shot 2020-02-13 at 2 26 35 PM](https://user-images.githubusercontent.com/38014119/74560762-1c423100-4f1c-11ea-8a60-4a1e0b5b3f54.png)

**Comment by RichardHaynes** [comment]
Having similar issues with rich text editor (Summernote).  Feel this should be "out of the box" for an IDE.  Rich text editors are so common.

**Comment by tourdedave** [comment]
Can you provide a SIDE project that reproduces this?

**Comment by AutomatedTester** [comment]
Closing as no info was given

**Comment by Richisfree** [comment]
For any that return to this page the workaround for me in the "Summernote" rich text editor was to use the "code view".  This is accessed by clicking the "</>" icon in summernote toolbar.  Ensure to click again to return to the normal view before progressing.  The commands were: 
`click css=.note-icon-code`
`type css=.note-codable <p>My text input here</p>`
`click css=.btn-codeview `
Sorry I wasn't able to post the example SIDE script, I couldn't find a public example of Summernote editor where results were meant to be persisted to a database and re-displayed (our own implementation is behind a log in screen).
