### ISSUE TITLE
quoted text in noscript tag treated as elements

### ISSUE THREAD

**Issue by wnm3** [SeleniumHQ/selenium-ide#956]
## 🐛 Bug Report

A page contains code like below (as shown in Chrome debugger:
```
<noscript>
"
<BR><BR>
<table style="WIDTH: 100%">
<tr>
 	<td align="center">
		<table class="CTXMSAM_LogonFont">
			<tr id="errorMessageRow">
				<td class="glowBoxLeft">&nbsp;</td>                            
				<td class="loginTableMidWidth">
					<div id="feedbackArea">
					<div id="feedbackStyle" class="feedbackStyleError">
					<span id="errorMessageLabel" class="messageStyle">
					JavaScript is either disabled in or not supported by the Web browser.  
					To continue logon, use a Web browser that supports JavaScript or enable JavaScript in your current browser.
					</span>
					</div>
					</div>
				</td>                           
				<td class="glowBoxRight">&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>
</table>

<table style="display:none">
"
</noscript>
```
however, it seems to ignore the quotes and treats the content as Elements rather than as a TextElement.

URL is: https://emea-portal.ubm.com/vpn/index.html
## To Reproduce

Capture the page content. The resulting HTML shows the </noscript> tag capturing the entire body, rather than just the table...

![image](https://user-images.githubusercontent.com/1359024/74685904-ea400180-519d-11ea-9f02-d7c4eaa72717.png)

## Expected behavior

If content in a <noscript> tag is quoted, treat it as a TextElement rather than parsing as Elements...

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: OSX 
Selenium IDE Version:  3.141.0
Browser:
Browser Version: Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
@wnm3 can you provide a SIDE project file that demonstrates the issue?

**Comment by AutomatedTester** [comment]
Closing as requested info not provided
