### ISSUE TITLE
execute script > Unable to have comments in script?

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#958]
## 🐛 Bug Report

I attempted to add a comment in my array so I can keep track of what each element means. However, when I now run this it breaks the selenium script so I have to remove all comments from my array to proceed.

![image](https://user-images.githubusercontent.com/4522927/74762385-a7515d00-5275-11ea-8398-ca4e5cac37bf.png)

## To Reproduce

Command: execute script
Target: return array=[1234 //comment here,  "text a", "text b" ]
Value: test

## Expected behavior

The command successfully proceeds.

## Project file reproducing this issue (highly encouraged)

[experiment array comment.zip](https://github.com/SeleniumHQ/selenium-ide/files/4220762/experiment.array.comment.zip)

## Environment

OS: Win10
Selenium IDE Version:   3.16.1

**Comment by corevo** [comment]
// comments the rest of the line
Try using /* comment */

**Comment by p2635** [comment]
Works perfectly, thanks @corevo
