### ISSUE TITLE
Selenium IDE is not executing properly script when '.' (dot) is included

### ISSUE THREAD

**Issue by d-miloradovic** [SeleniumHQ/selenium-ide#959]
## 🐛 Bug Report

I've tried to execute JS script in Selenium IDE, but that script wasn't executing properly. That was function with 2 statements, and Selenium IDE was always skipping first one and was going straight to the second.

## To Reproduce

1. Unpack the attached file and open 'example.side' with Selenium IDE
2. For base URL, set the path to the file where you extracted it
3. Run test

## Expected behavior

When there is '.' (dot) in my string, function should execute "if" statement and not skipping to 'else'

## Project file reproducing this issue (highly encouraged)

- [example.zip](https://github.com/SeleniumHQ/selenium-ide/files/4230628/example.zip)
- [Screenshot of the test](https://user-images.githubusercontent.com/55413601/74933546-81969600-53e4-11ea-99da-2424f7b2f74c.png)

## Environment

OS: Linux Ubuntu 18.04.4 LTS
Selenium IDE Version:     
Browser: Google Chrome
Browser Version: 80.0.3987.87

**Comment by tourdedave** [comment]
The function you're passing to `replace` references the variable you're trying to modify. Instead, you can reference the property name as a param on the function -- `replace` will pass it implicitly ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Using_an_inline_function_that_modifies_the_matched_characters)). Also, you can simplify the conditional branch down to a one-liner with a ternary operator (which isn't necessary, just makes it easier to read given the limited space in the IDE input field).

[example.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/4285558/example.side.zip)
