### ISSUE TITLE
How to upload user-extension .js in new Selenium IDE for chrome

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#96]
I have old tests where I have written custom commands and there is provision in old selenium ide to upload user-extension .js in developer options in ide. How can I achieve that in new selenium IDE . I could not find a way to upload files. 

Even I have used concept of rollup in old selenium IDE where rollup acts a function in which same lines of steps can be grouped and can call them in all test cases and use them by passing different parameters .This needs user-extension.js file upload in ide settings.

**Comment by peter-kehl** [comment]
See https://github.com/SeleniumHQ/selenium-ide/issues/85.

May I suggest you close this ticket (#96).

**Comment by corevo** [comment]
It is a bit of a different ticket, since this is user based logic changes, rather than plugin based.  
The problem with this is that we can not verify the script's validity and make sure it works with "good intentions".  
I'm unsure how to proceed, perhaps we can run logic in content script level, but that would also impose constraints, and risk end users' privacy.

**Comment by manikumary** [comment]
Hi , yes this is different from #85 issue. This is re-using steps within scripts and adding them as function.
It is already there with old selenium IDE it is not new feature request. I am not sure about how old selenium IDE handled this risk factor. But it is badly needed for me .

**Comment by corevo** [comment]
This risk factor was different, since Mozilla back with the old extension format was more lenient with the overall permissions an extension could have.

**Comment by corevo** [comment]
The plan is to move to playback on WebDriver on the somewhat near future.  
WebDriver doesn't support Selenium 1.0 prototypical behavior, therefore we simply won't be able to support this in the project, and you will have to move to the newly published [plugin API](https://github.com/SeleniumHQ/selenium-ide/wiki/Getting-Started-with-Plugins).
