### ISSUE TITLE
Trying to store Big list of naughty strings as an array > Invalid or unexpected token

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#960]
## 🐛 Bug Report

As summary.

## To Reproduce

I'm trying to store the big list of naughty strings as an array with 'execute script' but it's not working.

## Expected behavior

It should store the array correctly.

## Project file reproducing this issue (highly encouraged)
[blns.zip](https://github.com/SeleniumHQ/selenium-ide/files/4230677/blns.zip)

**Comment by p2635** [comment]
I realised the project file doesn't even open properly. So here is the command:

command: execute script
target: return (insert big list of naughty strings here: https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json)
value: x

**Comment by tourdedave** [comment]
Try using the `store json` command instead.

https://www.selenium.dev/selenium-ide/docs/en/api/commands#store-json

**Comment by p2635** [comment]
Hi @tourdedave, I think tried store json already as well and it's just something in the string that breaks it
