### ISSUE TITLE
selenium-side-runner command line error

### ISSUE THREAD

**Issue by Swaroop4** [SeleniumHQ/selenium-ide#962]
## 🐛 Bug Report

Hello Friends,

I am getting below error while running the "selenium-side-runner" in command line , please guide me how to fix it.

selenium-side-runner C:\Users\SDN004\Downloads\scheduler\sec2.side
'selenium-side-runner' is not recognized as an internal or external command,
operable program or batch file.

Environment
OS: Windows 10 Enterprise
Selenium IDE Version: Version 3.16.1
Selenium SIDE Runner Version: 6.10.2
Node version: v12.9.0
Browser: Google Chrome Version 80.0.3987.116 (Official Build) (64-bit)

**Comment by corevo** [comment]
Seems like it is not in your `PATH` make sure that the result of `npm get prefix` is in your PATH.

**Comment by corevo** [comment]
Also make sure you've install it using `npm i -g selenium-side-runner`

**Comment by Swaroop4** [comment]
@corevo 
C:\Users\SDN004>npm get prefix
C:\Users\SDN004\AppData\Roaming\npm

Have already install npm i -g selenium-side-runner

**Comment by corevo** [comment]
Is this directory in your PATH?

**Comment by Swaroop4** [comment]
yes 
![image](https://user-images.githubusercontent.com/61415448/75157030-56d87480-5739-11ea-83f6-69e883b38ea5.png)

**Comment by corevo** [comment]
This seems to be a Windows configuration issue, please refer to guides on how to add directories to your machine's PATH https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by corevo** [comment]
We have an official guide, I didn't know

Anyway up to date information is available here on adding things to your `PATH`
https://www.selenium.dev/documentation/en/webdriver/driver_requirements/#adding-executables-to-your-path

**Comment by Swaroop4** [comment]
ok, i have just changed my cmd directory to "C:\Users\SDN004\AppData\Roaming\npm>"  it ran but given me 1 failed,with error "The ChromeDriver could not be found on the current PATH." so i am using Latest "Google Chrome Version 80.0.3987.116 (Official Build) (64-bit)" so which should i download and install

**Comment by corevo** [comment]
Again, please refer to the guide on how to add the directory to your PATH, that is your underlying issue, you've changed the directory, and now the problem was pushed back to chromedriver, but it is the same problem.

Following the instructions on either one of the links I've sent will solve your problem.

**Comment by Swaroop4** [comment]
Thanks for your quick reply will check and let you know
