### ISSUE TITLE
How to integrate this new IDE test cases to Continous integration (CCnet)

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#97]
In old IDE test suite and test case are saved as HTML. HTML clearly shows the passed lines of test in green and failed lines in red. This helps to integrate results to Continuous integration where selenium RC helps to run selenium test suite and html plugins help to show the pass and fail reports to CCNet.

How this can be achieved with new selenium IDE for chrome where I could see test suite and test case are saved as (.side) extension file. how will they show the passed and failed results and which one helps to these side extension file to integrate CC.net .

**Comment by corevo** [comment]
See #68 
CI integration is currently being worked on, a side runner will take an exported version of the .side file and will run it, and report the results.  
Since its still WIP it's not available in the chrome store version, but hopefully it'll be released soon.
