### ISSUE TITLE
Export's aren't aware of dependencies.

### ISSUE THREAD

**Issue by MarkoMackic** [SeleniumHQ/selenium-ide#971]
## 🐛 Bug Report

If a test contains run ${SOME_OTHER_TEST} command then ${SOME_OTHER_TEST} should be bundled as method in export class. 

## To Reproduce

Export test `export_helloWorld`, and class will contain test method that calls `das();` which is not exported so the class is unusable.

## Expected behavior

Test `das` should be exported as method without `@Test` annotation ( in Java export context).

## Project file reproducing this issue

[aaa.zip](https://github.com/SeleniumHQ/selenium-ide/files/4265749/aaa.zip)

## Environment

OS: Widows 10
Selenium IDE Version: 3.16.1
Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Comment by tourdedave** [comment]
This is the export I'm getting with the project you provided (which is correct).

```
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExporthelloWorldTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public void das() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(794, 510));
    driver.findElement(By.name("q")).sendKeys("dsada");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
  }
  @Test
  public void exporthelloWorld() {
    das();
  }
}
```

What are you seeing for the export?

**Comment by MarkoMackic** [comment]
That's if you export whole suite, but if you export just export_helloWorld, you'll see that it has export something like this.. 

`// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExporthelloWorldTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exporthelloWorld() {
    das();
  }
}`

**Comment by MarkoMackic** [comment]
You're correct, I was testing with changes done on my branch, this is not an issue.
