### ISSUE TITLE
Selenium for firefox quantum

### ISSUE THREAD

**Issue by jorpilo** [SeleniumHQ/selenium-ide#98]
I am wondering when will selenium update in order to be supported for firefox quantum
Any guess about it?
Or how could I install it on a windows with firefox 58

**Comment by olds97lss** [comment]
You can get a version of the WIP here:
https://github.com/SeleniumHQ/selenium-ide/releases

**Comment by jorpilo** [comment]
OK thanks I finally made it to work.
Is there any way to save the test case as HTML as the old selenium did?

**Comment by corevo** [comment]
I'm afraid not, is there a specific reason you would like to do that?

**Comment by martinrbarnes** [comment]
You can do this by issuing keyboard Ctrl S and entering the name of the file into the dialog box.  I use Sikuli for this, but robot would do as well. 
I have seen a few people ask why this would be desirable.  For me, running hands-off, I want to know what caused a problem. I have log files and error trapping of course. However as I produce an HTML save for any trapped error, when I need to understand why an instruction failed it is hugely advantageous to have the HTML to view - and to Inspect on.  The more common approach seems to be to save a bitmap screenshot, but that does not give me access to the HTML.

**Comment by jorpilo** [comment]
Yes there is a specific reason, I am trying to use Selenium IDE with pandora UX for web monitoring:

https://wiki.pandorafms.com/index.php?title=Pandora:Documentation_en:UX_Monitoring

as far as I understood, it uses selenium IDE html tests
