### ISSUE TITLE
The new "Wait for Text" command does not wait if the element does not exist yet

### ISSUE THREAD

**Issue by carlos-granados** [SeleniumHQ/selenium-ide#980]
The new "Wait for text" command correctly waits if the element does not have the text but it won't wait and will throw an error immediately if the element that you want to check does not exist yet. It should wait until the element can be located

**Comment by tourdedave** [comment]
Merged in PR #981

**Comment by tourdedave** [comment]
Fixed in [v3.17.0](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.17.0)
