### ISSUE TITLE
Autocomplete for existing test cases

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#983]
## 🚀 Feature Proposal

Given I create some test cases and I'm creating a new command, when I select 'run' and start typing in the target field then I can see some autocomplete options.

## Motivation

To save time if you have longer test case names or names you can't remember the exact text for, autocomplete can save the day.

## Example

As described in the proposal.

**Comment by p2635** [comment]
My coding skills are limited but if this proposal gets accepted, I could certainly give it a go and try to send a PR but I need to learn how to set up the dev environment.

**Comment by MarkoMackic** [comment]
I'll take this.

**Comment by p2635** [comment]
Thanks @MarkoMackic , I guess I can just read your code if I'm ever interested on how it's implemented.
