### ISSUE TITLE
how to build a selenuim-ide extention  in windows

### ISSUE THREAD

**Issue by HHH1994** [SeleniumHQ/selenium-ide#991]
### Please note that this issue tracker is not a help form and this issue will be closed.

i try to execute command "npm run build" in the path ./selenuim-id/packages/selenuim-ide,
but always generate a project which is not integrated. when i drag it into chrome and use, the broswer always tell me occur some mistakes。
can u give me some advice?   i really want to study.

**Comment by tourdedave** [comment]
The issue tracker is not the place for inquiries like this. Please see the help section of our website for better places to submit your questions in the future ([link](https://www.selenium.dev/selenium-ide/help)).

Be sure to follow the build instructions from branch [v3](https://github.com/SeleniumHQ/selenium-ide/tree/v3#building).
