### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by lnsane** [SeleniumHQ/selenium-ide#993]
hi guys, I'm a JAVA developer. I'm writing a JavaScript application now. I really want to use the xpath method to get elements from your source code. I looked at it for a long time and finally took it out, but I found it getting more and more difficult  Among them, some knowledge of using nodejs and webpack, I have also learned, but after I use yarn to build, it reports an error. I would like to ask you how to debug the application of the chrome plugin. Thank you. I look at the oldest released version.  1.0, thank you

**Comment by corevo** [comment]
This issue tracker is meant to track bugs in Selenium IDE, for general purposes questions you can use our slack channel.

In general in order to debug a web application you open the web inspector, this is also true for Selenium IDE.
