### ISSUE TITLE
Change cache file size for Firefox in Selenium IDE using python2

### ISSUE THREAD

**Issue by Z-Zen** [SeleniumHQ/selenium-ide#994]
Hello,

Is it possible to change the cache disk capacity `browser.cache.disk.capacity` for Firefox in Selenium IDE using python2 ?

Thanks

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
