### ISSUE TITLE
Selenium-side-runner bugs while IDE runs test smoothly

### ISSUE THREAD

**Issue by MiiChiel2000** [SeleniumHQ/selenium-ide#995]
## 🐛 Bug Report

I create macro's in the selenium IDE, it runs well. Yet in the selenium-side-runner it bugs. With simple commands:

![afbeelding](https://user-images.githubusercontent.com/59735838/77756263-21bc8c00-702f-11ea-9942-913cf7d09860.png)

Error:
![afbeelding](https://user-images.githubusercontent.com/59735838/77756313-36008900-702f-11ea-9f55-dc7e635da530.png)

Running selenium-side-runner 3.17.0; 
Selenium IDE: 3.17.0
Latest Chrome Google Chrome is up-to-date:
Versie 80.0.3987.149 (Officiële build) (64-bits)

Windows 10

And while i am at it, is there an update in the pipeline for the IDE? like more commands such as OnError and Goto / Label?

Thnx cheers.

**Comment by corevo** [comment]
This is a known limitation atm, and will be fixed in the electron based version of Selenium IDE.

Closing as it is a duplicate.
