### ISSUE TITLE
Need help on FindElement Issue

### ISSUE THREAD

**Issue by oosafhayat** [SeleniumHQ/selenium-ide#998]
Hi All,
I have just started testing selenium automation on my company’s applications using Visual studio 2019 and C#.
I saved the automation process in C# and added it to my code.

Part of the code that I retrieved is this :

driver.Navigate().GoToUrl("https://diswlogin.siemens.com/login?state=g6Fo2SBWalBPQk0ydHlvX1FVdUNHOHE0dWdLdzNVcFc1VjRnWKN0aWTZIEtQNUJMaHVVZURKa1VCTkVfN1FsTnpKZmhzRVhGZm1ko2NpZNkgMGVCQXdaWTRWdUJGNUh3Skg1RGwyRzB1NkFpRUV1c2c&client=0eBAwZY4VuBF5HwJH5Dl2G0u6AiEEusg&protocol=samlp");
    driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
    driver.FindElement(By.Id("username")).Click();

The programs bugs on the findelement part….

System.ArgumentException: 'elementDictionary
Parameter name: The specified dictionary does not contain an element reference'

Can you help or direct me to any coding help.I have checked online and found none.

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.
